### ISSUE TITLE
Implement InfluxDB storage

### ISSUE THREAD

**Issue by ryanbyyc** [deepstreamIO/deepstream.io#10]
http://influxdb.com/
https://github.com/influxdb/influxdb

[Wishlist]

**Comment by matdehaast** [comment]
+1

**Comment by yasserf** [comment]
I looked a bit into this and don't think having a time series connector would work with records very well. Would recommend using the connector as an external db, combined with listening and rpcs on a backend process to allow data to be consumed and published in realtime.
