### ISSUE TITLE
"ReferenceError: name is not defined" crash when server removed from cluster

### ISSUE THREAD

**Issue by TimMun** [deepstreamIO/deepstream.io#1008]
I'm currently getting a crash when a server is removed from a cluster:

ReferenceError: name is not defined  at DistributedStateRegistry.onServerRemoved 

@deepstream/server/src/services/cluster-state/distributed-state-registry.ts:123:31

**Comment by yasserf** [comment]
on it!

**Comment by yasserf** [comment]
Can you try 4.2.5 please?

**Comment by TimMun** [comment]
wooo that was fast. Yes, it seems to be working now. Thank you kindly!
