### ISSUE TITLE
HTTP 404 : Only /health-check supported

### ISSUE THREAD

**Issue by HeikoMueller** [deepstreamIO/deepstream.io#1014]
Hi.

I am trying to update a record update over HTTP Post request. The server keeps responding with a 404 error: " Only /health-check supported". 

1) Is there anything I was missing in the config file ? 
2) I assume that 6020 is the right port for data update requests, while 8080 is for custom authentication logic on another host. Is this correct ?

Thank you very much !

**Comment by yasserf** [comment]
Hello! Nope currently 6020 is for websockets and 8080 if for http requests. V5 merges this together so that it all runs on 6020. But currently all you need to do is use 8080

**Comment by HeikoMueller** [comment]
Thanks!
