### ISSUE TITLE
Performance limitations still valid ?

### ISSUE THREAD

**Issue by HeikoMueller** [deepstreamIO/deepstream.io#1015]
Hi,

I just wanted to know if the limitations for the open source version of deespstream.io mentioned at https://deepstreamhub.com/compare-products/ are still valid ?

max concurrent connections ca 10.000
max messages per second ca 200.000
max throughput per second ca 4 MB

Can you please elaborate on the throughput a bit more ? Does this imply that the 200.000 messages are around 2 bytes each  (4MB / 200.000) ? 

What is the server setup that these numbers are related to ?

Thank you very much !
Heiko

**Comment by yasserf** [comment]
hello!

These limitations are no longer valid no. I haven't setup any performance harness recently but we have removed all enterprise limitations from the OS verson meaning you can now scale using clustering and send whatever size message you want, as long as you allow it in your config.yml file
