### ISSUE TITLE
Add throttle to storage connector writes

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#102]
Thanks @Svenskunganka for suggesting this. It can be required in certain instances to throttle writing to the database for records with a high update frequency. I'd suggest adding the following option to the server

``` javascript
server.set( 'storageDelay', 5000 );
```

This would mean that the first change to a record is written to the database straight away, however the soonest the next state will be written is 5 seconds later.

This is a simple initial implementation. There is a lot of room to make this more powerful, e.g. by adding recordName specific delays or delays based on a combination of writes and time, similar to Redis' SAVE configuration.

**Comment by yasserf** [comment]
This should be done within storage connectors instead of deepstream, as different connectors can respond in different ways.
