### ISSUE TITLE
`deepstream hash` is unable to run in current implementaion

### ISSUE THREAD

**Issue by valer-cara** [deepstreamIO/deepstream.io#1025]
Converted to a proper issue:
https://github.com/deepstreamIO/deepstream.io/commit/ccf59e010d06ca1bb7b3cb3c04a62525a6d74e9a#r35647566

No longer able to run `deepstream hash` because the current impl seems to remove the ref to `users.yml` while it does check for that path to be not empty.

**Comment by yasserf** [comment]
Thanks again for raising, will be releasing a patch soon to fix this and one or two other small things (mainly typescript related)

**Comment by yasserf** [comment]
Fixed in 5.0.1

Thanks again for raising!

**Comment by yasserf** [comment]
https://github.com/deepstreamIO/deepstream.io/issues/1026

For writing some basic scripts to test

**Comment by valer-cara** [comment]
Thanks for the fast fix! :1st_place_medal:
