### ISSUE TITLE
Lists don't aren't written to storage with Mongodb connector

### ISSUE THREAD

**Issue by abird** [deepstreamIO/deepstream.io#1033]
Deepstream version: 5.0.4

There is an error when attempting to write lists to Mongodb, so the lists are not actually saved to storage.

From the docs for Lists, if I do the following:

const list = client.record.getList( 'cars' );
list.setEntries( [ 'car/1', 'car/2' ] );

This is what shows up in the Mongo log:

I  WRITE    [conn2] update default.deepstream_docs command: { q: { ds_key: "cars" }, u: { $set: [ "car/1", "car/2" ] }, multi: false, upsert: true } numYields:0 ok:0 errMsg:"Modifiers operate on fields but we found type array instead. For example: {$mod: {<field>: ...}} not {$set: [ \"car/1\", \"car/2\" ]}" errName:FailedToParse errCode:9 locks:{} 0ms

So it's trying to set the value of a Mongo document to an array instead of setting a field in the document to the array.

**Comment by grydstedt** [comment]
Also seeing this

**Comment by yasserf** [comment]
Thanks for raising. A community member made a fix. Will release shortly

**Comment by yasserf** [comment]
Fix released (not tested by me personally but verified by community member)

**Comment by abird** [comment]
Thank you!
