### ISSUE TITLE
A few issues with storage authentication

### ISSUE THREAD

**Issue by abird** [deepstreamIO/deepstream.io#1035]
I found a few issues with storage authentication. I was able to fix them, but was not able to successfully submit a pull request. Attached is the source file with my changes.
Here are the issues:

- "storageId" constant was defined after it was accessed
- when creating a new user, the result was not properly returned in a promise
- when validating an existing user, the partition between the hash and the salt was not properly done due to variableness in the length of the base64-encoded hash

[storage-based-authentication.ts.zip](https://github.com/deepstreamIO/deepstream.io/files/3889625/storage-based-authentication.ts.zip)

**Comment by yasserf** [comment]
Pushed your fixed, thanks and sorry about the delay
