### ISSUE TITLE
Protocol / implementation concerns

### ISSUE THREAD

**Issue by Matthias247** [deepstreamIO/deepstream.io#104]
Hi everyone,

I found deepstream through HN and got curious on how it works, since I'm working on some things that are quite similar. After looking through the available documentation and parts of the code I'm afraid I have to report here that some things look not really reliable from my perspective:

## TCP message processing

You seem to make the typical mistake of treating TCP as message based while in reality it's a stream, with absolutly no guarantees in which chunks you might receive messages that you maybe have sent "at once". If I look here: https://github.com/deepstreamIO/deepstream.io/blob/0daa9fad79d3cce4c65fa039d39b12fa2d23c996/src/tcp/tcp-socket.js#L93 I get the assumption that this will only work if it finds an end of a message a the end of your received chunk. It could perfectly be possible that this will never be the case. In that case you will grow your `_messageBuffer` endlessly - until you crash. And this not only with invalid input but also with perfectly legal input. The other cases are that you receive half a message that somehow contains a `MESSAGE_SEPERATOR` character somewhere in the middle or a combination of x messages, which might have been delivered at once (this case seems to be handled). 

Talking about these seperators, next point:

## Using character seperators to seperate message parts

This will **only** work if you forbid these characters in the **complete** content. I can't find references that this is the case. They may not be emitted by a JSON serializer, but from your documentation it is not really specified if all strings (also event names, user names, ...) and objects are JSON encoded and/or somehow sanitized or not.

All in all I would really advise anyone against using special characters for termination of fields and messages in any networking protocol. It is error prone and also slow to parse. Using length prefixing is a lot easier for most applications.

## Protocol messages

I haven't really looked trough that in detail. But one thing that I saw is that you probably also should have correlation IDs for all kinds of control messages (e.g. also subscribe, publish & co) to correlate requests for the system to do some things against the responses. And most likely also error responses for all of these. You can for example take a look at the WAMP specification which parameters could be needed, it's fairly good.

**Comment by WolframHempel** [comment]
Hey @Matthias247 

thanks, that's amazing feedback.

### TCP message processing
You are right. This is something we need to address quickly, as it presents a potential way to crash the server remotely. I'll raise an issue for it immediately. 
Our solution will be a `maxMessageSize` option. If the max message size is breached, the current buffer is emptied, scanned for EOM characters and only the last incomplete message remains. If no EOM characters are found a MAXIMUM_MESSAGE_SIZE exceeded error will be returned and whatever was received will get dropped. Love to hear your thoughts about this solution

### Using character seperators to seperate message parts
I completely understand your point on this one, but there were two considerations that led us to the current solution
- **Message Size**: Adding a message size upfront makes perfect sense, but it does increase the amount of characters that are being transferred by quite a bit. I agree that for most use-cases the increase is trivial and acceptable, but there are numerous usages in the Finance and IoT space where a large amount of extremely granular messages are transmitted, e.g. prices for a stock or readings from a sensor. Our goal always was, to reduce the deepstream protocol to the absolute minimum, so any message size header can add up to 30% to the total payload.
- **Escaping**: Yes, we could introduce character escaping for our control-characters. On the other hand, a lot of protocols and naming convention have a set of "forbidden" characters. In our case this set is just two invisible print-control whitespace characters. So far, we haven't had any reports of this causing issues (although I completely accept the theoretical possibility) and believe that the benefits of parsing speed make this a viable choice.

### Protocol messages
We do trust the order of things on the wire - so subscriptions to A, B and C should receive Acks in the same order. Actions that send data, e.g. setting a record's value or sending an event don't receive an 'ACK' for performance reasons. We rely on the server sending an error in those rare cases where it hasn't worked.

**Comment by Matthias247** [comment]
Your maxMessageSize solution will work, but it's not a good one. Imagine you get a high volume of messages, and each chunk that is delivered does not and at EOM. Now the latency for processing the first received message will be the time until MAX_MESSAGE_SIZE is exceeded or no new messages arrive -> bad. The only sane solution is to search each received chunk for the EOM char, if found and the first finding is not at the end of the chunk split the buffer, concat it to possibly previous received chunks and forward the messages. As you might imagine this is slow because you have to linearly search **all** chunks, and in bad cases you also have lots of buffer copy operations (if your remaining application can't cope with that messages are delivered as Buffer lists and not in a single Buffer). If you have a length prefixed message it gets much easier. You extract the length, can allocate a Buffer of this exact size (no realloc needed later), and you don't have to scan the payload.

This is also why I would argue that while I understand your reasons for doing it that way (as you described), you probably achieved exactly the opposite of what you wanted. Of course the overhead on the wire is lower (1byte vs probably 4 byte per seperator), but the processing overhead is much higher. And for most connections this is what counts. In your current implementation there is lots of overhead (buffer concatenation, splitting, the missing searching, probably the need for escaping, ...) that will mostly have a much higher inpact on throughput and latency than copying a few bytes more from/to the network stack. And if you think 4 bytes is too much you can even go to a variable-length encoding like Protobuf, Messagepack, CBOR, HPACK & Co are doing it. Then in most cases there would be 0 bytes overhead and a good middle ground for the parsing overhead. If you really care about high performance there's a lot of things to optimize before try to drop a few bytes of serializtion overhead, liking reducing the number of syscalls and memory allocations, using TCP Cork & Co or even going away from TCP, going away from node to something like Seastar, etc.

Having forbidden character will bite you sooner or later, when some application of a customer does not work and nobody knows why. Imho there are 2 viable ways: Explicitly forbid them (scan all payloads and reject ones that do not conform) and give error messages if someone tries to use them or allow all characters and apply the necessary escaping or guarding. And if you want to support binary payloads and don't want to enforce base64 encoding (which is sloooooow) then the way to implicitly forbid users not to use some byte values won't work anyway.

Regarding protocol messages another scenario:  
Your user sits in front of a SPA which is connected to your server. He selects something which triggers a subscription. Before the ACK is received from the server the user changes his mind and clicks something else, which would cancel the subscription and create a new one. When he then gets an ACK he might see this as a response for the first subscription (which he already forgot about) and may wonder why he later gets a second ACK. There should be no need for clients to track how many requests they sent and if there is anything outstanding for which now real answer is expected anymore. Having correlation IDs for these requests it is obvious to the client that only the second ACK is a response to his recent subscribe event.  
You are correct that the real situation is obvious for the server if the messaging ordering is guaranteed (which might also be hard in some scenarios, like if you route messages through external message brokers which don't guarantee message ordering or if you route them through multiple connections in parallel).



Oh, back to maxMessageSize: You will want it anyway. But only as some basic safety check for the server and not for deferring message processing.

**Comment by WolframHempel** [comment]
Closing this for now, please feel free to reopen
