### ISSUE TITLE
deepstream.io clients V4+

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io#1043]
This repo is for a discussion for development of a golang client using protobuf.

Generally the recommended approach would be to:

1) Get protobuf message parsing and building working. The client js example is [here](https://github.com/deepstreamIO/deepstream.io-protobuf-js). Once that works the client will be infinitely easier to write.
2) Build the simplest possible client to wrap your head around how its done. Example [here](https://github.com/deepstreamIO/deepstream.io-dummy-client/blob/master/src/index.ts)
3) Implement connection logic (tbh with the world of docker nowadays it feels like exiting the process and getting it recreated is cleaner than having to try reconnecting logic)
4) Implement Events (super simple)
5) Implement Records. If a goclient has reached this stage I'm happy to jump on calls and dedicate time to more detailed documentation, but I don't want to put in the effort now since we had loads of docs for V3 and very few clients came out of it (although it was way worse in terms of implementation and protocol).

Thanks!

**Comment by valentinvichnal** [comment]
Everyone is welcome to contribute:
https://github.com/deepstreamIO/deepstream.io-client-go
https://github.com/deepstreamIO/deepstream.io-protobuf-go

**Comment by valentinvichnal** [comment]
Did someone work on this before? Any recommended packages?

For WebSocket this should work: https://github.com/gorilla/websocket
