### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by sittingbool** [deepstreamIO/deepstream.io#1045]
accessing deepstream.io gives a 404

**Comment by dargolith** [comment]
Yep, can't reach API-documentation and need it.

**Comment by ghoskins** [comment]
Same here.

**Comment by yasserf** [comment]
Looking into it!

**Comment by yasserf** [comment]
https://deepstreamio.github.io/deepstream.io-website/

**Comment by yasserf** [comment]
Okay so github deploys deleted the CNAME field which broke

its up now but via HTTP
