### ISSUE TITLE
Websites down

### ISSUE THREAD

**Issue by janober** [deepstreamIO/deepstream.io#1062]
Is maybe not the perfect way to communicate that and you are probably already aware of that but all your websites are down.

**Comment by yasserf** [comment]
so it looks like for some reason AWS stopped accepting my card. Had to use another but account is still suspended. Now we wait I guess.

Also not sure why AWS stopped charging my registered card 🤦🏽‍♂️

**Comment by yasserf** [comment]
Okay, so it's back up for a while now, my AWS account just got suspended and I need to take that up with bank. Thanks for raising!

**Comment by janober** [comment]
Ah great. You are welcome. Enjoy the rest of the weekend!
