### ISSUE TITLE
Move project builds to circleci 

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io#1067]
Currently a massive circleci fanboi, but also because it’s easier to maintain one build over two different CI systems.

The majority of work is already done, just waiting for circleci to enable OS X builds.

Will need people to test artifacts for new build, but generally this should be a huge step in the right direction for testing plugins and so forth.

**Comment by slachtar** [comment]
Please let me know if I could help in testing.

**Comment by yasserf** [comment]
This is looking quite miserable. The free circleci tokens are a mess when you enable macos and native module building is also failing.

Since the current CIs work will close this down now as a nice to have.

Thank you .travis and appveyor 😁
