### ISSUE TITLE
add pagination support for list

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#107]
Improve handling of long lists by adding pagination options, e.g.

``` javascript
// load initial list
myList = ds.record.getList( 'super-long-list', { start: 2000, end: 2200 });

// change window
myList.setOptions({ start: 2200, end: 2400 });
```

**Comment by iamjochem** [comment]
hi there,

Deepstream looks very interesting, nice work! The lack of pagination makes me doubt whether it is a good fit for what I need (I am still investigating DS - there is also a good chance that I don't yet understand the feature-set properly), to that end I was hoping if you had any idea how complex and/or likely the list pagination feature is to be implemented (and if so on what kind of time-scale it might land?)

I have been reading your documentation and one thing I have not been able to determine is what kind of technical limits there are to Lists in terms of length ... 10,000 ? 100,000 ? 1,000,000? ... 

> as an aside - List pagination seems to have cross-cutting concerns with regard to your Search-Provider functionality ... both could do with pagination, and if you have pagination then you probably also want sorting & filtering ... maybe pagination, sorting & filtering should be only/primarily a Search-Provider responsibility?

**Comment by WolframHempel** [comment]
Hi @iamjochem,

lists are implemented on top of records and are subject to the same size limit of 4MB, so at say 20 characters per UTF-8 record name this leads to ca. 200.000 entries. You've probably seen this already, but the important thing is that lists contain the names of records, not their actual data - they're basically just arrays of short strings.

This is also why pagination hasn't been higher up the priority chain so far. As lists only contain references, it's relatively easy to build virtualized pagination on the client side, e.g. by loading a list of 20 entries and dynamically subscribing / unsubscribing only to the data that's in view.

Sorting and Filtering however is a different story. I agree that the various search providers (e.g. elasticsearch/rethinkdb) would need to take care of the sorting and filtering and deepstream would probably add pagination on top of the filtered result-set.

**Comment by ronag** [comment]
We've built infinite pagination on top of deepstream without to much hassle. I would say deepstream is an excellent match.

**Comment by stemuk** [comment]
Just to get it right: how would the pagination implemented so far work in a simple chat history where I would at first like to lazy-load the 20 latest messages till the user hits the scroll threshold. Then again the next 20 messages and so on. Is this possible with the method described by @WolframHempel ?

**Comment by Sotatek-NhuanHoang** [comment]
Create a record named "last_100_messages". It contains full detail of last 100 messages. If you send message or get previous messages, using api.

**Comment by fortranlee** [comment]
Use events to subscribe for new messages, and RPCs to request for previous messages.

**Comment by Sotatek-NhuanHoang** [comment]
What happen if user disconnected and reconnected

**Comment by fortranlee** [comment]
Use RPC to request latest messages whose id is grater than the last message id when reconnected

**Comment by Sotatek-NhuanHoang** [comment]
Great idea!

**Comment by yasserf** [comment]
Closing this issue as Lists as we know it in deepstream will be deprecated in a future release in favour of a custom type that doesn't require as much client logic and bandwidth. There are custom solutions using listening which work great but require a micro-service to do the pagination for you.

Something roughly like (for simplicity and using pseduo regex matchers):

```
client.record.listen('fruit/{from}/{to}', (name, { accept }) => {
  accept()
  const list = client.record.getList('fruit')
  list.subscribe(() => {
    client.record.setData(name, list.getEntries().slice(from, to))
  })
}) 
```

**Comment by yasserf** [comment]
Feel free to reopen if the example doesn't make sense!
