### ISSUE TITLE
TypeScript Compile Error : An accessor cannot be declared in an ambient context 

### ISSUE THREAD

**Issue by gigenthomas** [deepstreamIO/deepstream.io#1074]
typescript  : 3.5.3
Angular CLI: 8.3.28
Node: 12.18.0
@deepstream/client": 5.0.8

"typeRoots": [
      "node_modules/@deepstream/client/deepstream-client.d.ts" 
]

Get the following error after upgrade to Angular 8. Works just fine in Angular 7.

ERROR in node_modules/@deepstream/client/dist/connection/connection.d.ts:27:9 - error TS1086: An accessor cannot be declared in an ambient context.

27     get isConnected(): boolean;

Any help is greatly appreciated !!

Gigen

**Comment by jaime-ez** [comment]
Hi, can you re-open the issue in the deepstream client repo since it is a client issue? Thanks

**Comment by yasserf** [comment]
seems this is an issue with angular/typescript version

https://github.com/storybookjs/storybook/issues/9463

easiest thing is apparently adding  "skipLibCheck": true

**Comment by gigenthomas** [comment]
Thank you @yasserf . Confirmed that the above fix works 

Regards,
Gigen Thomas
