### ISSUE TITLE
Use deepstream client in node throws error

### ISSUE THREAD

**Issue by geohuz** [deepstreamIO/deepstream.io#1075]
I'm trying to programing a server side client to connect to deepstream server to manager list of task, so I'm using node with @deepstream/client, 

```
import DeepstreamClient from '@deepstream/client'

const dss = new DeepstreamClient('xxx.xxx.xxx.xxx:6020/deepstream')
dss.login()
```

run the script file with `node --experimental-modules taskserver.mjs  
`
And I get:  ```TypeError: DeepstreamClient is not a constructor```

Am I doing correctly?

**Comment by yasserf** [comment]
It’s { DeepstreamClient } since the function is not the default export.
