### ISSUE TITLE
[DOCS] Fix 404 on https://deepstream.io/install/

### ISSUE THREAD

**Issue by chris-aeviator** [deepstreamIO/deepstream.io#1077]
The deepstream.io install instructions that are linked on multiple docs are unavailable due to the following 404 message:

```
404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: install/index.html
    RequestId: 9B96257D20D749B9
    HostId: +/AAuO8WohNtfogri5Iez0y8a7mbzQkeey+Typ6PX68GPHE7KmG7cJJEBfkasvE5aZb0vOhBmUA=

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: error.html

```

**Comment by jaime-ez** [comment]
Hi, thanks for raising this issue.
A fix will be pushed and it should be live on the next deploy. If a link went by without being updated let us know.
Please for future website issues raise it on the website repo: https://github.com/deepstreamIO/deepstream.io-website/issues
And pull requests are always welcome :)
