### ISSUE TITLE
uws above version v18  causes uws http server to crash

### ISSUE THREAD

**Issue by fortranlee** [deepstreamIO/deepstream.io#1079]
The parameter `request` is no longer available since this commit

https://github.com/uNetworking/uWebSockets.js/commit/b4df9ebf5f4c3ecc884d5f5e0df1cd04b8caa7c3#diff-01c1a4e28835a7d097ce62009d6e3db1L97-R127

**Comment by jaime-ez** [comment]
Indeed, perhaps the upgrade property should be used now: 
https://unetworking.github.io/uWebSockets.js/generated/interfaces/websocketbehavior.html#upgrade and then pass the url to the ws connection as in this example: https://github.com/uNetworking/uWebSockets.js/blob/master/examples/Upgrade.js

Feel free to make a pull request, I'll try to work on it this weekend.

**Comment by yasserf** [comment]
👍 nice!
