### ISSUE TITLE
Deepstream Server doesn't respond request

### ISSUE THREAD

**Issue by Urahara** [deepstreamIO/deepstream.io#108]
Hi!

I'm trying to access the URL of my server created using deepstream but get no response (no error occurs and my request keep loading without response).

If i use TCP protocol i receive:
INCOMING_CONNECTION | from 127.0.0.1:44282 via tcp

But nothing happens too.

command: node start.js

I'm using Linux (Ubuntu).

```
var DeepstreamServer = require( 'deepstream.io' ),
    server = new DeepstreamServer();

// Optionally you can specify some settings, a full list of which
// can be found here //deepstream.io/docs/deepstream.html
server.set( 'host', '127.0.0.1' );
server.set( 'port', 6020 );

// start the server
server.start();
```

**Comment by yasserf** [comment]
Hey!

We don't respond to requests on the HTTP server in deepstream. If you would like to access the HTTP server to attach any responses you can create one and then pass it in via the following config in deepstream.io:
```
/**
* An existing http server to listen to rather
* then letting deepstream create it's own.
*
* Note: If webServerEnabled is false it will ignore
* the passed in httpServer
*
* @type net.HttpServer || net.HttpsServer
* @default true
*/
server.set( 'httpServer', httpServer );
```

If your just trying to connect to deepstream I would recommend looking at the client section in [the getting started tutorial](https://deepstream.io/tutorials/getting-started.html).

**Comment by yasserf** [comment]
Closing this issue for now, feel free to open if you have any follow question

**Comment by topcheese** [comment]
Perhaps a note should be added?  I expected the same results after installing.  Better yet a default test page.

**Comment by Urahara** [comment]
@topcheese Just run a localserver. :)

**Comment by WolframHempel** [comment]
@topcheese deepstream is just not a http server in the sense that it serves websites etc...

**Comment by topcheese** [comment]
Hi, thanks for the replies. I like the way Horizon does its server for RethinkDB, and include a simple page to test the connection.  I'm having issues  on windows 10 with ack_timeout.  It seems to connect to the database, but never reads or writes the data to record.  Still looking into it, seems to run In Ubuntu.

**Comment by topcheese** [comment]
I've been looking for a backend to use with Semantic-UI and I think this might be a perfect fit.  I'm trying to keep it small as possible, so it looks like I will be able to use it with DietJS to get routing.
