### ISSUE TITLE
Socket hangup error using version 5.1.1

### ISSUE THREAD

**Issue by dvkmca** [deepstreamIO/deepstream.io#1081]
Hi,

I am able to connect to deepstream using 3.1.0 version but I could not able to connect to deepstream with 5.1.0 version.

Please see attached screenshots and help me to fix the issue.

Thanks,
DVK
<img width="670" alt="ds3 1 0" src="https://user-images.githubusercontent.com/70193819/91142133-ec939300-e6cd-11ea-918e-194b66fb4d81.png">
<img width="673" alt="ds5 1 1" src="https://user-images.githubusercontent.com/70193819/91142152-f2897400-e6cd-11ea-8265-1465227f4b51.png">

<img width="784" alt="C# code" src="https://user-images.githubusercontent.com/70193819/91142117-e3a2c180-e6cd-11ea-8c2e-caba31e57f46.png">

**Comment by jaime-ez** [comment]
It's probably a client problem. which client are you using?

**Comment by jaime-ez** [comment]
Feel free to reopen if problem persist and share some code to replicate.

**Comment by yasserf** [comment]
The issue is your using the default path, which is using protobuf since v4. You need to use the older compatibility path in order to work. I'm not familiar with the .net library but my guess is it's the third parameter in the DeepstreamClient call.

**Comment by dvkmca** [comment]
Thank you all for your responses. I will recheck and let you know if still
problem persists.
