### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by bookking3000** [deepstreamIO/deepstream.io#1093]
Hi,

I've installed Deepstream on a Debian Server using this Tutorial: https://deepstream.io/tutorials/install/linux/.

I used v5.1.8.

I ran into the following error:
> CONFIG_TRANSFORM | Loaded content from /root/conf/permissions.yml for fileLoad(permissions.yml)
> INFO | logger ready: std out/err at level INFO
> INFO | server name: kiw821qi-prrbzyia8xs0
> INFO | deepstream version: 5.1.8
> INFO | configuration file loaded from conf/config.yml
> INFO | library directory set to: /root/lib
> CLUSTER_JOIN | kiw821qi-prrbzyia8xs0
> CLUSTER_SIZE | The cluster size is now 1
> TELEMETRY | ERROR | Invalid deployment id, must be uuid format. Feel free to use this one "da525fa2-c1c8-4767-9f61-b3a607d3671c"
> INFO | monitoring ready: Noop Monitoring
> INFO | subscriptions ready: Subscription Registry
> INFO | storage ready: Noop Storage
> INFO | cache ready: Local Cache
> INFO | permission ready: Valve Permissions
> INFO | locks ready: Distributed Lock Registry
> INFO | clusterNode ready: Single Cluster Node
> INFO | clusterRegistry ready: Distributed Cluster Registry
> INFO | clusterStates ready: Distributed State Registry
> INFO | telemetry ready: Deepstream Telemetry
> INFO | authentication ready: Open Authentication
> INFO | Listening for http connections on 0.0.0.0:6020
> INFO | Listening for health checks on path /health-check
> INFO | httpService ready: NodeJS HTTP Service
> INFO | connectionEndpoint ready: Binary WebSocket Connection Endpoint
> INFO | connectionEndpoint ready: WS Text Protocol Connection Endpoint
> INFO | connectionEndpoint ready: WS Text Connection Endpoint
> INFO | connectionEndpoint ready: HTTP connection endpoint
> INFO | Deepstream started
> Error: socket hang up
>     at connResetException (internal/errors.js:570:14)
>     at Socket.socketCloseListener (_http_client.js:389:25)
>     at Socket.emit (events.js:228:7)
>     at TCP.<anonymous> (net.js:664:12) {
>   code: 'ECONNRESET'
> }
> TELEMETRY | ERROR | Telemetry error: Error: socket hang up

I've already tried reinstalling and updating everything with apt, also I tested the [Docker-Container,](https://deepstream.io/tutorials/install/docker/) which has thrown the same error.

Thanks in advance

**Comment by yasserf** [comment]
Looks like that's just an issue with the telemetry not working. I haven't set up a new server/serverless yet after the previous machine was decommissioned. You can just turn telemetry off for now I believe.

**Comment by jaime-ez** [comment]
Yes that doesn't affect the server usage, just ignore the error or set telemetry to false in the config file.

**Comment by yasserf** [comment]
I'll get telemetry up again. I just don't have a prod db currently to save the data in, but should have one in a week.

**Comment by jaime-ez** [comment]
Hi, telemetry is disabled by default in the latest version.
