### ISSUE TITLE
Feature: Get a list of all available records/events/rpcs

### ISSUE THREAD

**Issue by redlock** [deepstreamIO/deepstream.io#1101]
Hello,
A much needed use case that I often face is to query the server for a list of available records (or other objects). Currently I can't find a way to do it. It helps a lot for debugging while in development; to see if a record was created and why some record is missing (record name misspelled, etc). 
Some metadata that can come along with the query, such as when the record was created and when it was last updated and the size of the record.

Thanks

**Comment by slachtar** [comment]
Hello,
IMHO record creation timestamp and any other information can be
added/updated by the client maniplulating the record. Later you can
retrieve this information.

As for checking if a record was created or not, the snapshot method will
return null if record does not exist.

Regards,

**Comment by redlock** [comment]
Hi,
Right now my clients connect to a metadata server to get a list of records that they can subscribe to. This metadata server won't be needed if I can simply query Deepstream for all available records. Also, sometimes you can't find a record and the reason is because there was a typo or the record name is different in some minor way. Having a list of available records you can quickly see where the fault lies.

Another use case is while in development you want to test whether you can subscribe to a record in your dev Deepstream instance, but you aren't sure what records are available (because it is a dev server use for testing). Every time I face this scenario I have to either guess the records name from memory or start some other client to create a new record.
 
Implementation wise it does seem like an easy feature to add.

**Comment by slachtar** [comment]
I see better your use case now, thank you.

My idea is to avoid any over head server side to keep it as light as
possible, that's why I suggested to do things client side.

May be it could be added as server feature that can be
activated/deactivated in config file.

**Comment by yasserf** [comment]
So the server already contains all of this logic inside of the state registries, the easiest thing to do would be to add a HTTP request that just dumps it out if the correct auth token is there. That way you don't need to add anything to clients or realtime protocols.

**Comment by redlock** [comment]
Another use case is that this allows for creating an admin console for a Deepstream server. Someone can build something similar to Firebase admin console, where you can inspect, brows and update data in a nifty web ui.

**Comment by jaime-ez** [comment]
Hi, if someone want's to implement this please make a pull request following yasser suggestion.
Thanks!
