### ISSUE TITLE
Update uWebSockets to 20.4.0

### ISSUE THREAD

**Issue by caracal7** [deepstreamIO/deepstream.io#1107]
Current version of uWebSockets working only in very old Node.js v15

I tried to build deepstream.io server with uWS 20.04.0 and upgrade Node.js to latest. 
I didn't find any issues in my projects after that.
New uWS makes possible to run deepstream server with latest Node.js 17.1.0☝️

I can't make pull request because I tried uWS in a little bit hacky way🤷‍♂️. I change it in a node_modules folder and rebuild the server. No changes in deepstream code needed.

My server running with latest uWS and Node.js without any problems

**Comment by jaime-ez** [comment]
Hi, make a pull request and CI should warn of any issues. However lets keep nodejs on the LTS version, that is 16.x.

**Comment by jaime-ez** [comment]
done on v6.0.0
