### ISSUE TITLE
Getting WebSocket Connection to failed error

### ISSUE THREAD

**Issue by gerrietech** [deepstreamIO/deepstream.io#1109]
I am trying to connect my javascript file to my deepstreamIO server but i get the error WebSocket connection to 'wss://localhost:6020/deepstream' failed
This is my js file:
```
var client = deepstream("wss://localhost:6020");
client.login({}, function(success, data) {
    print(succes+" "+data)
    if (success) {
        console.log("Connected to deepstreamm!!!")
    } else {
        console.log("failed: "+data)
    }
});
```
I am using a https server and the deepstreamIO server is on the same machine as the https server

**Comment by jaime-ez** [comment]
Hi, try `deepstream("localhost:6020/deepstream");` thats the default connection url
