### ISSUE TITLE
Bad JSON is returned

### ISSUE THREAD

**Issue by caracal7** [deepstreamIO/deepstream.io#1112]
Bad JSON is arrived to client after another client call `client.record.setData('my_record', my_json);`

I get this issue only with one specific query from DB. Result after this query is 100% valid JSON (about 3K lines).
After I call `client.record.setData('my_record', my_json);` on node.js client I get this error in browser(Safari or Chrome)

![Снимок экрана 2021-12-21 в 17 13 22](https://user-images.githubusercontent.com/5710103/146944723-b942239b-be3c-4659-aa3e-f659e785e008.png)

Error in line 22

![Снимок экрана 2021-12-21 в 17 26 20](https://user-images.githubusercontent.com/5710103/146948082-46bd1c64-b0c8-4f96-ab05-17c4ae7efb5b.png)

if I `console.log(message.data)` before line 22 I get string with four [U+FFFD](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character) characters in a random places. Thats why JSON.parse() gets the error

![Снимок экрана 2021-12-21 в 17 49 20](https://user-images.githubusercontent.com/5710103/146949534-9e10a1bf-ab71-43fd-80ec-6f483569198b.png)

![Снимок экрана 2021-12-21 в 17 49 43](https://user-images.githubusercontent.com/5710103/146949544-a1b3c092-4e80-4843-8d68-8a794fac0eb7.png)

Looks like a bug with message encoding/decoding 

I don't know how to isolate and reproduce this issue right now.

Sorry for my terrible english

**Comment by jaime-ez** [comment]
Hi, I'm going to close this here because it should be opened in the deepstream-client-js repo. please reopen there if problem persists

And I don think it is deepstream related, all encoding/decoding is done using protobufjs...please double check that your original data is not corrupt, adn take a look at https://github.com/protobufjs/protobuf.js/issues if there is something there.

**Comment by caracal7** [comment]
> And I don think it is deepstream related, all encoding/decoding is done using protobufjs...please double check that your original data is not corrupt, adn take a look at https://github.com/protobufjs/protobuf.js/issues if there is something there.

You are right. 
This is a problem with protobufjs. 
Protobufjs is not well maintained anymore. 400+ opened issues. Seems like to solve any problems with Protobufjs is too difficult. I changed **connectionEndpoints** to **ws-json** and it is solve my problem and data is not corrupted.

Is it not a problem to use **ws-json** in production?

**Comment by jaime-ez** [comment]
It is not optimal to use the json endpoint in production in terms of ressource efficiency, but it can be done
