### ISSUE TITLE
Subscription getting triggered after a delay

### ISSUE THREAD

**Issue by Rajat619** [deepstreamIO/deepstream.io#1115]
**• Hardware Platform **
(MACOS M1/ Docker image 16.2)
**• DeepStream Version **
“@deepstream/cache-redis”: “^2.0.9”,
“@deepstream/client”: “^5.2.4”,
“@deepstream/clusternode-redis”: “^1.0.1”,
“@deepstream/server”: “^5.2.4”,
“@deepstream/storage-postgres”: “^3.0.4”,
**• How to reproduce the issue? **
One of my subscriptions where we keep on adding new values to the record set is getting triggered like 500 times. At that time, the subscription to update the record data is not working properly. It is getting delayed by several seconds (5-6s at least) **

**Comment by jaime-ez** [comment]
Hi, please provide example code to reproduce and what are your deepstream client options ?
