### ISSUE TITLE
No declaration files in NPM package

### ISSUE THREAD

**Issue by romanzy-1612** [deepstreamIO/deepstream.io#1118]
**Describe the bug**
No typing in the latest npm release. The error message is
```
Could not find a declaration file for module 'deepstream.io'.
```

**To Reproduce**
1. Initialize new package.json
2. Run `npm install deepstream.io`
3. `import { Deepstream } from 'deepstream.io'`

**Expected behavior**
Types should be included as this server is written in TypeScript

**NPM package version**
3.2.5

**Comment by romanzy-1612** [comment]
Thank you! This solved the issue.

As a new user I was really confused when it came to installing client aswell. So there are 2 packages: `@deepstream/client` and `deepstream.io-client-js`. I assume that `@deepstream/client` and `@deepstream/server` are for the latest version (v6), right?

The documentation for this library is the best i've seen, but it is really not clear what packages to install or how to get types working for the browser version as well (because it needs to be imported on window).

**Comment by jaime-ez** [comment]
If you're working on a nodejs environment for developing your client (using webpack, babel, etc) check out https://deepstreamio.github.io/docs/tutorials/install/nodejs, there you will get type definitions.

and yes the packages named `deepstream.io` are the older version 3, that uses a different message protocol. Some people still use them, thats why they're still available. But only the latest packages named `@deepstream` are maintained.

Feel free to ask questions if you have any!

**Comment by romanzy-1612** [comment]
I was able to finally resolve this issue by switching to vite. Will post here in case someone has the same issue.

How to get this working:

1.) Scaffold new project via `npm create vite@latest my-vite-app`
2.) Edit vite.config.ts to this:
```
import { defineConfig } from "vite";

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    lib: {
      entry: "src/my-element.ts",
      formats: ["es"],
    },
    rollupOptions: {
      input: {
        main: "./index.html",
      },
    },
  },
  resolve: {
    alias: {
      "@deepstream/client": "@deepstream/client/dist/bundle/ds.min.js",
    },
  },
});
```
3.) Use deepstream normally 
```
import { DeepstreamClient } from "@deepstream/client";
const client = new DeepstreamClient("localhost:6020");
```
