### ISSUE TITLE
deepstream triton backend exit error

### ISSUE THREAD

**Issue by Smart-Bobo** [deepstreamIO/deepstream.io#1121]
When I use Python deepstream to call the Triton ensemble model (such as pre-processing, inference and post-processing), no error is reported in the model inference stage, but an error is reported at the end of the model.
The error message is as follows.
This question puzzled me. Ask the developer for help

chinese describe：
当我使用python deepstream调用triton集成模型（比如前处理、推理、后处理），在模型推理阶段没有报错，但是在模型结束的时候报错了。
错误信息如下。
这个问题让我很疑惑。请求开发人员的帮助

Cleaning up...
Cleaning up...
ERROR: infer_trtis_server.cpp:881 Triton: failed to stop repo server, triton_err_str:Internal, err_msg:Exit timeout expired. Exiting immediately.

**Comment by jaime-ez** [comment]
wrong repository
