### ISSUE TITLE
Endpoint not found Error for Http Request

### ISSUE THREAD

**Issue by rakshaySingh888** [deepstreamIO/deepstream.io#1125]
We are getting "Endpoint not found" if we are trying to emit data to deepstream from an HTTP request. Am I missing anything in the config?

const requestBody = {
  body: [{
    topic: 'event',
    action: 'emit',
    eventName: 'test-event',
    data: { some: 'data' }
  }]
};

Sending this is in body for the url: localhost:6020

**Comment by jaime-ez** [comment]
see the docs for the default path: https://deepstreamio.github.io/docs/docs/server/configuration#http
