### ISSUE TITLE
Other free alternative

### ISSUE THREAD

**Issue by ScreamZ** [deepstreamIO/deepstream.io#1127]
Just opening this thread in case someone is looking for a free and open-source alternative that can be installed on premise.

We have thinks like SUPABase, or Kuzzle but they require database and maybe other services.

Also looked at game engines (which fullfils purpose not so different)
- https://www.colyseus.io/
- https://heroiclabs.com/

**Comment by jaime-ez** [comment]
Hi, thanks for supporting the project, but this is not an issue. If you want to discuss something please use the discussions forum https://github.com/deepstreamIO/deepstreamIO.github.io/discussions

Best
