### ISSUE TITLE
starting deepstream as daemon fails

### ISSUE THREAD

**Issue by slachtar** [deepstreamIO/deepstream.io#1129]
**Describe the bug**
when starting deepstream as daemon, it fails.

**To Reproduce**
./deepstream daemon

node:internal/modules/cjs/loader:949
  throw err;
  ^

Error: Cannot find module '/opt/deepstream/start'
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.5.0

**Expected behavior**
start ds

**Screenshots**

**Server version**
DS 7.0.1 on ubuntu 20.04

**Comment by jaime-ez** [comment]
Hi, has it ever worked? I have never used it since I just use pm2 ... 
Maybe it's best to eliminate that feature altogether and suggest using pm2, forever or any other process manager?

**Comment by jaime-ez** [comment]
Hi, just made a release with a bug fix that was working locally on my machine, but when downloading the binary from github it doesnt. Can you check if it works for you?

**Comment by slachtar** [comment]
Hi,
Thank you for your reply.
The error appeared when I was generating deepstream.service linux systemd
service via the command line: deepstream service add ...
The problem is that this command generates deepstream daemon instead of
deepstream start in the deepstream.service file.
I agree you with that the feature should be removed because we're using
process mangers like pm2 or systemd or others. Just we need to fix the
deepsteam.service generator so it generates start instead of daemon.
As for testings, I'm using the binary version, will try some code when I'll
be in office today.
Thank you

**Comment by jaime-ez** [comment]
it should be fixed on v7.0.3, please reopen if you still have issues
