### ISSUE TITLE
Is it possible to transfer an image/video (binary message) to deepstream server?

### ISSUE THREAD

**Issue by Rajan** [deepstreamIO/deepstream.io#113]
If not, what would be the best approach to implement this?

**Comment by WolframHempel** [comment]
Deepstream is a server for realtime text messaging and data-sync. To process video's and images you'd be looking for a classic http server with support for binary data, HTTP POST and the likes. 

If you're using NodeJS, you'd be looking for e.g. [ExpressJS](http://expressjs.com/) or [Koa](http://koajs.com/) - both of which can easily be used together with deepstream.

Just spin up your express server, get the underlying http server instance from it and pass it to deepstream using

```
dsServer.set( 'httpServer', httpServer );
```

That's pretty much it. We're planning on adding more code-samples and a tutorial to the deepstream website soon

**Comment by Rajan** [comment]
Ahh. I was thinking to build something while avoiding HTTP entirely.
Engine.io does support Binary data transfer. So, I was assuming that was
possible.

**Comment by petemill** [comment]
You could encode to base64, right?

**Comment by Svenskunganka** [comment]
@petemill yes but that adds quite a large overhead, and there's also the issue that most databases that support binary data has a different kind of API for that - and usually have a size limit on documents in which the Storage Connector you use would simply just insert it into the database as a regular field.

It's better to connect Deepstream to a simple Express server that has a file upload route. WebSockets require an HTTP server for the initial upgrade handshake either way so this is the best solution. If you use RethinkDB, you still get the real-time power of Deepstream when you change a file document that Deepstream may be subscribed to. If you use something else that doesn't have the real-time capabilities like RethinkDB has, you can still notify Deepstream users by publishing to the Message Connector (e.g Redis pub/sub or RabbitMQ).

**Comment by qrpike** [comment]
But doesn't WebSockets protocol have the ability to send binary data?

- https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

**Comment by ronag** [comment]
@qrpike: It's still a bad idea since processing large files would significantly slow down the deepstream server, things like record updates and messages would have to wait for the file to be transferred etc...

**Comment by qrpike** [comment]
@ronag Agreed, however it makes a lot of sense for things like protobuf's which can do bitpacking and are substantially smaller than JSON. Reducing bandwidth heavily.

**Comment by ronag** [comment]
@qrpike: That would be a different issue though :)...

**Comment by WolframHempel** [comment]
It's a fair question/feature-request that has come up a few times, similar to http transfers or general asset hosting. 

Technically, these would be possible (if necessary by establishing a secondary connection for the image data so to not clock up the primary one) - but its just not what deepstream is about.

Deepstream is a fast server for realtime data There is a wealth of very mature solutions for image/video/asset handling that can easily be used in conjuction with it (see https://deepstream.io/tutorials/integrations/other-http/). 

Deepstream is about realtime

**Comment by Rajan** [comment]
body, p, div {
        font-family: arial;
        font-size: 14px;
      }
      body {
        color: #000000;
      }
      body a {
        color: #1188E6;
        text-decoration: none;
      }
      p { margin: 0; padding: 0; }
      table.wrapper {
        width:100% !important;
        table-layout: fixed;
        -webkit-font-smoothing: antialiased;
        -webkit-text-size-adjust: 100%;
        -moz-text-size-adjust: 100%;
        -ms-text-size-adjust: 100%;
      }
      img.max-width {
        max-width: 100% !important;
      }
      .column.of-2 {
        width: 50%;
      }
      .column.of-3 {
        width: 33.333%;
      }
      .column.of-4 {
        width: 25%;
      }
      @media screen and (max-width:480px) {
        .preheader .rightColumnContent,
        .footer .rightColumnContent {
            text-align: left !important;
        }
        .preheader .rightColumnContent div,
        .preheader .rightColumnContent span,
        .footer .rightColumnContent div,
        .footer .rightColumnContent span {
          text-align: left !important;
        }
        .preheader .rightColumnContent,
        .preheader .leftColumnContent {
          font-size: 80% !important;
          padding: 5px 0;
        }
        table.wrapper-mobile {
          width: 100% !important;
          table-layout: fixed;
        }
        img.max-width {
          height: auto !important;
          max-width: 480px !important;
        }
        a.bulletproof-button {
          display: block !important;
          width: auto !important;
          font-size: 80%;
          padding-left: 0 !important;
          padding-right: 0 !important;
        }
        .columns {
          width: 100% !important;
        }
        .column {
          display: block !important;
          width: 100% !important;
          padding-left: 0 !important;
          padding-right: 0 !important;
        }
      }
    
    
    
     
  
  
    
      
        
          
            
              
                
                  
                    
                      
                        
                          
                          
                            
                              
                                
    
      
        
          
        
      
    
  
    
      
        
          
        
      
    
  
    
      
        
            Lucky you
        
      
    
  
    
      
        
          
        
      
    
  
    
      
        
             

We just got you a free premium invite thanks to the 38 people from your Gmail network who recently joined us. 

 


We showcase every idea, project, and start-up from around the world and connect them to the millions of people who could work with them, including you.

 

        
      
    
  Get your invite 
    
      
        
            - from California with love -
        
      
    
  
    
      
        
          
            
              
            
          
        
      
    
  
    
      
        
            

	
		
			
			 
			
			 
		
	



	
		
		
		
			2017 Wittycircle Inc
		
		
		
		
			169th 11th St, San Francisco, CA
		
		
		
		
			wittycircle.com
		
	



        
      
    
  
                              
                            
                          
                          
                        
                      
                    
                  
                
              
            
          
        
      
    
  
This email was sent by Wittycircle, to unsubscribe click here.

**Comment by yasserf** [comment]
@Rajan deleted your message since it was a lil spammy.

On this issue though, version 4 is a binary protocol and hence this issue will be quite easy to implement. We will be looking to implement it with events and RPCs initially since records are JSON.
