### ISSUE TITLE
Is there a simple way to not receive message send from self?

### ISSUE THREAD

**Issue by geohuz** [deepstreamIO/deepstream.io#1130]
Is there a server setting which make sure a provider client doesn't get the change to record/list by itself?

**Comment by jaime-ez** [comment]
you mean that you change a record data but don't want to susbcribe to it? if so, you should use `client.record.setData` , look the docs [here](https://deepstreamio.github.io/docs/docs/client-js/datasync-client-record#clientrecordsetdataname-path-data-callback)

**Comment by geohuz** [comment]
Thanks! @jaime-ez

**Comment by jaime-ez** [comment]
Ok, no you can't do that currently at the server level. Data changes are broadcasted without informing which user made the change. My advice is to review your client side logic in order to avoid loops.

**Comment by geohuz** [comment]
All right, currently I'm using the ```client.record.has(recordName)``` as a way to check the client memory if the record has been fetched, something like:

```js
  let localRecordContent = {}
  let localRecordExist = await dsc.record.has(recordName)
  if (localRecordExist) {
    localRecordContent = dsc.record.getRecord(recordName).get()
  } 
```

not sure if this works.

**Comment by jaime-ez** [comment]
You're mixing concepts:
`client.record.has` tells you wether the record exists in the server (including database/cache if you're using)

If you want to keep track of records at the client level, one way is to use a singleton pattern:

```js
const client = new DeepstreamClient()
const currentRecords = new Map()
const getRecord = (recordName) => {
  let record = currentRecords.get(recordName)
  if (!record) {
    record = client.record.getRecord(recordName)
    currentRecords.set(recordName, record)
  }
  return record
}
const discardRecord = (recordName) => {
  const record = getRecord(recordName)
  record.discard()
  currentRecords.delete(recordName)
}
const deleteRecord = (recordName) => {
  const record = getRecord(recordName)
  record.delete()
  currentRecords.delete(recordName)
}

```

**Comment by geohuz** [comment]
Thank you @jaime-ez !  That should solve the problem!
