### ISSUE TITLE
Is there documented way to remove items from record object with path?

### ISSUE THREAD

**Issue by geohuz** [deepstreamIO/deepstream.io#1131]
There is no document about manipulate the record object by using the path, execpt for set a property, I counldn't find how to remove property from map, remove item from array, append to the tail of the array (not by index) etc. Could someone help with the situation?

Thanks!

**Comment by jaime-ez** [comment]
Hi. read the docs please, the updated version is https://deepstreamio.github.io/

remove property from record: https://deepstreamio.github.io/docs/docs/client-js/datasync-record#erasepath-string
append element at the end of the list: https://deepstreamio.github.io/docs/docs/client-js/datasync-list#addentry-entry-index- (just don give an index))
https://deepstreamio.github.io/docs/docs/client-js/datasync-list#removeentry-entry-index-

**Comment by geohuz** [comment]
@jaime-ez thanks for the reply, I think there is a question left, that is how to append item into nested array in a record? Should I always specify the index? 

Thanks

**Comment by jaime-ez** [comment]
a record is just a JSON object. Do it as with any JSON object...
