### ISSUE TITLE
Presence - knowing which clients are connected

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io#118]
This is a placeholder for having Presence functionality in deepstream, so we could know which clients are currently logged in.

This is a placeholder for any suggestions on the topic before we do any concrete API planning.

**Comment by AlexBHarley** [comment]
I would like to work on this

An initial client API for basic use could be:

`client.presence.get() // returning usernames of connected clients`
`client.presence.onLogin( callback ) // notification of client login`
`client.presence.onLogout( callback ) // notification of client logout`

**Comment by yasserf** [comment]
Awesome!

We generally came up with a very similary API:

```javascript
ds.getPresentClients(function( <map> connectedClients ){
    //connectedClients
    {
        'userA': {} // potentially will contain connectionCount, loginTime, ping etc.
    }
});

ds.onPresentClientAdded( function( userName ){
});

ds.onPresentClientRemoved( function( userName ){
});
```

We want to have connected clients be a map for easy lookup, and mostly because we want to have the potential of sending meta data associated to the user, such as device type, amount of devices logged in and others.

To simplify things further ( and since knowing who is only online requires you to be online ) the get method can work async ( same as snapshot ) so that it always retrieves it from the server, and clientAdded/clientRemoved events only send individual client changes.

Hope that makes sense!

**Comment by timaschew** [comment]
I think we can improve and make the naming more clear. 
Maybe a combination of `onLogin` and  `onPresentClientAdded`, or we replace `Added` by `Connected`?

**Comment by ecerroni** [comment]
It would be useful to allow the client to pass an additional `payload` besides the 'authParam' at login.

This payload should be available to both `ds.getPresentClients` and `ds.onPresentClientAdded` so that can be retrieved by any client.
