### ISSUE TITLE
A way to delete a field from document via deepstream Record

### ISSUE THREAD

**Issue by vsadokhin** [deepstreamIO/deepstream.io#119]
Hello there!

I explained the issue on [stackoverflow](http://stackoverflow.com/questions/36473729/delete-record-field-via-deepstream-record/36494764). It's about an ability to delete a field from document using Record like. Consider a document looks like:
```javascript
{
  fieldToClean: {
    fieldA: '..',
    fieldB: '..',
    fieldC: '..'
  }
}
```

And I'm looking something like that:
```javascript
record.delete('fieldToClean.fieldB')
```
or
```javascript
record.set('fieldToClean.fieldB', undefined)
```

I found the only way to do it fetching whole document, deleting unnecessary field and then set the document again like:
```javascript
var record = deepstream.record.getRecord('<proper path>')
record.whenReady(function(){
  var fieldToClean = record.get('fieldToClean')
  delete fieldToClean.fieldB
  record.set('fieldToClean', fieldToClean)
})
```

**Comment by yasserf** [comment]
Bit of overlap with #29, which deals a bit with edge cases around Arrays. Be good to target both when implementing.

**Comment by yasserf** [comment]
Closing this since it is a client issue:

https://github.com/deepstreamIO/deepstream.io-client-js/issues/111

**Comment by ronag** [comment]
Why doesn't this work?

```record.set('fieldToClean.fieldB', undefined)```
