### ISSUE TITLE
feature req: Offline mode

### ISSUE THREAD

**Issue by gebrits** [deepstreamIO/deepstream.io#12]
Very interesting project. Kudos!

If you don't mind, I'm listing a couple of feature requests that might be discussion worthy. 

First up: Offline mode -- allowing mobile devices to go offline, save to local storage and resync + patch when coming back online.

**Comment by WolframHempel** [comment]
Thanks for suggesting, that is already planned (to an extend). If the connection drops it currently stores messages in memory and sends then once the client is online again. I think changing this to localstorage makes a lot of sense.

**Comment by gebrits** [comment]
Great, watching

**Comment by yasserf** [comment]
As mentioned by @gothy in hoxton-one/deepstream.io#38 if the app is loaded without an internet connection we might want to revisit what is sent to the backend since ack's will timeout.

**Comment by ecerroni** [comment]
There is any ETA about the above feature requests? 

Offline mode 
Loading client even if no internet connection

**Comment by yasserf** [comment]
@ecerroni not yet unfortunately. We will be looking to implement these in new clients such as android/ios due to their mobile/native behavior and then move changes back once we are happy with the API

**Comment by yasserf** [comment]
https://github.com/deepstreamIO/deepstream.io-client-js/issues/174

**Comment by snowyu** [comment]
Is there any progress, since two years have passed?

**Comment by DiegoBM** [comment]
Interested on this as well? Did it get finally shipped on any of the versions after 1.0?

**Comment by alexiri** [comment]
I'm also very interested in this. I'm working on a mobile app that should ship with data for offline use, but that should be able to update its data if it has network access.

Has there been any progress? As I understand it now, I'd have to re-download all the data when the app is able to connect, which is far from ideal.

**Comment by yasserf** [comment]
This is finally in V4! RC is out now. Can't believe I'm finally knowing out such an early request!

**Comment by yasserf** [comment]
http://deepstream.io-v3.s3-website-us-east-1.amazonaws.com/releases/client-js/v4-0-0/index.html

**Comment by slachtar** [comment]
Super good news, thank you.
