### ISSUE TITLE
Deepstream does not differentiate between \u001e & \u001f characters in Auth Messages

### ISSUE THREAD

**Issue by adityamenon** [deepstreamIO/deepstream.io#120]
I noticed that, when I send a running deepstream server the following Auth message:
```
{"raw":"A\u001fREQ\u001f{\"username\":\"Wolfram\",\"password\":\"blah\"}","topic":"A","action":"REQ","data":["{\"username\":\"Wolfram\",\"password\":\"blah\"}"]}
```
with the following lines uncommented on `start.js`: https://github.com/deepstreamIO/deepstream.io/blob/9233441ec5b54b21974cf677724db49b16cfda9e/start.js#L29..L42

I get the message `AUTH_SUCCESSFUL | Wolfram` from the server.

However, according the [message structure](https://deepstream.io/info/messagestructure/index.html) documentation:
```
<topic>|<action>|<data[0]>|...|<data[n]>+
| and + are used in these examples as placeholders, messages are actually separated by invisible Ascii control characters ("record separator" (30) and "group seperator" (31))
``` 

I would expect the server to fail **unless** it gets `{"raw":"A\u001eREQ\u001f{\"username\":\`... as the message.

Is this a bug or expected behavior?

**Comment by yasserf** [comment]
To make sure, your sending down:

A|REQ|{"username":"username","password":"blah"}+

where as you stated, | and + are used in this example as placeholders, messages are actually separated by invisible Ascii control characters ( "record separator" (30) and "group seperator" (31) )

Or are you sending `A|REQ|{"username":"username","password":"blah"}`? ( without the char 31 ending? )

**Comment by adityamenon** [comment]
I'm sorry, I got it correct now, I wasn't reading the docs properly, of both Go & deepstream.

I just verified that sending the wrong message, with `|` at the end instead of `+` doesn't actually work as I claimed in my bug report. Nor does omitting `+` work.

On a happy note, this helped me figure out how to use Go syntax to get the right characters (updating the wiki). Thanks for your time!

**Comment by yasserf** [comment]
Nice! If you think the docs didn't make it clear just let us know where and we can try improve the wording or examples
