### ISSUE TITLE
cannot subscribe to deepstream started event when using redis connector

### ISSUE THREAD

**Issue by timaschew** [deepstreamIO/deepstream.io#122]
This works fine:
```
deepstream.on('stopped', () => {
  console.log('stopping deepstream')
})
deepstream.on('started', () => {
  console.log('deepstream server started')
})

deepstream.start()
console.log(deepstream._events)
```
But when I add the redis connector before starting deepstream:
```
deepstream.set('cache', new RedisCacheConnector ({
  port: 6379,
  host: 'localhost',
}))
```

then my __started__ event handler is not called anymore
but I still get the same output for `deepstream._events`

```
{ stopped: [Function], started: [Function] }
```

**Comment by yasserf** [comment]
This was probably due to redis never connecting properly? Tested multiple times since then and works ( on all os systems =D )
