### ISSUE TITLE
Differential Synchronization in Deepstream

### ISSUE THREAD

**Issue by philmaker1** [deepstreamIO/deepstream.io#138]
I'm a huge fan of deepstream. I've also been exploring into using differential synchronization as a potential strategy for messaging in distributed apps. e.g. manipulating the state of data instead of implicitly passing messages. The project AeroGear employs differential synchronization. I just think that it would be very nice to operate directly on simple data structures which get synchronized automatically between clients or agents on the server. This might not be ideal for every situation but I like it because it's simple. Does anyone have any interest in this or implementation thoughts on integrating differential synchronization within deepstream?

Thanks,
Philip

**Comment by WolframHempel** [comment]
Hi @philmaker1 ,

I'm a bit confused, isn't that exactly what deepstream's records are?

**Comment by WolframHempel** [comment]
Closing this for now, please feel free to reopen.

**Comment by philmaker1** [comment]
I wasn't completely clear in my original post. My intention is to re-implement one of the following projects using on top of deepstream (potentially). They are passive synchronization frameworks which employ differential synchronization.

https://github.com/janmonschke/diffsync
https://github.com/benjamine/dialogo

Just commenting on something which interests me greatly. No action needed.
