### ISSUE TITLE
feature req: elasticsearch as read only adapter for advanced querying

### ISSUE THREAD

**Issue by gebrits** [deepstreamIO/deepstream.io#14]
A great setup I'm using a lot is letting the Rethinkdb changefeed update Elasticsearch which in turn is used for reads/querying only.

It would be great to integrate the above with deepstream somehow, so the frontend could do all sorts of advanced querying. 

Thoughts?

**Comment by yasserf** [comment]
Sounds good, just for my benefit though: Would you expect deepstream to connect to elastic search directly? Otherwise you could use the existing [connector for RethinkDB](https://www.npmjs.com/package/deepstream.io-storage-rethinkdb)

**Comment by gebrits** [comment]
Deepstream would probably connect to ES directly for queries. There would be no write/change interface between deepstream and ES since this is all handled as per the rethinkDB changefeed setup above.

**Comment by thedrow** [comment]
Yes please :)

**Comment by yasserf** [comment]
@gebrits We just released a version of a [elastic search connector](https://github.com/deepstreamIO/deepstream.io-storage-elasticsearch) for deepstream.

This directly uses  elasticsearch as the main db which isn't the kind of setup your using, but it would be good to get your thoughts on it as well as see if there's a way we can possibly use parts of it for your use case.

Thanks!

**Comment by yasserf** [comment]
Closing this issue. Be interesting to see what kind of API a read only adaptor would have. My guess would be it would provide RPC's since elastic search doesn't provide realtime updates on queries.
