### ISSUE TITLE
runtime cli

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#140]
As part of the permission based config / executable distribution it would be great to offer a runtime command line interface, similar to what e.g. nginx provides. This might require bundling deepstream with a daemon - we'll need to look into this.

Generally, here's what I'd propose

```shell
$ deepstream start
$ deepstream stop
$ deepstream status
$ deepstream reload-permissions //reload permissions on the fly
...more?
```

**Comment by yasserf** [comment]
We currently have an init.d file for this to work on linux using:
```
service deepstream start
```

I suggest we go down the standard console application for when we have the folder structure deployment ( influenced by nginx ):

```
deepstream  start [-c /path/to/config]
deepstream  stop
deepstream  quit [ this isn't supported by deepstream, and requires us to gracefully close connections and expect a longer closing down period] 
deepstream  reload-permissions [-p /path/to/permissions]
deepstream  reload-users [-p /path/to/users]
deepstream install cache redis/latest [-p /path/to/libs]
```

**Comment by timaschew** [comment]
`start`, `start -d` (background),  `stop`, `status` is done in #189 
`intall` was already done in #181 

The current option to pass the path to the libs is `-l` or `--libPrefix`.

BTW: Here is the snippet to use a local domain socket to communicate between different processes: https://gist.github.com/timaschew/278db182a964fde5fb21119fc49c3b3a

It's the `server.listen(path[, backlog][, callback])` API:

> On UNIX, the local domain is usually known as the UNIX domain. The path is a filesystem path name. It gets truncated to sizeof(sockaddr_un.sun_path) bytes, decreased by 1. It varies on different operating system between 91 and 107 bytes. The typical values are 107 on Linux and 103 on OS X. The path is subject to the same naming conventions and permissions checks as would be done on file creation, will be visible in the filesystem, and will persist until unlinked.
>
>On Windows, the local domain is implemented using a named pipe. The path must refer to an entry in \\?\pipe\ or \\.\pipe\. Any characters are permitted, but the latter may do some processing of pipe names, such as resolving .. sequences. Despite appearances, the pipe name space is flat. Pipes will not persist, they are removed when the last reference to them is closed. Do not forget JavaScript string escaping requires paths to be specified with double-backslashes, such as:

See here for more information: https://nodejs.org/api/net.html#net_server_listen_path_backlog_callback
