### ISSUE TITLE
Background / Push notification sync

### ISSUE THREAD

**Issue by jcampbell05** [deepstreamIO/deepstream.io#142]
How does deepstream sync with iOS apps when they are in the background via push notifciations or HTTP ?

**Comment by yasserf** [comment]
Hey @jcampbell05,

Deepstream.io doesn't currently have a native iOS client to support push notifications. Follow #68 for any updates.

Worth mentioning if you write an application using Cordova or PhoneGap it should run the application as a background task which means you would get updates via the websocket connection.

**Comment by yasserf** [comment]
Closing issue for now, feel free to reopen if you want any further details
