### ISSUE TITLE
out-of-the-box authentication handler

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#145]
When distributed as an executable, deepstream needs to provide ways to authenticate a user. I'd like to suggest the following three built in choices

### Open
```javascript
{
	authentication: {
		type: 'open',
		settings: {}
	}
}
```
As simple as it gets. Let's everyone in and assigns the username `open`

### File based
```javascript
{
	authentication: {
		type: 'file',
		settings: {
			path: './users.json',
			salt: '8461e583d072df',
			hashAlgo: 'sha-1'
		}
	}
}
```
Reads user credentials from a JSON file with the below format. Users can specify the path of the file, which hashing algorithm to use, which salt to append to the hashes and whether the file should be watched. If watch: true, deepstream will reload the authentication data whenever the file changes.
```javascript
{
	"mike24": { "password": "ffa6706ff2127a749973072756f83c532e43ed02", "data": {} }
	"trix": { "password": "be23bb299c1219418461e583d072df4e307fcac3", "data": {} }
}
```
the data field in the file can be used to specify arbitrary authentication data, e.g. roles or access levels.

### Http Webhook
```javascript
{
	authentication: {
		type: 'http-hook',
		settings: {
			endpointUrl: 'https://myserver.com/authenticate-user',
			permittedStatusCodes: [ 200 ],
			requestTimeout: 1000
		}
	}
}
```
Allows to specify an http endpoint that will be contacted via post request whenever a user tries to connect to deepstream. The post request's payload contains the JSON encoded authentication and connection data
```javascript
{
	connectionData: { /***/ },
	authData: { /***/ }
}
```
The http server can now respond with 200 and an optional JSON payload for authData if the connection is authenticated. **Everything** other than a 200 status-code will be interpreted as a rejection and the payload will be used as a rejection message

### Other?
I think between these three, we're covering most usecases. OpenAuth etc. would certainly be nice, but still requires you to manage the credentials returned by the open auth provider - so it can't be configuration only

**Comment by KrishnaPG** [comment]
It would be great if a 'function handler' can be added as additional mechanism. Http Webhook can resolve many cases, but when using DB based authentication, not all DB support Http API straight away and creating another dedicated server for HTTP before the DB could be complex. 

A function auth handler will accept the auth data and returns a promise that finally gets evaulated to true/false. Inside the function one can implement what ever the underlying mechanism they need to use to perform the real authentication.

**Comment by yasserf** [comment]
We do allow custom authentication plugins. Is that what you mean? We probably need to fix up the website docs to explain that better!

**Comment by KrishnaPG** [comment]
Thank you @yasserf Yes, custom auth plugins. After reivewing examples somehwere, it looks like one has to implement the "authenticationHandler" and "permissionHandler" - correct?
