### ISSUE TITLE
Conflict Handling?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#149]
I've started looking into deep stream and the core issue I'm having is how to handle conflicts? e.g. I'm looking for something like https://www.firebase.com/docs/web/api/firebase/transaction.html or https://github.com/pouchdb/upsert.

**Comment by WolframHempel** [comment]
Hi @ronag,

pull requests #137 on the server and [#105](https://github.com/deepstreamIO/deepstream.io-client-js/pull/105) are currently under review, adding exactly the functionality that you describe. They will allow clients to specify a merge strategy that will be executed on conflict, both globally and on a per-record basis. You can find more details in [this issue](https://github.com/deepstreamIO/deepstream.io-client-js/issues/82). Please let me know if this fulfills what you are looking for.

**Comment by ronag** [comment]
@WolframHempel: Almost. I would like to have an API where the update can be easily retried.

**Comment by WolframHempel** [comment]
if I'm not mistaken, that's very much what this will be:
```javascript
myRecord.setMergeStrategy(function( remoteValue, recordName, callback ) {
	var localValue = ds.record.getRecord( recordName );
	//do your merging, then retry
    callback( error, mergedVersion );
});
```

**Comment by yasserf** [comment]
That's correct, the merged version that is returned will be set onto the record as an update and sent to the server. If the merge conflict fails again the client will be notified, until it works. This is similar to how the transaction works.

Only thing that's different is the api, which is:

```
myRecord.setMergeStrategy(function( record, remoteValue, remoteVersion, callback ) {
    var localValue = ds.get();
    //do your merging, then retry
    callback( error, mergedVersion );
});
```

This stops users from having to remember to discard the record, and also reduces what would have been a pretty long argument list.
