### ISSUE TITLE
NATS Message Connector

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#151]
http://nats.io

I might have a go at this myself.

**Comment by KrishnaPG** [comment]
+1 for NATS. Given their performance claims over kafka, would be interesting to see how much DeepStream performance improves over other connectors (if any benchmarks exists with, say, kafka with deepstream), especially in the pubsub and rpc side where persistence is not much required.

**Comment by yasserf** [comment]
Awesome!

Theres a message template that should take u 50% of the way there

https://github.com/deepstreamIO/deepstream.io-msg-connector-template

**Comment by UltraNemesis** [comment]
I have implemented a minimal NATS connector for deepstream based on the msg-connector template. All the basic tests that come with the connector are passing. 

https://github.com/UltraNemesis/deepstream.io-msg-nats

**Comment by yasserf** [comment]
I'm keeping this open because I want to see if I can find a volunteer that can set it up. Really like what I read about NATs and would be interesting to see how it plays with our performance framework

**Comment by ronag** [comment]
https://github.com/nxtedition/deepstream.io-msg-nats
