### ISSUE TITLE
Ignores url path

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#153]
When I do:

```
deepstream('localhost:3000/deepstream')
```

Deep stream still tries to connect using the following url:

```
http://localhost:3000/engine.io/?EIO=3&transport=polling
```

Though I would expect it to connect to:

```
http://localhost:3000/deepstream/engine.io/?EIO=3&transport=polling
```

I need this in order for the load balancer to properly route the traffic.

**Comment by WolframHempel** [comment]
that's correct. The URL is used for both TCP and engine.io connections, so only host and port, but not ath or protocol parts of the URL are taken into account. You can easily specify the path for engine.io using the [`path` client option](https://deepstream.io/docs/client_options.html).

```javascript
var ds = deepstream( 'localhost:3000', { path: 'deepstream' });
```
