### ISSUE TITLE
Add CI and publishing scripts for connectors

### ISSUE THREAD

**Issue by timaschew** [deepstreamIO/deepstream.io#161]
Goal for each connector:
1) Ensure tests run and pass in CI
2) Get connector to package self using package script on github tags
3) Update license and include contributing file
4) Create a release/test branch that installs on linux/mac/windows and ensures the package runs successfully.
5) Provide example config file ( to be used by part 4 ) that the cli tool can show when installing.

- [ ] deepstream.io-provider-search-rethinkdb

- [ ] deepstream.io-storage-connector-template

- [ ] deepstream.io-cache-memcached
- [ ] deepstream.io-cache-redis
- [ ] deepstream.io-cache-hazelcast

- [ ] deepstream.io-storage-rethinkdb
- [ ] deepstream.io-storage-mongodb
- [ ] deepstream.io-storage-elasticsearch

- [ ] deepstream.io-msg-connector-template

- [ ] deepstream.io-msg-kafka
- [ ] deepstream.io-msg-redis
- [ ] deepstream.io-msg-amqp
- [ ] deepstream.io-msg-direct ( not published just license )

**Comment by yasserf** [comment]
Done:
 deepstream.io-cache-memcached
 deepstream.io-cache-redis
 deepstream.io-storage-rethinkdb
 deepstream.io-storage-elasticsearch
 deepstream.io-msg-kafka
 deepstream.io-cache-hazelcast

Missing:
 deepstream.io-msg-redis
 deepstream.io-storage-mongod
 deepstream.io-msg-connector-template
 deepstream.io-msg-amqp
 deepstream.io-msg-direct ( not published just license )
