### ISSUE TITLE
Record Transaction/Upsert

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#170]
Continuing from #149

I would like a `transaction/upsert` api to perform atomic updates against the server:

```
myRecord.transaction(function(localValue, remoteValue, remoteVersion, callback) {
    //do your merging, then retry
    callback( error, mergedVersion );
}, function(err) {
  if (err) {
    // Failed
  } else {
   // Accepted by server
  }
})
```

This is similar to `setMergeStrategy` but I need to be able to do it on a per operation basis, not per record basis and also know when it has been properly applied on the server

**Comment by AlexBHarley** [comment]
#458
