### ISSUE TITLE
Does deep stream consolidate changes from storage connector?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#174]
If I perform changes directly to the database (e.g. RethinkDB) does those changes get consolidated into the deepstream? i.e. would the changes propagate into record listeners? and if so how are conflicts originating from the storage handled?

**Comment by yasserf** [comment]
No, changes are pushed directly using vanilla JS. If you want to manipulate files in the database directly you would need to setup a rethinkdb change listener in a provider to then notify clients. You can look at the rethinkdb-search-provider for an example.
