### ISSUE TITLE
Deepstream Hub for on-premise installation

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#175]
Will it be possible to hook up on premise installations to deep stream hub? The dashboard looks like it would be very useful for debugging.

**Comment by WolframHempel** [comment]
We're planning two things in this area: A VPN connection that allows you to connect your own datastore to deepstreamhub and a deepstreamHub Enterprise Edition for on-premise installation (similar to e.g. Github enterprise).

It will be possible to connect clients, but not servers to deepstreamHub
