### ISSUE TITLE
Network Partitioning & Offline First

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#176]
As far as I've understood Offline First support is somewhere in the roadmap. I would like to raise the issue of network partitioning in the context of this. Offline first will require some form of re-synchronisation when going online again. I wonder if this could potentially also be applied during network partitioning? i.e. when a deep stream server looses connection to the rest of the cluster, but could still function.

An example of this would be where your installation is done on two different locations, e.g. on-premise and cloud. If the on-premise installation looses connection to the cloud it could potentially still work (through an on-premise cache/storage) and then re-sync the cloud once connection is re-established.

**Comment by WolframHempel** [comment]
This is a really interesting proposal. It's worth noting though that the data-layer (e.g. cache/database) is what keeps the state and all servers, independent of location retrieve it from there - deepstream doesn't keep distributed state as such. Still though, definitely valuable to improve support for clustered deployments

**Comment by yasserf** [comment]
I could argue this theoretically works already, although I haven't tested it.

Test case

```
- Connected to cloud
- Get recordA
- Set recordA version to 100

- Lose connection to cloud
- Client connects to a local deepstream, sends all subscriptions ( which includes initial read )
- Local deepstream says version is 90, client does merge and sets it to 101

- Reconnecting to cloud is the same process
```

A problem would be for common records that more than one client owns, which would end up having multiple merge conflicts at the same time.
