### ISSUE TITLE
Does server.close wait for all RCP calls to finish/timeout?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#177]

**Comment by WolframHempel** [comment]
It does not. It disconnects all sockets and emits `close` once all are disconnected

**Comment by ronag** [comment]
@WolframHempel: I see. Any advice on how to achieve a graceful shutdown of a deep stream server?

**Comment by ronag** [comment]
Closed in favour of https://github.com/deepstreamIO/deepstream.io/issues/258
