### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by meepeek** [deepstreamIO/deepstream.io#193]
The concept is interesting however, I tried react example and failed. Details as follow:

https://github.com/deepstreamIO/ds-demo-simple-app-react

This one, I can start the server but access localhost:6020 returns nothing and the console shows no error either.

Is there any other working example ?

**Comment by timaschew** [comment]
Hi meepeek,
you can find two working examples in this repo: https://github.com/deepstreamIO/ds-tutorial-react
I will check the broken one later.

**Comment by yasserf** [comment]
Closing until we get a reply if it was due to versioning issues
