### ISSUE TITLE
More information about clustering

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#195]
The information in regards to running a deepstream cluster is a bit lacking right now?
- How does it work?
- Can I add instances?
- Can I remove instances?

e.g. if I have deepstream running on AWS could I make it work with the auto-scaler?

**Comment by WolframHempel** [comment]
In short: yes - by using a message bus (eg. Redis, AMQP, Kafka etc) you can create a horizontal array of deepstream-nodes and distribute clients between them, either directly or load balanced via NginX / HA Proxy.

Our stack runs on AWS as well. The only thing that doesn't easily work with AWS is Elastic Load Balancing for browser connections. The combination of HTTP and WebSocket connections that engine.io uses needs to be routed to the same instance, but ELB only supports Sticky Sessions for one or the other, but not the combination of both.

Having said that: We're aware that our documentation has notable gaps around this. One of the main deliverables for the 1.0 release is a completely revamped website with extended tutorials, guides and documentation. Large parts of the team as well as external technical writers are working on this at the moment...stay tuned

**Comment by ronag** [comment]
@WolframHempel: How does clustering interact with record conflicts?

**Comment by KrishnaPG** [comment]
@WolframHempel your message above is indicating 'engine.io' as the underlying core, while https://github.com/uWebSockets/uWebSockets#built-with-µws is indicating deepstream as built with uws. 

Does it imply, you are using Engine.io with uws as underlying transport, or one would has to opt-in / configure some settings with Deepstream somehow to take advantage of uws?

**Comment by yasserf** [comment]
@KrishnaPG We are using uws with engine.io instead of the default ws library. It should work out of the box.

`INFO | Using uws websocket server`

If uws doesn't run on your machine, which is a problem with windows, it will fallback to using ws.

**Comment by KrishnaPG** [comment]
Cool. Thanks for the confirmation @yasserf

**Comment by yasserf** [comment]
No worries. One of the many stories we are currently tackling is an automated performance harness. I'm looking forward to seeing the difference between ws and uws in numbers!

**Comment by 00christian00** [comment]
Hi guys, any update on this? Was going crazy looking for the docs, read every page and just found this.
Do you have any example?

I'm especially interested in how deepstream deals with datacenters.
Is it possible to have 2 deepstream nodes connected and synced but each with it's own cache?
Cause using the cache from another remote location would render the datacenter pointless, since it would be used for data locality.

**Comment by ronag** [comment]
@00christian00: Currently all nodes in a cluster must have a shared cache, see https://github.com/deepstreamIO/deepstream.io/issues/399.

**Comment by WolframHempel** [comment]
We'll prioritize deployment and operations tutorials for this week. In general, Robert is right, nodes need to share state which is done via a cache or database (you can use a shared database and local caches for faster read/write access.)

It has to be said though that this is mainly mitigating the problem. At some point your data needs to be send from one data-center to the other - whether this is done by deepstream via a message bus, by a distributed cache via its protocol or via a sharded database doesn't make too much of a difference.

Likewise, if you have users in Europe and the US who are expected to see each others changes, you can gain performance improvements for data-access by running multiple data-centers each with their local cache, but updates will still need to travel between the continents

**Comment by ronag** [comment]
@WolframHempel: I don't think multiple data-centers will work. You **must** have a cache as a single source of truth or conflict (version exists) resolution will not work.

**Comment by 00christian00** [comment]
Yes that's exactly what I wanted to accomplish:
1 Datacenter in US  with local db and local cache
and 
1 Datacenter in Asia with local db and local cache

They both write to their local db and cache and the user can see only it's local version, while in the background they get  slowly synced.
I am using couchbase which already have cross data center replication, but it doesn't allow any programmatic control, so I wouldn't be able to sync the in memory db and would have to continuosly poll the db for changes to load in memory.
I also don't have clear if deepstream when clustering handle sharding of the data internally or if it leaves everything to the database. 

@ronag 
I would gladly help, but need to learn how to walk before I start running :)
The fact about uncertainity of disconnected node is worrying, can you clarify?

**Comment by 00christian00** [comment]
By the way, I read you internally use a timestamp uuid. 
I am using snowflake using this : https://www.npmjs.com/package/flake-idgen
It is based on the tech of twitter, I think it's much better because it has the concept of datacenter and process inside, and can distribute much better than timestamp based.

**Comment by ronag** [comment]
> The fact about uncertainity of disconnected node is worrying, can you clarify?

@00christian00: The official (not our fork) does not support eventual consistency which means that any disconnected node would only be able to potentially read and not write. @WolframHempel can probably clarify in regards to different failure modes (bump https://github.com/deepstreamIO/deepstream.io/issues/207).

> Regarding conflicts resultion, what pass the data to the devs and let the application decide what to do with it. Every scenario it's different so it doesn't make sense to constrain it.

Our fork doesn't care care how the conflicts are resolved as long as they are resolved by somebody through the database interface, e.g. couch base.

> what happen if two users register with the same name at the same time?

The same thing happens as in couch base.

If you have questions about our fork please refer to its issue tracker. https://github.com/nxtedition/deepstream.io/issues. I think we should keep things here to the official deepstream server.

> By the way, I read you internally use a timestamp uuid. 

Who? Where?

**Comment by 00christian00** [comment]
> @00christian00: The official (not our fork) does not support eventual consistency which means that any disconnected node would only be able to potentially read and not write. @WolframHempel can probably clarify in regards to different failure modes (bump #207).

I just noticed that's not an official fork, my replies were all related to the official deepstream.
Your fork made a significant change that I don't like, removing the cache connector so I would rather continue with the official one.

I can't find it but I swear I read deepstream keep an internal log in the db to make sure each client receive all messages. So once a node come back it should receive all the messages it lose when it was down. Did I dream it?

> Who? Where?
From the docs:
> They consist of a base64 encoded millisecond timestamp and a random string

`

**Comment by ronag** [comment]
> Did I dream it?

I believe so... Messages are not persisted anywhere. If the node wasn't shutdown and only temporarily disconnected then maybe?

**Comment by WolframHempel** [comment]
Deepstream offers eventual consistency. Every update is identified by an incremental version number. If versions clash or are dropped a merge routine on the client that send the update is invoked. As for the backend please find all details [here](https://deepstream.io/tutorials/core/storing-data/). 
@ronag's fork is following a fundamentally different philosophy within which all data storage and distribution is handled by CouchDB with deepstream being a realtime wrapper on top. 
Whilst this can be done I'd like to emphasize that this is not an official fork and not supported by us.

**Comment by ronag** [comment]
> Deepstream offers eventual consistency. 

This is only true for clients connected to the same cluster. Deepstream does not offer eventual consistency between different clusters.

**Comment by WolframHempel** [comment]
That is correct. However a cluster doesn't need to be limited to a data-center, but can be spread via a distributed cache

**Comment by ronag** [comment]
@WolframHempel: Yep, but how would it behave during a network partition, which could be argued is inevitable when running multiple data-centers.

**Comment by WolframHempel** [comment]
It very much depends on your architecture. If you're building an application with a one-directional data-flow from back to frontend or without concurrency, e.g. a stock price screener, metric dashboard etc very simple setups will suffice, e.g. just a message bus between datacenters and the internal cache within every node.
For larger deployments running a distributed cache, e.g. something like Redis in conjunction with Zookeeper would be able to manage the partitioning.

**Comment by 00christian00** [comment]
@WolframHempel 
So I was correct and this update queue is saved in the db, right? I can't find that info on the link you provided.  And this is valid for all protocols : data-sync,rpc and pub-sub?

If you manage a cluster with diffent datacenter, can you specify different rules/setting for each?

**Comment by ronag** [comment]
@WolframHempel How would conflicts that occur while they are disconnected be resolved?

**Comment by ronag** [comment]
> So I was correct and this update queue is saved in the db, right?

There is no update queue saved in the db. It lives in memory in the node process.

**Comment by WolframHempel** [comment]
- If a client disconnects it will attempt to reconnect. Updates that are to be send out during that time will be buffered and sent once connected
- If a deepstream node goes down during an update, the update will be lost
- Other than that, interaction between deepstream and its cache should be < 1ms, leaving the critical window small

**Comment by ronag** [comment]
@WolframHempel: Consider the following

Server <-> Cache | Datacenter boundary | Cache <-> Server

If the datacenter boundary goes down both sites could continue working. However, with the current architecture there is no way to re-concile the partition. Even if the cache itself supports some form re-conciliation you will loose data if the same record has been updated while partitioned. Correct?

Given that I would never recommend using deepstream in a cross datacenter environment if unnoticed data loss is not acceptable.

**Comment by rileylark** [comment]
I'd like to clarify with an example setup. Let's say I have deepstream servers set up with Redis as a cache & Postgres as a database. 

1. A client requests to write data to a path.
2. A deepstream server receives the request & updates the cache (redis)
3. Then the deepstream process dies before it can persist to the database (postgres)
4. ? What happens next?

Is it 4: the client thinks the write succeeded, but actually the data will be lost once the cache is cleared?

**Comment by ronag** [comment]
@rileylark: Clients are never notified of write success.

1. A client requests to write data to a path.
2. A deepstream server receives the request & updates the cache (redis)
3. Then the deepstream process dies before it can persist to the database (postgres)
4. Deepstream starts. Failed writes are not persisted to database.
5. Client writes new data to same path at which point it can be persisted to database.
