### ISSUE TITLE
Make constants static on deepstream available in documentation

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#196]
I need to be able to access the deepstream constants without actually having a deepstream instance in e.g. a permissionHandler.

**Comment by yasserf** [comment]
Shouldn't this already be the case?

```
/**
 * Expose constants to allow consumers to access them without
 * requiring a reference to a deepstream instance.
 *
 *
*/
Deepstream.constants = C;
```

I believe that might just be lacking documentation, will raise a card for the documentation revamp

**Comment by yasserf** [comment]
Reopening to keep track of issue

**Comment by yasserf** [comment]
Done in docs
