### ISSUE TITLE
messageConnector wasn't initialised in time (event=PLUGIN_ERROR)

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#201]
I think the `dependencyInitialisationTimeout` is to low. Currently the redid-msg-connector isn't able to connect quick enough. I have to change the timeout to 200ms.

**Comment by ronag** [comment]
I see no reason why it couldn't be set to 1s?

**Comment by yasserf** [comment]
Should be set to:
```dependencyInitialisationTimeout: 2000```

**Comment by yasserf** [comment]
Closing in favor of #202
