### ISSUE TITLE
default options not being applied when using configuration object?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#202]
Given:

https://github.com/deepstreamIO/deepstream.io/issues/201
https://github.com/deepstreamIO/deepstream.io/issues/197

I believe that the default configuration options are not applied when passing configuration as an object to the deepstream constructor.

**Comment by yasserf** [comment]
Closed other two issues. This will be released in next beta version (  second to last beta version! )

**Comment by yasserf** [comment]
This will be fixed in beta.6

**Comment by timaschew** [comment]
fixed in https://github.com/deepstreamIO/deepstream.io/commit/d9e751d26b4e067e57c09ebbfa38cb12b944eeb5#diff-7bfe6d62286deffc4ab3d25d3d7694e9R234 and will be published in beta.6
