### ISSUE TITLE
permissionHandler.onClientConnect?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#204]
Since `isValidUser` has been moved to `authenticationHandler` there is no easy way to know in the `permissionHandler` whether a client has been connected (and authenticated).

Could we have a  `onClientConnect` in the `permissionHandler`?

**Comment by yasserf** [comment]
That data is provided within the authData params:

this._options.permissionHandler.canPerformAction(
			socketWrapper.user,
			parsedMessages[ i ],
			this._onPermissionResponse.bind( this, socketWrapper, parsedMessages[ i ] ),
			socketWrapper.userData
		);

Which is set by the auth handler during login.

**Comment by ronag** [comment]
That's not quite what I mean but it can be accomplished through that yes.
