### ISSUE TITLE
How to access records in the authenticationHandler?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#205]
I need to be able to lookup e.g. password hashes stored in deepstream records from the authentication handler...

However, I can't just send in a deepstream client into the handler because the client should be created AFTER the server has started since the client will start connecting right away...

What's a good practice here?

**Comment by WolframHempel** [comment]
There are two approaches:

You can create a client once the server emits `'started'` or you can keep a reference to the Storage or Cache connector and use it's `get()` method,e.g. (untested)

```javascript
var Deepstream = require( 'deepstream.io' ),
    RedisCacheConnector = require( 'deepstream.io-cache-redis' ),
    server = new Deepstream();

var cacheConnector = new RedisCacheConnector( {
  port: 6379,
  host: 'localhost'
});

server.set( 'cache', cacheConnector );

server.set( 'permissionHandler', {
    isValidUser: function( connectionData, authData, callback ) {
        cacheConnector.get( 'user/' + authData.username, function( error, result ){
        	//check result
        	callback( null, authData.username );
        });
    }
});

server.start();
```

**Comment by ronag** [comment]
> You can create a client once the server emits 'started'

But I can't create the server without the authenticationHandler and I can't create the authenticationHandler without the client and I can't create the client without the server being started...

I could create a null reference to the client but I'm not very happy with those kind of magical side effect solutions.

Will the cache connector fallback to the storage connector?

**Comment by ronag** [comment]
I'm re-opening this. Using the storage connector will work for my current use case where I only do a few reads. Though in the future when I need to access records for permission decision it won't be fast enough and the client would be required.

**Comment by yasserf** [comment]
@WolframHempel Maybe we could also have the recordHandler set on the authenticationHAndler?

```
	if( this._options.permissionHandler.setRecordHandler ) {
		this._options.permissionHandler.setRecordHandler( this._recordHandler );
	}

	if( this._options.authenticationHandler.setRecordHandler ) {
		this._options.authenticationHandler.setRecordHandler( this._recordHandler );
	}
```

That way users can use the internal cache and storage fallback mechanism if need be ( although if they go crazy and start setting things I'm not owning that decision =P )

@ronag thoughts? The recordHandler allows you to .get() which retrieves from the cache and if it doesn't exist from storage, else it would return null in which case u'll have to deal with it not existing yourself ( most likely just return false )

**Comment by yasserf** [comment]
@ronag

**Comment by ronag** [comment]
@yasserf: The only public method I can find on record-handler is `handle`?

I think we should make the minimal api available.

**Comment by yasserf** [comment]
After discussing with the team this morning the general vote was to not expose the recordHandler as an official API, since it is a core piece of functionality and if someone uses it incorrectly could cause some odd side effects.

I guess you'll have to implement a very basic version, which tries to get it from cache and if it doesn't exist gets it from storage instead. The version we use internally also allows setting of data which is a dangerous entry point for plugins to have.

Sorry for the indirection, hope that helps.
