### ISSUE TITLE
Failure modes?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#207]
What happens if:
- Temporarily loose connection to msg connector?
- Temporarily loose connection to cache connector?
- Temporarily loose connection to storage connector?
- Permanently loose connection to msg connector?
- Permanently loose connection to cache connector?
- Permanently loose connection to storage connector?

**Comment by yasserf** [comment]
Very good question! It would currently log the error and the connector would be responsible for  reconnecting. I'll discuss this with the core team and see if we can standardize an approach.

**Comment by ronag** [comment]
@yasserf: I'm especially interested in what guarantees are given, what kind of consistency issues might occur and how it would affect the system.

- If cache dies but storage works does it affect system functionality and can it recover?
- If storage dies but cache works does it affect system functionality and can it recover?
