### ISSUE TITLE
The end result of getting started tutorial

### ISSUE THREAD

**Issue by rahmonov** [deepstreamIO/deepstream.io#215]
Maybe I am missing something, but I don't have anything at the end of the `getting started` tutorial except for one input. This is what it says at the end:

    Now open your page in two browser windows and watch both inputs stay in sync

what is meant by both inputs? some image or better yet gif file would be great here for beginners like myself

**Comment by timaschew** [comment]
Hi @rahmonov 

Sorry that it didn't work for you. I created a repo with exact the same content of the getting started example: https://github.com/timaschew/deepstream-getting-started

The page (index.html) contains a `<input>` element which is *connected* to the deepstream record with the nam __someUser__. If you open the page in two windows or in two browsers you can see how the value of the input element will kept in sync. It's kind of a simulation of two users if you open the page in two windows.

**Comment by rahmonov** [comment]
@timaschew oh I see now! My bad! sorry! 

It actually says   `TWO browser windows`

Thanks!

**Comment by timaschew** [comment]
But you're right anyway to improve the docs with a gif or so.
We are working currently on the documentation, the tutorials and the guides. 
They will be released on our new website soon.

Greetings to Uzbekistan! (I was born in Almalyk, my father in Tashkent)
Xayr!

**Comment by rahmonov** [comment]
oh really?) that is awesome! 

I really want to contribute to an open source project like this one, and I saw an open issue about python client for deepstream! That's why I was looking through the tutorials in the first place :) 

Look forward to cooperating then! 

So, not xayr! but, Ko'rishguncha!
