### ISSUE TITLE
create a password hash via cli

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io#248]
`deepstream encrypt <password>`

should encrypt a clearname password for the user to insert into his users.json file

**Comment by WolframHempel** [comment]
Thanks for adding that. Someone will point out though that its not actually encrypting, it's hashing. Encryption is reversible, e.g. can be decrypted, hashing is not. Could we just call the command `hash` or something

**Comment by yasserf** [comment]
Sure. I was using the same command as Travis.

Will do it and also find out why deepstream --help and --version go straight to node

**Comment by timaschew** [comment]
Can this issue be closed?
