### ISSUE TITLE
ElasticSearch Connector ZIP is broken on Windows

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#249]
At least on windows

![image](https://cloud.githubusercontent.com/assets/1503717/16512097/e2511376-3f57-11e6-9e71-6a17a50ff718.png)

**Comment by WolframHempel** [comment]
Works on Ubuntu
![image](https://cloud.githubusercontent.com/assets/1503717/16512735/ef02e368-3f5e-11e6-9be2-13653c9ec75f.png)

**Comment by yasserf** [comment]
odd, works on my windows machine too 

![image](https://cloud.githubusercontent.com/assets/2734923/16515575/04165f96-3f73-11e6-8dce-cc6014c1b592.png)

**Comment by yasserf** [comment]
Can you run it with a --verbose flag?

**Comment by WolframHempel** [comment]
yup,

![image](https://cloud.githubusercontent.com/assets/1503717/16515622/578dd44c-3f73-11e6-80fa-4cc03938f543.png)

**Comment by WolframHempel** [comment]
Are you running it in CMD or cygwin?

**Comment by yasserf** [comment]
cygwin, running it command and will update.
 
winRar shouldn't be affected by that though right?

**Comment by WolframHempel** [comment]
Yup, Cygwin works.

**Comment by yasserf** [comment]
![image](https://cloud.githubusercontent.com/assets/2734923/16517994/c103fab6-3f80-11e6-8709-25c5a534095c.png)

**Comment by yasserf** [comment]
Could you also throw in the info data now? Be good to know which deepstream version is running!

**Comment by yasserf** [comment]
that was cwd

**Comment by yasserf** [comment]
closing since this isn't specific to elasticsearch, i believe it might due to files not being downloaded properly randomly but can't replicate currently
