### ISSUE TITLE
Amend Ubuntu install script

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#251]
![image](https://cloud.githubusercontent.com/assets/1503717/16512356/9bcbc1aa-3f5a-11e6-9141-c57de7de3816.png)

Not really a bug / issue as such, but we need to add `sudo` before tee for Ubuntu installs

`echo "deb http://dl.bintray.com/deepstreamio/deb $DISTRO_NAME main" | sudo tee -a /etc/apt/sources.list`

See related issue [here](http://askubuntu.com/questions/185268/permission-denied-etc-apt-sources-list)

**Comment by WolframHempel** [comment]
Similar problem with `apt-key`, needs to be 

`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61`

![image](https://cloud.githubusercontent.com/assets/1503717/16512487/32987fb4-3f5c-11e6-917a-3f23136df6a7.png)

**Comment by WolframHempel** [comment]
The following works as a copy & paste solution for Ubuntu installs. The source command loads lsb-release and exposes it as environment variables that are used to populate `$DISTRIB_CODENAME`

```bash
source /etc/lsb-release && echo "deb http://dl.bintray.com/deepstreamio/deb $DISTRIB_CODENAME main" | sudo tee -a /etc/apt/sources.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
sudo apt-get update
sudo apt-get install -y deepstream.io
```

**Comment by yasserf** [comment]
Sorry I'm confused, is this a documentation issue or a code issue?

**Comment by WolframHempel** [comment]
My bad, it's not really an issue at all. More of a reminder on how we need to amend the install script we recommend on the website. Will close shortly

**Comment by yasserf** [comment]
cool, just want to see what issues to fix in next rc
