### ISSUE TITLE
Minor! Inconsistent use of msg / message

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#255]
It's 
```bash
deepstream install msg redis
```
but
```yaml
plugins:
    message:
    ....
```

Not the end of the world

**Comment by timaschew** [comment]
To make it consistent, without any special conditions in the code we should publish the package
on npm also with message instead of msg

**Comment by WolframHempel** [comment]
Definitely not. This would break everyone's dependencies. If anything we could adjust the install command

**Comment by timaschew** [comment]
Why it would break? We can keep the old package, just releasing all new versions only to the new name

**Comment by WolframHempel** [comment]
That would leave two packages with almost identical names on NPM and leave it to the user to guess which one's which

**Comment by yasserf** [comment]
Yep, renaming it to message makes sense. Can go into next rc
