### ISSUE TITLE
Feature Request - Distributed Locks

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#256]
Would be nice to have access to locks through the deepstream API, e.g. (http://redis.io/topics/distlock).

**Comment by yasserf** [comment]
We discussed this internally and it would be a cool feature, but is quite a big piece of work in comparison to some other quick wins.

We will keep this on the roadmap and prioritize accordingly

**Comment by ronag** [comment]
@yasserf: I've noticed that the new distributed state has some form of locks. Could that be used by clients to achieve this feature?
