### ISSUE TITLE
"safe" whenReady

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#257]
What is the recommended way to handle `whenReady` deadlocks on errors?

Does a wrapper like this make sense?

``` javascript
whenReady () {
    const rec = this
    return new Promise((resolve, reject) => {
      rec.whenReady(resolve)
      rec.on('error', reject)
    })
  }
```

**Comment by yasserf** [comment]
That actually does make sense, onReady would fail on a CACHE_RETRIEVAL or STORAGE_RETRIEVAL error. However, I'm not certain if those errors on `client` or the actual record.

If on client it would be more like:
```javascript
whenReady () {
    const rec = this
    return new Promise((resolve, reject) => {
      function recordFail( errorType, name ) {
         if( errorType.match( /CACHE_RETRIEVAL|STORAGE_RETRIEVAL /  && name === record.name ) {
          client.off( 'error', recordFail );
          reject();
         }
      }
      rec.whenReady(() => {
         resolve()
        client.off( 'error', recordFail );
      })
      client.on( 'error', recordFail );
    })
  }
```

Didn't test this code out btw! Just the general direction

**Comment by ronag** [comment]
@yasserf: That makes sense. Thanks! Would this maybe something to add to the official implementation?

**Comment by ronag** [comment]
@yasserf: It would also fail on a client disconnect/reconnect?

**Comment by yasserf** [comment]
that would also require the following:

```
if( 
   ( errorType.match( /CACHE_RETRIEVAL|STORAGE_RETRIEVAL| /  && name === record.name ) ) || ( errorType === 'CLIENT_DISCONNECTED' ){
   client.off( 'error', recordFail );
   reject();
}
```

you could also simply do the following:

```
whenReady () {
    const rec = this
    return new Promise((resolve, reject) => {
      rec.whenReady(() => {
         resolve()
         client.off( 'error', onAckTimeout );
      })
      rec.once( 'error', onAckTimeout );
    })
  }
```

However, this means 
1) It won't capture message denied errors ( this raises a question if MESSAGE_DENIED should be via client or on the record, or both )
2) Current ack timeouts occur as soon as record is created regardless of status, however going forward this would be changed to buffer timeouts to only start once connection is back up
3) If you ack timeout is too low you would get a reject but then also get a ready, however your promise would already be resolved. Thats why I mentioned the above scenario to wait specifically for explicit errors instead.

I would probably go with the second implementation. We don't currently have promises, but will most likely create on a utiil library like yours or the one by @brieback https://github.com/briteback/deepstream-utils

**Comment by ronag** [comment]
@yasserf: I would suggest this should be considered a bug as the current behaviour can deadlock applications.

**Comment by yasserf** [comment]
Can you confirm the following would fix the issue?
We will be implementing:

> 1) It won't capture message denied errors ( this raises a question if MESSAGE_DENIED should be via client or on the record, or both )

So message denied will trigger an error.

We'll also trigger an error message for CACHE_RETRIEVAL|STORAGE_RETRIEVAL on individual record.

**Comment by ronag** [comment]
I'm not familiar enough with all the edge cases. But yes, that sounds reasonable. The important thing is that `whenReady` cannot get stuck.

Though, wouldn't fixing it require you to change the callback signature to `(err, record)`?

**Comment by yasserf** [comment]
Yeah I was going to mention that. I don't think we would be able to change the callback signature since its a breaking change in one of the most use methods. 

Easiest solution would be to guarantee that error will be called on the record itself as well as globally for something like your promise wrapper to work properly.

**Comment by ronag** [comment]
> Yeah I was going to mention that. I don't think we would be able to change the callback signature since its a breaking change in one of the most use methods.

I would like to argue that it's worth it. In particular all callbacks (in nodejs world) should have the `(err, ...args)` signature.

> Easiest solution would be to guarantee that error will be called on the record itself as well as globally for something like your promise wrapper to work properly.

That kind of breaks the, easy to do right and difficult to do wrong, principle. Basically you would end up with no one actually considering the case...

I would be happy with `whenReady2` or `whenReadyOrError` or whatever. I don't like the wrapper/shim approach in regards to core functionality, as you said, this method is used very commonly.
