### ISSUE TITLE
Kafka connector not available via CLI

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#260]
I think we might still need to release that one

**Comment by yasserf** [comment]
Yeah, the build broke which stopped deployment. Thinks it's got to do with Amazon side instance not being configured properly

**Comment by yasserf** [comment]
Yeah, the build broke which stopped deployment. Thinks it's got to do with Amazon side instance not being configured properly

**Comment by yasserf** [comment]
Fixed. Timeouts where too low for the deployment of kafka we are using
