### ISSUE TITLE
login() never succeeds for browser client

### ISSUE THREAD

**Issue by airguru** [deepstreamIO/deepstream.io#262]
Hello,

I have set up a test app according to https://deepstream.io/tutorials/deepstream-express.html where the client js library is included from https://rawgit.com/deepstreamIO/deepstream.io-client-js/master/dist/deepstream.min.js.

The server runs fine and tcp client trying to login succeeds. Browser client, however, never calls the login callback function. While inspecting network requests, i see connection upgraded to websocket and then exchanging string of "2" and "3" frames indefinitely ([screenshot](http://i.imgur.com/quea3wO.png)).

When trying to connect with `{transports: ['polling']}` only, i see a string of poll request timeouting after 25s, also failing to login ([screenshot](http://i.imgur.com/b4xZrsU.png)).

When I tried to look what happens in server code, I only see that in `src/message/connection-endpoint.js` the method `ConnectionEndpoint.prototype._onConnection` is successfully executed and at the end the authCallBack appears to be set.

```
socketWrapper.authCallBack = this._authenticateConnection.bind( this, socketWrapper );
socket.on( 'message', socketWrapper.authCallBack );
console.log('CALLBACK SET'); //debug
```

however, the `ConnectionEndpoint.prototype._authenticateConnection` is never called afterwards (it is called for TCP connection though).

Server log displays:
```
INCOMING_CONNECTION | from http://localhost:6020/hello (::1) via engine.io
CALLBACK SET
```
and nothing else.

I am using node.js v.4.4.7, but I am getting the same behaviour on hosting with node 5.3 and 5.5.
To rule out some engine.io issues i tried to run some socket.io [example](http://stackoverflow.com/questions/9914816/what-is-an-example-of-the-simplest-possible-socket-io-example) and it works fine. Can it be some problem with the build of client js library?

Thanks for any help and I apologize if this doesn't belong here.

EDIT: If trying to do anything without login callback, i get ACK_TIMEOUT errors which seem to indicate unsuccessful connection.

**Comment by timaschew** [comment]
Hi Pavel, we currently working on a new release and the since client of the test app [points master](https://github.com/deepstreamIO/ds-tutorial-express/blob/a3495549276b48e350040b8c1337377aa86db992/client/index.html#L9) and your server to the [latest (stable)](https://github.com/deepstreamIO/ds-tutorial-express/blob/master/server/package.json#L12) which is currently 0.9 they the setup is not working.

We will cleanup our test apps soon to avoid this in future but also without pointing to a specific version.
For now you can just point in your HTML to the latest stable client version, which is this URL:

https://raw.githubusercontent.com/deepstreamIO/deepstream.io-client-js/0.5.0/dist/deepstream.min.js

**Comment by airguru** [comment]
I suspected that it will be something like this! :) Now it works, thanks a lot!

**Comment by jugglingcats** [comment]
I am getting a similar issue from browser using deepstream core 1.0.3 and deepstream js client 1.0.2 both from NPM. The same client code running under node is working fine. I see the websocket call with 101 response but nothing after that and the login callback is never called.

**Comment by timaschew** [comment]
@jugglingcats is your sample React project on GitHub and public? This way we can try to reproduce your issue very easy.

**Comment by jugglingcats** [comment]
Was using the wrong port! Didn't appreciate that `port` is for browser and `tcpPort` is for regular node client. Copy paste error from my node client sample... Tx
