### ISSUE TITLE
line ending CR breaks npm binary

### ISSUE THREAD

**Issue by timaschew** [deepstreamIO/deepstream.io#277]
See https://github.com/deepstreamIO/ds-tutorial-react/issues/1

The npm release contains a CR in [this line](https://github.com/deepstreamIO/deepstream.io/blob/v1.0.0/bin/deepstream#L1)
It will be fixed in the next release, for now you can do this, to fix it

```
curl https://raw.githubusercontent.com/deepstreamIO/deepstream.io/v1.0.3/bin/deepstream > node_modules/.bin/deepstream
```

**Comment by timaschew** [comment]
git client needs to have the settings to checkout with unix line endings

**Comment by yasserf** [comment]
this an issue again in 1.0.1 then? =(

I think I'll change the build to publish on tags once build is successful. One less thing for us to do! ( Unless we don't tag versions (a) ) Otherwise this will always risk happening again

**Comment by timaschew** [comment]
I have this issue with 1.0.2.
Okay, let's do the publish on CI

**Comment by yasserf** [comment]
#311
