### ISSUE TITLE
Invalid Message

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#285]
Not sure how I managed to get this. Nor how to debug. Any advice?

I believe this is a rather invalid message:

![screen shot 2016-07-13 at 10 30 00](https://cloud.githubusercontent.com/assets/3065230/16796805/c5158788-48e4-11e6-975a-beae95fd9aa6.png)

![screen shot 2016-07-13 at 10 28 12](https://cloud.githubusercontent.com/assets/3065230/16796752/853131b2-48e4-11e6-92aa-e5e6522a0802.png)

**Comment by ronag** [comment]
After clearing redis and rethinkdb the error went away. I believe this should be caught somewhere earlier in the chain, maybe even on the server?

**Comment by yasserf** [comment]
This is interesting, very curious how to reproduce.

We could introduce a protocol error to catch the client from trying to write something that isn't an object. Don't know if that was the problem though ( or if its even possible ).

Will require more info to reproduce, but we will also try it out on our side.

**Comment by ronag** [comment]
@yassef: Sorry. I have so many errors right now and I don't know what's causing them. I will provide more details as soon as I have them myself.

**Comment by ronag** [comment]
https://github.com/deepstreamIO/deepstream.io-storage-rethinkdb/pull/9
