### ISSUE TITLE
PacketLogger

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io#287]
We want to be able to log all incoming and outgoing messages on deepstream for debug purposes.

This flag will live in the higher config level

``` yaml
packetLog: <boolean>
```

and when used with an external logger such as winston will use a seperate log level

``` yaml
logger.log( 'packet', 'R|C|bob|1|{}' )
```
### NOTE:

This will make deepstream ALOT slower and is not the audit log solution that is recommended or suggested for production environments.

**Comment by MedSolve** [comment]
How is this feature coming along?

**Comment by AlexBHarley** [comment]
@MedSolve, this would be used mainly for local development and we're not looking into this at the moment. 

If you need this functionality you can put a couple of log lines in the `ConnectionEndpoint` and `SocketWrapper` classes.
