### ISSUE TITLE
Deepstream creates a table?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#289]
When starting up deepstream and looking in rethinkdb I can see the following under deepstream_records:

```javascriot
{
"__ds": {
"_v": 0
} ,
"ds_id":  "roles"
} {
"__ds": {
"_v": 0
} ,
"ds_id":  "fields"
}
```

What is this?

**Comment by yasserf** [comment]
Good question, we'll have to replicate it since I can find any mention of this in the server or provider.

Is this without a client being connected?

**Comment by ronag** [comment]
@yasserf: Hm, yes it might be a client.
