### ISSUE TITLE
Documentation - merge strategies

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#302]
Merge strategies seems to be missing from the documentation, https://www.deepstream.io/docs/client-js/datasync-record/datasync-record.html

Also, a more in-depth explanation of how it works would be nice, e.g. how does several conflicting updaters eventually reach an agreement?

**Comment by yasserf** [comment]
Small favour, can you please use index.html files for links? =D

Seems we are missing a file, will take a look and get back to you.

**Comment by ronag** [comment]
@yasserf index.html what? Not following. I got to that link by clicking on the doc links at deepstream.io?

**Comment by ronag** [comment]
<img width="1303" alt="screen shot 2016-07-26 at 20 22 42" src="https://cloud.githubusercontent.com/assets/3065230/17150139/969e0184-536e-11e6-8aa3-0a7257691d04.png">

**Comment by yasserf** [comment]
That link you provided is what is called via Ajax and has non of the styling or layout around it.

**Comment by ronag** [comment]
@yasserf: That link should probably not be directed to when clicking on "Record" then :).

**Comment by ronag** [comment]
Seems ok in Chrome. No styling when clicking in Safari.

**Comment by yasserf** [comment]
That link isn't directed to when you click record, it retrieves the document and replaces the content it without reloading the page to save on time required for refreshing and rerunning highlighting scripts.

**Comment by ronag** [comment]
> That link isn't directed to when you click record

In safari it is. 

Not sure what we're discussing here. If I click on the "Record" link in Safari that is the exact page I end up in. Nothing more to say. I didn't go into to the source code and copy that link before posting here.

**Comment by yasserf** [comment]
Sorry, turns out that issue is replicated only in safari and certain IE browsers. Is a different we'll also address, thanks for indirectly raising/finding it!

**Comment by Srushtika** [comment]
Hi @ronag ! Thanks for opening this issue and apologies for an extremely delayed reply. Here's a [guide](https://deepstreamhub.com/tutorials/guides/handling-data-conflicts/) that explains the merge strategies for records in deepstream.

**Comment by thetomester13** [comment]
I'm wondering how to go about implementing a merge strategy in the config.yml file. The documentation talks about configuring it when you stand it up, but I'm using a config file to stand up deepstream. When trying to configure it like so: `mergeStrategy: LOCAL_WINS`, I'm still getting VERSION_EXISTS errors on the server.

**Comment by crapthings** [comment]
@thetomester13 

i've got this too

```
VERSION_EXISTS | open tried to update record users to version 8 but it already was 8
```
