### ISSUE TITLE
permissions is not supporting `user.data`

### ISSUE THREAD

**Issue by timaschew** [deepstreamIO/deepstream.io#310]
see https://github.com/deepstreamIO/ds-demo-retrospective-board/commit/e13e1e34d7178d72c3de683ad4fce060de0c62f9#commitcomment-18449093

**Comment by AlexBHarley** [comment]
This is actually already resolved. Just changed back to user.data instead of serverData in PR [#1](https://github.com/deepstreamIO/ds-demo-retrospective-board/pull/1)
