### ISSUE TITLE
cache retrieval error results in a record update error

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#318]
```
Object {error: "media/cirhu6cjl00ck3k5h90mxu6uk", event: "CACHE_RETRIEVAL_TIMEOUT", topic: "R"} "Deepstream Error."
deepstream.js?481c:20 Object {error: "1", event: "RECORD_UPDATE_ERROR", topic: "R"} "Deepstream Error."
```

Shouldn't it just fallback to the storage in this scenario?

**Comment by yasserf** [comment]
Cache is much more likely to have the actual latest version, whereas storage could be a few behind. We only get the data from storage when it doesn't exist in the cache at all. Generally depending on storage as a backup if your cache layer goes down introduces potential write/read/permission sequence issues.

**Comment by ronag** [comment]
@yasserf: I see, then this is probably a duplicate of a the more epic "resiliency" issue.

**Comment by yasserf** [comment]
Yup!
