### ISSUE TITLE
TypeError: Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by rationalthug** [deepstreamIO/deepstream.io#320]
After I launch a deepstream server using the node api, I use

`server.on('started', launchClient)`

to start a client running in the same node process, where launchClient is a function. When the client tries to connect to the server, I can see the connection being received in the log:

`INCOMING_CONNECTION | from 127.0.0.1:51407 via tcp`

But immediately after, I get the following error:

 `TypeError: Cannot read property 'log' of undefined
at HttpAuthenticationRequest._onComplete (/node_modules/deepstream.io/src/authentication/http-authentication-request.js:51:25)
`

At first, I thought this might be due to a logger configuration error, but that doesn't seem to be the case. Should I be starting the client in it's own process?

**Comment by rationalthug** [comment]
Ok, actually launching the client in a separate process does NOT solve the issue. I don't see any other required config settings in the docs. What am I missing?

**Comment by rationalthug** [comment]
Found the bug in `authentication/http-authentication-request.js`. 

The calls to the logger in _onComplete should be calling `this._logger.log` instead of `this._settings.logger.log` Will send a pull request to fix.

**Comment by yasserf** [comment]
Good find!

If you don't mind, could u agree to the cla first?

https://deepstream.io/info/community/cla/

Thanks!

**Comment by rationalthug** [comment]
Sure thing, just submitted the cla.

**Comment by yasserf** [comment]
got it, cheers
