### ISSUE TITLE
Feature Request - GET /healthcheck

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#326]
It would be nice if deepstream could provide a GET /healthcheck HTTP route for health monitoring third-party services.

Any recommendations on how to implement this in user space?

**Comment by WolframHempel** [comment]
Yup, I'm in favor of having that as well. You can set up most  loadbalancers to run health checks against the TCP port, but if you want to use it with e.g. AWS application ELB, you need a HTTP endpoint that returns 200
