### ISSUE TITLE
Add Deepstream as a Windows service

### ISSUE THREAD

**Issue by poloagustin** [deepstreamIO/deepstream.io#327]
Hi, guys

I tried adding the Deepstream executable as a Windows service with the following command.

`C:\Windows\Microsoft.NET\Framework64\v4.0.30319\InstallUtil.exe C:\deepstream\deepstream.exe`

This throws the following error:
**System.BadImageFormatException: Could not load file or assembly 'file:///C:\deepstream\deepstream.exe' or one of its dependencies. The module was expected to contain an assembly manifest**

It'd be great to be able to get the Deepstream server running on the back as a service in Windows systems.

**System Details**
Windows edition: Windows 2012 R2 Standard

Thanks.

**Comment by dciimtN** [comment]
InstallUtil.exe is for .NET applications. See following text from msdn.microsoft.com
> You cannot use Installutil.exe to deploy a Windows service that was created by using C++, because Installutil.exe cannot recognize the embedded native code that is produced by the C++ compiler. If you try to deploy a C++ Windows service with Installutil.exe, an exception such as BadImageFormatException will be thrown. To work with this scenario, move the service code to a C++ module, and then write the installer object in C# or Visual Basic.

**Comment by layanto** [comment]
Try https://nssm.cc. I tried with x64 nssm on Windows 10, I didn't do much testing but appeared to be working.

**Comment by yasserf** [comment]
I tried doing this but had no luck =( Happy to accept any PRs, only tricky thing is if your using native code it has to compile into a binary... kist incase it wans't bad enough lol
