### ISSUE TITLE
js client: first call to deepstream throws error in update

### ISSUE THREAD

**Issue by edwardsmarkf** [deepstreamIO/deepstream.io#328]
hello - newbie here who cannot tell if i have discovered a DS issue, or i am doing something really stupid, or perhaps both.    this is a NEW installation running on an amazon-ec2 instance which has nothing except for "yum deepstream" and two scripts (both below)

thank you all very much.

stack trace (does NOT include my script name, which is very surprising):
# 

```
/home/ec2-user/node_modules/deepstream.io-client-js/src/record/record.js:542
               if( currentValue !== this._oldPathValues[ path ] ) {
                                                       ^

TypeError: Cannot read property 'testValueTwo' of null
   at Record._completeChange (/home/ec2-user/node_modules/deepstream.io-client-js/src/record/record.js:542:43)
   at Record._applyUpdate (/home/ec2-user/node_modules/deepstream.io-client-js/src/record/record.js:427:7)
   at Record._$onMessage (/home/ec2-user/node_modules/deepstream.io-client-js/src/record/record.js:302:8)
   at RecordHandler._$handle (/home/ec2-user/node_modules/deepstream.io-client-js/src/record/record-handler.js:228:25)
   at Client._$onMessage (/home/ec2-user/node_modules/deepstream.io-client-js/src/client.js:128:42)
   at Connection._onMessage (/home/ec2-user/node_modules/deepstream.io-client-js/src/message/connection.js:323:17)
   at emitOne (events.js:96:13)
   at emit (events.js:188:7)
   at TcpConnection._onData (/home/ec2-user/node_modules/deepstream.io-client-js/src/tcp/tcp-connection.js:180:7)
   at emitOne (events.js:96:13)
```

``` javascript
// server

var deepstream = require('deepstream.io-client-js');

ds = deepstream( '127.0.0.1:9021' ).login();
ds.record.listen('test', function (recordName, isSubscribed)    {

       record = ds.record.getRecord(recordName)        ;

       record.subscribe ('testValueOne', function(value)       {
               record.set ('testValueTwo' , 'SERVER: initial testValueTwo setting.' );
       });

       record.subscribe ('testValueTwo', function (value)  {
               console.log('in whenReady area');
       });
});
```

``` javascript
// client

var deepstream = require('deepstream.io-client-js');
ds = deepstream( '127.0.0.1:9021' ).login();

//record = ds.record.getRecord('test' + ds.getUid()     )       ;
record = ds.record.getRecord('test' + (new Date).getTime()      )       ;
//record = ds.record.getRecord('test'   )       ;

record.set('testValueOne', 'value set here');
record.subscribe ('testValueTwo', function (value)  {
       testValueTwo = record.get('testValueTwo'                );
}); 
```

**Comment by yasserf** [comment]
This is super wierd

```
	if( this._oldPathValues === null ) {
		return;
	}

	var path, currentValue;

	for( path in this._oldPathValues ) {
		currentValue = this._getPath( path ).getValue();

		if( currentValue !== this._oldPathValues[ path ] ) {
			this._eventEmitter.emit( path, currentValue );
		}
	}

	this._oldPathValues = null;
```


Your stack trace is saying oldPathValues is null, but their is a check earlier to ensure it isn't, and the key you got is from within the map itself..

I'll try to reproduce it, but this is just WTF *mind blown*

**Comment by yasserf** [comment]
Got it ( theoratically ), this is a recursion issue. Basically:

1-> server update calls subscribe
2 -> notifies 1
2-> locally call set
3-> notifies 2
4 -> finishes notifes 2
5 -> continues notifies 1
6 -> *BOOM*

The boom happens because the recursive notification uses the same record singelton object which is nulled before it calls 3


We'll look into this. For now though the best approach *MIGHT* be to move the subscription order around. Let me know!

```
ds.record.listen('test', function (recordName, isSubscribed)    {

       record = ds.record.getRecord(recordName)        ;

       record.subscribe ('testValueTwo', function (value)  {
               console.log('in whenReady area');
       });

       record.subscribe ('testValueOne', function(value)       {
               record.set ('testValueTwo' , 'SERVER: initial testValueTwo setting.' );
       });
});
```

**Comment by edwardsmarkf** [comment]
> This is super wierd
but that is what all the women said of me back in high school.  

> For now though the best approach MIGHT be to move the subscription order around. 
your suggestion works!

> We'll look into this. 

keep me notified please.  and of course if you see a better way of doing what i am trying to accomplish, please let me know.

**Comment by yasserf** [comment]
What your doing is legit, just not sure what the end goal is tbh.

Given this isn't a blocker well plan in soon

**Comment by edwardsmarkf** [comment]
here is what i am trying to do:

1) client creates record which will contain username/password value
2) server checks username/password and subscribes to clients record if login OK
3) server adds a data item to the record
4) server subscribes to future changes to the data item
5) server saves future changes to the data item made by the client.

my logic could probably use some improvement !   any suggestions are most welcome.

**Comment by timaschew** [comment]
First of all let's use not the word *server*, to avoid confusion with the deepstream server.
It looks like you want to do some communication between two (deepstream) clients. We can call them publisher and subscriber or just client1 and client2, because a client can do both at the same time.

I'm not sure what you want to do, you tried to explain it in deepstream terminology, maybe it's better to explain it in a general way?

You need to be aware if you really need a record, because records are for state. The first step (a record with username/password) looks more like an event.

I created an example with two clients, they do something different, but maybe it helps you to get what you need. I also add some logic to allow starting the clients in an arbitrary order and by an arbitrary delay (client1 can be started 2 seconds before client2 and vice versa).


__client1.js__
```javascript
'use strict'

const deepstream = require('deepstream.io-client-js')
const client = deepstream('localhost:6021').login({}, function(success, data) {
	if (success) {
		const recordName = 'foo/bar'
		const record = client.record.getRecord(recordName)

		const id = setInterval(() => {
			if (record.get('data') == null) {
				client.event.emit('custom-login', {
					username: 'user',
					password: 'pass',
					recordName: recordName
				})
			} else {
				clearInterval(id)
				// start to trigger changes which are subscribed by the other client
				let counter = 0
				setInterval(() => {
					record.set('info', counter++)
				}, 1000)
			}
		}, 1000)
	} else {
		console.error(arguments)
	}
})

client.on('error', (data) => {
	console.error(data)
})
```

__client2.js__
```javascript
'use strict'

const deepstream = require('deepstream.io-client-js')
const client = deepstream('localhost:6021').login({}, function(success, data) {
	if (success) {
		client.event.subscribe('custom-login', eventData => {
			console.log('resceived event')
			if (eventData.username === 'user' && eventData.password === 'pass') {
				console.log('custom-login successfull')
				const record = client.record.getRecord(eventData.recordName)
				record.subscribe(recordData => {
					console.log(`record by ${eventData.username} has changed to`, JSON.stringify(recordData))
				})
				record.whenReady(() => {
					record.set('data', {meta: 'connected'})
				})
			}
		})
	} else {
		console.error(arguments)
	}
})

client.on('error', (data) => {
	console.error(data)
})
```

**Comment by edwardsmarkf** [comment]
it never ceases to amaze me what i can learn from looking at other peoples stuff.  thank you Tim.
