### ISSUE TITLE
Feature Request - Rest API

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#335]
It would be nice. Especially in terms of third party integrations against a system using deepstream to have a rest api with the basic POST,PUT,GET,PATCH methods against records.

It's rather trivial to implement outside of deepstream but native support would be a nice to have.

**Comment by yasserf** [comment]
Agreed, we would love to have this too. Would also be a great way to map to events / rpcs as well as integrating easier with languages that don't cater so well with consistent connections.

Will leave this as a feature request and revisit it in a few months time once we have some breathing space on our roadmap.

**Comment by yasserf** [comment]
Happy to say this one actually made it
