### ISSUE TITLE
Feature Request - Server Side Record Merge

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#337]
Would be useful when using e.g. `REMOTE_WINS` as the default merge strategy, i.e. most of our records can be resolved using a simple `Object.assign` and being able to do that without coding anything in the clients would be a nice to have.

**Comment by yasserf** [comment]
To clarify.. a merge strategy on the client that can merge the sever data into the local data?

The repo/title makes it sound like I might have understood it wrong and we are talking about putting it on the server..

If I'm right, that should be easy, we can add a third strategy and look at it when revisiting merge tasks.

**Comment by ronag** [comment]
No, I was thinking the server tries to merge the records to avoid contention when several clients are trying to update the same record, i.e. make it possible to handle record merging on the server side.

**Comment by ronag** [comment]
example:

```javascript
const assignMergeStrategy = (record, remoteData) => Object.assign(record.get(), remoteData)
```

server
```javascript
const ds = deepstream({
   mergers: {
     pattern: 'foo/*'
     merger: assignMergeStrategy
   }
})
```

client
```javascript
const foo = ds.record.getRecord('foo/*')
// Doesn't have to worry about conflicts...
```

**Comment by ronag** [comment]
@yasserf: What was the motivation for putting conflict resolution on client side instead of server side?

**Comment by yasserf** [comment]
@ronag: It was because clients should have the option of actually dealing with merge conflicts, either via a visual indicator or selecting different strategies dynamically.
