### ISSUE TITLE
Listening 2.0

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io#342]
This is an epic that can contain thoughts/suggestion on improving any listening related functionality.
This is only for Features and Enhancements, bugs should be raised as individual issues.

**Comment by yasserf** [comment]
https://github.com/deepstreamIO/deepstream.io/issues/338

**Comment by ronag** [comment]
- Listener Groups
- Load Balancing Strategies
- "change mind"

**Comment by ronag** [comment]
In regards to "change mind" I would like to be able to do this:

```javascript
Observable.defer(() => Observable.create(o => {
  // Fetch next job
  const callback = (match, isSubscribed, response) => {
    if (isSubscribed) {
      response.accept()
      o.next(match)
      ds.record.unlisten(jobPattern, callback)
    }
  }
  ds.record.listen(jobPattern, callback)
}))
.mergeMap(match => {
  // Process job if not already done...
}, null, 4)
```

**Comment by ronag** [comment]
@yasserf: Not sure where this is documented. But will the server retry un accepted records:
- A: when a new listener register
- B: retries all rejecting listeners after a timeout?

**Comment by yasserf** [comment]
Listening was simplified massively in V4, and added a rematchInterval. Currently it just randomly selects providers and its a free grab for all with a distributed lock system when in a cluster (any server can provide the subscription, may be less efficient than previous where it was always on the same node). Will open an issue at some point to allow stopping providing a subscription. Would be cool to do this:

```
ds.record.listen ((name, response) => {
  response.onStop(() => {
    const record = ds.record.getRecord(name)
    record.on('hasProvider', () => {
      // actually stop. This allows the user to ensure you can close a micro service without actual downtime
      record.close()
    })
  })
  setTimeout(response.stop, 5000) // stop for some reason)
})
```
