### ISSUE TITLE
NPM WARNS

### ISSUE THREAD

**Issue by eriknyk** [deepstreamIO/deepstream.io#347]
```bash
npm install
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

**Comment by yasserf** [comment]
Hey,

Thanks for the notice. This issue should now be solved on the pure-uws branch since we no longer depend on engine.io which has a few outdated modules.

**Comment by yasserf** [comment]
Closing for now, but feel free to reopen if this isn't the case!
