### ISSUE TITLE
Add version tags in DockerHub

### ISSUE THREAD

**Issue by kop** [deepstreamIO/deepstream.io#350]
Official Deepstream image in DockerHub [deepstreamio/deepstream.io](https://hub.docker.com/r/deepstreamio/deepstream.io/) currently has only `latest` tag available.

It's considered a very bad practice to use `latest` tags in production.

Please configure a correct mapping between GitHub and DockerHub tags.

**Comment by yasserf** [comment]
Good point!

We are going to hookup git tags to the build so that should solve that

**Comment by yasserf** [comment]
Done ( and will continue doing moving forward )
