### ISSUE TITLE
[Feature Request] File Management Integration

### ISSUE THREAD

**Issue by meepeek** [deepstreamIO/deepstream.io#351]
I know that something similar had been mentioned in #113 but this idea is a bit different.

File upload is one of the common features. There were NPMs around but integration with Database is not an easy task. I think it would be very nice to have a plugin that

1. It handles file transfer from client to server
2. It organizes the files being uploaded in configurable path
3. It does the hash for you and stores records in designated Database
4. You can call a javascript function on the client and it will be converted to URLpath, which also cacheable by cache server
5. If the user was not authorized, it would, instead, generate a link to forbidden image.

Please follow the link below, it is one of the most useful addons that I ever using with Meteor. It won an award in mid-2016

https://github.com/VeliovGroup/Meteor-Files

@Rajan @petemill

**Comment by ronag** [comment]
I think this is out of scope of deepstream core.

**Comment by WolframHempel** [comment]
Hi @meepeek 

generally, deepstream is a TCP/Websocket server using a textbased protocol. File based operations I'd argue are still best performed via HTTP/FTP using binary data - so at the moment would be quite far from deepstream's core functionality.
