### ISSUE TITLE
Question - Current Conflict Behaviour?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#353]
I'm a bit unsure what is considered a conflict and not. Especially in regards to PATCH messages. If a PATCH doesn't conflict, does or does the server not send a version exists error? Is this documented somewhere I haven't looked?

**Comment by ronag** [comment]
#348

**Comment by yasserf** [comment]
If a patch conflicts, the client requests the entire state of the record and processes that as a merge conflict instead

**Comment by ronag** [comment]
@yasserf: I understand that. I'm unsure about what the server considers a "patch conflict". Is it different version or data key conflicts?

**Comment by WolframHempel** [comment]
version conflicts don't take the data into account. Every record has a version number that's incremented upon update. If two clients try to update to the same version, the second gets rejected and has to merge

**Comment by ronag** [comment]
@WolframHempel: Thanks. That's what I thought. Would be nice to have server side merges. Currently I've got very chatty clients since they have high contention on the same records.
