### ISSUE TITLE
Emitting multiple events via a single message

### ISSUE THREAD

**Issue by qrpike** [deepstreamIO/deepstream.io#364]
I have read through the docs and it doesn't seem possible for a client to subscribe to multiple events or a wildcard name of events. 

Eg: if you have `news/sports`, `news/business`, and `news/entertainment` being emitted, how would I go about listening to all of these events? Or multiple events.

``` javascript

// Client
client.event.subscribe( 'news/*', ( event, data ) => {
    // handle published data
    console.log('event name', event)
    console.log('event data', data)
})

or 

client.event.subscribe([  'news/business', 'news/sports' ], ( event, data ) => {
    // handle published data
    console.log('event name', event)
    console.log('event data', data)
})
```

This would be much more efficient than having to emit the event twice. Once in `news/sports` and one in `all-news`.

**Comment by yasserf** [comment]
A client can't subscribe to all possible things  with a wildcard because it would put the backend under alot of unnecessary load with regex comparisons.

The second use case does make sense, currently we would do it as:

```
function onNewsRecieved( eventName, data ) {
  console.log( eventName )
  console.log( data )
}

client.event.subscribe( 'news/business', onNewsRecieved.bind( this, 'news/business' );
client.event.subscribe( 'news/sport', onNewsRecieved.bind( this, 'news/sport' );
```

**Comment by qrpike** [comment]
Understood. Is it possible to emit an event to multiple channels? I am streaming stock quotes and I want to be able to emit `quote/MSFT` so clients can listen to MSFT changes only. As well as the possibility to subscribe to all events, possibly like a `all-quotes`. Seems redundant having to emit the same data twice.

**Comment by yasserf** [comment]
It currently isn't no. That would have to be a new multicast event which we don't currently support. It seems interesting but is currently quite low priority.

**Comment by yasserf** [comment]
I don't think we will ever get around to this tbh. Having to register a many to on event will result in some massive code restructuring. Hence closing as part of backlog grooming

**Comment by arvindnrbt** [comment]
But what about sending multiple events? More like pubnub to send events to different devices / users about their specific data? Is there a way to do this now?

**Comment by yasserf** [comment]
hey @arvindnrbt, I'm afraid I'm not following. You can send different events, you just can't subscribe to events using regular expressions, has to be one to one mappings.
