### ISSUE TITLE
custom authenticationHandler docs

### ISSUE THREAD

**Issue by arunkjn** [deepstreamIO/deepstream.io#365]
Hi I was trying to implement a custom authenticationHandler using the following code

``` javascript
deepstream.set( 'authenticationHandler', {
    isValidUser: function( connectionData, authData, callback ) {
        console.log(connectionData);
        console.log(authData);
        validateToken(authData.token, callback);
    }
});
```

It gives me a very meaningful error - `Error: permissionHandler needs to implement isReady or be an emitter`
But I cant seem to find any relevant docs or examples to refer to while implementing this.
I Found a reference [here](https://github.com/deepstreamIO/deepstream.io/blob/d39e139d1359956c792f18747bd97e8932494730/CHANGELOG.md#breaking-changes). But still no example.

Can someone please refer me to plugin api docs or releavant examples

**Comment by WolframHempel** [comment]
Hi @arunkjn ,

its true, ever since we've started gradually moving out of the NodeJS space we've neglected the Node API docs a bit (deepstream will increasingly become a C/Node hybrid, but still support a Node API).

Here's how it would work for you:

```javascript
const EventEmitter = require( 'events' ).EventEmitter;

class MyAuthenticationHandler extends EventEmitter{
	constructor() {
		// Extend EventEmitter
		super();

		// Or start with false if you need to do some initialisation first
		// and call this.emit( 'ready' ); a bit later
		this.isReady = true;
	}

	isValidUser( connectionData, authData, callback ) {
        console.log(connectionData);
        console.log(authData);
        validateToken(authData.token, callback);
    }

    onClientDisconnect( username ) {
    	//optional callback for disconnecting clients
    }
}

deepstream.set( 'authenticationHandler', new MyAuthenticationHandler );
```

**Comment by athakral** [comment]
a quick related question. Does this authenticationHandler and permissionHandler are invoked on each operation or only when the users logs in?

In my opinion, the authenticationHandler would be invoked when the client invokes login method and the permissionHandler would be invoked for each and every operation. 

Now, what I found is that CustomPermissionHandler has a method canPerformAction which gets serverData as last parameter and this value is set by the CustomAuthenticationHandler's isValidUser's callback by passing the value of the serveData. 

So, if my assumption is right and CustomAuthenticationHandler is invoked only once and CustomPermissionHandler is invoked for every operation, then will the canPerformAction will get same serverData for every operation ?

**Comment by WolframHempel** [comment]
that's spot on. The intention behind the serverData is that upon login the authenticationHandler can lookup additional meta-data, e.g. a user's role or access level. This metadata will be associated with the connect socket and passed to canPerformAction on every invocation to help the permissionHandler make decisions

**Comment by athakral** [comment]
perfect thanks a ton :). Just wanted to double check

**Comment by oldlam** [comment]
extra info for who's also writing their own authenticationHandler,
the callback is with two arguments:
- isAllowed
- userData
