### ISSUE TITLE
Feature Request: Record with expiry

### ISSUE THREAD

**Issue by arunkjn** [deepstreamIO/deepstream.io#367]
Hi,

Could we have a behaviour where the records can be set with an optional TTL after which they are deleted by deepstream server and the clients subscribed are notified of deletion.

**Comment by yasserf** [comment]
Hey Arunkjn,

I would recommend this to be done via a provider as it isn't really required as part of the core server.

If you are using a database that supports changefeeds/live queries you can apply a filter that will return all records that TTL has expired and call `record.delete()` on them.

A much simpler solution if using a cache would be to listen to `EXPIRE` events ( for example in redis http://redis.io/topics/notifications ) and deleting the record associated.

**Comment by ScreamZ** [comment]
Can be nice to document this in some sort of FAQ ;)
