### ISSUE TITLE
Question: Cache vs Db management

### ISSUE THREAD

**Issue by arunkjn** [deepstreamIO/deepstream.io#368]
Hi,

Can you shed some light on how deepstream decides to store an info in cache vs database if both of them are configured. Can this be decided by the clients?

Also, when using redis will it provide both cache and database functionality? I would be using amazon elastic cache with redis backend for the same.

**Comment by WolframHempel** [comment]
It store it in both, first in the cache in a blocking way and outside the critical path in the database in a non-blocking way.

Here's an animation illustrating this.

![deepstream data flow](https://deepstream.io/tutorials/core/cluster-messaging/internal-workings.svg)

You can also find more information here: https://deepstream.io/tutorials/core/storing-data/

**Comment by WolframHempel** [comment]
Btw, I think you're questions are excellent and might be of general interest. Would you mind asking them on Stackoverflow with a deepstream.io tag instead?

http://stackoverflow.com/questions/tagged/deepstream.io

**Comment by arunkjn** [comment]
Hi,

Thanks for the quick response.

I just posted my question [here](http://stackoverflow.com/questions/39826923/database-vs-cache-management-in-deepstream)
