### ISSUE TITLE
Question - events arrays

### ISSUE THREAD

**Issue by SneakBug8** [deepstreamIO/deepstream.io#380]
Can Deepstream send arrays with Events?
I think "no", because it is what i have.
Sending:
`var packet=[];
    packet.nickname=new String(mynickname);
    packet.x=coordx;
    packet.y=coordy;
    client.event.emit('login', packet)`;
Getting:
`chatcall(packet.nickname+" "+packet.x+" ; "+packet.y);`
Seeing:
![image](https://cloud.githubusercontent.com/assets/11244723/19270216/876e81e4-8fc7-11e6-912a-31f1d90b1818.png)

**Comment by WolframHempel** [comment]
Yes you can.

```javascript
ds.event.emit( 'some-event', [ 'a', 'b', 'c']);
```

Maybe I'm misunderstanding the question though

**Comment by SneakBug8** [comment]
Well. But why now i get only "undefined", when sending event with array?

**Comment by AlexBHarley** [comment]
@sneakbug8 are you still having trouble with this? Could you get back to us with a snippet showing the error?

**Comment by yasserf** [comment]
Closing as inactive
