### ISSUE TITLE
[feature-request] Allow sending of Binary / Protocol Buffers

### ISSUE THREAD

**Issue by qrpike** [deepstreamIO/deepstream.io#388]
Using protobufs are much more efficient than sending JSON over the wire. 

Using protobufs ( binary format ) instead of JSON provides:
-  Data only messages. JSON sends the structure and data in the same message. Protocol buffers only send data and both sides have the schema. Allowing much less bandwidth to be used per message. Since the schema for my messages will never change, it doesn't make much sense sending it every single time.
- In turn this offers more throughput for whatever net bandwidth you have. Also allowing clients to stream more data and using less bandwidth ( mobile and slower connections ).

WebSockets as a protocol allows for sending binary messages, for extremely high usage/bandwidth instances of DeepStream this would help a lot.

**Comment by KrishnaPG** [comment]
+1 for binary support. But please make it generic binary (and not specific to protobuf).

**Comment by WolframHempel** [comment]
We've discussed binary transports internally and would like to propose the following API, Feedback would be most welcome.

At its core, deepstream's binary functionality would have three methods:
```javascript
// subscribe to incoming transmissions
ds.binary.subscribe( namespace, transmission => {} )

// unsubscribe
ds.binary.unsubscribe( namespace, transmission => {} )

// send a file or byte array, metadata is optional
transmission = ds.binary.sendBlob( namespace, Blob, metaData )
```
the `transmission` object that's returned to both sender and receiver would have the following structure

```javascript
/*** properties ***/

// size of the transmittion in bytes
transmission.size;

// Number between 0 and 1 indicating the transmission progress
transmission.progress;

// Boolean indicating if all bytes have been received
transmission.isComplete

// Boolean indicating if this transmission has been aborted
transmission.isAborted

// Boolean indicating if this transmission has been aborted
transmission.isEnded

// Boolean indicating if this client is a sender or receiver of this transaction
transmission.isIncoming

// Optional freeform data that can be passed to sendBlob
transmission.metaData

/*** events ***/

// (receiver only) receipt of a single chunk within a transmission
transmittion.on( 'data', chunk => {})

// emitted when a receiver aborts receipt of further chunks
transmission.on( 'abort' )

// emitted at the end of a transmission
transmittion.on( 'end' )

/*** methods ***/

// (sender): abort sending further chunks, will trigger 'abort' event for receivers
// (receiver): abort receiving chunks, will trigger abort locally
transmission.abort();
```

a simple usage example with a browser based file upload / download for another client could look as follows:

### sender
```javascript
$( 'input[type=file]' ).on( 'change', () => {
	var file = this.files[ 0 ];
	ds.binary.send( 'songs', file, { fileName: file.name });
});
```
### receiver
```javascript
ds.binary.subscribe( 'songs', transmission => {
	var incomingFileData = [];

	transmission.on( 'data', chunk => {
		progressBar.update( transmission.progress );
		incomingFileData.push( chunk );
	});

	transmission.on( 'abort', () => {
		alert( 'transmission aborted' );
	});

	transmission.on( 'end', () => {
		const blob = new window.Blob( incomingFileData );

		// Slightly hacky browser way to force file downloads from JS memory
		const anchor = document.createElement( 'a' );
		anchor.href = URL.createObjectURL( blob );
		anchor.download = transmission.metaData.fileName;
		anchor.click();
	});
})
```

**Comment by yasserf** [comment]
#796

**Comment by KrishnaPG** [comment]
From the above example code, it looks like this is 'broadcasting' style, that one sender sends and multiple receivers can receive at the same time. Correct?

What happens if multiple senders start sending different binary files at the same time? Is it possible for the receivers to identify which one belongs to which? The `transmission` object doesn't seem to offer that field.

Or, should the `namespace` be unique for each transmission (i.e. no two senders can use the same namespace) ?
