### ISSUE TITLE
How to revoke access for particular user?

### ISSUE THREAD

**Issue by singggum3b** [deepstreamIO/deepstream.io#395]
For example some user already logged in , but the admin decided to revoke that user's access. (or force logout)
How to do this with deepstream?
Another related question is how to allow only one connection of particular user at a time ( & force logout the old connection)

**Comment by yasserf** [comment]
This requires a custom authentication handler that can receive messages to revoke users.

Will try and schedule a blogpost for this soon in the near future

**Comment by n-scope** [comment]
Is it still possible ? Would you have some details about revoking user ?

**Comment by yasserf** [comment]
#787 

This will be added via the Admin API epic
