### ISSUE TITLE
Per Node In Memory LRU faster than distributed Redis?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#397]
Just a thought. But wouldn't using a `lru-node` cache in every deepstream node be a lot faster than using a distributed Redis cache? In total more memory would be used but performance could be significantly faster. Any thought or comments on that?

From what I understand the cache for the different nodes does not need to be synchronised since every update is sent to every node which then will all write the same value to the cache connector?

**Comment by yasserf** [comment]
The message isn't written to each cache connector, it only fans out the update to all other nodes when put on the message bus.

```
	/*
	 * If the update message is received from the message bus, rather than from a client,
	 * assume that the original deepstream node has already updated the record in cache and
	 * storage and only broadcast the message to subscribers
	 */
	if( socketWrapper === C.SOURCE_MESSAGE_CONNECTOR ) {
		this._$broadcastUpdate( recordName, message, socketWrapper );
		return;
	}
```

**Comment by ronag** [comment]
@yasserf: Thanks! If I remove that line I can have pure in memory caching. Which is what I wanted.
