### ISSUE TITLE
default "local" cache plugin issues with clustered setup

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#399]
Related https://github.com/deepstreamIO/deepstream.io/issues/397

The local cache plugin will not work in a clustered environment due to the following code:

```
    /*
     * If the update message is received from the message bus, rather than from a client,
     * assume that the original deepstream node has already updated the record in cache and
     * storage and only broadcast the message to subscribers
     */
    if( socketWrapper === C.SOURCE_MESSAGE_CONNECTOR ) {
        this._$broadcastUpdate( recordName, message, socketWrapper );
        return;
    }
```

Maybe there should be a flag indicating whether the cache is distributed or not and in such a case always broadcast the update?

**Comment by ronag** [comment]
I know that it's not supposed to be used in a prod environment. But you never know what people do... would also suggest that it be based on `lru-cache` or you might run out of memory...

**Comment by yasserf** [comment]
Local cache was never really expected to be used in a more than one node formation. 

Since we might be looking to remove the messages from updates ( since it chokes message buses quite badly ) I'll be closing this issue.
