### ISSUE TITLE
Win 10 Connection error

### ISSUE THREAD

**Issue by hipkiss91** [deepstreamIO/deepstream.io#407]
```
deepstream.min.js:2 WebSocket connection to 'ws://localhost:6020/deepstream' failed: Connection closed before receiving a handshake.
deepstream.min.js:2 --- You can catch all deepstream errors by subscribing to the error event ---
deepstream.min.js:2 Uncaught Error: connectionError: [object Event] (C)
```
That's the error I'm seeing. What's happening? It worked yesterday - turned my computer on this morning and now it doesn't work. Why?

**Comment by yasserf** [comment]
What branch are you running on?

**Comment by hipkiss91** [comment]
I've actually since fixed the issue by restarting my laptop. 
I downloaded the client from deepstream.io website. v1.1.1 for the server.
For the client I'm just using the CDN: which is also v1.1.1.

I believe I've found the problem - there seems to be a port conflict between WAMP (I'm using V3 64 bit) and deepstream, when launching WAMP then DS. But it seems the issue persists if I don't restart my machine and just restart the services in the opposite order.

**Comment by yasserf** [comment]
It is curiosity, which can are you using?

**Comment by yasserf** [comment]
Cdn* autocorrect

**Comment by hipkiss91** [comment]
`https://cdn.rawgit.com/deepstreamIO/deepstream.io-client-js/master/dist/deepstream.min.js`
The one used in this example: https://deepstream.io/tutorials/core/getting-started-quickstart/

**Comment by yasserf** [comment]
Yeah, that is using master and not v1.1.1

Version 1.1.1 would actually be:

https://cdn.rawgit.com/deepstreamIO/deepstream.io-client-js/v1.1.0/dist/deepstream.min.js

We are currently working on putting releases up on cdnjs as well, but for now that should work better.

**Comment by hipkiss91** [comment]
Awesome. Thank you. I would npm install it etc but I'm in the beginning stages of playing around with deepstream. I'll let you know how that works. And close the issue if req.

**Comment by yasserf** [comment]
If it isn't an issue you can close it, if you still can't connect let me know!

**Comment by hipkiss91** [comment]
Thanks! Seems to have fixed the issue!
