### ISSUE TITLE
Feature Request - Storage Exclusion Connector

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#415]
I would like to have more fine-grained control over storage exclusion. I would e.g. like to be able to use things like:

``` javascript
  async exclude (recordName, prevData, nextData, callback) {
    if (recordName.match(/^search\//)) {
      return true
    }

    if (recordName.match(/^stats\//) && parentRev) {
      return nextData.status === prevData.status
    }

    if (recordName.match(/^file\//) && parentRev) {
      return nextData.writing === prevData.writing
    }

    return false
  }
```

**Comment by yasserf** [comment]
Given we strive to provide an API that can be used by binary and nodejs modules alike this will need to be a sort of plugin / middleware. Happy to accept any PRs related to this though

**Comment by ronag** [comment]
any provided record should be excluded everything else should be included

**Comment by yasserf** [comment]
We will be looking to have a configurable way of setting this, since reducing writes to databases as part of deepstreamHub is important. Just not sure how yet.
