### ISSUE TITLE
Question - Record "Atomic Bit" size limit?

### ISSUE THREAD

**Issue by hipkiss91** [deepstreamIO/deepstream.io#417]
Is there a limit (bytes) for a Record? I.e. given the example in the link below, how big can the 'coords' message body be?
https://deepstream.io/tutorials/core/datasync-records/

**Comment by yasserf** [comment]
The size of your record depends on three things:

1) The maximum size allowed by your cache choice
2) The maximum size allowed by your storage choice
3) Less the maximum message sized allowed by deepstream

```
maxMessageSize

Sets the maximum message size allowed to be sent to the server (in bytes).
Default: 1048576
```

**Comment by hipkiss91** [comment]
@yasserf Further to this. I'm finding it difficult figuring out the difference between deepstream Events (pub/sub) and Records. Is it just that Records are used to interact with data on the server/in a DB?  
Finally, if I subscribed to an event `client.event.sub('news/front', x())` then if I did `client.event.emit('test', 'test')` would that `emit` then publish to the `news/front` "channel"?
