### ISSUE TITLE
unauthenticatedClientTimeout handles values wrong

### ISSUE THREAD

**Issue by PhillippOhlandt** [deepstreamIO/deepstream.io#423]
Right now, the `unauthenticatedClientTimeout` option accepts a number for a timeout or `null` for no timeout.
This behaviour is not consistent with other options.

It should accept a number for a timeout and `false` for no timeout. Everything else (`null`, `0`, `-1`) should lead to an error.

**Comment by MuriloFrade** [comment]
Hey @PhillippOhlandt thanks for opening this issue. We will add schema validations in the server options.

**Comment by MuriloFrade** [comment]
https://github.com/deepstreamIO/deepstream.io/commit/cfc9185365da2dc3c5b327581577f17e458cd2ea
