### ISSUE TITLE
Websocket Compression?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#426]
https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-28

Thoughts? Has it been tried with deepstream?

**Comment by yasserf** [comment]
@alexhultman, thoughts?

**Comment by alexhultman** [comment]
My personal opinion is that websocket compression is crap and that the application itself should make use of a better protocol so that compression becomes unnecessary in the first place. My opinion is that the JSON + compression idea is far inferior to \<insert any other format\> + no compression.

**Comment by ronag** [comment]
@alexhultman: I don't know much about this but from what I've read the compression can achieve around 50% compression rate. I don't see how a different encoding scheme could achieve that?

**Comment by alexhultman** [comment]
Sure you can achieve 99.99999% compression rate too. The compression rate is a direct measurement of how inefficient your original protocol is. If your application level protocol sends text, then sure, it might be a good idea to compress the text *before* you emit/send it. But to introduce a global compression of everything is going to result in:

* Tons of memory overhead per connection
* Tons of throughput loss
* Worse compression in most small messages (many small messages will be *larger* than the original)

If you instead aim for designing an efficient protocol from the start then you wouldn't have to compress things. Sadly, JSON is everywhere..

**Comment by alexhultman** [comment]
I worked for a company where they used JSON to send numbers... I swapped that protocol for a binary protocol with IEEE754 and it reduced the bandwidth by 95%, improved performance by at least 10x and increased the accuracy from 6 decimals to like 20 (decimal estimation). This was done in about 10 lines of JS. Point is that people need to design things better from the start.

**Comment by mariovalentim** [comment]
Hi guys,

I haven't found any information on the documentation with regards to per-message deflation. Is Deepstream (or underlying libs) supporting this RFC  (https://tools.ietf.org/html/rfc7692 )?
