### ISSUE TITLE
Message decoding/encoding in workers using transferable objects?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#427]
Has this been considered as an alternative to node cluster? #412 Might have less overhead and provide more fine grained parallelism (e.g. a single connection).

**Comment by yasserf** [comment]
Yes and no. Message parsing and formatting will happen in native modules to speed it up, so won't be done via workers.

Closing as we won't be moving it towards workers. We will provide an interface for the native module incase you decide to implement yourself in js.
