### ISSUE TITLE
How are updates sent out?

### ISSUE THREAD

**Issue by matthewoates** [deepstreamIO/deepstream.io#432]
Looks like an awesome project. I'm digging around to see how realtime updates of subscribed records are propagated to clients and I can't find any info on that.

Is the full JSON blob sent out, or is there some sort of diffing mechanism? This could heavily influence the design of larger records that have frequent but small changes.

**Comment by ronag** [comment]
If a client sends a `PATCH` then the same `PATCH` will be sent to all local subscribers. https://github.com/deepstreamIO/deepstream.io/blob/master/src/record/record-handler.js#L312

**Comment by matthewoates** [comment]
Thanks!
