### ISSUE TITLE
Can deepstream auto populate created_at/updated_at fields on persisting to storage?

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io#438]
Can deepstream auto populate date/timestamp to created_at/updated_at fields on persisting to storage? I know I can do this client side but this will allow client to manipulate the date/timestamp. Maybe this is more for storage connector than deepstream.

**Comment by Iiridayn** [comment]
I'm hoping to put a similar feature in as part of the validation in our permissions [Valve](https://deepstream.io/tutorials/core/permission-conf-simple/) file.

**Comment by WolframHempel** [comment]
that's a good question. We're generally looking at introducing data-transforms into Valve in the mid-term to allow for the addition of user specific values, as well as fields such as timestamps

**Comment by layanto** [comment]
Will this work as a workaround until Valve has data-transforms? For each storage connector (eg deepstream.io-storage-rethinkdb), modify the set(key,value,callback) method to insert updated_at timestamp? However, this timestamp will only be in the storage and not in deepstream's cache.

**Comment by fredguest** [comment]
honestly created_at/updated_at timestamps are table stakes for any moderately useful application that is based on user generated content, and it does seem that the most appropriate place to do this work would be within valve. where does this lie on the roadmap?

**Comment by yasserf** [comment]
> Maybe this is more for storage connector than deepstream.

This should definitely be added to connectors and not via deepstream. Some databases like postgres also have triggers that would automatically do that for you.
