### ISSUE TITLE
Performance of rpc versus pub/sub

### ISSUE THREAD

**Issue by mikeptweet** [deepstreamIO/deepstream.io#441]
I did the following two tests and pub/sub is substantially faster than rpc ... in my tests on localhost (using browser client), a round trip pub/sub takes less than a millisecond whereas a simple rpc takes almost a second ...

//Pub/Sub Test
client.event.subscribe('messages', function(data){
     console.timeEnd('Elapsed');
     console.log(data);
});

console.time("Elapsed");
client.event.emit('messages', Date())

//This takes less than a millisecond

//RPC test
client.rpc.provide( 'add-two-numbers', ( data, response ) => {
    response.send( data.numA + data.numB );
});

console.time('Elapsed');
client.rpc.make( 'add-two-numbers', { numA: 7, numB: 13 }, ( err, result ) => { 
   console.timeEnd('Elapsed');
    console.log(result);
});

//This takes upwards of a second

**Comment by WolframHempel** [comment]
that makes sense as they are very different things. Generally:

- The messages for your pub/sub test probably never left the client. If both `emit` and `subscribe` are on the same client, pub-sub works just like a local JavaScript event emitter. This test would only make sense if you have two separate clients, one sender and one receiver. The problem here however is clock-sync between the two. Try doing a ping->pong setup where client a emits an event that's received by client b and client b responds with another event as soon as that events received.

- RPC has four network hops (requestor->deepstream->provider->deepstream->requestor) whereas pub/sub only has two (emitter->deepstream->subscribers)

- RPC has more overhead for request routing as it needs to allocate the response to the right endpoint rather than fanning it out

Either way though, it shouldn't be more than a couple of milliseconds on a local setup. Where are your clients and servers running?

**Comment by mikeptweet** [comment]
Thanks for the prompt response ...

I did my test again with two browser instances and the pub/sub round trip is only a couple of milliseconds whereas the rpc is an average of ~700ms roundtrip time, which seems excessive give I am running on localhost

on browser 1
ds.event.subscribe('messages', function(data){
    ds.event.emit('response', Date())
})

ds.rpc.provide( 'add-two-numbers', ( data, response ) => {
    response.send( data.numA + data.numB );
});



on browser 2
ds.event.subscribe('response', function(data){
 console.timeEnd('Elapsed')
})

console.time("Elapsed");
ds.event.emit('messages', Date())


console.time('Elapsed');
ds.rpc.make( 'add-two-numbers', { numA: 7, numB: 13 }, ( err, result ) => { 
   console.timeEnd('Elapsed');
    console.log(result);
});

It's a windows 10 box running node 7 

the server is simply

const DeepstreamServer = require('deepstream.io')
const C = DeepstreamServer.constants
/*
The server can take
1) a configuration file path
2) null to explicitly use defaults to be overriden by server.set()
3) left empty to load the base configuration from the config file located within the conf directory.
4) pass some options, missing options will be merged with the base configuration
*/
const server = new DeepstreamServer({
  host: 'localhost',
  port: 6020,
  tcpPort: 6021
})

/*
Optionally you can specify settings to set in complex objects, such as dataTransforms, a HTTPServer
or a plugin which you want to reuse within your application
*/
server.set('dataTransforms', [{
  topic: C.TOPIC.RPC,
  action: C.ACTIONS.REQUEST,
  transform: function(data, metaData) {}
}])

// start the server
server.start()


and the client is
<!DOCTYPE html>
<html>
    <head>
        <script 
            type="text/javascript" 
            src="https://cdnjs.cloudflare.com/ajax/libs/deepstream.io-client-js/1.1.1/deepstream.js">
        </script>
    </head>
    <body>
        <input type="text" />
        <script type="text/javascript">
            ds = deepstream( 'localhost:6020' ).login();
            record = ds.record.getRecord( 'someUser' );
            input = document.querySelector( 'input' );

            input.onkeyup = function(){
                record.set( 'firstname', input.value );
            };

            record.subscribe( 'firstname', function( value ){
                input.value = value;
            });
        </script>
    </body>
</html>

I am running the tests in the browser console

**Comment by daviderenger** [comment]
@mikeptweet you must be doing something wrong, I just measured our RPC for creating a chat message. It involves a pretty advanced permission check, created a message record, setting timestamp on roomRecord, sending notifications to mobile devices etc and the round-trip time is below 40ms. This is on localhost. Doing the same RPC on our live servers is a little longer but not much (faster servers, more network time).

Have you tried with the server on a Linux machine?

**Comment by yasserf** [comment]
@mikeptweet I'm closing the issue due to inactivity. If you figured out why it took that long and it is deepstream related please let us know!
