### ISSUE TITLE
Missing connectionData with 2.0.0

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io#450]
Just upgraded to deepstream 2.0.0 and noticed that connectionData sent to http auth via POST is now blank (connectionData: {}). Previously I could retrieve connectionData.remoteAddress (IP address of the client logging in). Is this a bug?

**Comment by daviderenger** [comment]
I'm having the same problem, I got:

connectionData: { remoteAddress: undefined }

**Comment by yasserf** [comment]
Thanks for letting us know, we'll be looking into this shortly!

**Comment by daviderenger** [comment]
So now with 2.0.1 I receive connectionData: { remoteAddress: '127.0.0.1' }

And that is good but I'm still missing the headers, is there anything new or extra I need to do to get the headers too? I see that this if: if( this.socket.upgradeReq ) { says it has to be an upgrade req 
this is the response:

Request Method:GET
Status Code:101 Switching Protocols
Connection:Upgrade
Sec-WebSocket-Accept:M9ZKv3HaZNGR/JsSGLGgMxSIh68=
Sec-WebSocket-Version:13
Server:uWebSockets
Upgrade:websocket

So it should provide the headers right?

**Comment by daviderenger** [comment]
So I found the problem (but not the solution):

In socket-wrapper.js I log this

SocketWrapper.prototype.getHandshakeData = function() {
	var handshakeData = {
		remoteAddress: this.socket._socket.remoteAddress
	};

console.log("socket upgradeReq?", this.socket.upgradeReq ? this.socket.upgradeReq.headers : null);

	if( this.socket.upgradeReq ) {
		handshakeData.headers = this.socket.upgradeReq.headers;
		handshakeData.referer = this.socket.upgradeReq.headers.referer;
	}

	return handshakeData;
};


And this is the result when connecting with one client:

setting-6 socket upgradeReq? { upgrade: 'websocket',
setting-6   connection: 'upgrade',
// and the rest of the headers here
setting-6   cookie: 'the real cookies here',
setting-6   'sec-websocket-key': '/b+HQTDHdgGeA26k0LF/UQ==',
setting-6   'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits' }
setting-6 INCOMING_CONNECTION | from undefined (127.0.0.1)
setting-6 socket upgradeReq? null
setting-6 socket upgradeReq? null
setting-6 {"name":"setting","hostname":"hem","pid":14144,"level":20,"filename":"is-valid-user.js","msg":"Connection data: { remoteAddress: '127.0.0.1' }","time":"2016-11-26T14:39:01.717Z","v":0}

So getHandshakeData is called three times and only the first time it has the upgradeReq but apparently its not the data that is passed along to the is-valid-user callback function.

**Comment by daviderenger** [comment]
bumo @yasserf I think this should be reopened

**Comment by yasserf** [comment]
Hey @daviderenger, thank you for the detailed description. We'll be looking into it shortly!
