### ISSUE TITLE
Valve permission checking if intersect between two Arrays

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io#454]
Following the nesting cross-references example in https://deepstream.io/tutorials/core/permission-conf-advanced/, how should the Valve permission be updated if instead of user.country we have user.countries: ['USA','SPA']? Provided that at least one country appears in both Arrays then permission granted.

**Comment by layanto** [comment]
Related to issue https://github.com/deepstreamIO/deepstream.io/issues/459

**Comment by WolframHempel** [comment]
Makes sense to have intersects.

**Comment by yasserf** [comment]
Valve is generally quite CPU intense. I would say if you have complex permissions you used a custom permission handler or going forward a plugin-combiner which allows you to run multiple plugins so for specific names you can implement your own very basic JS functions.
