### ISSUE TITLE
AuthParams as JSON string, In Java Client.

### ISSUE THREAD

**Issue by chinmaygit** [deepstreamIO/deepstream.io#466]
Hi, I use JACKSON in my android project and deepstream java client seems using GSON you may have obvious reasons to use GSON,  It will be duplication of json library for me, and i hope most of the android developers are using JACKSON. I suggest if you change it to json String rather than com.google.gson.JsonElement, it will be easy and universal.

**Comment by yasserf** [comment]
hey @chinmaygit 

Opened an issue against Java repo in favour of deepstream.io:
https://github.com/deepstreamIO/deepstream.io-client-java/issues/62

This requires a bigger discussion about how we plan on doing this. One approach might be JNI bindings into C++ land, which means we can then have two seperate java libraries, but won't be happening anytime soon =(

**Comment by chinmaygit** [comment]
Okay... good...
