### ISSUE TITLE
Documentation for using deepstream 2.x with PassportJS

### ISSUE THREAD

**Issue by geecu** [deepstreamIO/deepstream.io#469]
It would be great if there was a blog post or documentation guide/tutorial on how to achieve Facebook login (or another oAuth provider) with deepstream 2.x, similar to [this post](https://deepstream.io/blog/using-passportjs/) that only works with deepstream 1.x. 

The post should be updated to state that it only works with deepstream 1.x and it should link to the post for version 2.x. 

This issue was created following @yasserf's suggestion in #455

**Comment by yasserf** [comment]
Gist here:

https://gist.github.com/yasserf/07cb500c038a9648bc5f51fea062ca88

Need to update blog accoridngly!

**Comment by yasserf** [comment]
Closing as we don't have a custom http server since v1 and this would be recommended to be done via the HTTP API to a central login service.
