### ISSUE TITLE
subscriptionRegistery & string sender

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#473]
Not quite following this:

https://github.com/deepstreamIO/deepstream.io/blob/master/src/utils/subscription-registry.js#L225

What if the sender is a string, e.g. `C.SOURCE_MESSAGE_CONNECTOR`?

**Comment by yasserf** [comment]
Honestly don't know ontop of my head.

Should get a reply as part of fixing #533

**Comment by ronag** [comment]
@yasserf: See https://github.com/deepstreamIO/deepstream.io/pull/555/commits/1735774c026cc45ffe596c1eea5d9e35a6ae20a9

**Comment by yasserf** [comment]
Sweet!

I might just cherry-pick that statement for now then.
