### ISSUE TITLE
Excessive stringification

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#478]
Currently there is quite a lot of unnecessary stringification going on the same record version:

```js
// receive update
JSON.parse
// deepClone
JSON.stringify 
JSON.parse
// send to redis
JSON.stringify
// send to db
JSON.stringify
// read from redis
JSON.parse
// everytime record is sent to a client
JSON.stringify
```

Basically all instances of `JSON.stringify` in the list above could be avoided.

Not sure what the complexity vs performance metrics would be to resolve these...

**Comment by yasserf** [comment]
This is something we will address is v3.0 with new storage APIs

**Comment by yasserf** [comment]
Addressed in V4, we now do lazy parsing for data (only parses once and only if needed due to being a patch or permission check).
