### ISSUE TITLE
Some options are missing in the packaged DS versions

### ISSUE THREAD

**Issue by PhillippOhlandt** [deepstreamIO/deepstream.io#488]
In the packaged versions of DS (tested yum and mac), some config options are missing in the shipped config.yml.

Just noticed because I looked for `unauthenticatedClientTimeout` and `healthCheckPath` who are both missing.

**Comment by yasserf** [comment]
Good point, this is because we have a separate config file for packaged versions.

**Comment by PhillippOhlandt** [comment]
Personally, I would like to have all possible options in the packaged one so I don't forget to adjust something.
