### ISSUE TITLE
Inaccurate Presence for users with multiple sessions

### ISSUE THREAD

**Issue by PhillippOhlandt** [deepstreamIO/deepstream.io#491]
I experienced some weird behaviour with presence.

In my test setup, I have a little app where I can login using username/password, defined in the `users.yml` file. I use a single DS instance (2.0.1) without any connectors.

I opened the app in two browser tabs on the same device and browser and:
1. logged in on tab 1 -> presence listener gets triggered with the login
2. logged in on tab 2 -> presence listener does nothing
3. logged out on tab 1 -> presence listener gets triggered with the logout
4. logged out on tab 2 -> presence listener does nothing

So, in reality, after step 3, I am still logged in on tab 1 but DS thinks I am logged out.
It's not only the listener. When I request the full list of logged in users after step 3, it's empty too.

**Comment by yasserf** [comment]
This should have been fixed in 2.1.0, can you confirm?

**Comment by PhillippOhlandt** [comment]
Yep, working all fine since that release!
