### ISSUE TITLE
Server Config Location on Linux

### ISSUE THREAD

**Issue by ChristophConrads-deepstreamHub** [deepstreamIO/deepstream.io#492]
## Problem Statement

Currently, the location of the server configuration files (config, user list for file-based authentication, permissions) seems to differ across Linux distributions (see [this GitHub comment](https://github.com/deepstreamIO/deepstream.io-website/pull/77#discussion_r92046517)).

## Linux Filesystem Conventions

Usually, system-wide configuration can be found in `/etc` ([source](https://en.wikipedia.org/wiki/Unix_filesystem#Conventional_directory_layout)), user-specific configuration can be found in a hidden file in the user's home directory or in non-hidden files in a hidden directory (https://stackoverflow.com/a/1024121), some applications look in the current working directory for config files where this is useful, and the command can be used to specify config file locations. The priority of the possible locations in decreasing order is usually as follows:
- command line or environment variables,
- current working directory,
- user's home directory,
- `/etc`.

Often, select options can be overridden with command line parameters or environment variables. Finally, an application has to specify if it reads all available configuration files or only the first config encountered by the program. If the application reads all available configuration data, then it has to define how multiple occurrences of the same parameters are handled.

Since deepstream is not a graphical application, it can probably ignore the [_XDG Base Directory Specification_](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (XDG stands for X Desktop Group, nowadays known as freedesktop.org).

### Examples

The revision control system [git](https://git-scm.com) reads the following config files (in this order):
- `/etc/gitconfig`,
- `$XDG_CONFIG_HOME/git/config`,
- `~/.gitconfig`, and
- the current git repository if the current working directory is part of a git repository.

Options given multiple times are overwritten by files read later (https://git-scm.com/docs/git-config) and options provided on the command line have the highest priority.

## Case Study: Apache HTTP and nginx

I briefly talk about the behavior of the webservers [nginx](https://nginx.org) and the [Apache HTTP Server](https://httpd.apache.org). 

The standard location of the config file is `PREFIX/conf/httpd.conf` though Ubuntu, Debian, and Gentoo move this file to `/etc/apache2/` ([source 1](https://www.digitalocean.com/community/tutorials/how-to-configure-the-apache-web-server-on-an-ubuntu-or-debian-vps), [source 2](https://wiki.gentoo.org/wiki/Apache#.2Fetc.2Fapache2.2Fhttpd.conf)), where `PREFIX` is the value of the `--prefix` option set at compile time. The nginx configuration file location is not uniquely specified in the documentation ([example](http://nginx.org/en/docs/beginners_guide.html)), but often it can be found at `/etc/nginx/nginx.conf`, e.g., on Ubuntu, Debian, and Gentoo ([source 1](https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-16-04), [source 2](https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-debian-8m), [source 3](https://wiki.gentoo.org/wiki/Nginx)).

## Solution Proposal

Based on the behavior of Apache HTTP and nginx, I propose that deepstream on
Linux should move its configuration files to `/etc/deepstream` unless it was installed with npm.

**Comment by yasserf** [comment]
I believe this is how it works now. Unless I'm totally incorrect

This issue documentation is <3

**Comment by mrby** [comment]
![Screen Shot 2017-07-07 at 16.42.50.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588a1d5fc3985120000a471e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246454f46b7191a379e90c2f53415a4ebe5d4a1f06a3a3dc78e2a436628f5408bed26c5921c03c10ffec851fea01ba25d84a86e7bc9850d2aa6c7bb3d4d216744b470a83ed5f33aa984fc151f248e94852ac153163f43b.png)

**Comment by yasserf** [comment]
cool, thanks!

For path references, using pwd is a lil easier to prove absolute paths ;)

**Comment by k3rn3l-p4n1c** [comment]
Is it possible to override configs with environment variables or command line arguments?
