### ISSUE TITLE
Relative Path Handling

### ISSUE THREAD

**Issue by ChristophConrads-deepstreamHub** [deepstreamIO/deepstream.io#493]
## Problem Statement

The server config may contain relative paths but nowhere does the documentation specify the base directory (directories).

## Case Study: Apache HTTP and nginx

If the directive [`ServerRoot`](http://httpd.apache.org/docs/2.2/mod/core.html#serverroot) was given in the config, Apache interprets all paths relative to the path given in `ServerRoot`. Its value defaults to the `--prefix` argument used for building the software and the default value of `--prefix` is `/usr/local/apache2` ([source](https://httpd.apache.org/docs/2.4/install.html#overview)). nginx interprets paths relative to the value of [`--prefix`](https://nginx.org/en/docs/configure.html), too, unless overridden on the command line with the [`-p` flag](https://nginx.org/en/docs/switches.html). The default value of `--prefix` is `/usr/local/nginx` ([source](http://nginx.org/en/docs/configure.html)). Note that older nginx versions behaved differently (see https://serverfault.com/a/384606).

## Solution Proposal

Based on the behavior of Apache HTTP and nginx, I propose that deep stream
- interprets all paths relative to a root path,
- provides options in the config file and maybe on the command line to override the root path.

deepstream on Linux installed with a Linux package manager (APT, yum, or similar) or npm should contain a harcoded root path. The standalone binary should use the current working directory as the root path although we could determine where the binary is located with the aid of the `proc` filesystem ([source](http://superuser.com/questions/103309/how-can-i-know-the-absolute-path-of-a-running-process)).

**Comment by yasserf** [comment]
This is an important fix, but we need to figure out exactly how we want it to work incase of backwards compatibility changes.
