### ISSUE TITLE
MacOS standalone binary hashing broken

### ISSUE THREAD

**Issue by ChristophConrads-deepstreamHub** [deepstreamIO/deepstream.io#494]
The password hashes generated by the MacOS standalone binary v2.0.1 always lead to authentication errors.

The error must be located in the hash computation because the default config files shipped with the standalone binary work with both the standalone binary and the deepstream server installed via npm. Similarly, using newly generated password hashes causes authentication failures with both programs.

Steps to reproduce:
- download the binary ([direct link](https://github.com/deepstreamIO/deepstream.io/releases/download/v2.0.1/deepstream.io-mac-2.0.1.zip))
- unzip
- enable file-based authentication in `conf/config.yml`
- start the server
- connect with a client, username `userA`, password `password`
- observe `AUTH_SUCCESSFUL` message in server output
- kill client and server
- compute a password hash with `./deepstream hash password`
- copy the new hash into `conf/users.yml`
- start the server
- connect with a client, username `userA`, password `password`
- observe `INVALID_AUTH_DATA` message in server output, `AUTH_SUCCESSFUL` is expected

**Comment by ChristophConrads-deepstreamHub** [comment]
Hash computation with deepstream 2.0.1 installed with npm works.

**Comment by yasserf** [comment]
Can we reverify if this is broken?

**Comment by mrby** [comment]
![Screen Shot 2017-07-10 at 12.01.45.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588a1d5fc3985120000a471e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f36b7191a379ed0c2b50415b4bbe5d4a1f06a3a3dc78e2a436628f5408bed26c5921c03c10ffec851fea01ba25d84a86e7bc9850d2aa6c7bb3d4d216744b470a83ed5f32aa984fc151f043e1445da2153066f43b.png)
