### ISSUE TITLE
Idea: Adding support for graph databases

### ISSUE THREAD

**Issue by mirokk** [deepstreamIO/deepstream.io#495]
Hello,
not a bug, but an idea:
what about adding support for graph databases? they are perfect for most of your use cases.
I'd recommend ArangoDB as its the best available fully open source graph database on the market..

**Comment by WolframHempel** [comment]
Deepstream's records / lists work similarly to the way a document oriented database is organised: schema-less documents, identified by a unique id. Relations are modeled by referencing a record's unique id from within another record or list. As a result, I'm afraid deepstream wouldn't be able to make use of the Graph features (or relational database features for that matter). One could however create a connector for ArangoDB's key-value store

**Comment by mirokk** [comment]
Thank you for the reply, that makes sense. 
Is there a way to model typical graph applications with deepstream directly in a performant way? Like "show me friends of my friends" or "show me Tags or Interests of people that have similar interests like me"?
Or would you rather use deepstream only for the realtime updates, and have a separate application for things that require a graph -  as those questions from above (show me friends of friends) don't require realtime anyways..

**Comment by kristianmandrup** [comment]
You could perhaps leverage something like Gun or Neo4J. Ideally you would use/link multiple different DBs to support different scenarios/use cases for working with your data.

**Comment by yasserf** [comment]
Just confirming that @kristianmandrup is correct. Some of our users tend to put things in elasticsearch and a no sql db and use them to query things differently. I hope that helped =)
