### ISSUE TITLE
Deepstream.io Compression

### ISSUE THREAD

**Issue by devcem** [deepstreamIO/deepstream.io#496]
Hello,

How can i implement compression method for client and server? I want to transform output and input data to reduce bandwidth size. Is that possible at the moment? I'm planning to work on /message (directory) or read-message.js. I'm not sure which is can be easily. I was planning to ask you in different way but Github just allowed me to ask you with creating issue ticket. Sorry about that :(

Also I just take a look into code and plan to do it with that way :
- Update **message-parser.js** "parse" function. For server-side.
- Update **message-parser.js** "parse" function. For client-side.

I'm not sure but i guess parse function helps to transform each data that server handle. So my question is that if i update parse function to reduce bandwidth, would it be easiest and right way to do that?

Regards

**Comment by ronag** [comment]
you should probably do this inside `record-handler` on the server and `record` in the client. Basically you want to compress the `data` part of the `UPDATE`, `READ` and `PATCH` messages.

Example: https://github.com/nxtedition/deepstream.io-client-js/blob/master/src/record/record.js#L201
