### ISSUE TITLE
Incomplete permissions file crashes deepstream server

### ISSUE THREAD

**Issue by ChristophConrads-deepstreamHub** [deepstreamIO/deepstream.io#497]
Client code, server code, config.yml, users.yml, permission.yml in one zip: [issue496.zip](https://github.com/deepstreamIO/deepstream.io/files/651868/issue496.zip)

Use the following file as `permissions.yml`:
```
record:
    "*":
        create: true
        write: "user.mayWrite"
event:
    "*":
        subscribe: true
rpc:
    "*":
        provide: true
presence:
    "*":
        allow: true
```
Checking for the existence of a record with `client.record.has()` will cause the MacOS standalone server binary to throw the following uncaught exception:
```
TypeError: Cannot read property 'regexp' of null
TypeError: Cannot read property 'regexp' of null
    at ConfigPermissionHandler.canPerformAction (nexe.js:25475:19)
    at MessageProcessor.process (nexe.js:25003:35)
    at ConnectionEndpoint.<anonymous> (nexe.js:24445:60)
    at Server.native.server.group.onMessage (nexe.js:1225:23)
```
With deepstream 2.0.1 installed via npm the error is as follows:
```
/Users/christoph/node_modules/deepstream.io/src/permission/config-permission-handler.js:164
		regexp: ruleData.regexp,
		                ^

TypeError: Cannot read property 'regexp' of null
    at ConfigPermissionHandler.canPerformAction (/Users/christoph/node_modules/deepstream.io/src/permission/config-permission-handler.js:164:19)
    at MessageProcessor.process (/Users/christoph/node_modules/deepstream.io/src/message/message-processor.js:63:35)
    at ConnectionEndpoint.<anonymous> (/Users/christoph/node_modules/deepstream.io/src/message/connection-endpoint.js:315:60)
    at Server.native.server.group.onMessage (/Users/christoph/node_modules/uws/uws.js:403:23)
```

What I expect is
- deepstream refusing to use the provided `permission.yml`, or
- deepstream not crashing because of an uncaught exception.

**Comment by yasserf** [comment]
Both options should be viable. Great catch!

**Comment by adamgoose** [comment]
Still experiencing this with v3.0.0.

**Comment by MuriloFrade** [comment]
The server in the 3.1.1 version is not crashing with the provided code and configurations but this still a bug. 

The client logs first the error `recordName UNSOLICITED_MESSAGE R` followed later by `No response received in time for R|H|recordName RESPONSE_TIMEOUT R`.

**Comment by MuriloFrade** [comment]
This is an issue in the JS client now. 
The client is receiving this message
```
{ 
  raw: 'R\u001fE\u001fMESSAGE_DENIED\u001frecordName\u001fH',
  topic: 'R',
  action: 'E',
  data: [ 'MESSAGE_DENIED', 'recordName', 'H' ] 
}
```
But the record handler is handling as an UNSOLICITED_MESSAGE.

**Comment by yasserf** [comment]
This no longer crashes the server. V4 client now has correct error parameters and catches errors if using promises.
