### ISSUE TITLE
IE Error "The connection with the server was terminated abnormally"

### ISSUE THREAD

**Issue by cpoyraz** [deepstreamIO/deepstream.io#502]
I get data from stream via DeepStream client in IE. And console shows constantly an error message below

SCRIPT12030: WebSocket Error: Network Error 12030, The connection with the server was terminated abnormally

What may cause of this?

**Comment by yasserf** [comment]
What version of IE are you using?

**Comment by cpoyraz** [comment]
![ie](https://cloud.githubusercontent.com/assets/467161/21307309/a3fa1408-c5dd-11e6-9790-d512edbe3751.png)

**Comment by yasserf** [comment]
Great thanks! Well look into this and let you know if we can replicate the issue asap

**Comment by yasserf** [comment]
So I ran it in IE11 and wasn't able to replicate it:

![image](https://cloud.githubusercontent.com/assets/2734923/21308317/ba028c8e-c5d9-11e6-8390-d65e794dd5f0.png)

Can you also confirm what version of deestream and the client you are using? And if this issue happens with just deepstream code or if you have anything custom that triggers it

**Comment by cpoyraz** [comment]
I am using Deepstream 2.0 version and as client , it is from the url  https://cdnjs.cloudflare.com/ajax/libs/deepstream.io-client-js/2.0.0/deepstream.min.js .

The architecture is like this.
![deepstream](https://cloud.githubusercontent.com/assets/467161/21310684/2aac2492-c5ec-11e6-9670-f9c1a14e1ce7.png)

**Comment by cpoyraz** [comment]
When I check the deepstreams, all deepstream servers logs the lines like below

INCOMING_CONNECTION | from undefined ( ... )
AUTH_SUCCESSFUL | open
CLIENT_DISCONNECTED | open
INCOMING_CONNECTION | from undefined ( ... )
AUTH_SUCCESSFUL | open
CLIENT_DISCONNECTED | open
INCOMING_CONNECTION | from undefined ( ... )
AUTH_SUCCESSFUL | open
CLIENT_DISCONNECTED | open
INCOMING_CONNECTION | from undefined ( ... )
AUTH_SUCCESSFUL | open
CLIENT_DISCONNECTED | open
CLIENT_DISCONNECTED | open
CLIENT_DISCONNECTED | open
INCOMING_CONNECTION | from undefined ( ... )
AUTH_SUCCESSFUL | open
INCOMING_CONNECTION | from undefined ( ... )
AUTH_SUCCESSFUL | open
CLIENT_DISCONNECTED | open
INCOMING_CONNECTION | from undefined ( ... )
AUTH_SUCCESSFUL | open
CLIENT_DISCONNECTED | open
INCOMING_CONNECTION | from undefined ( ... )
AUTH_SUCCESSFUL | open
CLIENT_DISCONNECTED | open
INCOMING_CONNECTION | from undefined ( ... )
AUTH_SUCCESSFUL | open

**Comment by cpoyraz** [comment]
I tested with deepstream io client sample, it runs without error like you said.  The difference between codes is the multiple event subsciptions, I changed my code with single event subsciption, it runs. But I updated it with multiple event subcriptions, the error below occurs 

SCRIPT12030: WebSocket Error: Network Error 12030, The connection with the server was terminated abnormally

**Comment by cpoyraz** [comment]
fixed in deepstream 2.1.0 and deepstream-js-client 2.1.1

**Comment by yasserf** [comment]
Happy to hear!

**Comment by tony-gutierrez** [comment]
What was the cause!? this error is all over the internet. What can you do server side to avoid it?

**Comment by yasserf** [comment]
I unfortunately don't know what exactly fixed it =(
