### ISSUE TITLE
Calling `record.unsubscribe()` does not remove all subscriptions

### ISSUE THREAD

**Issue by ChristophConrads-deepstreamHub** [deepstreamIO/deepstream.io#508]
Demo code:
-  [private repo link](https://github.com/deepstreamIO/deepstream.io-website-examples/tree/master/records/unsubscribe)
- [public unsubscribe-example.zip](https://github.com/deepstreamIO/deepstream.io/files/663798/unsubscribe-example.zip)

**Comment by ChristophConrads-deepstreamHub** [comment]
According to the [JavaScript client record documentation](https://deepstream.io/docs/client-js/datasync-record/), unsubscribe should remove all callbacks:
```
Unsubscribe all callbacks not associated with a path:
user.unsubscribe()
```

**Comment by PawkaHub** [comment]
I'm running into this one as well. Any ideas as to why it'd be happening?

**Comment by yasserf** [comment]
This is a client issue, it appears we are passing undefined into the off command and its doing a `.length' which makes it think that the path exists.

https://github.com/component/emitter/blob/187492ab8028c7221b589bdfd482b715149cd868/index.js#L89
https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/src/record/record.js#L245

```
a = function(a,b) {
  console.log(arguments.length)
}
a('1')  // 1
a(undefined) // 1
```

Seems like a quick fix, we'll get it in the next release!

**Comment by EnigmaCurry** [comment]
This is broken for list.unsubscribe() (without callback specified) too:

![list.unsubscribe](http://ec-screenshots.s3.amazonaws.com/64dce5f4-0816-11e7-b97a-525400990d79.png)

**Comment by jshrt** [comment]
This is fixed in v4. Closing.

---
_You can test this using this_ [_script_](https://github.com/deepstreamIO/test-scripts/blob/v4-test/scripts/records-subscriptions.js)
