### ISSUE TITLE
creating two db with same name while getting/creating (nonexistent) records fast!

### ISSUE THREAD

**Issue by cpoyraz** [deepstreamIO/deepstream.io#511]
I am using rethinkdb as storage and setting database as "A" and defaultTable as "B". I called the function getRecord for nonexistent record like "d/1" and "d/2" in loop  and it creates two databases with the name "d" and then deepstream and rethinkdb stop working.

**Comment by WolframHempel** [comment]
thanks for raising this. Could you provide some more detail please:

- does it create two databases or tables?
- what happens when "deepstream and rethinkdb stop working"? Are there any error messages?

Many thanks,

Wolfram

**Comment by cpoyraz** [comment]
it creates two tables with the same name.

And then it gives an error containing ambiguous table .

Regards,

Cengiz

**Comment by yasserf** [comment]
I have seen this issue before without deepstream, rethinkdb does that due to it's distributed mechanism ( no dB lock ). Personally no idea how to fix it :(

**Comment by cpoyraz** [comment]
I think that two ways can be used for fixing
- Creating table previously.
- Making an interval like 1s between getRecord calls.

**Comment by cpoyraz** [comment]
It seems the best solution will come from RethinkDB crew. Thanks, Yasser.

**Comment by WolframHempel** [comment]
The general scenario is that if you initially write a topic to 2 different deepstream servers they get in a race condition => On rethink it creates 2 tables, On postgres it throws a constraint error.

**Comment by yasserf** [comment]
Unfortunately there isn't a way we can really solve this with a cluster, and is a symptom of writes occurring at the same time from multiple servers. Introducing a locking mechanism would just kill performance. Best approach is to create your tables upfront if you know this would be an issue.
