### ISSUE TITLE
Multiple set on the same record only writes the first value to database

### ISSUE THREAD

**Issue by SejH** [deepstreamIO/deepstream.io#517]
After running the the following code only one of the three values will be saved to the database.
Using deepstream.io 2.1.1, deepstream.io-client-js 2.1.1 and deepstream.io-storage-rethinkdb 1.0.2.

```javascript
const dsc = require('deepstream.io-client-js')('ws://localhost:8000');
function set(key, val) {
  const record = dsc.record.getRecord('foo');
  record.whenReady(() => {
    record.set(key, val, error => {
      console.log('Set done', { error, key, val, recordData: record.get() });
      record.discard();
    });
  });
}

dsc.login({}, (success, data) => {
  set('foo', 1);
  set('bar', 2);
  set('baz', 3);
});
```
With the output:
`Set done { error: null, key: 'foo', val: 1, recordData: { foo: 1, bar: 2, baz: 3 } }`
`Set done { error: null, key: 'bar', val: 2, recordData: { foo: 1, bar: 2, baz: 3 } }`
`Set done { error: null, key: 'baz', val: 3, recordData: { foo: 1, bar: 2, baz: 3 } }`

Database after:
```json
{
    "__ds": {
    "_v": 1
    } ,
    "foo": 1 ,
    "id":  "foo"
}
````

**Comment by AlexBHarley** [comment]
@SejH this has been fixed now. Could you please try and let us know?

**Comment by SejH** [comment]
@AlexBHarley The issue seems to be fixed!
