### ISSUE TITLE
Is it possible to send multiple responses to an rpc make?

### ISSUE THREAD

**Issue by cpoyraz** [deepstreamIO/deepstream.io#521]
Is it possible to do the use case like below?

1. User sends an RPC make request to register an account
2. RPC provider should send progress-info messages about rpc process like "starting..","checking if username exists", "creating.."

**Comment by yasserf** [comment]
Using RPCs only, no. But what we often do is turn a uuid of a record or event the RPC provider creates that the client can listen to for updates of that RPC post response.

**Comment by yasserf** [comment]
Return*

**Comment by cpoyraz** [comment]
Thanks
