### ISSUE TITLE
What's the difference between Ejabberd and Deepstream?

### ISSUE THREAD

**Issue by prafulbagai** [deepstreamIO/deepstream.io#524]

**Comment by Srushtika** [comment]
Hi @prafulbagai ! Ejabberd is a server that works on XMPP protocol - something that's specifically built to support chat applications. Whereas deepstream is a realtime server that works on websockets thus allowing simultaneous two way exchange of data  allowing apps to work in realtime.

deepstream comes with three different products with varying features. Feel free to go through the [comparison](https://deepstreamhub.com/compare/) page to know more.
