### ISSUE TITLE
Does deepstream have some fallback options?

### ISSUE THREAD

**Issue by rsdrsd** [deepstreamIO/deepstream.io#529]
Deepstream is a websocket server, but I can't find if it has some fallback options like long-polling or not. It is nowhere mentioned in the docs. I can assume that it hasn't but I want to know it for sure.

**Comment by jdmnd** [comment]
Hi @rsdrsd,

Sorry for the delayed response.
Deepstream v2.0 dropped support for engine.io, and all later versions will only support WebSockets. In browsers without WebSocket support, the client will fail to start. 
Hope that clears things up, we'll take a look at making this clearer in the documentation. 

John
