### ISSUE TITLE
`delete` events don't flow to clients connected before mine

### ISSUE THREAD

**Issue by mclark-newvistas** [deepstreamIO/deepstream.io#533]
Common setup:
1. load browser window 1
2. load browser window 2
3. In both (order doesn't matter): `var r = client.record.getRecord('test'); r.on('delete', function() { console.log('deleted'); });`

This is incorrect:
1. Run common setup
2. In 2: `r.delete()`
3. Notice how 1 doesn't show the deleted message
4. In 1: `r.delete()`
5. Now it does, though the record wasn't in the database anyway

It should work the same as:
1. Run common setup
2. In 1: `r.delete()`
3. Notice how 2 also shows the deleted message
4. In 2: `r.delete()`
5. Notice this time deepstream complains that the record is already destroyed

**Comment by mclark-newvistas** [comment]
Not sure if this is a client or server issue

**Comment by mclark-newvistas** [comment]
`client in RECORD ACK ["DELETE", "test"]` is missing on the other client - which suggests to me that this is a server error, since the other client is not getting the `ACK`

**Comment by yasserf** [comment]
Hey,

Thanks for raising this. Delete functions should work regardless of the order of the clients connected, we'll look into this asap.

Cheers,
Yasser

**Comment by mclark-newvistas** [comment]
```
var deepstream = require('deepstream.io-client-js');

function client() {
	return new Promise((resolve, reject) => {
		var client = deepstream('localhost:6020').login({}, (success, data) => {
			if (!success) return reject(data);
			resolve(client);
		});
	});
}

function testRecord(client, label) {
	return new Promise(resolve => {
		client.record.getRecord('test').on('delete', function() {
			console.log(label, 'deleted');
			client.close();
		}).whenReady(r => resolve(r));
	});
}

var A = client();
var B = client();

var rA = A.then(client => testRecord(client, 'rA'));
var rB = rA.then(() => B).then(client => testRecord(client, 'rB'));

if (process.argv[2] === 'work')
	rB.then(r => r.delete());
else
	rA.then(r => r.delete());
```

Seems to be failing sometimes even when run as `node test.js work`, but that should be a different issue - demonstrates the failure correctly every time when not supplied "work" as an argument.

**Comment by mclark-newvistas** [comment]
Intermittent failure for 'work' happens when `socket.uuid` for A is `>` `socket.uuid` for B. Still tracing cause.

**Comment by yasserf** [comment]
Ah, I think you might have nailed it. A delete removes the subscription from the registry, but we send updates on next tick.

Subscription registry would be my bet on the problem root!

**Comment by mclark-newvistas** [comment]
Yeah, I can think of two broad solutions - either pass the current subscribers with the message to the delayed broadcasts structure, or return to a callback which then does the unsubscribe in the delete code. There are possibly others which I have not considered due to unfamiliarity.

Given that the delayed broadcasts structure is clearly doing unusual things for benchmark purposes I am hesitant to change it to a simpler, slower implementation. I'll try the callback route - should be safe to just process a block of callbacks once the messages have gone out.

**Comment by ronag** [comment]
@yasserf: See https://github.com/deepstreamIO/deepstream.io/pull/555/commits/1c84145f09fef5fd3c00bba120ad36cd7f71b806

**Comment by yasserf** [comment]
@ronag is ur commit a fix? If so will try to replicate before and after

**Comment by yasserf** [comment]
I believe this has been fixed
