### ISSUE TITLE
response timeout due to asynchronous method used in rpc provide method in spite of setting autoAck to false

### ISSUE THREAD

**Issue by cpoyraz** [deepstreamIO/deepstream.io#534]
I call once the rpc for registering then it returns two responses. I set the timeout values to 1 min and I am sure that process does not do it more than 1 min. How is that possible? 
```
client.rpc.provide("register", function(data, response){
   client.rpc.make("anorherProcess", data, function(err, result){
if (err){
   response.send({"err": err});
   return;
}
    response.send({"err": err, message:  'user is added successfully!'});
});
});

client.rpc.make("register", data, function(err, result){
   console.log("err:", err, " result:", result);
});
```

> err: RESPONSE_TIMEOUT  result: undefined 
> err: null  result: { message: 'user is added successfully!'}
>

**Comment by cpoyraz** [comment]
I think it is because of aynchronous method used in rpc provide method, Why rpc triggers timeout error before timeout value from config file passed?

**Comment by yasserf** [comment]
Thanks for raising! We will take a look at this as soon as possible.

If possible, can you raise issues against the SDK repo? It makes it easier for sprint planning. 

Thank you!

**Comment by Sheshagiri** [comment]
This seems to be happening with deepstream.io-client-java as well.

**Comment by AlexBHarley** [comment]
Hi @Sheshagiri, it looks like the correct config option to be using is `rpcResponseTimeout`, rather than `rpcTimeout` as seen [here](https://github.com/deepstreamIO/deepstream.io-client-java/blob/master/src/main/java/io/deepstream/ConfigOptions.java#L40).

Could you please try that and let us know if you're still having trouble?

**Comment by Sheshagiri** [comment]
@AlexBHarley  thank you for the prompt response. After adding the `rpcResponseTimeout` flag to the client I don't see the `RESPONSE_TIMEOUT` issue.
