### ISSUE TITLE
DB and Cache Connectors in Deepstream

### ISSUE THREAD

**Issue by minaxi30** [deepstreamIO/deepstream.io#542]
Hi, We are going to make multiplayer game server over DeepStream. Do we really need to have these ? cant we save data locally in internal memory, as DeepStream does if you don't have any DB connectors.

**Comment by AlexBHarley** [comment]
You could do that but if you want data to be persisted and synced across multiple deepstreams you'll need a cache or storage connector

**Comment by yasserf** [comment]
Hope that answered your question! Closing issue
