### ISSUE TITLE
Is data/record sync faster than event emitting?

### ISSUE THREAD

**Issue by nolram88** [deepstreamIO/deepstream.io#545]
I've been experimenting with deepstream on and off for the past couple months and I was hoping to get some clarification on best case scenario throughput expectations for each method of communication. My use case prefers smaller and faster messages.

**Comment by WolframHempel** [comment]
events are generally faster as they don't have to access caches or storage layers - they do however not hold state

**Comment by yasserf** [comment]
Hope that answered your question! Closing issue
