### ISSUE TITLE
Rooms creation in Node JS for a Multiplayer Games

### ISSUE THREAD

**Issue by pasha30** [deepstreamIO/deepstream.io#546]
Hi, We are making a game server for casino games over DeepStream, We are writing it in Node JS . I am using DeepStream List to make rooms with a minimum and maximum limit of the clients(List count). A room can only have maximum 5 clients. So if i would say that we have 10000 rooms available and then new user is come to connect then how can i check for free room or DS list which are free for new connection in a fast way basically i need to search that which list have free space or which list's count is less then 5. What is fastest way to do it

**Comment by WolframHempel** [comment]
It'd go via the database. Use one of the available connectors for e.g. RethinkDB, Mongo or PostGres. Lists are stored as documents with `{ entries: [ 'entry-a', 'entry-b' ] } etc, you can search for the entries array's length < 5 using PostGres JSON search or normal Mongo or Rethink
