### ISSUE TITLE
O(n^2) ops in subscription registry

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#552]
Looking at the implementation of `isLocalSubscriber` it looks like this is very inefficient and can make `subscribe` & `unsubscribe` performance killers when there are thousands of clients subscribing to thousands of records.

```js
  isLocalSubscriber(socketWrapper) {
    for (const name in this._subscriptions) {
      if (this._subscriptions[name].indexOf(socketWrapper) !== -1) {
        return true
      }
    }
    return false
  }
```

This is essentially, O(n^2)... samething with `unsubscribeAll`

I believe another map between socketWrapper and subscription names would be appropriate O(log(n))?

**Comment by ronag** [comment]
Making `_subscriptions[name]` a `Set` would at least move it down to O(nlog(n)) which is a bit better... though it should not be worse than O(log(n)).

**Comment by yasserf** [comment]
I agree, this is one of the biggest bottlenecks we currently have.

We are currently building a performance framework for a before and after comparison which we are planning on using prior to any performance improvements / releases and this is the first improvement we are looking to make.

**Comment by yasserf** [comment]
Thanks again for fixing this! =D
