### ISSUE TITLE
Game Lobby for Multiplayer game server 

### ISSUE THREAD

**Issue by pasha30** [deepstreamIO/deepstream.io#556]
How can i create a Common lobby for a multiplayer game over server, which can track of all connection and disconnection of clients , like if we have two or more different game server on the same host so how we will connect to the game server on which we want to connect. so i need to make a lobby for each game so that i can track user's connection or disconnection for the particular server and i can create lobby for each game server

**Comment by AlexBHarley** [comment]
Hi @pasha30, deepstream has a [presence API](https://deepstream.io/docs/client-js/presence/) which can notify you when clients login/logout. For game lobbies you might want to take a look at [records](https://deepstream.io/docs/client-js/datasync-record/) and [lists](https://deepstream.io/docs/client-js/datasync-list/).

You could use records to track clients connected to each room and other data, and a list to hold a reference to the rooms.

**Comment by pasha30** [comment]
Hi , I get to know that we can use List to make different rooms/lobby over server. I am new to server side development. I am bit confuse now. Like i need to make list(rooms) at server side. So which module I'll use to make server side code ? should i code using node js module of deepstream . Currently i have just connected to deepstream server and also concted rethinkdb and redis cache connector. So do i need to write a separate node module to do  server side coding  using node deepstream.io-client-js ? or do i need to implement a server over deepstream.io module?
