### ISSUE TITLE
Mongo DB and Rethink DB 

### ISSUE THREAD

**Issue by pasha30** [deepstreamIO/deepstream.io#557]
I need to use db connector and cache cache connector in our multiplayer game server. Which one is better for teen Patti kind of casino games  ? Which cache connector is more suitable for game servers

**Comment by ronag** [comment]
Use RethinkDB. I don't think Mongo has any significant advantages.

**Comment by minaxi30** [comment]
do we need any cache connector also with rethink DB as rethink is a real time db.

**Comment by ronag** [comment]
Yes, you should use a cache connector, Redis is probably simplest.
