### ISSUE TITLE
delayed broadcast tests?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#560]
I think the delayed broadcast stuff are missing tests?

**Comment by yasserf** [comment]
These are covered by E2E tests,  Tests will need to be added for #533 to ensure we can reproduce the issue which should increase the overall coverage.

Will leave this open as a low priority to get some unit tests at some point in the future, possibly as part of 2.3 milestone with subscription changes

**Comment by yasserf** [comment]
We removed the broadcast coalescing in v4 since it doesn't play nice at all with binary and almost all users have it disabled
