### ISSUE TITLE
is it necessary to put lists data for rooms into DB 

### ISSUE THREAD

**Issue by pasha30** [deepstreamIO/deepstream.io#561]
If we are making some rooms(deepstream List) over server , user comes and connects in the room and some time we delete that room or list if its not required. every room will have some rules . so do i need to put those list of room  and associated player as records in list over database (rethink db ) ? can we put them is in local memory ? what problems may occur if we put that room data in local memory ?

**Comment by rsdrsd** [comment]
How do you add a user to a room and how do you disconnect a user from a room if browser is closed for example?
