### ISSUE TITLE
Delayed broadcast can cause client to never receive message?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#562]
Assume that delayed broadcasts are enabled and a client sends:

```
<< READ
<< UNSUBSCRIBE
>> READ
```
In this case the client *might* never receive any `READ` reply since `UNSUBSCRIBE` removed the subscription before `onBroadcastTimeout`. This is not a bug per se but there might be better examples of similar edge cases that actually cause problems.

Is this a problem or am I missing something? @yasserf

**Comment by ronag** [comment]
I believe in `onBroadcastTimeout` we have to make a union of `sockets` and `delayedBroadcasts.uniqueSendersVector`?

**Comment by alexhultman** [comment]
If the client actively removed its subscription before it got any response I would say this is according to design. The client will have to wait until it receives what it wants before it changes its mind. There are tons of cases where the client might never receive anything anyways - the only guarantee the OS gives the application layers is that what you handed it has now been copied to the kernel - there is no such guarantee that the client has received anything. The client shouldn't depend on internal implementation details of the server -> if you want to read data then you better wait for it before you cancel it.

This is my opinion, but I'm not working on DS anymore so I'm not involved with this.

**Comment by ronag** [comment]
@alexhultman 

>> you handed it has now been copied to the kernel - there is no such guarantee that the client has received anything

This is interesting. Isn't there a guarantee that the client have received everything between successful PING/PONG?

**Comment by alexhultman** [comment]
I'm not working on this anymore. My opinion is that this is according to design. I don't have the DS protocol in my head right now.

**Comment by yasserf** [comment]
I believe this is connected to #533 where the server unsubscribed the user and never actually tells them.

As such this is a duplicate so will close in favor of #533
