### ISSUE TITLE
socketWrapper.uuid is not an uuid

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#563]
`socketWrapper.uuid` is not an uuid. I would suggest that:

- Rename it to `id`.
- Use a `this.id = (counter++ % SAFE_MAX_INT)` implementation to avoid unlucky collisions (I'm not sure how good `Math.random()` entropy is?) as well as making id's strictly increasing which can have some benefits in other parts of the code.

**Comment by yasserf** [comment]
socketWrapper.uuid has been removed since we no longer use the broadcast lists. Slightly slower now but it has quite a few timing issues. Once UWS implements sub/pub we can just natively use that.
