### ISSUE TITLE
Where's the C source code?

### ISSUE THREAD

**Issue by vangelov** [deepstreamIO/deepstream.io#564]
I was just wondering where can I find the C part of the server source? The documentation says it's a "combination of low level C for messaging and networking and Node logic" but it seems there are no .c or .cpp/.cc files in the project. I found this: https://github.com/deepstreamIO/libdeepstream, but it's empty. Thanks!

**Comment by ronag** [comment]
The "C" part that is referred is the C++ in https://github.com/uWebSockets/uWebSockets which is used as the web socket engine.

**Comment by vangelov** [comment]
Thanks for the quick answer!
