### ISSUE TITLE
 RethinkDB search provider

### ISSUE THREAD

**Issue by pasha30** [deepstreamIO/deepstream.io#565]
what is rethink search provider ? do we really need to use it in real time game server

**Comment by yasserf** [comment]
Hey @pasha30 

The rethinkdb search provider is used to be able to autogenerate lists with certain criterea

You are not forced to use it at all, but if you are using rethinkDB already its a very nice addition that plays nicely with deepstream.

Documentation bottom of page here:

https://deepstream.io/tutorials/integrations/db-rethinkdb/

**Comment by pasha30** [comment]
I am unable to connect serach provider with our server, I have tried but facing issues . currently I am  using this code snippet to start ds server. I am a bit confused how to connect search provider 



onst DeepstreamServer = require('deepstream.io')
// const DeepstreamClient = require( 'deepstream.io-client-js' );
const C = DeepstreamServer.constants
const RethinkDBStorageConnector = require( 'deepstream.io-storage-rethinkdb' )
const RedisCacheConnector = require( 'deepstream.io-cache-redis' );

(function(deepStreemServer){
  deepStreemServer.startServer = function(){
    const server = new DeepstreamServer({
      host: 'localhost',
      port: 6020
    })
    server.set( 'storage', new RethinkDBStorageConnector( {
      port: 28015,
      host: 'localhost'
      //splitChar: '/'
    }));
    server.set( 'cache', new RedisCacheConnector( {
      port: 6379,
      host: 'localhost'
    }));
    server.start()
  }
}(deepStreemServer))
module.exports = deepStreemServer;
