### ISSUE TITLE
RpcHandler.getAlternativeProvider can return invalid provider?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#566]
Since `getAlternativeProvider` uses a copy of subscribers (`local`) https://github.com/deepstreamIO/deepstream.io/blob/master/src/rpc/rpc-handler.js#L216, which is not updated when a provider is unsubscribed or closes, it can return an invalid/closed/unsubscribed provider?

@yasserf: bug?

**Comment by yasserf** [comment]
Yup, will label accordingly
