### ISSUE TITLE
Make actions part of the topic (smarter pub/sub)

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#568]
e.g. topic = `${C.TOPIC.RECORD}.${C.ACTION.UPDATE}`. This would give us more fine grained control, e.g. we could subscribe to changes to a specific record only:

```js
message.subscribe(`${C.TOPIC.RECORD}.${C.ACTION.UPDATE}.${recordName}`, ...)
```

where the current behaviour could be implemented as:

```js
message.subscribe(`${C.TOPIC.RECORD}*`, ...)
```

**Comment by ronag** [comment]
This could solve the #548 problem using:

```js
message.subscribe(`${C.TOPIC.RECORD}.${C.ACTION.UPDATE}.${recordName}`, (subject, [ version, data ]) => {
  const name = subject.match(/\.(.*)^/)[0]
})
```

```js
message.publish(`${C.TOPIC.RECORD}.${C.ACTION.UPDATE}.${recordName}`, [ version, data ])
```

**Comment by ronag** [comment]
Furthermore adding queues would be great :)

```js
message.subscribe(`${C.TOPIC.RECORD}.${C.ACTION.READ}.*`, { queue: C.ACTION.READ }, (topic, [ version, data ]) => {
  const name = subject.match(/\.(.*)^/)[0]
})
```

**Comment by ronag** [comment]
This is more of a nice to have. Low prio.

**Comment by yasserf** [comment]
I would recommend this be split in half as an issue, the first part 

> message.subscribe(`${C.TOPIC.RECORD}.${C.ACTION.UPDATE}.${recordName}`, ...)

is something we planned on doing already ( unfortunately not made very visible on our issues so far) so we can track for a near release

The second with queues belongs more to a much larger discussion further down the line
https://github.com/deepstreamIO/deepstream.io/issues/570

**Comment by yasserf** [comment]
Closing due to 3.0 cluster change
