### ISSUE TITLE
Are socket message callback guaranteed to always send a complete message?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#571]
e.g. if the socket closes while receiving data or the client decides to split a large message into smaller ones? Does web sockets buffer up the entire message before dispatching the `message` callback?

**Comment by yasserf** [comment]
As far as I am aware with the websocket protocol (from writing the C++ client) you need to recieve a FIN packet to indicate the message is complete, otherwise its considered corrupt and won't be processed.

**Comment by ronag** [comment]
Alright, so web socket messages are sent atomically.
