### ISSUE TITLE
Load balancer with backend logic server ?

### ISSUE THREAD

**Issue by hoangtrongphuc** [deepstreamIO/deepstream.io#576]
When I use 1 backend server, CPU usage is 80%. How can I scale backend server and deepstream ?

**Comment by yasserf** [comment]
Can you provide a bit more context on what a backend server is in this question? Thanks!

**Comment by hoangtrongphuc** [comment]
I have one game server real-time, each tick server update whole game state, check collision and update GameState record on deepstream. Deepstream push update to all client which tracking "GameState" record. Forward message work fine but my backend server (update logic and check collision) all usage 80-90 % CPU. How can I load balance my process to multi server (share GameState)

**Comment by meepeek** [comment]
I am also looking for cluster docs or example. As far as I read, this is my opinion:

1. Clustering Deepstream -- I think you can cluster deepstream server by connecting another deepstream instance to the same cache, message, store database. In #195, @WolframHempel mentioned about sharing message bus, which I assume it is the Redis server that handling the message. Also @ronag commented that all cluster node must share cache.

2. Clustering Game Server -- Not sure what's your setup look like. In the docs, there was a section about Node API on the server side https://deepstream.io/docs/server/node-api/. However, if you are using the API, deepstream server and game server should be in the same node. So I guess your game server was connect to deepstream as a javascript client with e.g. 'compute-unit' role and you have the problem where the server pick up all loads by itself.

If that the case, I think you can create a channel e.g. 'round-robin' which the compute node will watch the value to determine if it was their turn to compute. Once the node takes it's turn, it change the value to let the other node knows that its turn has come.

Haven't tested the idea, hope it is useful to you.
