### ISSUE TITLE
excessive rpc usage and connection reset

### ISSUE THREAD

**Issue by cpoyraz** [deepstreamIO/deepstream.io#579]
Hello,
My code constantly sends data using rpc and it reconnects if it is disconnected or receives no_rpc_provider error. After 24 hours, I noticed that an error below had occured and application is crashed.

What may cause of that?

error: Two connections heartbeats missed successively event: Two connections hea
rtbeats missed successively topic: C
Error: read ECONNRESET
    at exports._errnoException (util.js:1023:11)
    at TCP.onread (net.js:572:26)

**Comment by yasserf** [comment]
Seems the server stopped sending pings or the connection dropped. We have a fix that changed this from going into the error state and rather reconnecting, will be in next release

**Comment by yasserf** [comment]
This should have been fixed in the 2.1.2 js client. Be great if you can confirm. Thanks!

**Comment by DAmesberger** [comment]
I have a similar problem here:

Error: connectionError: Two connections heartbeats missed successively (C)
    at Client._$onError (/home/pi/node_modules/deepstream.io-client-js/src/client.js:198:9)
    at Connection._checkHeartBeat (/home/pi/node_modules/deepstream.io-client-js/src/message/connection.js:263:16)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)

Always happens after a couple of minutes max. I am using version 2.1.2

**Comment by cpoyraz** [comment]
It seems it is fixed , thanks Yasser

**Comment by yasserf** [comment]
Create, thanks @AlexBHarley and @cpoyraz for fixing and raising!

@DAmesberger just to double check, is there any chance you may have had the artifact cached?
