### ISSUE TITLE
[RFC] Command to sync cache to the database

### ISSUE THREAD

**Issue by PhillippOhlandt** [deepstreamIO/deepstream.io#580]
I think it would be cool to have a little utility command on the deepstream cli to sync the cache content to the DB. 

This is a little bit edge-case'ish but I can imagine that there are a few people starting their cluster with only a cache (e.g. redis in appendonly mode) who want to upgrade to a proper DB later on.

**Comment by yasserf** [comment]
I would argue this should be a non core command in deepstream / aka a seperate module. But its a neat feature otherwise

**Comment by PhillippOhlandt** [comment]
Yep, would work too. This would require a separate plugin type, right?

**Comment by yasserf** [comment]
sorry, I meant more of a different repo at a utility tool
