### ISSUE TITLE
Inconsistency in presence

### ISSUE THREAD

**Issue by AlexBHarley** [deepstreamIO/deepstream.io#582]
```
client.login({ username: 'Alex' }, success => {
    client.presence.getAll(usernames => {
        // 'Alex' will not be in usernames
    }
})
```

```
client.presence.subscribe((username, login) => {
    console.log(username)
})
client.login({ username: 'Alex' }, success => {
})
```

In the second code snippet, it will tell you that the user Alex logged in.

**Comment by yasserf** [comment]
Fix: Don't inform user of himself being online.

**Comment by yasserf** [comment]
This falls under the presence rework story

**Comment by AlexBHarley** [comment]
Looks like this isn't an issue anymore. Tested with deepstream v3.1, even on client reconnection the callback is not fired with the clients own username
