### ISSUE TITLE
State Connector

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#584]
I believe this has been discussed somewhere, but I'm just putting it here for reference. I would request a feature where we can replace the native deep stream cluster stuff (distributed state, locks etc...) with  a connector which wraps e.g. etcd or consul.

**Comment by ronag** [comment]
Work in progress API https://gist.github.com/ronag/383fbec9b79da35bce2f659b57050cdc

Which is needed for our listener rewrite at https://github.com/nxtedition/deepstream.io/blob/listener/src/listen/listener-registry.js

**Comment by ronag** [comment]
https://github.com/deepstreamIO/deepstream.io/pull/588

**Comment by yasserf** [comment]
Closing this due to 3.0 cluster change
