### ISSUE TITLE
Unable to connect android client 

### ISSUE THREAD

**Issue by pasha30** [deepstreamIO/deepstream.io#589]
Hi , I need urgent help , I am starting deepstream server from its node module . if i am connecting any cleint from node js then its connecting.but if i am connected any android client then its not connecting . can we connect to a websocket from android side ?

i am using following code to login into DS from android side 
 dsclient = new DeepstreamClient("ws://localhost:6020/deepstream");
//                  LoginResult result = dsclient.login(gson.toJsonTree("{\"username\":\"test\"}"));
                    LoginResult result = dsclient.login();
                    if (!result.loggedIn()) {
                        System.err.println("Provider Failed to login" + result.getErrorEvent());
                    }else{
                        System.out.println("Provider Login Success");

}

**Comment by yasserf** [comment]
Hey Pasha,

We are literally releasing a client right now and that should ideally fix it or give better error results

Thanks!
