### ISSUE TITLE
Possibility to invalidate cache/force reload from database

### ISSUE THREAD

**Issue by snc** [deepstreamIO/deepstream.io#590]
I would like to do atomic operations in the database, like incrementing integers. This is for example possible with rethink db. This increment would be triggered in a RPC call using a direct connection to the database. The problem is the caching layer, how to tell deepstream that it should reload the data from the database to update the cache?

**Comment by ronag** [comment]
I would suggest that you create a service which sends messages to deepstream through the message connector.

I think a version of the `UPDATE` message could be used which only contains the record name (and optimally version) which would force deepstream to delete it from the cache and if there are any active subscribers, read it from storage.

**Comment by ronag** [comment]
Though I'm unsure how this would behave together with the strict versioning of records that deepstream uses...

**Comment by yasserf** [comment]
This won't be possible due to how things are designed. Sorry =(
