### ISSUE TITLE
Multiple Subscribe/Discard bug

### ISSUE THREAD

**Issue by valentinvichnal** [deepstreamIO/deepstream.io#592]
Discarding and Subscribing to the same List throws these errors in the client:
```
DS error: lists/todos UNSOLICITED_MESSAGE
DS error: lists/todos MULTIPLE_SUBSCRIPTIONS
DS error: lists/todos ACK_TIMEOUT
DS error: lists/todos RESPONSE_TIMEOUT
```

**Comment by datasage** [comment]
I did run into a similar version of this bug. It would appear that not all subscriptions on a record are removed when the record is removed.

If you recreate the same record and resubscribe to it, you get a multiple_subscriptions error.

I'm attempting to track this down.

**Comment by ronag** [comment]
It's a know bug. There are some async issues with the current implementation.

**Comment by ronag** [comment]
Close in favor of https://github.com/deepstreamIO/deepstream.io-client-js/issues/204

**Comment by datasage** [comment]
I don't think its entirely related to the JS client.

My scenario involves two clients.

1. Client A connects to record.
2. Client B deletes record.
3. Client A everything seems to clean up correctly on client.

Later, without reconnecting client A.

1. Client B recreates record.
2. Client A resubscribes to record.

At this point we get the unsolicited read message and a multiple subscriptions error.

This would seem to indicate that the server kept the subscription for Client A even though the record was deleted.

**Comment by datasage** [comment]
Looking at the wire on "Client A".

I see the delete event being sent when the record is removed. When the record is recreated by Client B, but before i subscribe again with Client A. I'm getting a read update message as if I am still subscribed to the record.

**Comment by yasserf** [comment]
This is interesting. Seems like we should be able to replicate it using your steps in the E2E tests.

> Later, without reconnecting client A.

Does that mean without disconnecting and connecting the client? Do you do that with B?

**Comment by datasage** [comment]
Yeah, the client A stays connected. Client B does disconnect after deletion of the record. and the reconnects to create it again later.

I did dig through the code, nothing stands out for me as to why this is happening. But it does seem like the subscription persists somehow.

**Comment by yasserf** [comment]
Possibly (only for the duration of the client A connection). I'll try and replicate

**Comment by datasage** [comment]
Its possible the change in master fixed it, going to check out the master branch and give a test.

**Comment by datasage** [comment]
I think this change fixed the issue: https://github.com/deepstreamIO/deepstream.io/commit/4d58524df029533f87904dab447a3220bd837db9#diff-24cd6f59e2d8f7a7d05c57cbc5d5c710L424

**Comment by yasserf** [comment]
Sweet!

**Comment by yasserf** [comment]
@ronag Nice side effect! =D

**Comment by yasserf** [comment]
I'm going to re-purpose this thread if that's okay. I want to get a code freeze ( aka a branch which I will then release ). The release process is pretty painless but I usually run deepstream.io RC through our internal systems before releasing it. 

Be good to know which PRs should make the cut, given the weekend is over I won't be able to have much breathing space while I work on some of the deepstreamHub stuff.

#618 #621 #617 Seem pretty small

#610 Looks great and passes all the E2E, but will need a bit of UTs ( its dropped to 96% :O )

**Comment by datasage** [comment]
Getting a release out would be awesome. This subscription bug is somewhat blocking for me at the moment.

**Comment by datasage** [comment]
Well, this is still broken.

Delete events do not broadcast. The subscribers have been removed by the time the broadcast fires.

Might have something to do with the async nature of this, looking into it.

**Comment by datasage** [comment]
Setting broadcastTimeout to -1 does allow the events to be sent. 

I guess i can see two options to fix this:

1. Allow certain messages to override the delay and thus skip the timeout to broadcast right away.
2. Reference the subscribers within delayedBroadcasts instead of accessing them later.

Any preferences on which way to fix this?

**Comment by layanto** [comment]
I think this issue is still in 2.2.0.

I use component based app with each component handling the subscription and discarding of list/record. When a component is loaded, I subscribe to list (via rethinkdb search provider) and to all the records in the list. When a component is destroyed (such as when navigating to another component), I discard the list and all the records in the list. If I navigate to a component that also have the same list, I will get multiple UNSOLICITED_MESSAGE, MULTIPLE_SUBSCRIPTIONS and No ACK message received. I think this is because one component discard the list/records only for the next component to immediately re-subscribe to the list/records.

**Comment by datasage** [comment]
That might have something to do with how the search provider works? In which case it might be a separate issue from this one.

**Comment by valentinvichnal** [comment]
My issue was that my List's Id is based on the component's state, it first got a default Id from the props, 
but after the Id changed again it was difficult to understand how to subscribe again.
In the debug I saw my code called discardList and subscribeList many times, a few times in the wrong order.

I found a solution where I only discard when the Id is different then the one was before,
and subscribe in the callback of the setState, or else the subscribe function won't know about the new Id state.

It took me weeks to understand this, I hope this will help for somebody.
```js
// Life cycle
  componentDidMount() { this.subscribeList(); }
  componentWillUnmount() { this.discardList(); }
  componentWillReceiveProps(nextProps) {
    const { id } = this.state;

    if (id === nextProps.id ) { return; }

    this.discardList();

    this.setState({
      name: nextProps.id 
    }, () => {
      this.subscribeList();
    });
  }
```

**Comment by jshrt** [comment]
Possibly the same issue [#502](https://github.com/deepstreamIO/deepstream.io/issues/508) ?

**Comment by yasserf** [comment]
We will address this properly with the current client SDK improvements for version 4

**Comment by yasserf** [comment]
Closing as I believe this has been fixed with batch requests and buffer discard timeouts.
