### ISSUE TITLE
Better Write Acks

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#595]
I've been pushing this for quite a while and after further discussion with @yasserf I thought I'd sketch down a proposal.

Instead of making write acks an optional feature (due to performance implications). I would like it to be performant enough for an "always" on flow. Simplifying and avoiding "special" cases.

I think write acks can be done in a way that is negligible for performance. Instead of ack:ing every write it is enough if the server sends an ack indicating that all writes from a specific client has been processed.

Each client keeps a (client) global sequence number which is sent with and incremented for every write. When the server has processed all the writes in it's buffer it would simply send to each client a single ack (for multiple writes) containing the highest sequence number. That way the client can easily decide which writes have been processed and which are still pending. If they have been processed and no error have been received, the write succeeded.

e.g.

```
CLIENT 
<< UPDATE [name = 1, version = 1, data, sequence = 1]
<< UPDATE [name = 1, version = 2, data, sequence = 2]
<< UPDATE [name = 2, version = 1, data, sequence = 3]
<< UPDATE [name = 3, version = 1, data, sequence = 4]
>> ERROR [name = 2, version = 1, data, sequence = 3]
>> ACK [sequence = 3]
>> ACK [sequence = 4]
```

This would require https://github.com/deepstreamIO/deepstream.io/pull/554 in order to maintain message orderings for messages from a specific client.

**Comment by yasserf** [comment]
Write acks are now based on a correlationId + using a flag in protobuf. Closing this as I doubt it will be done.
