### ISSUE TITLE
How to access detail of client making RPC call in backend RPC provider?

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io#596]
Is it possible to access the detail of client (e.g. username, user id) making RPC call in backend RPC provider? This can be useful for audit/logging purpose to record who called the RPC and with what data.

**Comment by layanto** [comment]
While the client can put its user id as part of data, this data is from client - meaning can be manipulated.

**Comment by layanto** [comment]
Is it possible to access serverData of the client making the RPC call in the RPC provider callback?

**Comment by snc** [comment]
Sending the user id as part of the RPC data is the first step. The second step should be to validate that it was not manipulated via the permission system:

```yaml
rpc:
  "user*":
    request: "data.userId === user.id"
```

**Comment by layanto** [comment]
@snc Thanks for this. I will try this. But I still think this should not be the case. This solution requires the client to send its user id with valve permission checking that it has not been tampered with so rpc provider can access this information. user object is accessible in valve permission, why not make this user object also accessible in rpc provider callback? Change (data, response) => {} to (data, response, user) => {}.

**Comment by snc** [comment]
In previous versions of deepstream server this was possible with the help of `dataTransforms` but this feature was dropped in 2.0.

**Comment by mariotacke** [comment]
I agree with @layanto. What's the reasoning behind not providing user data in a context object? Most auth libraries do this by default.
