### ISSUE TITLE
Do you have a plan to simplify code use async/await + class as node v7.6.0 has supported it natively

### ISSUE THREAD

**Issue by SteveCruise** [deepstreamIO/deepstream.io#616]
I use pomelo (https://github.com/NetEase/pomelo) before. But they still use es5. I hate es5.

**Comment by AlexBHarley** [comment]
Hey @SteveCruise, there are a few places we use classes in the server, however we don't have plans to introduce promises.

In the client we've had a few different ideas such as:

- returning promises when no callback is given
- providing a wrapper module that "promisifies" the api

Interested to get the communities opinion on these.
