### ISSUE TITLE
Cleanup CONSTANTS

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#619]
There are a lot of unused constant currently lying around.

**Comment by AlexBHarley** [comment]
We may tackle this as part of a micro optimisation where we rename all from 

`C.ACTIONS.---` and `C.EVENT.---` 

to 

`C_ACTIONS_---` and `C_EVENT_---`

**Comment by Sheshtawy** [comment]
Hello, Do you guys want help taking care of this? is it just renaming all constants and removing the unused ones?

**Comment by phoenikx** [comment]
Hi
If this still hasn't been done, I can help in this. I am getting started with open source and this will serve as a great motivation. Please let me know.

**Comment by yasserf** [comment]
Hey! Thanks for reaching out. We actually switched to using typescript which gives us unused constant detection out of the box.

If there are any other issues that you might like to try out let me know, always happy to have contributors!
