### ISSUE TITLE
java client v2.0.5 setting path for a record where the path doesn't exist yet throws exception

### ISSUE THREAD

**Issue by honorcode** [deepstreamIO/deepstream.io#629]
Documented behavior is not being observed, instead NPE exception is thrown.

        Record dummyRec = ds.record.getRecord("events/DUMMY");
        Record dummyResultOfSetPath = dummyRec.set("a.b.c", jsonElemObjValueForABCNestedObj);

Exception in thread "main" java.lang.NullPointerException
	at io.deepstream.UtilJSONPath.setIterateThrough(UtilJSONPath.java:78)
	at io.deepstream.UtilJSONPath.set(UtilJSONPath.java:180)
	at io.deepstream.Record.set(Record.java:880)
	at io.deepstream.Record.set(Record.java:248)
	at com.ticketmaster.bedrock.rapidoid.iris.Tools.initDeepstream(Tools.java:243)
	at com.ticketmaster.bedrock.rapidoid.iris.Application.main(Application.java:32)

**Comment by honorcode** [comment]
Docs:

Paths

get(), set() and subscribe() can be used to get the entire record's data, but also support "paths". Paths let you access sub-parts of your record's data using JSON notation, e.g. pets[1].fur.color. **If a value for a path that doesn't exist yet is set, the path will be created on the fly.**

**Comment by honorcode** [comment]
Also, if the path does exist, then it appears the JsonElement value arg must a full wrapping object to the nested depth of the path, instead of just the path's value (e.g. a.b.c -> 5 ->EXCEPTION, must be {a: {b: {c: 5} } } ) - This is a major pain point for ease of use!

**Comment by AlexBHarley** [comment]
@honorcode thanks for this. I can take a look this week for you.

**Comment by AlexBHarley** [comment]
@honorcode, this should be fixed in 2.0.6. Could you try it out and let us know?

**Comment by honorcode** [comment]
You bet, thanks, I'll let you know.

**Comment by honorcode** [comment]
Confirmed! 
Awesome - that's a big win!
+1 @AlexBHarley 
Thanks for the quick reaction time!
