### ISSUE TITLE
Race condition in _checkClosed

### ISSUE THREAD

**Issue by Lalem001** [deepstreamIO/deepstream.io#63]
I have found a race condition in [_checkClosed](https://github.com/hoxton-one/deepstream.io/blob/master/src/message/connection-endpoint.js#L114) where the `close` event from the `_tcpEndpoint` fires before the callback for `_server.close`. The result is that `deepstream.io server` will never emit `close`.

This can easily be resolved with Promise.all, but I do not see the use of promises in this file.

The only other solution I can think of is to have the `_server.close` callback also call `_checkClosed`.

**Comment by WolframHempel** [comment]
Hi @Lalem001 ,

thanks for raising this. We've literally just released a new version of the server (0.7.1) which fixes #44 (release notes here). Would it be possible that this release already fixes the issue?

**Comment by Lalem001** [comment]
I am testing with 0.7.1. Perhaps I should have mentioned this in the original posts.

**Comment by WolframHempel** [comment]
Ah, cool, thanks for confirming. We'll look into it straight away.

**Comment by Lalem001** [comment]
Please also note #64 where the `_server.close` callback is not called in the first place.

**Comment by yasserf** [comment]
Perhaps this is an issue where the clients and tcp close before the server, and then engineio closed which means it doesn't actually do anything. Ran into that when writing tests for another issue, be good to see if this can still be duplicated after the next release.
