### ISSUE TITLE
Old uws versions removed from npm

### ISSUE THREAD

**Issue by SejH** [deepstreamIO/deepstream.io#630]
The old versions of uws has been removed from npm, including the version deepstream uses.
This makes it so we can't install deepstream from npm.
[Issue about it on the uws github.](https://github.com/uWebSockets/uWebSockets/issues/551)

**Comment by AlexBHarley** [comment]
Hi @SejH, this is now resolved in our latest release [here](https://github.com/deepstreamIO/deepstream.io/releases/tag/v2.1.6).

We haven't upgraded to 0.14, we've fixed on 0.12 for now and due to our build environment/production testing we'll be on this for a while.
