### ISSUE TITLE
UNSOLICITED_MESSAGE: RASworld exception

### ISSUE THREAD

**Issue by gaurav90jain** [deepstreamIO/deepstream.io#631]
Hi,
I am getting below exception while using deepstream please give me the cause of this exception:
                                    FATAL EXCEPTION: pool-1-thread-1
                                    Process: com.adcoretechnologies.lactefo, PID: 27125
                                    io.deepstream.DeepstreamException: UNSOLICITED_MESSAGE: RASworld

**Comment by AlexBHarley** [comment]
Hi @gaurav90jain, it looks like you might be getting this while using the java client. Do you have any steps to reproduce?

**Comment by AlexBHarley** [comment]
Doing some backlog clean up and we've released quite a few java versions since March. Happy to look into this if anyone is having this problem

**Comment by zebpaypeswani** [comment]
I am getting same problem not all the time but often.
