### ISSUE TITLE
Reducing size of query subscription names

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#634]
We've discussed this in person but I thought I'd make a proper proposal.

Consider the following case:

```
ds.record.getRecord(`search?${JSON.stringify(bigQuery)}`)
```

The subscription name in this case can become very large with negative impact on performance.

One way to resolve this is to replace the `{JSON}` part with a `{HASH(JSON))}` and send the `JSON` as a payload, somehow and on the receiving end, i.e. providers reverse it. It's possible already to implement this in user land, but it's not pretty.

**Comment by yasserf** [comment]
This is implemented in the new search provider by using an RPC that returns a hashed value to get the record with. Not as pretty as before but it works https://deepstream.io/guides/realtime-search/doing-a-realtime-search/
