### ISSUE TITLE
Change docker documentation to point towards deepstream.io-docker

### ISSUE THREAD

**Issue by honorcode** [deepstreamIO/deepstream.io#635]
Following install instructs from your site and your docker repo.
Nothing works as advertised.
What is the current status? 
When is an expected fix coming?

**Comment by honorcode** [comment]
Using up-to-date version of Docker-for-Mac.

**Comment by honorcode** [comment]
Does the Docker installation only support running the Node.js deepstream server?
Is the source and versioning different for the Node.js server vs the binaries?
The config.yml is diff than the current deepstream.io repo (binaries)?

**Comment by honorcode** [comment]
I suppose we could always roll our own from scratch from one of your linux installation instructions.
Do any devs already have such a dockerfile to share?

**Comment by honorcode** [comment]
docker build -t deepstream .
Sending build context to Docker daemon 12.29 kB
Step 1/9 : FROM mhart/alpine-node:4
4: Pulling from mhart/alpine-node
709515475419: Pull complete 
c5f6409719f7: Pull complete 
Digest: sha256:2359add0831042266c908348983ee784afe8c2c0f4054a17d14cff39a53f299e
Status: Downloaded newer image for mhart/alpine-node:4
 ---> 7fbe0ac58f25
Step 2/9 : RUN apk add --update build-base python
 ---> Running in 37bd7c8731c3
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/27) Installing binutils-libs (2.26-r0)
(2/27) Installing binutils (2.26-r0)
(3/27) Installing gmp (6.1.0-r0)
(4/27) Installing isl (0.14.1-r0)
(5/27) Installing libgomp (5.3.0-r0)
(6/27) Installing libatomic (5.3.0-r0)
(7/27) Installing pkgconf (0.9.12-r0)
(8/27) Installing pkgconfig (0.25-r1)
(9/27) Installing mpfr3 (3.1.2-r0)
(10/27) Installing mpc1 (1.0.3-r0)
(11/27) Installing gcc (5.3.0-r0)
(12/27) Installing make (4.1-r1)
(13/27) Installing musl-dev (1.1.14-r14)
(14/27) Installing libc-dev (0.7-r0)
(15/27) Installing fortify-headers (0.8-r0)
(16/27) Installing g++ (5.3.0-r0)
(17/27) Installing build-base (0.4-r1)
(18/27) Installing libbz2 (1.0.6-r5)
(19/27) Installing expat (2.2.0-r0)
(20/27) Installing libffi (3.2.1-r2)
(21/27) Installing gdbm (1.11-r1)
(22/27) Installing ncurses-terminfo-base (6.0-r7)
(23/27) Installing ncurses-terminfo (6.0-r7)
(24/27) Installing ncurses-libs (6.0-r7)
(25/27) Installing readline (6.3.008-r4)
(26/27) Installing sqlite-libs (3.13.0-r0)
(27/27) Installing python (2.7.12-r0)
Executing busybox-1.24.2-r13.trigger
OK: 203 MiB in 40 packages
 ---> 6a3046baac2b
Removing intermediate container 37bd7c8731c3
Step 3/9 : RUN mkdir -p /usr/local/deepstream/conf
 ---> Running in 3e2dc56489e3
 ---> f9c45106195a
Removing intermediate container 3e2dc56489e3
Step 4/9 : WORKDIR /usr/local/deepstream
 ---> 52cd00c70277
Removing intermediate container 9b00fc7e3ea3
Step 5/9 : RUN npm install deepstream.io deepstream.io-logger-winston deepstream.io-msg-redis deepstream.io-cache-redis deepstream.io-storage-rethinkdb --production
 ---> Running in 1158d5ac0f8e
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/deepstreamIO/uws-dependency.git /root/.npm/_git-remotes/https-github-com-deepstreamIO-uws-dependency-git-6512d8a2: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/deepstreamIO/uws-dependency.git /root/.npm/_git-remotes/https-github-com-deepstreamIO-uws-dependency-git-6512d8a2: undefined

> hiredis@0.5.0 install /usr/local/deepstream/node_modules/deepstream.io-cache-redis/node_modules/hiredis
> node-gyp rebuild

make: Entering directory '/usr/local/deepstream/node_modules/deepstream.io-cache-redis/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  AR(target) Release/obj.target/deps/hiredis-c.a
  COPY Release/hiredis-c.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
  SOLINK_MODULE(target) Release/obj.target/hiredis.node
  COPY Release/hiredis.node
make: Leaving directory '/usr/local/deepstream/node_modules/deepstream.io-cache-redis/node_modules/hiredis/build'

> hiredis@0.5.0 install /usr/local/deepstream/node_modules/deepstream.io-msg-redis/node_modules/hiredis
> node-gyp rebuild

make: Entering directory '/usr/local/deepstream/node_modules/deepstream.io-msg-redis/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  AR(target) Release/obj.target/deps/hiredis-c.a
  COPY Release/hiredis-c.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
  SOLINK_MODULE(target) Release/obj.target/hiredis.node
  COPY Release/hiredis.node
make: Leaving directory '/usr/local/deepstream/node_modules/deepstream.io-msg-redis/node_modules/hiredis/build'
npm ERR! Linux 4.9.13-moby
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "deepstream.io" "deepstream.io-logger-winston" "deepstream.io-msg-redis" "deepstream.io-cache-redis" "deepstream.io-storage-rethinkdb" "--production"
npm ERR! node v4.8.1
npm ERR! npm  v2.15.11
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/deepstream/npm-debug.log

**Comment by honorcode** [comment]
docker pull deepstreamio/deepstream.io
Using default tag: latest
latest: Pulling from deepstreamio/deepstream.io
45a2e645736c: Pull complete 
efa3d6a7202c: Pull complete 
dc92cea0405b: Pull complete 
0b2c7c990f85: Pull complete 
e56ff467adb4: Pull complete 
Digest: sha256:90b7825220bdebec3ada7adebe52b80e23648a150141b9c83dd00e0e23aeb091
Status: Downloaded newer image for deepstreamio/deepstream.io:latest

**Comment by yasserf** [comment]
You might want to try 

https://github.com/deepstreamIO/deepstream.io-docker

should update our docs accordingly!
