### ISSUE TITLE
Are all presence notifications global?

### ISSUE THREAD

**Issue by vincentwoo** [deepstreamIO/deepstream.io#636]
Ideally I'd like to only have a snapshot of presence for a given "room" that users connect to, representing a document those users are collaborating on at that given moment.

https://deepstream.io/docs/client-js/presence/ seems to suggest they are global.

**Comment by datasage** [comment]
As far as I am aware, they seem to be. You may be able to use listen on an event channel do do something similar but with a smaller scope.

**Comment by vincentwoo** [comment]
Hm, that doesn't seem terribly useful. The server needs to send the presence notices, since clients can't send their own. Listening on everyone's presence doesn't seem useful for most apps. Firebase solves this with the special `onDisconnect` flag.

**Comment by yasserf** [comment]
We are looking to extend the presence API so that we can pass in an array of users and in return be told whenever anything within that array changes.

We are also looking at something similar to disconnect functionality in a future release. 

If you would like to suggest your most ideal API for presence it will help when finalising the spec!

**Comment by vincentwoo** [comment]
I think tying presence to a document ref makes sense. Having to subscribe to each new user that joins the session creates a weird NxN problem where each client watches each other client. Ideally, you can just subscribes to "presence changes I care about".

**Comment by datasage** [comment]
I have limited use for presence on the user side unless it can be segmented by room or set. On server side, I don't really need segmentation. But this would be mostly to trigger code if a user is disconnected from the system. I haven't explored using presence yet, but i might in the future.
