### ISSUE TITLE
Vertical clustering

### ISSUE THREAD

**Issue by roblav96** [deepstreamIO/deepstream.io#638]
I notice that nowhere in the [cluster-messaging](https://deepstream.io/tutorials/core/cluster-messaging/) docs it mentions vertical clustering. I use pm2 to launch my apps with node.js cluster instances and I was wondering if it would be wise to spawn a deepstream server instance for each node.js cluster.

Great work on this entire project. I'm very excited to develop my new project with deepstream. Cheers =]

**Comment by yasserf** [comment]
Closing this as there isn't any way we can really get deepstream to scale verticialy due to stateful state registries
