### ISSUE TITLE
Sending big object via RPC

### ISSUE THREAD

**Issue by cpoyraz** [deepstreamIO/deepstream.io#645]
Hello,
when I try to send an object sized 2MB via RPC . I noticed rpc make function does not run callback method. What is your opinion about that? Is there any limit with object size?

Thanks

**Comment by AlexBHarley** [comment]
Hey @cpoyraz, we haven't had any serious issues sending payloads this size. We've seen performance drop off linearly with how big the payload is, however that's to be expected.

Are you still having trouble with this?
