### ISSUE TITLE
Running in production

### ISSUE THREAD

**Issue by sauliusgrigaitis** [deepstreamIO/deepstream.io#647]
What is the preferred way to run Deepstream.io server in production? Ubuntu packages don't come with Systemd scripts, so looks like standard way to run services maybe is not the preferred way.

I see there are Docker configs in [deepstream.io-docker](https://github.com/deepstreamIO/deepstream.io-docker). Is Docker preferred way to deploy Deepstream.io on production? Or users should simply create Deepstream.io scripts themselves?

**Comment by datasage** [comment]
I use supervisor to keep the processes up and running. This has worked well so far.

**Comment by yasserf** [comment]
We used pm2 internally, it works with both the binary and node versions.

A few other people use docker in production as well, either via ECS, DockerSwarm or Kubernetes.

**Comment by AlexBHarley** [comment]
Closing for a bit of issue clean up
