### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by datasage** [deepstreamIO/deepstream.io#648]
So I've been running this in production for the past couple of weeks. Using new relic server monitoring, I've seen memory usage increase day over day instead of dropping down during the night when our load is minimal.

It does drop a little bit at night (maybe some gc) but, its mostly flat.

So i got the chrome inspector working in my dev environment to look for places where objects do not get deallocated.

The first case i found is in connection-endpoint.js. Sockets get added to _authenticatedSockets, but never removed. Seems socket wrapper does have an event that can be used to remove sockets on close.

I will keep updating this ticket with more memory leak issues.

**Comment by datasage** [comment]
I have a fix for that one, https://github.com/deepstreamIO/deepstream.io/pull/649.

I haven't found any more, I need to set up an environment with a bit more data before getting a profile to see if there are any other objects hanging around.

**Comment by yasserf** [comment]
Hey, this is awesome, thank you for opening!

**Comment by datasage** [comment]
I just deployed the fix in my prod environment and memory usage is much more stable. I suspect that this may have caused some longer running gc pauses which may have contributed to cache_retreival_timeout errors.

The memory usage after less than a week of running was hitting over 1GB for each instance. This had to do largely with lots of short running connections from my application servers.

For the most part i think we are ok on the memory leak front. There was nothing else that was obvious in my data analysis. If i see the data usage grow again, I will do more digging. If not I will close this ticket in a few days.

**Comment by yasserf** [comment]
@datasage Thanks for the update. I'm hoping to setup some soak tests continuously as well on our servers and will release the charts/stats accordingly.

**Comment by datasage** [comment]
There may still be a small memory leak or something else going on. Ive seen memory appear to grow by a couple of MB over the day. The amount is rather small so it might be within the margin of error.

I am experiencing another problem, not entirely sure its memory leak related. Its possible that its connected.

After DS has been running for a few days, I will see an event that drops connections on both of my nodes as well as drops connection to the cluster message bus. 

After the clients reconnect, i see what looks like a cache stampede with thousands of errors related to cache_retreival_timeouts. 

Im not sure what has been causing this. It seems like it could be the load balancer, but that wouldn't account for the cluster leave/join messages. Maybe some kind of GC pause is being triggered? I've been trying different things to identify it, but no luck as of yet.

**Comment by hoangtrongphuc** [comment]
I'm testing deepstream with loadtest tool (websocket). After shutdown load test, deepstream dont release memory and use high CPU load.

**Comment by yasserf** [comment]
Interesting, can you provide any CPU stack traces?

**Comment by hoangtrongphuc** [comment]
I run loadtest in 60s, with 5000 connection each second. Each connection send text and close connection. But deepstream only process 500-600 CCU, with 600 CCU I see  ECONNREFUSED.
Some picture of test: 
[https://ibb.co/gsMoGQ](url)
[https://ibb.co/e66oGQ](url)
After I shutdown load test, deepstream use high CPU load and it can not release memory.
[https://ibb.co/gtRcAk](url)

**Comment by datasage** [comment]
Are you running the latest master copy? The latest release version does not have the memory leak fix that I added.

**Comment by hoangtrongphuc** [comment]
I 'm using deepstream 2.2.0 on Window. So I must get latest master copy from git ?

**Comment by yasserf** [comment]
Should be in the latest release now!

**Comment by AlexBHarley** [comment]
Is anyone still having problems with this?

**Comment by datasage** [comment]
I haven't seen anything show up on my metrics since the fix. I will reopen if I observe issues with this again.
