### ISSUE TITLE
How to configure data transforms for v>=2.0.0?

### ISSUE THREAD

**Issue by RashadSaleh** [deepstreamIO/deepstream.io#650]
Since v2.0.0, "direct" data transforms have been removed:

> You can no longer set custom data transforms directly on deepstream
(v2.0.0 release notes)

**My question is:** How can one then set custom data transforms "indirectly"? And, in general, why have data transforms been removed?

On a side note, I want to use data transforms to achieve "sub-record data permissioning" through filtering out private fields in a given record.

Thanks!

**Comment by yasserf** [comment]
Data transforms were removed because it was considered to go against deepstreams scaling concepts. It may be added in a different form going forward, but preferably via a plugin rather than the way we done it previously.
