### ISSUE TITLE
Record Set JsonPath with numeric parts that are not array indices returned different results on client vs server side

### ISSUE THREAD

**Issue by honorcode** [deepstreamIO/deepstream.io#651]
Using localhost (Mac osx) Deepstream.io 2.2.0, Java Client 2.0.8, no plugins

Upon setRecord(recId, "a.b.1", value) the end result of set shows the path created to be: 
{ "a": { "b": { "1": value } } }

Problem: data-sync/getRecord returns this record which does not match and will fail gson.toJson(elem):
{ "a": { "b": [ null, value ] } }

Example Test:
setRecord runtime breakpoint below ->

In UtilJsonPath.java :: setIterateThrough @ line 52
private static JsonElement setIterateThrough(JsonElement element, String path, JsonElement value, boolean delete)
... breakpoint at line 92:            updateValue(value, (JsonElement)parent, token, delete);
where runtime vars: 
    element = {"tickets":{"ticketTexts":{"1":{}}}}
    value = "BDD TESTING"
    token = "1"
    path = "tickets.ticketTexts.1"
    parent = "{"1":{}}"
    delete = false

BUT upon setRecord completing the data-sync'd record and / or subsequent getRecord returns this:
{"tickets":{"ticketTexts":[null,"BDD TESTING"]}}

**Comment by honorcode** [comment]
Btw, much of our data is deeply nested json objs with numerous objects members having numeric fieldnames. These are automated transforms in another ETL application, not possible to refactor easily.

**Comment by honorcode** [comment]
The numeric fieldnames also help significantly as the number of records scales due to memory usage for each fieldname's length for every obj. Smaller fieldnames = smaller objects = smaller data stores = less bandwidth.

**Comment by honorcode** [comment]
We also don't want the added padding of nulls in sparse arrays of slotted values.

**Comment by redlock** [comment]
this is probably related to the issue  #646 I have posted earlier. The fix is also posted. I hope they patch it soon

**Comment by honorcode** [comment]
@WolframHempel FYI the website link for the Contributor License Agreement is broken, I can't do a PR but below is my deepstream.io/master patch with my FIXes for the server-side issues #651 and #646.

**Comment by honorcode** [comment]
honorcode_deepstream_io_patch_fix_json_path_numeric_obj_member_support.diff (ok - .diff file type not supported so I guess I'll include my to .js files (json-path.js and json-pathSpec.js) as .txt files below.

**Comment by honorcode** [comment]
[json-path.txt](https://github.com/deepstreamIO/deepstream.io/files/931159/json-path.txt)
[json-pathSpec.txt](https://github.com/deepstreamIO/deepstream.io/files/931161/json-pathSpec.txt)

**Comment by honorcode** [comment]
@WolframHempel @yasserf @AlexBHarley
Opened related java-client issue found when testing:
https://github.com/deepstreamIO/deepstream.io-client-java/issues/84

**Comment by mrby** [comment]
![Screen Shot 2017-08-03 at 16.51.00.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588a1d5fc3985120000a471e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6454f06b7191a379e90c2e50415f4ebe5d4a1f06a3a3dc78e2a436628f5408bed26c5921c03c10ffec851fea01ba25d84a86e7bc9850d2aa6c7bb3d4d216744b470a83ed5f33aa984ec859f14ce34d54ad113765f43b.png)

**Comment by yasserf** [comment]
Closing in favour of https://github.com/deepstreamIO/deepstream.io/issues/1046
