### ISSUE TITLE
How to implement task queue with deepstream?

### ISSUE THREAD

**Issue by bnusunny** [deepstreamIO/deepstream.io#653]
We are using deepstream in production as our realtime message backbone for our telephony system. Very pleased with the overall performance. Thanks for the great work! 

We have a requirement to implement task queue to send jobs to a set of worker processes. I'm wondering if deepstream is a good fit. Maybe Lists can be used to do it?

**Comment by datasage** [comment]
You can't, at least not in the traditional way. In a traditional design, the queue system would ideally deliver the message to exactly one worker. The event system in deepstream is pub/sub style which means that all subscribers get the message.

You can sort of fake it, although not reliably, by making the producer decide which worker gets the message. This would be done by giving each worker its own event channel. If the worker failed before the events were handled, then the events would be lost.

There are a bunch of other awesome solutions (RabbitMQ, ZeroMQ, SNS, iron.io, gearman, etc.) for handling worker queues anyway which would be better than trying to make Deepstream handle it.

**Comment by bnusunny** [comment]
Thanks for the clarification. I will check out other options then. Just wanted to check if we can have one less dependencies.
