### ISSUE TITLE
Listen Snapshot

### ISSUE THREAD

**Issue by datasage** [deepstreamIO/deepstream.io#657]
Is there a reason why listen snapshot was removed? I searched through the existing issues and pull requests and didn't find much information about why. Was there an issue with how it worked with the cluster design?

I do have a use for it to see if a particular client is subscribed to a particular record or event.

**Comment by yasserf** [comment]
Listening changed significantly for 2.0, and the snapshot was never introduced into the client API or spec. The idea was to be able to provide a regex and get told of all the matching subscriptions as a one off request, but it clashed with active listening as a concept so we removed it while still a concept/in beta.

**Comment by datasage** [comment]
I do need some way to see if a particular authenticated client is still connected, which in using multiple nodes would require checking each node for active connections.

For my use case it could be against connections and not just listeners to a particular record, although listeners would be a much smaller set.

I guess from my standpoint, regex would not really matter, it would be either a query that would return true/false if the specified client was connected, or just return the list of all subscribers to a particular event or record.

Im fine with going ahead an implementing this. Do you have thoughts on how this should work?

**Comment by yasserf** [comment]
This was implemented via presence. Going forward you can also hook into the monitoring API in order to see what subscriptions are open.
