### ISSUE TITLE
deepstream.io client for Java

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#66]
Create a deepstream.io client for Java, that connects to deepstream via TCP and supports Authentication, Permissioning, Records, Events and RPCs.

**Great resources to get started:**
[Writing a deepstream client](http://deepstream.io/info/messagestructure/writing-a-client.html)
[Deepstream Messaging structure](http://deepstream.io/info/messagestructure/index.html)
[Detailed Cucumber Specs for Incoming and Outgoing messages (and associated behaviors)](http://deepstream.io/info/messagestructure/connectivity.html)
[Fully featured NodeJS Client as a reference](https://github.com/hoxton-one/deepstream.io-client-js)

**Comment by Vorror** [comment]
Actually trying my hand at the java imp. Have the first connecting.feature working, will head to loggining next after layouting out a lot of the ground work. It should be android compatible, but I'm not actively testing.

**Comment by WolframHempel** [comment]
Sounds amazing. Please don't hesitate to get in touch if we can help in any way.

**Comment by yasserf** [comment]
Times like this I wish github issues had a like button =P

**Comment by yasserf** [comment]
@Vorror Interested to know how this is going and if I can help in any way. Cheers!

**Comment by Vorror** [comment]
@yasserf I've been busy the past 10 days or so. And about to start the events/subscriptions. I've actually be wracking my brain around on how closely I should follow the javascript implementation(In regards to the public api). And I don't know what your thoughts on that are.

Once I implement a good deal of the event/subscriptions I plan to put the source on Github so progress can be tracked. Current goal is next week Monday.

**Comment by yasserf** [comment]
@Vorror Thanks for the update! Out of curiosity, what version of Java are you using/supporting? 

Regarding the api, it's generally good to have something that's similar for familiarity, but languages do model things differently enough for that not to make sense. Since the public API itself isn't huge it would be good to discuss the differences when you have time.

**Comment by Vorror** [comment]
Actually unfortunately I the project I planned to work on no longer rethink
so I most likely won't finish the deep stream lib :( sorry to let you know

**Comment by yasserf** [comment]
No worries, appretiate the quick feedback. Is there any chance you could show us what you currently got incasebee decide to add things to it?

**Comment by dxpelou** [comment]
I would like to take this is on! I noticed @yasserf already made a start to this. I would like to attempt to finish authentication, once i set up the test TCP server?

**Comment by yasserf** [comment]
@dxpelou Hey, awesome! Would love some collaboration on this. Feel free to message me on (slack)[https://deepstream-slack.herokuapp.com/] if you need any help ( and to avoid conflict given it's early days! )

**Comment by yasserf** [comment]
@dxpelou If you happen to have any time, were almost out with a release candidate and if u want to look at the API that would be awesome

**Comment by dxpelou** [comment]
Yeah sure I can do that

**Comment by yasserf** [comment]
Sweet! It's now also deployed so you can install it via maven or gradle if you want to try building something :D

**Comment by irfaan008** [comment]
@WolframHempel all links are expired now.
