### ISSUE TITLE
Enforce records exist as objects

### ISSUE THREAD

**Issue by AlexBHarley** [deepstreamIO/deepstream.io#661]
Currently there are no checks server side to ensure that records exist as objects, there is a check in the js client to ensure this.

Before adding these checks we should also discuss whether we want to allow records to exist as arrays as well - there are some use cases when this makes sense, instead of using lists.

**Comment by datasage** [comment]
Blindly using arrays should be discouraged due to possible merge issues. You can use objects in an array like way, but instead use a time ordered unique id for each record. This is less efficient but definitely more reliable.

**Comment by AlexBHarley** [comment]
Yep we had a discussion internally and agreed to keep using objects
