### ISSUE TITLE
subscription reg cluster add/remove

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#667]
I don't quite understand this:

https://github.com/deepstreamIO/deepstream.io/blob/3a4e5e7efabfc0b1ca2792326e993471bdc34f23/src/utils/subscription-registry.js#L303

https://github.com/deepstreamIO/deepstream.io/blob/3a4e5e7efabfc0b1ca2792326e993471bdc34f23/src/utils/subscription-registry.js#L334

Subscriptions are added to cluster everytime but only remove last time. Shouldn't it be one remove for each add?

**Comment by yasserf** [comment]
I didn't quite get it either, but turns out distributed state registry
guards adds for at most one and deletes immediately. Because of that the
state was invalid as we do some more thorough cache Layer debugging

**Comment by yasserf** [comment]
closing issue, let me know if that made sense to you!

**Comment by yasserf** [comment]
Reopening issue because 'facepalm' i just remembered that this was done outside of the if conditions because the plugin is meant to keep count of the amount of subscriptions. That is although it isn't in the distributed state registry it will be.
