### ISSUE TITLE
wishlist: deepstream.io features

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io#668]
Hello!

We want to create a central place to capture all of your feature requests for deepstream.io, which could both be things that are:

- external ( usually a seperate repo or something that doesn't touch the actual functionality or server
- internal ( things that touch the server or client sdks in terms of API or features )
- misc ( anything that doesn't fall under the first two! )

This will help us put together a much more visible roadmap which will be driven from the many companies currently in production, current issues and requests here!

Examples can be seen in below comments, or my personal favourite (which we might write a blog about ;) ):

=====

### Run against deepstream.io using an RF transmitter

**Type:** External

**Description:**
I really want to run clients on a [$1 Arduino chip](http://ebay.to/2k4C90F) that communicates using an RF transceiver

=====

*** Update ***

I will be adding issues to comments on the roadmap that have a card and will be worked on in the near future! Incase anyone gets an edit notification ;)

**Comment by PhillippOhlandt** [comment]
First: I vote for all the examples above! :D Plus:

---

### Golang client

**Type**: External

**Description**:
A golang client would help a lot with building strong microservices

**Comment by PhillippOhlandt** [comment]
### Make DS more fault tolerant

**Type:** internal

**Description:**
DS immediately crashes when it looses connection to a connector. I think it might be better to have some sort of timeout it tries to reconnect until it crashes.  In case the DB or cache has to restart or maybe some temporary network lags you would just reconnect instead of killing the whole connection for a lot of users.

**Comment by valentinvichnal** [comment]
### Make a MongoDB collection based DeepStream List Live using query string 

Type: internal

Description:
I would like to use a special List when the database is MongoDB, which:
- "Offline" by default with old items in it, the first subscriber gets this old data
(The default deepstream List)
- It has automatic listen: whenever the number of subscribed users > 0 it starts a setInterval
which runs the query againts the database or cache every (5-10sec) and update the state
- When every user unsubscribes it should clearInterval, and become offline again.

My recommended API would be similar what you already use in RethinkDB:
```js
var queryString = JSON.stringify({
  collection: 'post',
  query: [
   { vote: { $gt: 42 }
  ]
})
client.record.getList('post?' + queryString)
```

**Comment by valentinvichnal** [comment]
### Create pagination for List

**Type:** internal

**Description:**
I would recommend the pagination and length functions for Lists what was proposed by @WolframHempel and @yasserf 

Recommended API for Pagination:
```js
//get a moving window from 20 to 40
ds.record.getList( 'cars?start=20&length=20' );
```

Recommended API to get List Length:
```js
list.getLength( length => {});
list.on( 'lengthChanged', length => {}, true )
```

**Comment by hoangtrongphuc** [comment]
Unity .NET client

Type: External

Description:
A Unity client would help a lot with building netwoking in game

**Comment by yasserf** [comment]
### Official raspberry PI docker install

**Type:** External

**Description:**
Be great to be able to run deepstream.io on a RPI without needing to install node

**Comment by yasserf** [comment]
### RPC round robin

**Type:** Internal

**Description:**
I would to have RPCs or listening to be proxied in a round robin fashion instead of randomly

**Comment by yasserf** [comment]
### Presence API

**Type:** Internal

**Description:**
I would like to be able to subscribe to specific users presence instead of the global state of the system

My recommended API would be something like:

```
client.presence.subscribe(array<string>: userIds, (string: userId, boolean: isOnline) => {}, boolean: triggerImmediately)
```

**Comment by ScreamZ** [comment]
@yasserf For presence API, can be nice to send metadata (which can be any json object) on login. Which will be dispatched to presence API on user exit (network error, user leaving).

**Comment by alericmckearn** [comment]
**Agnostic Persistence Layer**

In order to make the product truly platform agnostic, it needs a way to move from one persistence layer to another.  So if I want to move from Rethinkdb to Postgres (or just a different instance of PostGres) I swap out the connector (new/legacy) and deepstream will move the data from one persistence layer to the other.

**Comment by yasserf** [comment]
Closing this issue as its hard to track issue going forward / given the dev winter on deepstream I think most people moved on =(. Thank you for the suggestions, hopefully some of them will come true!
