### ISSUE TITLE
Does deepstream.io provide any kind of rate limiting?

### ISSUE THREAD

**Issue by kksharma1618** [deepstreamIO/deepstream.io#670]
I am concerned about dos attacks against my deepstream.io servers. It's a public website, where user can register. Deepstream auth config allows only logged in user.

Can a malicious user register, and then connect to my deepstream server and launch million of events/records? How can I rate limit it per user/connection?
Can I also add limits on records? Size limits? Or number of records a user can create?

**Comment by kksharma1618** [comment]
I guess I can run deepstream as npm module in nodeapp. I can add datatransforms to calculate rates, then in permission handler I can reject if rates are surpassed.

**Comment by kksharma1618** [comment]
datatransforms is deprecated too :)
Hey @yasserf, any ideas how can I rate limit per connections/user? Any plugin hooks that will help. Can't find anything in docs.

**Comment by yasserf** [comment]
You can do that inside of the permission handler, by that time it has the message (including the record data) and the userId and you can easily contain a map of all users and increment their usages and reset them on a second based timeout.

Deepstream first point of defense is at the connection layer, which means if you have millions of sockets being created at one go your memory will grow massively too. Concepts like whitelisting and banning should usually done at a higher level such as your loadbalancer, as with any other public facing server

**Comment by kksharma1618** [comment]
Thanks. I will look into permissionhandler for rate limiting.
