### ISSUE TITLE
request: Build and push new docker image

### ISSUE THREAD

**Issue by ralphtheninja** [deepstreamIO/deepstream.io#671]
It would be nice if someone could update hub.docker.com with the latest release https://hub.docker.com/r/deepstreamio/deepstream.io/tags/

Cheers

**Comment by PhillippOhlandt** [comment]
See my comment in the linked issue.

**Comment by AlexBHarley** [comment]
Thanks @PhillippOhlandt. We'll be communicating releases better from now on
