### ISSUE TITLE
Added support for json validator for event, rpc, record

### ISSUE THREAD

**Issue by kksharma1618** [deepstreamIO/deepstream.io#673]
I wanted to restrict records, events, rpcs based on some schema, and created a plugin that allows you to do so.
https://github.com/kksharma1618/ds-plugin-validate (docs in the readme)

It's currently running on a fork of deepstream.io I created to code plugin support https://github.com/kksharma1618/deepstream.io/tree/pluginsupport (docs in the readme)
plugin loader code at: https://github.com/kksharma1618/deepstream.io/blob/pluginsupport/src/utils/pluginmanager.js
I updated deepstream _init function at https://github.com/kksharma1618/deepstream.io/blob/pluginsupport/src/deepstream.io.js to trigger some plugin events

@yasserf, would love your feedback on this. Is this something you want in deepstream.io itself? Plugin support? Or, json schema? 
I can probably put https://github.com/kksharma1618/ds-plugin-validate functionality directly into deepstream.io, without any kind of plugin support, if you are interested. 

I plan to use plugin support at https://github.com/kksharma1618/deepstream.io/tree/pluginsupport for a different rate limiter plugin that I am coding.

I have yet to write unit tests for https://github.com/kksharma1618/ds-plugin-validate 
Wasn't sure if you would want it in deepstream.io or will I have to use it as a plugin with my fork.

**Comment by AlexBHarley** [comment]
Hey @kksharma1618, thanks for this. Schema support is something that we have discussed internally but it's a bit further off in the roadmap.

At this stage we won't be able to take these changes into deepstream.io itself, the overhead of validating every message is quite high and will severely affect our hot path - something we've put quite a bit of work into lately.

In general though we are looking to extend the plugin ecosystem around deepstream and may set up a page with community and official plugins in the future.

**Comment by kksharma1618** [comment]
Thanks.  Plugin support will be really helpful.  For now we just created a small fork of deepstream with plugin support. We needed ratelimits and schemas.
