### ISSUE TITLE
Feature Request: isSubscribed method on clients

### ISSUE THREAD

**Issue by AlexBHarley** [deepstreamIO/deepstream.io#675]
Would be nice to provide an `isSubscribed` method on our clients for local subscriptions. This has been asked for by a few members of our community.

- `client.event.isSubscribed(subscriptionName)` 
- `client.record.isSubscribed(path)`
- `client.record.isSubscribed()` ? subscribed to any path?

Would be good if people could provide us some use cases for this method before we go about adding it.

**Comment by yasserf** [comment]
Still not certain what use cases this has to be honest. Which community member asked for it?

**Comment by yasserf** [comment]
This will be resolved via a monitoring API
