### ISSUE TITLE
Listening for provider reject

### ISSUE THREAD

**Issue by ScreamZ** [deepstreamIO/deepstream.io#676]
Hi,

any way to handle the case where no provider was able to handle a rpc request (server side) in order to dispatch some logs / alerts ?

Thanks

**Comment by yasserf** [comment]
The easiest way I can think of currently is if your logger catches the NO_RPC_PROVIDER log and does something, we already log it currently. Does that make sense?

**Comment by ScreamZ** [comment]
Yep all right,

I'm working on a wrapper library for deepstream applications (kind of framework) and I would like to implement a functionality that check current system charge (in term of CPU usage and RAM) and answer by reject or accept depending of the system load. Kind of custom load-balancer.

The thing is : if all my nodes are overloaded, client wont receive responses in that case I wanted to dispatch some alert to the sysadmin :)

I'll go that way then, should be a very very rare case.

Thanks again,
best regards

**Comment by AlexBHarley** [comment]
Thanks @ScreamZ, let us know how you get on.

**Comment by ScreamZ** [comment]
@AlexBHarley @yasserf,

made a first release, if you wants to check it out.

Won't say it's production ready while I've not finished implementing unit tests, but you can try to poke with it.

Best regards
