### ISSUE TITLE
Anonymous connections & authenticated connections

### ISSUE THREAD

**Issue by ScreamZ** [deepstreamIO/deepstream.io#678]
Hi (it's me again...),

The documentation seems to be not explicit on this (maybe am I wrong ?), I would like to implement an unauthenticated mode for some RPC.

Imagine I have a trading platform and I want people to receive real time update of the actions rates.
For that people are using deepstream with .login(null) and I use permission accordingly.

Now the guy register, he can buy actions using a special RPC. He login using .login({username .... and I can check him using permissions

How can i achieve that, seems like deepstreamhub allows it ?
Am I forced to create a "anonymous" user manually and log multiple user on it ? Or there is a another way ?

Thanks,
best regards

**Comment by AlexBHarley** [comment]
Hey @ScreamZ. 

In deepstream.io, when an unauthenticated user logs in `client.login(null)`, their user ID in Valve will be `open`.

You may be able to do something like the following in your valve rules

```
rpc:
  buy-item:
    make: "user.id !=='open'"
```

For your use case it may also make sense to have some additional client data for your permissioning that you set when users register.
