### ISSUE TITLE
UNKNOWN_TOPIC A

### ISSUE THREAD

**Issue by pgoergler** [deepstreamIO/deepstream.io#685]
Hello,

I'm trying deepstream, so i started with docker (v2.2.2):
```
docker run --rm -it --name deepstream -p 6020:6020 --network network_118 -v $(pwd)/data:/data deepstreamio/deepstream.io:latest
```

I install deepstream npm package: ("deepstream.io-client-js": "^2.1.5",)
```
npm install --save deepstream.io-client-js
``` 

I do:
```
import deepstream from 'deepstream.io-client-js';
let client = deepstream('localhost:6020');
client.on('error', function( error, event, topic ){
            console.log(error);
            console.log(topic);
            console.error(event);
          });
client.on('connectionStateChanged', function(state){
              console.log("deepstream state", state);
              if( state == "AWAITING_AUTHENTICATION") {
                console.log("deepstream login");
                client.login({username: "test"});
              } else if( state == "OPEN" ) {
                  console.log("deepstream open");
              }
          });
```

In my chrome dev i can see an error "UNKNOWN_TOPIC A"
Here a copy/paste of chromedev tools
```
09:21:02.806 dashboard.tag.html?e17e:20 A
09:21:02.806 dashboard.tag.html?e17e:21 X
09:21:02.806 dashboard.tag.html?e17e:22 UNKNOWN_TOPIC
(anonymous) @ dashboard.tag.html?e17e:22
Emitter.emit @ index.js?9678:145
Client._$onError @ client.js?e3ae:193
Client._onErrorMessage @ client.js?e3ae:218
Client._$onMessage @ client.js?e3ae:147
Connection._onMessage @ connection.js?142c:362
09:21:02.807 dashboard.tag.html?e17e:20 (2) ["UNKNOWN_TOPIC", "A"]
```
Why do i have this error ?

**Comment by yasserf** [comment]
Can you please paste the frames from the websocket connection? This seems
very odd. Thanks!

**Comment by pgoergler** [comment]
How can i get them ?

**Comment by yasserf** [comment]
https://kaazing.com/inspecting-websocket-traffic-with-chrome-developer-tools/

**Comment by pgoergler** [comment]
Here the copy/paste
```
CCH	5	10:11:22.102
CCHRws://localhost:6020/deepstream	37	10:11:22.106
CA	4	10:11:22.118
AREQ{"username":"paul"}	36	10:11:22.127
AREQ{"username":"paul"}	36	10:11:22.128
AA	4	10:11:22.160
RCRasterisk	14	10:11:22.163
XEUNKNOWN_TOPICA	20	10:11:22.164
```

**Comment by yasserf** [comment]
Looks like you are calling .login twice

The second time it is called your connection may already be authenticated
and hence your receiving unknown action

**Comment by yasserf** [comment]
We could probably improve that log 😁

**Comment by pgoergler** [comment]
This is weird, because as you can see id do :
```
client.on('connectionStateChanged', function(state){
              console.log("deepstream state", state);
              if( state == "AWAITING_AUTHENTICATION") {
                console.log("deepstream login");
                client.login({username: "paul"});
              } else if( state == "OPEN" ) {
                  console.log("deepstream open");
              }
          });
```
So the login request is only done after ```console.log("deepstream login");```, but in the javascript console the log appear only once

**Comment by pgoergler** [comment]
Here the console log:
```
deepstream state AWAITING_CONNECTION
10:11:22.104 dashboard.tag.html?e17e:54 deepstream state CHALLENGING
10:11:22.118 dashboard.tag.html?e17e:54 deepstream state AWAITING_AUTHENTICATION
10:11:22.119 dashboard.tag.html?e17e:56 deepstream login
10:11:22.120 dashboard.tag.html?e17e:54 deepstream state AUTHENTICATING
10:11:22.127 dashboard.tag.html?e17e:54 deepstream state AUTHENTICATING
10:11:22.160 dashboard.tag.html?e17e:54 deepstream state OPEN
10:11:22.161 dashboard.tag.html?e17e:59 deepstream open
10:11:22.169 dashboard.tag.html?e17e:51 (2) ["UNKNOWN_TOPIC", "A"]
```
Only one ```deepstream login``` appear but 2 ```AUTHENTICATING```

**Comment by pgoergler** [comment]
I have also override "client logging" with:
```
let fn = tag.client.login;
          client.login = function() {
            console.error("deepstream login request");
            return fn.apply(this, arguments);
          };
```
And there is only one "deepstream login request" in the console log.

**Comment by yasserf** [comment]
I need to see the code, this is most likely a weird use of the API, which
is a bug in itself for allowing the state.

Would that be possible?

**Comment by pgoergler** [comment]
ok i'll prepare a clean project

**Comment by pgoergler** [comment]
Here the project which use webpack:

**Comment by yasserf** [comment]
thanks! Will get back to you soon

**Comment by honorcode** [comment]
@yasserf I've seen this while testing 2.3.4 when I start up a second DS server (mac osx) I see the below console msgs on the second server (uuid -> *02* below) console when I attempt to use a DS java client to setData through first server (uuid -> *01* below):

CLUSTER_JOIN | RVD-02-DEBUG-deepstream-redis-localhost
INFO | Listening for websocket connections on 0.0.0.0:6021/deepstream
INFO | Listening for health checks on path /health-check 
INFO | connectionEndpoint ready: WebSocket Connection Endpoint
INFO | Deepstream started
CLUSTER_JOIN | RVD-01-DEBUG-deepstream-redis-localhost
**UNKNOWN_ACTION | A**

The UNKNOWN_ACTION does NOT show up on the console of the first server node (uuid -> *01*)

**Comment by pgoergler** [comment]
After some investigation, the ** UNKNOWN_TOPIC** appear when i do login() in the 
```
client.on('connectionStateChanged', function(state){
}```

i did it here, because i though we should wait the "AWAITING_AUTHENTICATION".

**Comment by yasserf** [comment]
Hey,

Apologies for the delay, we got a spit swept away with the 2.3.

Your last comment helps with understanding the issue more!

Generally you can login from anywhere, the states are maintained by the
SDK. It appears the server needs to return a better error message since
your still in the connection state when you send that message possibly.

**Comment by jshrt** [comment]
@pgoergler Your code does reproduce the error, but it has to do solely with your code.

If you call login from within the `connectionStateChanged` it happens to be trigger twice.

Checkout out this repo where I've reproduced your bug with your code and I have a normal version too:
https://github.com/deepstreamIO/bugs-reproduction/tree/685/685

@yasserf It turns out that if you happen to call `client.login` from within the `connectionStateChanged` event listener, it sort of gets trigger twice, I've checked that and it calls `_sendAuthArguments` twice and same goes with submitting to the endpoint so...

**Comment by MuriloFrade** [comment]
We will fix this by adding an 'ALREADY_AUTHENTICATED' error rather than an unknown topic. 

We'll also fix this in the client to avoid getting into that state

**Comment by yasserf** [comment]
Can you link this to the PR you made?
