### ISSUE TITLE
After getRecord(...) then record.discard(), with no record subscriptions, I receive UNSUBSCRIBE error msgs

### ISSUE THREAD

**Issue by honorcode** [deepstreamIO/deepstream.io#690]
RuntimeErrorHandler: onException: 
"R ACK_TIMEOUT No ACK message received in time for UNSUBSCRIBE"

java-client 2.1.0, server 2.2.2, redis cache plugin, all running local on mac

**Comment by yasserf** [comment]
Is this against master or against 2.2.2?

**Comment by honorcode** [comment]
I think that was master I built, so I'm guessing a WIP, I'll just wait for your release this week to rebuild and verify.

**Comment by yasserf** [comment]
releases all been silently released yesterday, blog posts and such following shortly 😁

**Comment by yasserf** [comment]
Is this still an issue? @honorcode

**Comment by honorcode** [comment]
@yasserf, Not seeing this at this time, looks resolved >= 2.3.4.

**Comment by yasserf** [comment]
Closing unless replicated post 2.3.4
