### ISSUE TITLE
Storage Timeouts

### ISSUE THREAD

**Issue by datasage** [deepstreamIO/deepstream.io#694]
So, this is an issue thats difficult to reproduce. it seems to occur in the server after its been running for some time, usually several hours ( or days).

We use mongo as the storage connector and Redis for cache and messages. 

Its hard to explain what exactly is happening, its like the server gets into a broken state. The logs will show all storage requests failing with timeouts. Hundreds to thousands of them. Sometimes there is indications of connection drops, but not always. 

Usually the server no longer handles records correctly until I restart it.

I had been restarting the instances daily overnight to avoid this issue, but today it happened after running for about 11-12 hours.

The logs don't provide enough information to know if this is an issue with the connection to mongo, or some bug happening internally. There is no memory leak as far as I can tell, or increase in traffic. 

Its possible the record request refactor might resolve this. I will look at updating things on staging before production. But has any seen an issue like this?

**Comment by datasage** [comment]
I dug up some more info.

It seems as if something is causing a bunch of extra cache and storage requests. Looking at metrics on the redis at about the time this failure happened, there was a huge increase in get commands and cache misses.

All these requests likely cascaded into the storage layer and caused the failure.

I am going to look more into the particular records that were showing errors and if they should have been in deepstream at the time of the error. These records may have possibly been deleted already which would explain the cache stampede. If that is the case, something is causing record names to be cached within deepstream?

**Comment by datasage** [comment]
The storage timeouts do seem to be based on records that were deleted several hours prior. There is definitely some odd behavior that is causing deleted records to be required.

**Comment by yasserf** [comment]
Interesting! I was looking for a reason to improve record deletion, hoping this is it. We'll take a look. Thanks for the insight, helps a lot!

**Comment by datasage** [comment]
We are using this in conjunction with the javascript client. The behavior does not seem consistent with issue though. The javascript client only ever subscribes to a subset of the data for a given a customer. The cache stampede seemed to involve records across all customers.

**Comment by AlexBHarley** [comment]
@datasage we'd quite like to look into this one. Is there any steps you could provide to reproduce?

We're thinking of running a script for ~24 hours that imitates your scenario, ie. clients connecting, subscribing to records, deleting records etc.

Is there anything specific or of note that you're doing that we could use to help write this?

**Comment by datasage** [comment]
It doesn't always happen within 24 hours, sometimes takes several days. But that might provide info as to where record names might be getting cached. I'm not using 2.3.0 yet, currently just 2.2.2. The issue has happened on some earlier versions too which is why i restart nodes each day.

In production running two nodes with a load balancer balancing connections between both instances. Redis is used for messaging and cache, Mongo Storage.

Data is organized by customer, using customerName/ in all record keys. Permission is used to limit what customers can read by the record prefix. It matches a key in the user data.

Most data updates are done by the server, often using upsert. Records are used for a limited amount of time, then the record is removed. We usually have around 400-500 clients during the peak period during the day.

Most records are referenced with list records. These list records always exist and are never deleted. The javascript client does subscribe to most active records for a given client. Once a record is removed, its removed from the list first, then the actual record is removed.

We also use events but most of those channels only have 1-2 subscribers. Server mostly publishes events.

**Comment by datasage** [comment]
Thinking about this a bit more, the client could actually be involved. We do run a status board component which customers use to monitor agents and calls. They are usually on this page for up to 24 hours.

If something caused a number of connections to drop at once, and the clients reconnected to the other node, its possible this could have caused the stampede.

I will look at some logs to see if I can correlate other events to this.

**Comment by datasage** [comment]
It does appear that for some reason I am keeping records bound on the client side, I need to do more digging into this to figure out if its an issue with the deepstream client or with my code.

This could definitely explain the stampede of requests if the client gets disconnected. Over several hours, some clients may end up binding thousands of records. If the records are getting a released correctly, there should only be 100-200 at most for a given client.

**Comment by yasserf** [comment]
Yup, thats a relief / makes sense! deepstream doesn't hold any references to records other than when a transition is in progress, meaning this would have been a substantial issue somewhere!

Thanks for keeping us updated!

**Comment by datasage** [comment]
Do messages get removed from the client if a delete event is passed? I'm not seeing a path through which that should get handled. It seems like the records stay in the client indefinitely.

**Comment by datasage** [comment]
Doing some tracing, i am seeing some records go through _removeRecord, but not all of them. All records should have delete triggered on it so I am not sure yet why some records are being removed and others are not.

**Comment by datasage** [comment]
I have tested in a very limited volume case, and everything works correctly. So it seems this issue has some sort of volume component to it.

I did some heap checking on the client and I did see my subscribed records grow to over 1000 after a couple of hours.

**Comment by yasserf** [comment]
> Do records get removed from the client if a delete event is passed? I'm not seeing a path through which that should get handled. It seems like the records stay in the client indefinitely.

Should be yes, we will need to replicate this, probably by doing bulk deletes and making sure things don't go wierd in edge cases

**Comment by datasage** [comment]
There might be some edge case going on, with enough volume. My very limited narrow test case seemed fine, but looking at a client with around 125 record subscriptions, the number just grows over time.

We are mostly relying on delete events to remove the records. But im checking to see if there are scenarios where something else is happening.

**Comment by datasage** [comment]
Are delete events property broadcast through all nodes?

**Comment by datasage** [comment]
I think that might be the bug, it appears that a delete event is not being passed into the message connector like updates are.

This is being called on update, but not on delete.

if (originalSender !== C.SOURCE_MESSAGE_CONNECTOR) {
    this._options.messageConnector.publish(C.TOPIC.RECORD, message)
  }

**Comment by yasserf** [comment]
I think your right. We will be looking to fix this ASAP.

Thanks alot for pointing this out.

**Comment by datasage** [comment]
It looks like the issue is fixed, closing this.
