### ISSUE TITLE
INCOMING_CONNECTION from undefined (undefined) with deepstream 2.3.0

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io#697]
With deepstream server 2.3.0 and deepstream client js 2.2.0, I am seeing INCOMING_CONNECTION from undefined (undefined) in deepstream server. And in my http auth backend, I no longer get connectionData. Is this a regression?

**Comment by yasserf** [comment]
Hey! Interesting, we'll look into this immediately.

**Comment by layanto** [comment]
With deepstream server 2.2.2, I get INCOMING_CONNECTION from undefined (127.0.0.1).

**Comment by yasserf** [comment]
We are looking into it now and will have a release out with a few tiny fixes by mid/end of day. Thanks for raising!

**Comment by yasserf** [comment]
@mrby what is the status of this being released?

**Comment by AlexBHarley** [comment]
This has landed in 2.3.2
