### ISSUE TITLE
Record deletion fails accross clustered nodes

### ISSUE THREAD

**Issue by jdmnd** [deepstreamIO/deepstream.io#703]
A failing e2e test has been added to the branch `cluster-record-deletion`: 
https://github.com/deepstreamIO/deepstream.io-e2e/blob/cluster-record-deletion/records/record.feature#L66

What should happen: 

 - the record deletion is distributed to all clustered nodes

What does happen:

 - the record deletion is only distributed to local clients
 - `UNKNOWN_ACTION | A` is logged by clustered deepstreams

**Comment by jdmnd** [comment]
The cause for this issue is that record deletions ACKs are sent over the message bus, but the record handler does not support record deletion ACKs. Furthermore, the record `_delete` handler has a guard suggesting that it expects record deletion messages from the message bus. 
So my expectation was that the standard behaviour would be to forward a record deletion to all servers/clients with the record. However it appears the JS client does not support record deletions from the server, only record deletion ACKs. 

Possible fixes:
- forward a record delete to the message bus, and add message delete handling to the javascript client
- continue sending a record ack to the message bus, and add a handler to the deepstream record handler to forward the ack to subscribers
- forward a record delete to the message bus, and modify the record handler to transform it into an ack before sending to subscribers

Interested to hear thoughts @yasserf @AlexBHarley

**Comment by datasage** [comment]
This is the root issue referenced in this ticket: https://github.com/deepstreamIO/deepstream.io/issues/694.

If there is anything I can do to help resolve this please let me know.

**Comment by jdmnd** [comment]
Ah that's interesting. I hadn't seen the most recent updates on that issue. The second fix described above should be the quickest win but I'll be afk until Tuesday morning. If you want to try fixing it before then I'd be happy to review a pull request over the weekend. 
The e2e feature linked above should be enough to confirm correct behaviour, although more features wouldn't hurt. 
Either way, you should expect to see a patched release out some time next week.

**Comment by datasage** [comment]
It does look like this might be a bit of a memory leak, since it keeps the subscribers to a deleted record, memory usage will grow over time. Although much slower than the previous memory leak I fixed.
