### ISSUE TITLE
storageHotPathPatterns splits an object by character

### ISSUE THREAD

**Issue by alericmckearn** [deepstreamIO/deepstream.io#708]
AWS: Redis(elasticache), Kafka, Postgres(rds)

Setup:
storageHotPathPatterns:
  - metrics7/

recordname1 = 'metrics6/messageFOO/' + ds.getUid()
recordname2 = 'metrics7/messageFOO/' + ds.getUid()

recordvalue (both) = {"t": "yo", "id": 0, "consumer": "None", "producer": "LoadTest", "createTimeStamp": "2017-06-02 12:06:59.385", "consumerTimeStamp": "2017-06-02 12:06:59.390"}

Result metrics6:
table metrics6
messageFOO/j3g819dl-fnpez01m099	{"_d": {"t": "yo", "id": 0, "consumer": "None", "producer": "LoadTest", "createTimeStamp": "2017-06-02 12:06:59.385", "consumerTimeStamp": "2017-06-02 12:06:59.390"}, "_v": 1}

Result metrics7:
table metrics7
messageFOO/j3g84p6u-18bepepatafi	{"0": "{", "1": "\"", "2": "i", "3": "d", "4": "\"", "5": ":", "6": "0", "7": ",", "8": "\"", "9": "c", "10": "r", "11": "e", "12": "a", "13": "t", "14": "e", "15": "T", "16": "i", "17": "m", "18": "e", "19": "S", "20": "t", "21": "a", "22": "m", "23": "p", "24": "\"", "25": ":", "26": "\"", "27": "2", "28": "0", "29": "1", "30": "7", "31": "-", "32": "0", "33": "6", "34": "-", "35": "0", "36": "2", "37": " ", "38": "1", "39": "2", "40": ":", "41": "0", "42": "9", "43": ":", "44": "3", "45": "9", "46": ".", "47": "8", "48": "4", "49": "7", "50": "\"", "51": ",", "52": "\"", "53": "c", "54": "o", "55": "n", "56": "s", "57": "u", "58": "m", "59": "e", "60": "r", "61": "\"", "62": ":", "63": "\"", "64": "N", "65": "o", "66": "n", "67": "e", "68": "\"", "69": ",", "70": "\"", "71": "c", "72": "o", "73": "n", "74": "s", "75": "u", "76": "m", "77": "e", "78": "r", "79": "T", "80": "i", "81": "m", "82": "e", "83": "S", "84": "t", "85": "a", "86": "m", "87": "p", "88": "\"", "89": ":", "90": "\"", "91": "2", "92": "0", "93": "1", "94": "7", "95": "-", "96": "0", "97": "6", "98": "-", "99": "0", "100": "2", "101": " ", "102": "1", "103": "2", "104": ":", "105": "0", "106": "9", "107": ":", "108": "3", "109": "9", "110": ".", "111": "8", "112": "5", "113": "2", "114": "\"", "115": ",", "116": "\"", "117": "t", "118": "\"", "119": ":", "120": "\"", "121": "y", "122": "o", "123": "\"", "124": ",", "125": "\"", "126": "p", "127": "r", "128": "o", "129": "d", "130": "u", "131": "c", "132": "e", "133": "r", "134": "\"", "135": ":", "136": "\"", "137": "L", "138": "o", "139": "a", "140": "d", "141": "T", "142": "e", "143": "s", "144": "t", "145": "\"", "146": "}", "__ds": {"_v": 0}}

**Comment by yasserf** [comment]
Fixed in 2.3.4
