### ISSUE TITLE
UNKNOWN_ACTION | A

### ISSUE THREAD

**Issue by honorcode** [deepstreamIO/deepstream.io#709]
commented same below in #685 

@yasserf I've seen this while testing 2.3.4 when I start up a second DS server (mac osx) I see the below console msgs on the second server (uuid -> 02 below) console when I attempt to use a DS java client to setData through first server (uuid -> 01 below):

CLUSTER_JOIN | RVD-02-DEBUG-deepstream-redis-localhost
INFO | Listening for websocket connections on 0.0.0.0:6021/deepstream
INFO | Listening for health checks on path /health-check
INFO | connectionEndpoint ready: WebSocket Connection Endpoint
INFO | Deepstream started
CLUSTER_JOIN | RVD-01-DEBUG-deepstream-redis-localhost
UNKNOWN_ACTION | A

The UNKNOWN_ACTION does NOT show up on the console of the first server node (uuid -> 01)

During this test NO api calls by the client are being made to the second server node (uuid -> 02) (btw port 6021)

**Comment by datasage** [comment]
This issue appears to be related to this one: https://github.com/deepstreamIO/deepstream.io/issues/703

**Comment by yasserf** [comment]
@datasage I believe this is related to authentication and not record deletes.

@honorcode are you doing a record delete?

**Comment by honorcode** [comment]
Yeah, on startup of a new session a session metrics record is cleared (deleted).

**Comment by yasserf** [comment]
@jdmd once your happy with the fix feel free to close this issue

**Comment by yasserf** [comment]
@jdmnd How's this looking in terms of release?

**Comment by jdmnd** [comment]
The fix is present in deepstream [v2.3.6](
https://github.com/deepstreamIO/deepstream.io/releases/tag/v2.3.6)
