### ISSUE TITLE
Running deepstream.io as a service

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io#711]
It's work looking into `https://github.com/stephenwvickers/node-os-service` which seems to make a very compelling way of having both linux and windows services running.

Would need a bit of playing with, and would still require users to

`deepstream service add --name deepstream1 --port2`
`deepstream service remove deepstream1`

And then if your on linux, you can do:

service deepstream1 start/stop/status

and if on windows you can do.. well windows services stuff.

**Comment by ScreamZ** [comment]
I'm currently using PM2 to emulate service mode, even with the binary use. If it can help ?

**Comment by WolframHempel** [comment]
PM2 works really well with deepstream's binaries too. Start it via
```
pm2 start --name ds-dev deepstream -- start -c ~/config-dev.yml
```
