### ISSUE TITLE
Best practices with single authoritative client on cluster

### ISSUE THREAD

**Issue by synthmeat** [deepstreamIO/deepstream.io#714]
We have deployed a cluster of deepstream nodes, and, beside it, a cluster of our own servers where we have various types of authoritative deepstream clients that run on backend (matchmaker, gamemaster, whatnot).

However, logic entails that only a single of those backend clients would run at any time, others being marked inactive and activating in case of, say, node failure.

For instance, there's always a single active matchmaker in entire infrastructure, and there's only single active gamemaster per active game.

We're not sure what would be idiomatic way to run this on deepstream abstraction concepts. Any hints?

**Comment by yasserf** [comment]
Hey,

It depends greatly on what the backend services do. We use micro-services and load distribution quite alot which means you don't have to run a single instance usually.

However, that being said, there are multiple other solutions depending on your desired output.

As a high level feature offer to solve this:

1- [active providers](https://deepstream.io/tutorials/core/active-data-providers/) to only allow one  backend process to satisfy commands
2- [presence](https://deepstream.io/docs/client-js/presence/) to listen to other backend processes logged in, basically using it as a lock. You can then use deepstreams apis to dynamically provide/unprovide things like RPC endpoints.

There are a couple other solutions, but the two above are the patterns I see/recommend using most often

**Comment by yasserf** [comment]
@synthmeat I hope this answers your question, if you have any follow up feel free to reopen this issue.
