### ISSUE TITLE
Brew Cask package for deepstream

### ISSUE THREAD

**Issue by randahlem** [deepstreamIO/deepstream.io#715]
Here ist the according PR, @jdmnd can you check the conflicts again? https://github.com/deepstreamIO/deepstream.io/pull/698

**Comment by yasserf** [comment]
So I got this working up until it still requiring sudo

So question is whether that is acceptable. It a time vs security aspect. 

Thoughts?

**Comment by randahlem** [comment]
I think we can leave it like this and if we find a solution, we push another version! Maybe someone else comes up with a PR after installing it with brew.

**Comment by yasserf** [comment]
PR commited 

https://github.com/caskroom/homebrew-cask/pull/36067

and now we wait..

I have no idea how we can automate this, alot of sed'n and git'n i guess
