### ISSUE TITLE
Error: Unknown option "dataTransforms"

### ISSUE THREAD

**Issue by jakobrosenberg** [deepstreamIO/deepstream.io#717]
Getting this error on Windows 10 x64. Node version v6, v7 and v8.

I followed the instructions here.
https://deepstream.io/install/npm/

**Comment by yasserf** [comment]
Transforms were removed since 1.0, we need to update documentation,
apologies!

**Comment by jakobrosenberg** [comment]
Thanks for your reply yasserf.

Is there a newer version of this page?

https://deepstream.io/docs/server/data-transforms/

**Comment by yasserf** [comment]
No, we fully removed the functionality since users were doing it for very compute intensive functions that didn't scale and blocked node. We are looking into i options, what's your use case?

**Comment by yasserf** [comment]
No, we fully removed the functionality since users were doing it for very compute intensive functions that didn't scale and blocked node. We are looking into i options, what's your use case?

**Comment by jakobrosenberg** [comment]
I'm building a digital order sheet for the production pipeline in a printing company. Think ad hoc task manager. (Realtime communication / updates are vital for the app to efficiently replace verbal instructions and handwritten notes. Both lead to inconsistent information and often untraceable errors)

The order sheet is massive and somewhat static. It resides in an MSSQL database and is served over GraphQL. Status, instructions, feedback and other realtime data is handled separately. To avoid multiple logins, I would like deepstream to serve both the realtime and static data.

Meteor is usually my go-to solution for apps like these, but deepstream seems to have matured a lot since I last considered it.

**Comment by jakobrosenberg** [comment]
I might have found an answer here.

https://gist.github.com/yasserf/07cb500c038a9648bc5f51fea062ca88

**Comment by yasserf** [comment]
We are [removing](https://github.com/deepstreamIO/deepstream.io-website/pull/146) the dataTransform docs from the website

I'm closing this issue because it directly correlates to `dataTransforms`, but if you have any further questions please feel free to reopen it or create a new one about best-practices or missing documentation. Thanks!
