### ISSUE TITLE
Valve Depermissioning After Subscribe

### ISSUE THREAD

**Issue by whaatt** [deepstreamIO/deepstream.io#718]
I have a chatroom-like use case right now with locators of the form `chat/$room`.

In `permissions.yml`, I am restricting read access to these chatroom records unless `oldData.users.indexOf(user.id) !== -1`, where `oldData` refers to the chatroom record. Clients can join and leave chatrooms by calling an RPC agent, which adds and removes them from the `users` list on the record.

This works fine if a client is trying to subscribe to a chatroom record, and they are not in the `users` list. In this case, the client receives a MESSAGE_DENIED error and is not allowed to subscribe.

If a client is already subscribed to a chatroom record, and then they are kicked out of the chatroom by an administrator, an RPC agent removes them from the `users` list. However, it seems like the client continues to receive callbacks of the chatroom data, which contradicts the Valve rule. Is this expected behavior?

If not, is there any way to remotely cut off the user from receiving further callbacks on the chatroom?

**Comment by WolframHempel** [comment]
Hi @whaatt - this is a tricky one. Valve rules are executed at the time of subscription, e.g. when calling `getRecord()` - they are not re-evaluated for outgoing messages. This means that when a client sends a message to a chat-room, it is validated as one write by valve, but for performance reasons there is no validation for each individual recipient, checking if they are still allowed to get it.

When a client connection is cut, it immediately reconnects and resubscribes - as part of which all subscriptions are re-evaluated. We are working on an official `ds.kick('username')` API that tells the server to disconnect a specific user. Until this is available you could implement a less secure version of the same by registering an RPC, e.g. `kick-me/username` on each client that forces it to disconnect and reconnect - of course this is in the client side script, so isn't save from manipulation.

**Comment by whaatt** [comment]
Got it; thanks!
