### ISSUE TITLE
when calling record setWithAck with a path no ack

### ISSUE THREAD

**Issue by grendo** [deepstreamIO/deepstream.io#719]
Hi,
  I am porting the java client to .net.  I just updated my port with the latest java code and the node deepstream server.  I have a test that is testing the record setWithAck and a path.  With the latest node server code I do not get an ack back.  With the 2.2.2 node version of the deepstream server I do get an ack back.  Has anyone seen an issue with setWithAck and path on the java client ?

**Comment by AlexBHarley** [comment]
Hey @grendo 

I just tried running this code

```
DeepstreamClient client = new DeepstreamClient("localhost:6020");
client.login();

JsonObject data = new JsonObject();
data.addProperty("hello", "there");

for (int i = 0; i < 10; i++) {
  Record record = client.record.getRecord(String.valueOf(i));
  RecordSetResult res = record.setWithAck("path", data);
  System.out.println(res.getResult());
}
```

On deepstream.io version `2.3.4` and deepstream.io-client-java `2.2.0`. The output I received was

```
null
null
null
null
null
null
null
null
null
null
```

Is there any more info you can provide for this issue?

**Comment by grendo** [comment]
This can be closed.  I updated my port to the latest java code and works now.
