### ISSUE TITLE
how load balancing works with presence or listeners?

### ISSUE THREAD

**Issue by mmobini** [deepstreamIO/deepstream.io#720]
Hi, thanks for your awesome library.

As I understand, I can monitor users subscription events through _presence api_.

Suppose I have 5 clients as servers for monitoring other clients behavior, the problem is all of them receive client.presence.subscribe event when new client disconnected but I only want one of them receive it. (for building a decentralized architecture which scales horizontally)

I have same problem with listeners. I need only one of related listeners receive an event.

**Comment by yasserf** [comment]
> As I understand, I can monitor users subscription events through presence api.

This isn't correct.The presence event only tells you who is currently logged in.

> Suppose I have 5 clients as servers for monitoring other clients behavior, the problem is all of them receive client.presence.subscribe event when new client disconnected but I only want one of them receive it. (for building a decentralized architecture which scales horizontally)

This is exactly how listening works, it tells your micro-service architecture when the first user ever subscribes or when the last user unsubscribes

https://deepstream.io/blog/listen-benefits/
https://deepstream.io/tutorials/core/active-data-providers/
https://deepstream.io/docs/client-js/pubsub-client-event/#client-event-listen-pattern-callback-

Let me know if those don't explain it in more detail

**Comment by mmobini** [comment]
Thanks. First link helped me.
