### ISSUE TITLE
Server Not Starting Via API

### ISSUE THREAD

**Issue by whaatt** [deepstreamIO/deepstream.io#721]
I have been using DS 2.2.2 for several weeks without problem, but now I upgraded to 2.3.4 and I can't seem to start the server using the Node API. I call `server.start()` and get the following:
```      _                     _                              _        
   __| | ___  ___ _ __  ___| |_ _ __ ___  __ _ _ __ ___   (_) ___   
  / _` |/ _ \/ _ \ '_ \/ __| __| '__/ _ \/ _` | '_ ` _ \  | |/ _ \  
 | (_| |  __/  __/ |_) \__ \ |_| | |  __/ (_| | | | | | |_| | (_) | 
  \__,_|\___|\___| .__/|___/\__|_|  \___|\__,_|_| |_| |_(_)_|\___/  
                 |_|                                                
 =========================   starting   ==========================
INFO | State transition (start): Stopped -> LoggerInit
```
Then the script immediately terminates without any message. Has the Node server API changed in 2.3.x?

**Comment by yasserf** [comment]
It shouldn't have no. Can you please post your config? Thanks!

**Comment by whaatt** [comment]
I am running a minimal script with the following contents:
```
var Deepstream = require('deepstream.io');
var server = new Deepstream({ port: 7000 });
server.start();
```

**Comment by yasserf** [comment]
That should certainly not have changed.

I know this certainly works:

X = new Deepstream()
X.set('port', 7000)
X.start()

I'll also test your issue once i have access to a computer later today or
tomorrow.

Can you let me know if that works for you?

**Comment by whaatt** [comment]
Didn't work, unfortunately. For debugging purposes, here are my environment details:
- Attempted to run the provided script on Windows 10 (running Node 6.10.2) as well as a remote Ubuntu 16.04 box (running Node 4.2.6).
- In both cases, I created a fresh directory, ran `npm install deepstream.io`, then attempted to run the given script. The `npm install` gave no errors.
- If I use the Deepstream release executables instead, there are no problems initializing the server.

**Comment by yasserf** [comment]
Thank you for the details!

Can you set the log level to debug? Might capture some more event logs.
Thanks!

**Comment by AlexBHarley** [comment]
Hey we've discovered the root cause of this. We'll have a fix out soon

**Comment by whaatt** [comment]
I believe the cause is the new version of `javascript-state-machine`! When I reverted that module from 3.0.1 to 3.0.0-rc1 the issue was resolved.

**Comment by yasserf** [comment]
Yeah, we just realized that too! Looking into fixing the version dependency
