### ISSUE TITLE
MacOS Server: storageExclusion does not work ( throws options.storageExclusion.test is not a function )

### ISSUE THREAD

**Issue by TimoRuetten** [deepstreamIO/deepstream.io#722]
I am using the (executeable) Deepstream Server version 2.3.3 for MacOS. When using the storageExclusion in my config file it does not work as expected.

The following error got throwed when trying to start the server:

`options.storageExclusion.test is not a function`

config.yml:

...
`storageExclusion: /^p\/.*/`
...

I also tried to wrap the regex as a String but the same error will get throwed.

My goal is to exclude all p/* records from getting stored in the database.

**Comment by mitel** [comment]
same behaviour with deepstream 3.1

**Comment by AlexBHarley** [comment]
Thanks for raising this. It looks like this was a left over from back when we exclusively supported the Node API. You'll need to use it that way doing something like:

```
new DeepstreamServer({ storageExclusion: new RegExp( ... ) })
```

We're going to be changing this in deepstream 4.0 (#807) soon to the string `storageExclusionPrefix`.
