### ISSUE TITLE
Documentation for 2.3 release

### ISSUE THREAD

**Issue by ScreamZ** [deepstreamIO/deepstream.io#723]
Hey,

just asked on twitter but I did not get any answers... Will the documentation for the 2.3 release will be available soon ? https://deepstream.io/docs/

Especially on hot path & generic plugin

best regards

**Comment by AlexBHarley** [comment]
Hey @ScreamZ 

We have documentation for:
- the new `setData` API [here](https://deepstream.io/docs/client-js/datasync-client-record/#client-record-setdata-name-path-data-callback-)
- the hot path config [here](https://deepstream.io/docs/server/configuration/)

At this stage we don't have a lot of documentation around the generic plugins. There should be a blog post/tutorial by @yasserf coming soon on writing a custom connection endpoint, stay tuned for that!

**Comment by yasserf** [comment]
Yup, the generic plugin is still in early beta as far as API's are concerned, so we can't really write any official documentation for it as of yet.

**Comment by ScreamZ** [comment]
Awesome, thanks, wasn't looking the right place. No problem for generic plugin, will wait ;)

**Comment by RashadSaleh** [comment]
@yasserf Can you please at least mention the kind of stuff the generic plugins would be able to do? 

If I could wish how they'd be, I'd say the best way from my side of things would be that deepstream.io emits events for all the various stuff it does (read operations; right operations; etc), and then the generic plugins can listen to these events, intercepting and modifying default behavior.
