### ISSUE TITLE
does supports deepstream.io multi tenancy 

### ISSUE THREAD

**Issue by gowridev** [deepstreamIO/deepstream.io#734]
We are building app and we are looking for multi tenancy support on server. plugin support for push notification, media server integration to store media data. SDK for ios and android.  We can use your server.

**Comment by yasserf** [comment]
I'm afraid we do not support multi tenancy on our open source server. If you are looking for those features I would recommend using deepstreamhub and creating seperate applications for each tenant. Happy to hav this conversation on slack. Thanks!
