### ISSUE TITLE
setData(id, recValue) creates empty record {} in cache when id does not exist, should create recValue

### ISSUE THREAD

**Issue by honorcode** [deepstreamIO/deepstream.io#735]
tested with java 2.2.0, server 2.3.4 w redis cache, all components running on mac

**Comment by honorcode** [comment]
subsequent setData(id, recValue) calls do properly write recValue to cache

**Comment by honorcode** [comment]
oops on the premature 'close'

**Comment by honorcode** [comment]
ok, more testing revealed this might be a race condition. Adding a Thread.sleep(ms) in between .setData and .getRecord seems to work as expected.

client.record.setData(id, rec);
Thread.sleep(2000); 
expectedRec = client.record.getRecord(id);

**Comment by yasserf** [comment]
yeah, thats expected behaviour since setData and getRecord are done in two seperate pipelines and don't enforce order.

Thanks for finding that out, was concerned for a sec =D
