### ISSUE TITLE
Possible Issue on Unsubscribe

### ISSUE THREAD

**Issue by datasage** [deepstreamIO/deepstream.io#737]
So this issue is a placeholder at the moment while i collect more data. What I seem to be observing is this:

Users with a long running connection log off when the shift is complete. Users may have been subscribed to 100+ records. This causes a spike in latency within deepstream.

This may be a combination of activity within deepstream and node triggering garbage collection. I have observed that about the same time, a bunch of record requests are made to the cache layer. They are not missing anymore as the delete issue is now fixed, but it does seem to be a spike of requests.

**Comment by datasage** [comment]
I don't know if its related to unsubscribe anymore. I have seen the spike at times where that should not be happening. Its not like the delete issue where its getting a bunch of records that were missing, these records do exist.

Instead, there is a spike of requests about 3-5 times the normal volume of get requests. After that happens there are some indications of latency within deepstream. I have not determined what might causing this spike yet.

**Comment by yasserf** [comment]
It does sound like garbage collection, but it doesn't explain why it would result in cache reads 😕

**Comment by datasage** [comment]
The latency is being measured from the target group on the amazon ALB load balancer, so it really only covers the initial connection and not processing or handling of packets later.

I will have to do some more digging to see what might be causing it. I've seen it occur a couple times per week.

**Comment by yasserf** [comment]
I have no idea how to replicate or go ahead with this =(, hopefully it has been fixed randomly in V4 or someone can replicate.
