### ISSUE TITLE
NodeJS valve permission example

### ISSUE THREAD

**Issue by MedSolve** [deepstreamIO/deepstream.io#748]
I can't find an example anywhere on how to set valve permission in NodeJS. Is it possible to set with:

server.set('permissions', Example permissions)

Please provide an example

**Comment by AlexBHarley** [comment]
@MedSolve you put all your permissions in the config file deepstream is run with. Take a look here https://deepstream.io/docs/server/configuration/#permissioning

**Comment by MedSolve** [comment]
There are a good number of reasons why I would not have my confuguration in an actual file. But this feature is not supported by deepstream?

-------- Oprindelig besked --------Fra: Alex Harley <notifications@github.com> Dato: 19/07/2017  00.23  (GMT+12:00) Til: "deepstreamIO/deepstream.io" <deepstream.io@noreply.github.com> Cc: Rune Rasmussen <rune@medsolve.dk>, Mention <mention@noreply.github.com> Emne: Re: [deepstreamIO/deepstream.io] NodeJS valve permission example (#748) 
@MedSolve you put all your permissions in the config file deepstream is run with. Take a look here https://deepstream.io/docs/server/configuration/#permissioning

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/deepstreamIO/deepstream.io","title":"deepstreamIO/deepstream.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/deepstreamIO/deepstream.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AlexBHarley in #748: @MedSolve you put all your permissions in the config file deepstream is run with. Take a look here https://deepstream.io/docs/server/configuration/#permissioning "}],"action":{"name":"View Issue","url":"https://github.com/deepstreamIO/deepstream.io/issues/748#issuecomment-316047361"}}}
