### ISSUE TITLE
Any chance of getting Alpine-based Docker image?

### ISSUE THREAD

**Issue by Kitanotori** [deepstreamIO/deepstream.io#753]
Current CentOS-based image takes 439MB. Would be nice to have an image based on the super lightweight Alpine Linux.

**Comment by yasserf** [comment]
Yeah that sounds awesome! We will add that in when we add the docker 3.0 release

Thanks!

**Comment by AlexBHarley** [comment]
I couldn't get this to work because we don't build apk's. 

However deepstream 3.0.0 is available on docker hub

**Comment by yasserf** [comment]
@Kitanotori do you have any experience with generating alpine images?

We could also simply just copy over the ZIP and run it that way instead, rather than a system install. We'll take a look and try and come up with a solution!

**Comment by Kitanotori** [comment]
I've been building Alpine images for couple own apps recently. I could try building one for Deepstream also.

**Comment by yasserf** [comment]
Done properly now for v4 as part of build
