### ISSUE TITLE
Not reading permissions file

### ISSUE THREAD

**Issue by MedSolve** [deepstreamIO/deepstream.io#755]
The following code is not working. I can still get list of records and read each record from my client. My list are called *chats* and my records are called *chat/something*.

// Source of main file in my npm project
main: src/index.js

```javascript
import * as DeepstreamServer from 'deepstream.io';
import { Database } from './database/database.component';
import { Authentication } from './authentication/authentication.component';
import { Permission } from './permission/permission.component';
import { ServerENV } from './server.env';

// setup basic server
const server = new DeepstreamServer(ServerENV);

// setup handlers
server.set('storage', new Database());
server.set('permission', new Permission());
server.set('authenticationHandler', new Authentication());

// start the server
server.start()
```

The class Permission holds:

```javascript
export class Permission {
    /**
     * Type of permission
     */
    type = 'config';
    /**
     * Options for config
     */
    options: any
    /**
     * New permission set and calucate path for options
     */
    constructor() {

        this.options = {
            /**
             * Maximum nesting level
             */
            maxRuleIterations: 3,
            /**
             * Time for permission cache
             */
            cacheEvacuationInterval: 60000
        };
        /**
         * path for configuration
        */
        this.options.path = process.env.production ? './permission.env.prod.json' : './permission.env.dev.json';
    }
}
```

And the files themself:
```json
{
  "record": {
    "chat/*": {
      "write": "user.data.role === 'admin'",
      "read": "user.data.role === 'admin'"
    },
    "chats": {
      "write": "user.data.role === 'admin'",
      "read": "user.data.role === 'admin'"
    }
  },
  "event": {
    "*": {
      "publish": true,
      "subscribe": true,
      "listen": true
    }
  },
  "rpc": {
    "*": {
      "provide": true,
      "request": true
    }
  }
}
```

**Comment by yasserf** [comment]
I am pretty uncertain of how this all works to be honest. It looks like your are overriding the permission plugin with your own that doesn't do permissioning..

**Comment by MedSolve** [comment]
Hi,
I found out the issue. I cannot use server set. When I pass configuration initially as I create the deep stream instance then it works! :-)


Sendt fra min Samsung Galaxy-smartphone.
-------- Oprindelig besked --------Fra: Yasser Fadl <notifications@github.com> Dato: 13/08/2017  23.51  (GMT+12:00) Til: "deepstreamIO/deepstream.io" <deepstream.io@noreply.github.com> Cc: Rune Rasmussen <rune@medsolve.dk>, Author <author@noreply.github.com> Emne: Re: [deepstreamIO/deepstream.io] Not reading permissions file (#755) 
I am pretty uncertain of how this all works to be honest. It looks like your are overriding the permission plugin with your own that doesn't do permissioning..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/deepstreamIO/deepstream.io","title":"deepstreamIO/deepstream.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/deepstreamIO/deepstream.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yasserf in #755: I am pretty uncertain of how this all works to be honest. It looks like your are overriding the permission plugin with your own that doesn't do permissioning.."}],"action":{"name":"View Issue","url":"https://github.com/deepstreamIO/deepstream.io/issues/755#issuecomment-322037503"}}}

**Comment by yasserf** [comment]
Ah yes, I thought that seemed the case. Deepstream set doesn't update the config, t actually replaces the entire plugin with your own instance.

Happy to hear it works!
