### ISSUE TITLE
record.setData and valve permissions error

### ISSUE THREAD

**Issue by jaime-ez** [deepstreamIO/deepstream.io#756]
Hi, I've got a valve rule that uses the incoming data for a record:  
```
write: "user.id === 'sysadmin' ||  (data.hi)"
```
If the user whose id is 'sysadmin' wants to update only a path: record.setData(name, 'bye', 'you') the rule breaks returning  
```
error when converting message data SyntaxError: Unexpected token b in JSON at position 0
```
For what I understand [here](https://github.com/deepstreamIO/deepstream.io/blob/master/src/permission/rule-application.js#L226) the code tries to parse the incoming data but since its a string and not a JSON an error is thrown...

Is it a bug or I am misunderstanding the rule logic?
Thanks!

**Comment by datasage** [comment]
The rule is fine, setData is expecting a json object passed with it.

**Comment by jaime-ez** [comment]
this works just fine: record.setData(name, 'hi', 'you')

**Comment by AlexBHarley** [comment]
As @datasage said, records are supposed to exist as json objects at the top level (not primitives or arrays). That being said we should probably validate this more client side.

This [PR](https://github.com/deepstreamIO/deepstream.io-client-js/pull/391/files) was recently merged which does more validation client side which may give you a better error message.
