### ISSUE TITLE
[FEATURE] Provide TypeScript typings

### ISSUE THREAD

**Issue by Kitanotori** [deepstreamIO/deepstream.io#757]
Typings for the Node API: https://deepstream.io/docs/server/node-api/

**Comment by hars-shhh** [comment]
@yasserf @WolframHempel any update on this?

**Comment by yasserf** [comment]
We actually just converted deepstream to typescript so this should come out of the box after our next major release end of year

**Comment by chapterjason** [comment]
@yasserf  A year's over, nothing happened?

**Comment by rodsfreitas** [comment]
Any update on this?

**Comment by yasserf** [comment]
We have a V4 version that is RC that is totally written in typescript, we will be looking to generate a declaration from that rather than maintain two

**Comment by rodsfreitas** [comment]
I'll wait for the V4. I didn't realised it existed. Thank you!

**Comment by yasserf** [comment]
Awesome! It’s current an RC and being used btw by some people, barely and
breaking changes. So if you want you can start using it now!
