### ISSUE TITLE
HTTP - Error message for wrong version should be more descriptive

### ISSUE THREAD

**Issue by MuriloFrade** [deepstreamIO/deepstream.io#763]
When I try to write a record incrementing  the version +2 the error message says more that I have a conflict than an invalid version value.

Request body when my current version is 1:
![image](https://user-images.githubusercontent.com/4869454/28618357-6a323632-7204-11e7-90d3-66ae85760ebe.png)

HTTP API response:

![image](https://user-images.githubusercontent.com/4869454/28618398-833ac856-7204-11e7-8004-7bed4718d1c8.png)

**Comment by yasserf** [comment]
Fixed in 4.0.0-rc.17
