### ISSUE TITLE
[QUESTION & BUG] Supported platforms? (issues with Safari 9.2)

### ISSUE THREAD

**Issue by Kitanotori** [deepstreamIO/deepstream.io#766]
Couldn't find any information on the supported platforms. I am having serious issues with older Safari versions. Also some Android users (browser, not native) reported issues with my Deepstream-based app. No error shown, but Deepstream doesn't start at all. Tried with several 2.x.x versions of Deepstream JavaScript client.

**Comment by yasserf** [comment]
Hey, sorry to hear! Just to make sure, are you including the code from the dist directory instead the src directory?

**Comment by Kitanotori** [comment]
Not sure what directories you mean. I use these: https://cdnjs.com/libraries/deepstream.io-client-js

e.g. `<script src="https://cdnjs.cloudflare.com/ajax/libs/deepstream.io-client-js/2.2.1/deepstream.min.js"><script>`

**Comment by Kitanotori** [comment]
Oh, sorry. Just noticed I posted the issue in wrong repository. My problem was with the JavaScript client, not the server app.
