### ISSUE TITLE
deepstream.io + nodejs + azure = uws error

### ISSUE THREAD

**Issue by dsaiju** [deepstreamIO/deepstream.io#768]
Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at e (D:\home\site\wwwroot\node_modules\deepstream.io\node_modules\uws\uws.js:31:19)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\deepstream.io\node_modules\uws\uws.js:35:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\deepstream.io\src\message\uws-socket-wrapper.js:5:13)

**Comment by yasserf** [comment]
Hey,

Do you have node-gyp installed correctly on your computer? That tends to be in the initial issue usually!

Cheers,
Yasser

**Comment by dsaiju** [comment]
@yasserf, this works fine on my local system. getting this error when i deployed to azure app service. i don't have access to the VM, but from the app settings i got to know it supports node js 6.9.1 out of the box so i guess node-gyp must have been there too?

**Comment by WolframHempel** [comment]
Afraid not - node gyp (and Python 2.x which it requires) need to be
installed explicitly on windows. Would it not be possible for you to use
the executable?

2017-07-31 19:17 GMT+05:30 dsaiju <notifications@github.com>:

**Comment by dsaiju** [comment]
@WolframHempel, i used kudu console to fetch the list of processes running on the VM and i could see an entry 'Python27' but nothing for *gyp*. does python27 mean node-gyp is installed already?

this link also says node-gyp is supported: https://feedback.azure.com/forums/169385-web-apps/suggestions/6573329-support-for-node-gyp-in-nodejs-applications

**Comment by dsaiju** [comment]
in the meantime i tried it on azure service fabric and facing a different problem. basically everything works fine on local system since my host is 'localhost' in both server.js side <<new DeepstreamServer(host, port)>> as well as in client.html side <<deepstream('localhost:6020').login({}, ...)>>. but once i move to cloud, getting below error:

WebSocket connection to 'ws://######.cloudapp.azure.com:6020/deepstream' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

i've played with 'localhost' and '######.cloudapp.azure.com' in server and client files in all combinations but can't seem to make it work. really want to add deepstream to our tech stack either as an azure app service or an azure service fabric, but stuck so far :(

**Comment by yasserf** [comment]
might be worth trying to use `0.0.0.0` as your host in the server rather than localhost?

**Comment by dsaiju** [comment]
@yasserf , wow... it worked! i love how fast the connection is made and records fly here and there. thanks guys 👍. this issue can be closed now as i let someone else bug u for azure app service and uws error ;)

**Comment by yasserf** [comment]
Awesome! Happy to hear it worked
