### ISSUE TITLE
Feathers.js Transport

### ISSUE THREAD

**Issue by RobIsHere** [deepstreamIO/deepstream.io#777]
Hi! The feathers.js framework gains a huge monumentum this time. And I've personally only made the best experiences with that. I won't use pure deepstream or meteor or something like that, because I'm very focused on getting my projects done in time and budget ;)

Feathers.JS is in deed transport-agnostic. So you can have everything over socket.io OR primus OR rest. OR deepstreamIO???

So my question: is there any feathers.js transport using deepstream already made by someone? Do you support deepstream in feathers?
See: https://docs.feathersjs.com/ecosystem/readme.html#transports

I would love to use german technology for the transport, because I think the correctness of german engineering would spare me some headaches in production. 

Also the perspective to roll out with the free and cheap implementation here and get professional cloud services for scaling later, when the app gets up and running on scale would be a plus.

And I read your performance comparison against socket.io. Hope it isn't faked on some specific side-case only, where deepstream outperforms? If the results are "real for the average use case", that's impressive!

**Comment by yasserf** [comment]
Hey,

Interesting idea. However deepstream itself isn't a transport layer, its a full server with concepts like permissioning / authentication / data-sync built in. As such using the two together with be a pretty ugly mashup of two great techs.

In terms of deciding between featherJS and deepstream, we have recently released a comparison page https://deepstreamhub.com/compare/ which covers how we differ. Would be more than happy to answer any specific questions you have though!
