### ISSUE TITLE
deepstream error listen EADDRINUSE 127.0.0.1:6020

### ISSUE THREAD

**Issue by MBehtemam** [deepstreamIO/deepstream.io#779]
i try to run my first `deepstream.io` server from [this link](https://deepstreamhub.com/open-source/install/npm/) but i get this error : 

[![enter image description here][1]][1]

error: 

    CONNECTION_ERROR | Error: listen EADDRINUSE 127.0.0.1:3003
    PLUGIN_ERROR | connectionEndpoint wasn't initialised in time
    f:\try\deep\node_modules\deepstream.io\src\utils\dependency-
    initialiser.js:96
    throw error
    ^

    Error: connectionEndpoint wasn't initialised in time
    at DependencyInitialiser._onTimeout 
    (f:\try\deep\node_modules\deepstream.io\src\utils\dependency-
    initialiser.js:94:17)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

and this is my code:

    const DeepStreamServer = require("deepstream.io")
    const C = DeepStreamServer.constants;
    const server = new DeepStreamServer({
      host:'localhost',
      port:3003
    })

    server.start();

  [1]: https://i.stack.imgur.com/pJFcU.png

**Comment by jdmnd** [comment]
Hi, please see this issue: 
https://github.com/deepstreamIO/deepstream.io/issues/769
The documentation that you may have used (on the deepstream.io website) is out of date and needs to be updated.
