### ISSUE TITLE
How to view all records of rethinkdb?

### ISSUE THREAD

**Issue by hopewise** [deepstreamIO/deepstream.io#78]
As I have used ``` deepstream.io-storage-rethinkdb ``` as a connector to get persistent messages, if I run the query at the admin dashboard of rethinkdb:

    r.db('deepstream').table('dsRecords3')

I only get the last sent message, but what if I want to show them all? I thought that if I cleared the text input, and entered another name, I should see the two names in the db, right? as it will insert a new record each mouseup.. ?

I am using the same example at starting tutorial with slight update:

    input.onkeyup = function(){
                record.set( 'firstname', {value: input.value, time: new Date() } );
            };

**Comment by WolframHempel** [comment]
Hi @hopewise ,

deepstream records are data-structures that can be observed and - most importantly - updated. Each record only produces one entry in a database, that is updated with every change.

If you'd like to create a list of records, you could do just that: Create a record with an individual id for each user, e.g. `user/homer`, `user/marge` and put them all into a [List](http://deepstream.io/docs/list.html), e.g. `simpsons`

So, what you're seeing is correct. Please let me know if that answers your question.

**Comment by hopewise** [comment]
Thank you, but in my case, each user's messages are a stream of
coordinates, how would I structure the record to have an entry for each
day, and then all coordinates will be pushed to the array that is
associated with the date..

Thus, I can get all streamed coordinates of a specific user for a specific
date.. ?

Thanks in advance for your advice.

**Comment by timaschew** [comment]
> can't I push the new coordinate without have to get the whole record each time?

If you don't set the whole data and you don't need to verify or handle somehow the old value, then you can do it this way.

**Comment by yasserf** [comment]
Closing for now as been inactive for a while
