### ISSUE TITLE
deepstream not reading authentication 'type'

### ISSUE THREAD

**Issue by dsaiju** [deepstreamIO/deepstream.io#783]
Hi, I modifed config.yml as below:
#Authentication
auth:
   type: http
   options:
     endpointUrl: http://localhost:6050/validateLogin
     permittedStatusCodes: [ 200 ]
     requestTimeout: 2000

But when I start the server, it doesn't look like this setup is recognized and all credentials are passed without any redirection to the endpoint.
![image](https://user-images.githubusercontent.com/10921212/29170835-ed657862-7df7-11e7-9364-dec14cd64da0.png)

any suggestions?

**Comment by yasserf** [comment]
can you please provide your entire config file?

**Comment by dsaiju** [comment]
[config.txt](https://github.com/deepstreamIO/deepstream.io/files/1215022/config.txt)
[serverjs.txt](https://github.com/deepstreamIO/deepstream.io/files/1215023/serverjs.txt)
@yasserf PFA the config and js files

**Comment by yasserf** [comment]
You need to point your deepstream to the config file if using npm

new Deepstream('./conf/config.yml')

**Comment by yasserf** [comment]
Hope that helped!

**Comment by dsaiju** [comment]
@yasserf sorry couldn't reply on time. yes, it works fine. thanks 👍
