### ISSUE TITLE
404

### ISSUE THREAD

**Issue by hopewise** [deepstreamIO/deepstream.io#79]
This page is not there! http://deepstream.io/tutorials/docs/record.html

I need to know if record is already or not, is this possible?

**Comment by WolframHempel** [comment]
Hi @hopewise,

thanks for pointing this out. Would you happent o remember how you got to that link? The records tutorial and documentation pages seem to be reachable from the menu:

http://deepstream.io/docs/record.html
http://deepstream.io/tutorials/records.html

To find out if a record is ready, you can just check `myRecord.isReady`. Records also have a `'ready'` event and a `whenReady( callback )` method

**Comment by hopewise** [comment]
Thanks, the hyper link Record here http://deepstream.io/tutorials/records.html leads to 404

**Comment by yasserf** [comment]
Fixed
