### ISSUE TITLE
WSS for HTTPS

### ISSUE THREAD

**Issue by jessy26** [deepstreamIO/deepstream.io#791]
Hi everyone !! 
How i can seting deepstream for https ??

**Comment by yasserf** [comment]
You can use a loadbalancer to SSL terminate or provide your ssl certificates directly into deepstream config

https://deepstreamhub.com/docs/server/configuration/#ssl-configuration

**Comment by jessy26** [comment]
Thank you my friend for your helpLe 13 sept. 2017 1:37 PM, Yasser Fadl <notifications@github.com> a écrit :You can use a loadbalancer to SSL terminate or provide your ssl certificates directly into deepstream config
https://deepstreamhub.com/docs/server/configuration/#ssl-configuration

**Comment by yasserf** [comment]
👍
