### ISSUE TITLE
lists access from http api

### ISSUE THREAD

**Issue by tzapu** [deepstreamIO/deepstream.io#793]
hi guys, impressive project 

is there any way currently or in future plans to access lists over http api?

cheers

**Comment by schulz3000** [comment]
A list is not more then a record with all record names in it, which this list reference to.
So you can call ReadRecord via HTTP API with the listname as recordname.
With the result from this first call you can get all records from the list with one additional batch call.

**Comment by tzapu** [comment]
i did play with that but it seems i can't create a list through the http api, trying to provide an array of strings in data results in error
```
{
  "topic": "record",
  "action": "write",
  "recordName": "users",
  "data": ["name1","name2"]
}
```
=> in 
`Failed to parse JIF object`

**Comment by tzapu** [comment]
explained here, https://github.com/deepstreamIO/deepstream.io/issues/74#issuecomment-328791644
should be avail in the next version
anyone know when the next version will come? :P
will close the issue anyway
thanks
