### ISSUE TITLE
Provide Arch Linux distrobution?

### ISSUE THREAD

**Issue by dzcpy** [deepstreamIO/deepstream.io#803]
Hi, I'd like to ask if it's possible to also provide an Arch Linux distribution? It's a very popular distro of Linux and the packaging system isn't hard.
Thanks

**Comment by yasserf** [comment]
Hey, we use FPM for packaging (https://github.com/jordansissel/fpm) as well as docker to compile deepstream on different distros. Using a combination of both should make it easy enough to create a binary.. I don't have much experience with it tho so knowing what docker image to built it on would probably help!

**Comment by andyhu** [comment]
Hi, thanks for the reply, FPM can natively support Arch Linux's packaging system since version 1.5. See:
https://github.com/jordansissel/fpm/pull/916
It is very easy to provide an AUR (Arch User Repository) package with FPM. Would you mind to create one?

**Comment by andyhu** [comment]
Also, I would like to know if deepstream is entirely written in Node.js? If that's the case maybe using as a native node module is faster than using the binary since it will introduce more overhead cost of docker?

**Comment by ronag** [comment]
docker won't have any overhead on ds

**Comment by yasserf** [comment]
Update on this, we can now build ARCH linux versions of deepstream. Not sure how to package it yet tbh.

**Comment by yasserf** [comment]
Closing this as I'm dropping support for packaging for different distros for V4 as it takes too much time and can be easily replaced with a simple script.
