### ISSUE TITLE
setData for new records 

### ISSUE THREAD

**Issue by mitel** [deepstreamIO/deepstream.io#804]
using:
- deepstream 3.0 (docker)
- js client 2.3.0
- no record `test/blah` is created before setData

this code works:

```js
setData('test/blah', {item:'blah'})
```

this code does not, the write is not commited:
```js
setData('test/blah', 'mypath', {item:'blah'})
```

this code works, the write is commited:
```js
const tmp = ds.record.getAnonymousRecord();
tmp.setName("test/blah");
setData('test/blah', 'mypath', {item:'blah'})
```

if no record exists, setData will create the record only if the path is not specified.

**Comment by yasserf** [comment]
Thank you for raising! We'll try get a fix in for this in soon!

**Comment by AlexBHarley** [comment]
@mitel I ran the following script

```
const deepstream = require('deepstream.io-client-js')

const client = deepstream(localhost:6020)
const recordName = `test/record-${Date.now()}`

client.login(() => {
  client.record.setData(recordName, 'path', { blah: 'thing' })

  setTimeout(() => {
    client.record.snapshot(recordName, (err, data) => {
      console.log(err, data)
    })
  }, 1000)
})
```

and got the following console output:

```
null { path: { blah: 'thing' } }
```

Are you using any storage or cache layers? And could you please try again with deepstream `v3.1.0`?

**Comment by mitel** [comment]
just tested with deepstream 3.1 and it behaves exactly the same.
yes, using Postgres 9.6 and redis.
so when i wrote that the write is not committed, i meant that the record is not committed to Postgres.

btw - the docker image with the 'latest' tag is still 3.0 in docker hub.

thank you

**Comment by AlexBHarley** [comment]
Just tested with:

- deepstream `3.1.0`
- postgres `9.6.1`

and am seeing the correct data in Postgres.

![screen shot 2017-10-10 at 10 37 54](https://user-images.githubusercontent.com/11168524/31377046-1f8d2dd8-ada7-11e7-98ac-1a2f1d51efde.png)

Will release `3.1.0` to dockerHub now, could you test with that and let us know?

**Comment by mitel** [comment]
Thanks Alex, the docker image is now 3.1.
Tested and the behaviour is the same, which is quite weird because my test is pretty much the same.
The only difference might be that my deepstream client is running on server-side (node.js).
Thanks for the support

**Comment by AlexBHarley** [comment]
Also running my client via node, however once it reaches the server this doesn't matter.

Could you get back to me with the full script you're using?

I see you using a function `setData` which is possibly different to me using `client.record.setData`

**Comment by mitel** [comment]
ok, i discovered the cause.
i'm using storageHotPathPatterns for that particular record.
i suppose this is the normal behaviour though, it just that it's not documented.

thank you

**Comment by yasserf** [comment]
Thanks for clarifying, the error you said shouldn't happen and we will fix the underlying issue (patch ontop of an empty object by default)

**Comment by jshrt** [comment]
Related https://github.com/deepstreamIO/deepstream.io/issues/861

**Comment by yasserf** [comment]
storageHotPathPatterns should reject patches with an error.

https://github.com/deepstreamIO/deepstream.io/blob/master/src/record/record-handler.ts#L199
