### ISSUE TITLE
Official site docs errors

### ISSUE THREAD

**Issue by noobiek** [deepstreamIO/deepstream.io#805]
Hi,

I want to thank you for your great effort. The software is awsome!

And I want to point your attention to several mistakes in docs on your site, namely:

On this page
https://deepstreamhub.com/open-source/integrations/other-nginx/
I found at least 2 mistakes:
1. Config line is unfinished and corrupted - "proxy_set_header Connection 'upgrade", it should be "proxy_set_header Connection $connection_upgrade;"
2. You have "upstream http-endpoint" in one place of config, and it is referenced as "proxy_pass http://httpendpoint;" later on, but it should be either http-endpoint or httpendpoint in both cases.

Webhook auth explanation is somewhat inconsistent
Here https://deepstreamhub.com/tutorials/guides/http-webhook-auth/ several time is explaned that return should have userId: 'some-username'
While here https://deepstreamhub.com/open-source/core/http-webhook-authentication/ it is stated that return should be like "username":"chris".
So which is it? UserId or Username?

In case I missunderstood something, please, let me know.

**Comment by Srushtika** [comment]
Hi @noobiek ! Thanks for pointing this out.
The nginx doc is now fixed.

For webhook auth, it is userId in case of deepstreamHub and username in case of deepstream.io. Those docs are updated as well!

Cheers!

**Comment by noobiek** [comment]
Hi,
You didn't correct nginx point N.2
The one about "upstream http-endpoint" and "proxy_pass http://httpendpoint;"
