### ISSUE TITLE
Publish deepstream 3.1.0 to NPM

### ISSUE THREAD

**Issue by daviderenger** [deepstreamIO/deepstream.io#806]
Hi, any reasons why 3.1 is not published to NPM?

**Comment by yasserf** [comment]
Nope, we just got blocked on it being published on Windows due to the machines refusing to compile deepstream in time. We'll sort this out on Wednesday (bank holiday right now). Thanks for raising!

**Comment by AlexBHarley** [comment]
`v3.1.0` is now up on NPM.
