### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by fhriley** [deepstreamIO/deepstream.io#810]
1. For the HTTP [webhook authentication tutorial](https://deepstreamhub.com/tutorials/guides/http-webhook-auth/), it says you should return `userId`. This should be `username`.
2. This [webhook documentation](https://deepstreamhub.com/open-source/core/http-webhook-authentication/) has 1) correct, however, in the part where it says `If a success, the deepstream console will show`, it shows the console saying `AUTH_SUCCESSFUL | OPEN`. `OPEN` authentication is not a success. When successful it will give the username.

**Comment by Srushtika** [comment]
Hi @fhriley ! Thanks for opening this issue.
There are two different things to consider here:
1. On deepstreamHub, you would use a userId and the tutorial you linked to in the first point, is a tutorial for deepstreamHub.
2. On deepstreamIO, you would use a username and the documentation you linked to in the second point, belongs to core(in other words deepstreamIO).

Hope it clarifies your query!

Also, thanks for pointing out that the screenshot says AUTH_SUCCESSFUL | OPEN, that will be replaced.
