### ISSUE TITLE
Presence API with JWT- Webhook

### ISSUE THREAD

**Issue by kamerk22** [deepstreamIO/deepstream.io#812]
@yasserf 

How can I use Presence API of deepstream with custom JWT - Webhook?
As I read documentation of Presence API it showing when using login with Auth then this will return username as a currently login user. Can I use same with JWT?

Current Setup
- JWT server for Authentication
- Deepstream Configured  for Auth.

**Comment by Srushtika** [comment]
Hi @kamerk22 !
Yes, for Webhook auth on deepstream.io, your auth server needs to return a username along with the client and server data as shown below. This is the username that you'll see in the presence callback.

```
if (/*auth data valid*/) {
    res.json({
      username: 'some-username',
      clientData: {  },
      serverData: {  }
    })
  } else {
    res.status(403).send('Invalid Credentials')
  }
```

**Comment by kamerk22** [comment]
@Srushtika 
Thanks for your answer.
How can I get event if user if login or logout.
Currently my code is 

```js
ds.presence.getAll((user) => {
    console.log(user);
})
```
Is there any event for login and logout with presence API?

**Comment by Srushtika** [comment]
@kamerk22 
`presence.getAll()` only gives you a list of the users who are logged in at the particular time when your code is executed. 

If you wish to get notified everytime one of your user logs in or logs out, you would want to subscribe to presence like this:

```ds.presence.subscribe((username, login) => {
    if(login){
    //handle what happens when a client with `username`=='username' logs in
    }else{
    //handle client logout
    }
})```

Hope that solves your query. Here's a complete guide on how to use presence in deepstream: https://deepstreamhub.com/tutorials/guides/presence/
