### ISSUE TITLE
5. Deploying on AWS link broken

### ISSUE THREAD

**Issue by Chinafreak** [deepstreamIO/deepstream.io#818]
"5. Deploying on AWS" from readme link is broken aka not available at Youtube.

**Comment by Srushtika** [comment]
Hi @Chinafreak ! Thanks for raising this issue. However, it would be much helpful if you could link the readme file here that you are referring to!

**Comment by Chinafreak** [comment]
Oh sorry. Of course I meant this readme.md 

https://github.com/deepstreamIO/deepstream.io/blob/master/README.md

**Comment by yasserf** [comment]
Seems like link was entirely removed.
