### ISSUE TITLE
Hotpath: specifying storageHotpathPattern and using setData for non-existing record crashes the server

### ISSUE THREAD

**Issue by jshrt** [deepstreamIO/deepstream.io#828]
To reproduce:

set storage hotpath pattern in `conf/config.yml`:
```
storageHotPathPatterns:
    - posts/
```

In the client:
```
const client = deepstream('url')
client.login({username: 'aa'}, (success) => {
  client.record.setData('whateverRecordName', 'whateverPath', 'sometstr')
})
```

The server drops with the following:
```
return builder(message, errorAction, errorMessage)
         ^
TypeError: builder is not a function
    at Object.exports.getErrorMessage (/home/jshrt/Workspace/projects/deepstream/io/deepstream.io/protocol/text/src/message-builder.ts:209:10)
```
Client code is reproduced in: https://github.com/deepstreamIO/test-scripts/blob/master/records/hotpath-setdata.js

### Update

It seems that there is a different problem that also crashes the server when using setData with write acknowledgement.

set storage hotpath pattern in `conf/config.yml`:
```
storageHotPathPatterns:
    - posts/
```

In the client:
```
client.login({username: 'medium/brian'}, () => {
        client.record.setData('posts/monday', {
            content: 'Horray'
        }, () => {
            console.log('data has been set')
        })
    })
```

The server drops with the following:
```
[RA.WRITE_ACKNOWLEDGEMENT.BYTE]: (msg, event, isAck) => `R${y}WA${y}${msg.name}${y}${JSON.stringify(msg.parsedData[0])}${y}${typed(msg.parsedData[1])}${x}`,
                                                                                                                      ^
TypeError: Cannot read property '0' of undefined
    at 17 (/home/jshrt/Workspace/projects/deepstream/io/deepstream.io/protocol/text/src/message-builder.ts:96:119)

```
Client code is reproduced in: https://github.com/deepstreamIO/test-scripts/blob/master/records/hotpath-setdata-writeack.js

#### PS : using the following works without breaking the server:
```
client.login({username: 'medium/brian'}, () => {
        client.record.getRecord('posts/monday')
        client.record.setData('posts/monday', {
            content: 'Horray'
        }, () => {
            console.log('data has been set')
        })
    })
```

**Comment by AlexBHarley** [comment]
This is an error in the new message builder @yasserf or @jdmnd. Possibly hasn't been implemented yet I'm not sure.

```
{ isAck: false,
  isError: false,
  topic: 5,
  action: 13,
  name: 'whateverRecordName',
  data: 'Ssometstr',
  path: 'whateverPath',
  version: -1,
  isWriteAck: false }
```

is coming into the `getErrorMessage` function which seems wrong though.

**Comment by yasserf** [comment]
Yeah, anything with

return builder(message, errorAction, errorMessage)
         ^
TypeError: builder is not a function
    at Object.exports.getErrorMessage (/home/jshrt/Workspace/projects/deepstream/io/deepstream.io/protocol/text/src/message-builder.ts:209:10)

is a text message builder issue. Nice issue ;)

**Comment by jshrt** [comment]
Although v4 uses the binary protocol, but we can consider this bug is still not fixed.
Mentioning https://github.com/deepstreamIO/deepstream.io/issues/860

**Comment by AlexBHarley** [comment]
This is fixed

**Comment by yasserf** [comment]
@jshrt why is this reopened?

**Comment by jshrt** [comment]
It must've been by accident, closing this again.
