### ISSUE TITLE
Presence subscribe callback for particular user gets triggered twice

### ISSUE THREAD

**Issue by jshrt** [deepstreamIO/deepstream.io#833]
In presence, if the client subscribes to the status of all the available users, and also subscribes individually to a particular user's status, the individual subscription gets triggered twice.

Example:

```
client.presence.susbcribe((username, loginStatus) => {
  console.log(`user ${username} logged: ${loginStatus}`
})

client.presence.subscribe('userA', (loginStatus, username) => {
  console.log('userA status:', loginStatus)
})
```

The callback for `userA` subscription gets triggered twice.

This would result in an undesired behavior for many use cases where the individual subscription mutates some external state for example.

Reproduction of the issue is available in: https://github.com/deepstreamIO/test-scripts/blob/master/presence/single-sub-called-twice.js

**Comment by yasserf** [comment]
nice catch

**Comment by jshrt** [comment]
This issue is fixed in v4 (_full test script in: https://github.com/deepstreamIO/test-scripts/commit/b826b8b7afee055db9bdc8b907fbaa122e4fcee3_)
