### ISSUE TITLE
MESSAGE_PARSE_ERROR crashes the server

### ISSUE THREAD

**Issue by jshrt** [deepstreamIO/deepstream.io#834]
After having broken the client to send random data to the server in the following manner:

_in Connection class in the client, in `sendMsg` method, wrap the sending in a for loop looping over the available actions_:
```
for(let key in C.ACTIONS) {
  this.send(messageBuilder.getMsg(topic, C.ACTIONS[key], data));
}
```

using the script at:https://github.com/deepstreamIO/test-scripts/blob/master/records/broken-client-record.js

The server crashed with the following message:
```
MESSAGE_PARSE_ERROR | [object Object]
deepstream.io/protocol/text/src/message-builder.ts:201
  const builder = BUILDERS[message.topic][errorAction]
                                          ^
TypeError: Cannot read property '67' of undefined

```

**Comment by yasserf** [comment]
what topic did it break on?

**Comment by jshrt** [comment]
It was records `R`

**Comment by jshrt** [comment]
This issue is fixed in v4 since v4 uses the binary protocol
