### ISSUE TITLE
WebHook Auth and dynamic permissions

### ISSUE THREAD

**Issue by noobiek** [deepstreamIO/deepstream.io#835]
Hi,

This is not an issue. It is a question regarding permissions. Sorry if it's a wrong place.

Anyway. I have a WebHook Auth that defines permissions for users logging in. Is there a way to refresh permissions without reconnecting the user (close() then login() again is not an option since it will close all current records, right?).

Background:
Current permissions setup looks like this:
materials/$docId:
  create: "user.data.materials.indexOf($docId) > -1"
...etc. So upon user log in webhook returns a list of IDs that are accessible to that user. If the list of accessible records changes for the user in the "App behind WebHook", I need to refresh these in the currect DS session somehow.
DS records are used for instant data exchange only, they do not store any actual record data. So WebHook basically tells DS if our user can exchange information with other users regarding this record.
I've read about "dynamic permissions", but those require additional permissions record inside DS, so I'll need some additional link between "App behind WebHook" and DS - this doesn't look very convinient.

I can alwats stick to long unique $docId, but...
Maybe there is some possibility to invoke session/permissions refresh on timer (without discarding currect docs and without loosing any data change events)? Thanks for any suggestions! 

And thank you for the great software!

**Comment by yasserf** [comment]
This will fall under the 4.5 release with the admin API (basically the ability to refresh permissions and kickout users for now)

**Comment by yasserf** [comment]
Linking to #787

**Comment by yasserf** [comment]
Unfortunately the admin API was pushed out of scope to client projects pivoting on usecase.

There is some work by the community potentially on a kick out user feature. Using V5 api refreshing yaml config should also be super easy to implement for those interested in putting in a few lines of code.

Generally it’s very hard to repermission dynamically without kicking out users. It’s doable, but would require elbow grease I don’t think we currently have capacity for.
