### ISSUE TITLE
Postgres Querying

### ISSUE THREAD

**Issue by sebastianmacias** [deepstreamIO/deepstream.io#836]
I'm looking at the [Searching and Querying](https://deepstreamhub.com/open-source/core/searching-and-querying/) docs and I see there are RethinkDB and Elasticsearch examples.

I have a couple of questions:

1. Can the same conditions (eq, gt, lt, ne, match) be used with the Postgres database connectors?

2. Does the realtime database support relationships and how do you query them?

ie.

```javascript

{
   HP(func: allofterms(name@en, "Harry Potter")) @cascade{
       name@en
       starring{
           performance.character@filter(allofterms(name@en, "harry")) {
               name@en
           }
           performance.actor {
               name@en
           }
       }
   }
}
```

Thanks

**Comment by yasserf** [comment]
Any database can use the same conditions, the logic itself isn't actually provided by the server but instead by a microservice that uses listening to generate automatic collections. You can make realtime postgres feeds if you either:

- Run the query on a cron job (a bit icky but means you can do things like just query a slave / backup db)
- Use postgres triggers to make it truly realtime, at the cost of the performance overhead triggers associate to each write.

Hope that helps, 
Thanks
