### ISSUE TITLE
No Debian Stretch deb package in bintray repositories. 

### ISSUE THREAD

**Issue by rajudev** [deepstreamIO/deepstream.io#843]
Dear deepstream Team,

I was looking for Installation instructions of deepstream on Debian referring this page http://dl.bintray.com/deepstreamio/deb/

I noticed that the instructions are still using `jessie` as the Debian release. 

I also browsed the bintray repository afterwards here http://dl.bintray.com/deepstreamio/deb/
even there are no debs present for the `stretch` release.

Debian stable has now moved to  the stretch and it would be nice if you could provide debs specifically for stretch/buster. 

I am aware that I can always get the latest deb from the release page and install that, which I have done when I needed it. But since you have a repo, it would be nice to have the deb upto date with the latest debian release. 

Also consider packaging deepstream directly in debian. Let me know If I can help there.

**Comment by yasserf** [comment]
https://github.com/deepstreamIO/deepstream.io/commit/a00a60aecf7e548b30add6c5cc4852bcb6b4c15c

That should add new releases to stretch

**Comment by rajudev** [comment]
Thanks @yasserf 

I just checked the bintray [repo](http://dl.bintray.com/deepstreamio/deb/)

When should I expect the release for `stretch` be available in the repos?

**Comment by mathieulj** [comment]
Any updates about this? I was wondering the same thing and stumbled onto this issue. It seems that as of today the binaries still are not in the repository.

**Comment by yasserf** [comment]
I will be dropping installs via apt and instead provide a very basic bash script that will download the binary. This will make it way easier for me to maintain. As such closing this issue. Sorry about the feature removal, but the replacement scripts should be extremely easy to use as well!
