### ISSUE TITLE
String based path for set/get and friends

### ISSUE THREAD

**Issue by Secretmapper** [deepstreamIO/deepstream.io#848]
It seems like the `set` path syntax of record doesn't support string based paths. Like so:

`record.set("path['string-based.path']")`

Is this deliberate (i.e. backend is not a string based hash), or an explicit design decision?

**Comment by yasserf** [comment]
This is because we have a pretty naive implementation of path parsing =(. Generally this will be removed at some point in the future for a more preferably JSON diff approach.
