### ISSUE TITLE
npm install on Windows fails due to node-gyp

### ISSUE THREAD

**Issue by batjko** [deepstreamIO/deepstream.io#85]
Hi guys,

Just wanted to try out the tutorial (on Windows machine) and already failed to even install the npm package:

```shell
deepstream-tutorial\node_modules\deepstream.io\node_modules\engine.io\node_modules\ws\node_mo
dules\utf-8-validate\build\validation.vcxproj(20,3): error MSB4019: The imported project "c:\Microso
ft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, a
nd that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit co
de: 1
```

![image](https://cloud.githubusercontent.com/assets/7287076/12973457/59c79c54-d0a4-11e5-8393-c3f4437c2f38.png)

I assume there is a prerequisite that needs to be installed in order to make it work (I never know what node-gyp actually needs), so perhaps the documentation just needs to point out what exactly?

Cheers

**Comment by WolframHempel** [comment]
Hi @batjko ,

node-gyp is a python based build tool for node that is used by engine.io (transport layer of socket.io and deepstream.io). It is however just an optional dependency, so if you don't have it it's usually ignored.

In your case however it looks like there is some node-gyp (probably from a previous python or visual studio install), so npm assumes it can use it, but something is misconfigured.

**Comment by batjko** [comment]
Thanks for the background, @WolframHempel.
Yes, there are a lot of npm packages requiring node-gyp, but I remember having issues with this before. 
Would you therefore recommend that I ignore the error or do I now need to get node-gyp working first, say by reinstalling it from scratch etc?

**Comment by WolframHempel** [comment]
If the install went through, I'd just ignore the error. Everything should work fine, the advantage that node-gyp gives you is that it compiles a few aspects of the code natively, thus making them a bit faster. This should however only really make a difference in production, which will most likely be on a linux-server.

**Comment by batjko** [comment]
Yup, works fine despite the error.
Thanks, @WolframHempel!
