### ISSUE TITLE
Providing an RPC twice crashes the server

### ISSUE THREAD

**Issue by jshrt** [deepstreamIO/deepstream.io#858]
In the v4 of the client, in the `rpc-handler`, if we remove the guard that verifies if the rpc was already registered, and try to provide multiple times the same rpc, the server crashes with the following:

Client guard: `src/rpc/rpc-handler:50` (_guard commented_):
```
  public provide (name: string, callback: RPCProvider): void {
    if (typeof name !== 'string' || name.length === 0) {
      throw new Error('invalid argument name')
    }
    // if (this.providers.has(name)) {
      // throw new Error(`RPC ${name} already registered`)
    // }
```

The server crashes with the following:
```
REQUEST | name: *g with correlation id: jatwb9hj-2jnloidb58c from open
NO_RPC_PROVIDER | name: *g with correlation id: jatwb9hj-2jnloidb58c
MULTIPLE_SUBSCRIPTIONS | repeat supscription to ".*" by open

/home/jshrt/Workspace/projects/deepstream/io/deepstream.io/protocol/binary/src/message-builder.ts:87
    throw new Error(`invalid ${TOPIC[message.topic]} ${(ACTIONS as any)[message.topic][action] || action}: ${metaError}`)
          ^
Error: invalid RPC MULTIPLE_PROVIDERS: meta object has unknown key n
```

Same goes for `RPC_NOT_PROVIDED` upon removing the guard that checks whether the rpc was provided before or not.

The error message:
```
/home/jshrt/Workspace/projects/deepstream/io/deepstream.io/protocol/binary/src/message-builder.ts:87
    throw new Error(`invalid ${TOPIC[message.topic]} ${(ACTIONS as any)[message.topic][action] || action}: ${metaError}`)
          ^
Error: invalid RPC NOT_PROVIDED: meta object has unknown key n
```

**Comment by yasserf** [comment]
Good cath!

**Comment by AlexBHarley** [comment]
Fixed in master. 

```
if (this.providers.has(name)) {
  throw new Error(`RPC ${name} already registered`)
}
```

this does crash the client, however that seems like correct behaviour

**Comment by mannyhappenings** [comment]
Why isn't there any way to check if there are providers already registered with same name?

I am talking about `DeepstreamClient` interface. Shouldn't there be a way to check if rpc provider is already registered apart from catching this Error?
