### ISSUE TITLE
Auth documentation errorCode does not exists

### ISSUE THREAD

**Issue by gerhardcit** [deepstreamIO/deepstream.io#863]
Not sure where else to post documentation anomalies
Below, it points to "errCode" which is not defined in the callback

https://deepstreamhub.com/open-source/core/auth-file/#page-header

```
client.login({
  username: 'chris',
  password: 'password' // NEEDS TO BE REAL
}, (success, data) => {
  if (success === true) {
    // Handle a successful login
  } else {
    // Handle an incorrect login, the errorCode is available
    console.log(errorCode)
  }
})
```

**Comment by jshrt** [comment]
Hello @gerhardcit, thanks for raising! We'll be updating our documentation asap!

Meanwhile, to catch login errors, the data parameters in the authentication callback holds either `clientData` in case of a successful login or `error` in case of a failed login, so code might be more like:

```
client.login({
  username: 'chris',
  password: 'password' // NEEDS TO BE REAL
}, (success, data) => {
  if (success === true) {
    // Handle a successful login
    console.log('clientData', data)
  } else {
    const error = data // holds value of error when login is incorrect
    console.log('failed to login, error:', error)
  }
})
```

In the coming version - _version 4_ - there will a promise based API which is a lot more convenient to use (_first beta is out, feel free to test it out!_):
```
client.login({}).then((clientData) => {
  console.log('successful login')
}).catch(err => {
  console.log('failed to login', err)
})
```

**Comment by gerhardcit** [comment]
@jshrt , the V4 beta versions have to be tested together correct? Server and JS client.

**Comment by jshrt** [comment]
That is correct @gerhardcit , you will need to be on 4th version of both client and server.
