### ISSUE TITLE
Future of Deepstream

### ISSUE THREAD

**Issue by reneroth** [deepstreamIO/deepstream.io#867]
Since DeepstreamHub is being terminated *very* abruptly with a 3-day-notice, I fear something really bad is happening behind the scenes. Does this have further implications for the future of the Deepstream project?

**Comment by DhavalW** [comment]
Would like to know too, since I'm using it in one of my projects thats
about to be launched very soon.

**Comment by webnugget** [comment]
I'm currently planning a migration of an existing project to deepstream. I would be very happy if we could get a short statement from the dev team why deepstreamhub is shut down. Will there be a way to scale deepstream without deepstreamhub? what about the other professional and enterprise features?

thx, Christian

**Comment by webnugget** [comment]
> Hi,
> 
> First of all, thanks so much for being one of deepstreamHub's early adopters – it's been an amazing journey and we really appreciate your trust and involvement.
> 
> Having said that, I'm sad to announce that we will discontinue the deepstream platform in its current state.
> 
> I know that this causes quite some inconvenience on your end and we very much apologize for that. To continue operating you can always export your data from the deepstreamHub platform and import it into deepstream open source.
> 
> The platform itself will remain accessible until December 22nd.  If you have any questions or there is any way to make the transition easier, please don't hesitate to contact us at info@deepstreamhub.com.
> 
> All the best,
> 
> the deepstream team

Got this via email yesterday.

**Comment by wehriam** [comment]
I was also worried by this news. Whatever the outcome, we plan to continue to use Deepstream in production environments. Our [open source clustering](https://github.com/wehriam/deepstream.io-cluster) is capable of coordinating 4-16 machines with very high performance, and the community  remains strong and engaged.

Deepstream is a tremendous project and more relevant than ever. I wish the contributing team nothing but the best and hope this is just a prelude to bigger and better things for all involved.

**Comment by yasserf** [comment]
Hello! This issue raises a really good question, and I apologise for us not yet releasing an official statement. As mentioned within the slack channel we are looking for a way to open sourcing clustering but are currently looking at our available options before we can do so. @wehriam I was following your extension closely and am really impressed with it. If we can get it working with V4 (current deepstream master) I would be happy to merge that in as a built in clustering solution. 

That being said, deepstreamIO and clients was and will always remain open source (AGPL and Apache2). The dev team have spent the last few months getting it upgraded to use a new binary protocol, upgrading the server to typescript and a much cleaner codebase, a rewrite of the JS client in typescript and babel thats supports offline functionality and provide a much better messaging spec called the universal realtime protocol (http://urp-protocol.io). The idea behind the spec is to allow realtime clients to be written, or to allow the different flavours of the server to be written (for example we were playing around with seeing how much more performance we can squeeze out of a go version).

From a technical point of view deepstream has evolved to become stronger and more powerful than it ever was, thanks to the hard work of all the staff and contributors involved, and there really isn't anything like it that is currently open source. If you know anyone who wants to learn or contribute to a data-sync technology in any language (clients), wants to try and see how much faster they can get a server while respecting the URP spec for full compatibility (server), wants to propose an extension to URP itself to support list deltas for example, or generally wants to be involved in a large open source project with thousands of tests and LOC ranging from UTs, integrations suites and even selenium please let us know!

Thank you again for all your support, and I hope we can provide a clearer roadmap/statement once we figure out the commercial aspects.

**Comment by brodybits** [comment]
Thanks @yasserf for the response. Do you guys plan to offer some kind of an enhancement or replacement for the deepstreamHub service within the near future?

**Comment by brodybits** [comment]
P.S. It was not clear to me if deepstream.io supports offline-first mobile data synchronization like realm.io does [1]. Any pointers?

[1] https://realm.io/solutions/offline-first/

**Comment by kosirm** [comment]
@yasserf Thanks for explanation from me to 😃 
Business is _just_ business and development is _just_ development... sometimes they _click_, sometimes not... Anyway, in last 25 years I've seen plenty of sh** software making huge money and vice versa. This project is really something extraordinary and for me as a user it's good to know that you have not dismissed this whole thing, so project will continue to live. And you know "_what goes arround comes arround_", so I trully hope that the team behind this project will be fairly rewarded with money, blessings and ❤️

**Comment by brodybits** [comment]
I would like to make a couple points:

If deepstreamHub does not continue as a business I sincerely hope the owners will do one more thing for the community and offer the optimized deepstream server code under a permissive license such as Apache 2.0, as suggested by someone else in private. It would be ideal if an organization such as Apache Foundation or JS Foundation would take it over for the benefit for all members of the user community.

I am planning to offer deepstream update and support services as an addition to the existing PhoneGap mobile database software that I support at <https://github.com/litehelpers>. (I already made a fork of a JavaScript version of the deepstream server while it was under MIT license and also forked the other deepstream repos.) I think my 5-6 years of work with SQLite on Cordova/PhoneGap (mobile app framework) together with almost 20 years of work in large-scale SMS (mobile text messaging) systems should prove to be a solid foundation. In case anyone is interested please contact me through my GitHub profile or <brodybits@litehelpers.net>.

I would like to make a final point of agreement with "what goes around comes around" in hope and with good faith that the founders and other team members may reap good rewards down the road!

**Comment by ScreamZ** [comment]
@yasserf Will there be any communication one day about Deepstream and Hub ? It's been one month that the platform has shutdown and still no vision on the future.

**Comment by yasserf** [comment]
Hey @ScreamZ, we are currently focusing on enterprise and open-source. The platform was resulting in alot of time spent by the team on auxiliary functions slowing down actual deepstream development massively. The main is that deepstream (along with upcoming v4) would not have built in clustering or monitoring (enterprise features) but will continue all the current specs and be enhanced with time. However I would recommend those who are not using it as an enterprise user to really try and help out if possible as alot of the features really do land in free open-source land. The current goal is to release V4 and make sure everyone is happy. Once that is the case we can explode into improvements as the codebase and creation of client SDKs are that much better now!

**Comment by ScreamZ** [comment]
Hey @yasserf,

Thanks for your quick reply !

So in order to summarise (correct me if I'm wrong), I didn't understand everything before:

- **DeepstreamHub is discarded** but the documentation for DeepStreamOpenSourceServer (DSOSS) (from HUB website) still remain relevant (You told me one time when I asked that I better should rely on deepstreamhub doc than the original doc in term of update and consistency).
- **Deepstream OpenSource Server** is still WIP for V4 (Perfect, typescript is nice ;-))
- **DeepStream Enterprise** remains in development and include such features as Clustering with you "Small World P2P" algorithm and monitoring that are not available in OpenSource (You must earn money and I totally understand that, I'm not complaining ;p).

Is is ok ? I just didn't understand everything upon I received the mail that told me that DSH was going to shutdown :)

Best regards,
Andréas

**Comment by WolframHempel** [comment]
Hey @ScreamZ - yes, that is a good summary. In a nutshell, we found that development, maintenance and monitoring the platform required an amount of investment very disproportionate to the value it created - and no wonder, not only are there numerous established offerings in this space (Firebase, Pusher, PubNub & Co), the things that differentiate deepstream, such as granular datasync and extreme performance where of less interest to the mostly more casual platform users. 
OpenSource and enterprise meanwhile were soaring and with our limited team and ressources we decided to focus fully on this space. My apologies for the bumpy communication around this, but your post above greatly summarizes where we are with 4.0 and lots of exciting developments for both yet to come

**Comment by yasserf** [comment]
> Deepstream OpenSource Server is still WIP for V4 (Perfect, typescript is nice ;-))

This is pretty far down the WIP route (currently RC stage) and we just need a few more people to use it before we can stamp it out. Also need to finish working on a Kotlin SDK, the new native runtime allows it to be called directly from swift, c++ and obviously supports all java versions starting from 1.6 which would make our lives pretty easy.

> (DSOSS) (from HUB website) still remain relevant (You told me one time when I asked that I better should rely on deepstreamhub doc than the original doc in term of update and consistency).

We have moved all documentation references again to just deepstreamHub with link forwarding from deepstream.io. All opensource documentation and APIs are also there. We will also probably move the opensource aspects and API documentation to an opensource github repo as documentation gets the most amount of love from the community which will then populate the website.

In general it would be great for people to adopt the RC version of deepstream so we can make officially release it and get back into more regular release cycles!

**Comment by daviderenger** [comment]
That is great news @yasserf and @WolframHempel. I was afraid that everything was going down and I held my breath for a clear answer from you!

I tried migrate to v4 a couple of months ago but there was to much breaking at the time and I was unsure how feature complete it was. I will get the RC up and running as soon as I can!

We are also interested to hear more about the Enterprise offering, I'll get back to you in another channel!

**Comment by ScreamZ** [comment]
@WolframHempel @yasserf Thanks for the reply, that was exactly what we were waiting for :)

May I suggest you to make a tweet with that topic linked, some people would probably enjoy having those ;)

Keep the good work, DS is still my preference between all available Backend as a Service (even If a team is dedicated building a concurrent solution in my company (kuzzle) ahah)

**Comment by balupton** [comment]
> We have moved all documentation references again to just deepstreamHub with link forwarding from deepstream.io.

Not sure that is smart move when the reputation of deepstreamhub has just been nuked but its announced shutdown. Wouldn't be smarter to kill deepstreamhub's website altogether, and just move everything to deepstream.io as now only the open-source project lives?

**Comment by yasserf** [comment]
I'm going to close this issue now as the platform has been closed for over a month.

As a summary, deepstream.io and deepstream enterprise are both still running normally. The *platform* was shutdown so we can concentrate on enterprise features and opensource and less on auxiliary functions. Hopefully over the course of the next few months things such as the data-explorer and other platform concepts will be released!
