### ISSUE TITLE
MySql connector with real-time-updated

### ISSUE THREAD

**Issue by lalov** [deepstreamIO/deepstream.io#868]

**Comment by lalov** [comment]
It should be possible to use https://github.com/nevill/zongji and https://github.com/numtel/mysql-live-select to make a MySql connector with realtime updates. 
Mysql-live-select provide events when a MySQL select statement result set changes by listening on the binlog (replication log).

**Comment by yasserf** [comment]
This isn't something we would be looking to do ourselves, as there are a huge ecosystem of db's with replication logs. If anyone ever does raise something we would be more than happy to reference it in our documentation!
