### ISSUE TITLE
Total online users API

### ISSUE THREAD

**Issue by hoangtrongphuc** [deepstreamIO/deepstream.io#869]
Presence getAll() get all player online, so if my server have 3k-4k user, I can't get all user list, how can I get num player online ?

**Comment by yasserf** [comment]
This is not doable unless you hook into monitoring for now =(

**Comment by yasserf** [comment]
I’m going to close this as in ideal world we would have presence channels similar to pusher, since presence is pretty simple it would be better to have that as part of an epic.
