### ISSUE TITLE
deepstream GET *

### ISSUE THREAD

**Issue by askucher** [deepstreamIO/deepstream.io#870]
I am happy to use deepstream server but I cannot understand how to make simple `GET *` api 

```
handler = (req, res)->
  res.writeHead 200, {'Content-Type': 'text/html'}
  res.end "<html></html>"

http.create-server(handler).listen(8080)
```
I have seen rps's `name`, `callback`. but in my case I have to return react app for all possible urls. 
Please help

**Comment by yasserf** [comment]
https://deepstreamhub.com/docs/http/v1/#making-an-rpc

Does that help?

Returning all possible urls is more complicated, since we don't expose that yet as an SDK function.

**Comment by yasserf** [comment]
Closing, but feel free to reopen if you want to discuss further
