### ISSUE TITLE
Any example for reactjs realtime chatting?

### ISSUE THREAD

**Issue by geohuz** [deepstreamIO/deepstream.io#871]
Is there any reason that no realtime chatting example for reactjs? All the examples are written with Angular. As a react guy, I would like to have a tutorial to follow. BTW, I saw there is another realtime chatting example written in angular on deepstreamHub, does it mean there are deepstreamHub specific APIs when writing chatting program use deepstreamHub? Thanks!

**Comment by jshrt** [comment]
Hello @geohuz 

*Deepstream* does not really care whether you use it with Angular, React or anything else. There are tutorials on how to use Deepstream with react, like this [one](https://deepstreamhub.com/tutorials/getting-started/react/) for example.

As far as a realtime chat server, it would be up to you to decide how to use the existing features of Deepstream to accommodate your necessities, i.e: I would use the presence APIs to show if a user is online or offline, I can abstract the chat between two users as a list to which you keep adding messages as records, matching some existing data model you already have.

Checkout this little [hack](https://github.com/jshrt/deepstream-react-chatapp) which can provide you with some ideas on how you can use deepstream js client with React, however it would be up to your to decide how many deepstream clients you would like to have per app, and what does each client do and what not. Also, make sure you go through the documentation, I am sure you will find it straightforward and pretty simple to understand.

Good luck
