### ISSUE TITLE
deepstream v4 documentation

### ISSUE THREAD

**Issue by VRspace4** [deepstreamIO/deepstream.io#873]
Hi, is there any documentation on the new deepstream v4? How is the Universal Realtime Protocol used and how different is it compared to v3? Any tutorials or examples on how to use the v4 javascript client? 

Thanks in advance.

**Comment by yasserf** [comment]
Sorry for the massive delay on this, the work that was required was underestimated.

The client is fully backwards compatible minus listening and chaining.

New documentation can be found on new website here (will be deepstream.io again once proof read and released):

http://deepstream.io-v3.s3-website-us-east-1.amazonaws.com/

And release notes are here:

http://deepstream.io-v3.s3-website-us-east-1.amazonaws.com/releases/client-js/v4-0-0/index.html
