### ISSUE TITLE
Can't NPM install it form Git

### ISSUE THREAD

**Issue by teckays** [deepstreamIO/deepstream.io#874]
I've tried to switch to the `v4.0.0-rc.2` version and getting an error:

```
npm install --save deepstreamIO/deepstream.io#v4.0.0-rc.2
npm ERR! path /Users/ . . . /node_modules/deepstream.io/dist/bin/deepstream
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/ . . ./node_modules/deepstream.io/dist/bin/deepstream'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/. . . /.npm/_logs/2018-01-31T10_57_45_574Z-debug.log
...
verbose exit [ -2, true ]
```

Env
```
Darwin 17.3.0
node v8.7.0
npm  v5.6.0
```

**Comment by Thomas-P** [comment]
There is no post install method in the package.json, so you had to build it by your own. Do a git clone, and run `npm run tsc`. From this point it should work as a local package for your project.

**Comment by teckays** [comment]
@Thomas-P thank you. I guess that no `postinstall` is an expected/desired behavior and therefore will not be included in the final v4 release?.

**Comment by yasserf** [comment]
We will actually publish dist files with npm to work normally ideally. If you decide to branch off of master though you will need to build the project with tsc.

**Comment by teckays** [comment]
@yasserf got it, thanks!
