### ISSUE TITLE
Property libDir on the configuration object

### ISSUE THREAD

**Issue by Thomas-P** [deepstreamIO/deepstream.io#876]
Hi, 

I think the `libDir` on the configuration object isn't used anymore. There is a libDir on the global object, which I think is only set if a yaml-Loader is present or if the module is used as a command line tool.

A good way is to remove this attribute from the configuration object and provide a setter method to the yaml reader.

The default value in which is paste by the default-options is also null.

**Comment by Thomas-P** [comment]
Hi,

I think `externalUrl` is also not used anymore. Can anyone confirm that?

**Comment by yasserf** [comment]
externalUrl isn't/never was actually and can be removed.

libDir is used within the configuration file which means it has to be accepted on the configuration object. The config file in yaml is equal to the config file you would pass in with a nodeJS API

**Comment by Thomas-P** [comment]
Ah, thanks for clarification. I will check this.. 
Think the issue can be closed for the moment.
