### ISSUE TITLE
Cant get rethink plugin to work with 4 rc3

### ISSUE THREAD

**Issue by daviderenger** [deepstreamIO/deepstream.io#878]
Hi,

I'm getting this with RC3:

SUBSCRIBE | for RECORD:global/global by zINP....
TypeError: Cannot set property '__ds' of undefined
in deepstream.io-storage-rethinkdb/src/transform-data.js:33:15

Tha data that is passed to the function is a 0 (just a zero) so data is undefined after 
var data = value._d

I didnt have this problem with RC1, have not tried with RC2 but I see that there are some code that should help with legacy plugins recently pushed.

The data is in the db and looks as it should, switching to version 3 branch still works with the same data and db-connector.

I have no cache attached at the moment, just storage.

**Comment by yasserf** [comment]
Thanks for raising! Odd, it worked well with other plugins I tried but will see what the difference is.

Could it be the data in ur db is corrupt since the RC2 actually required a different API on the storage layer?

**Comment by yasserf** [comment]
will take a look. My first instinct was the db data was incorrect but that doesn't seem to be the case! Thanks for raising! I tested it with other connectors and it seemed fine.

**Comment by yasserf** [comment]
Just tested with rethinkdb and it seems fine. Can you give me the stack trace by any chance?

**Comment by daviderenger** [comment]
Maybe there is a difference how to configure the storage? Trying with:

```
plugins: {
        storage: {
          name: 'rethinkdb',
          options: {
            host: config.db.host,
            port: config.db.port,
            splitChar: '/',
            database: config.db.db,
            primaryKey: 'id'
          }
        }
      },
```

Yields the error: "Error: Cannot find module 'deepstream.io-storage-rethinkdb'\n    at Function.Module._resolveFilename (module.js:538:15)\

And I'm pretty sure that worked with RC1.

So I'm using 

```
    DeepstreamServer.set( 'storage', new RethinkDbConnector({
      host: config.db.host,
      port: config.db.port,
      splitChar: '/',
      database: config.db.db,
      primaryKey: 'id'
    }));
```

Instead, the error is:

```
6|setting  | SUBSCRIBE | for RECORD:global/global by aYbx7nvHq5T5RbuSjTAzlEUGEm4Xff0%7Kd9vVg*GMf(klSg2e
6|setting  | TypeError: Cannot set property '__ds' of undefined
6|setting  |     at Object.module.exports.transformValueForStorage (/home/david/briteback/repos/briteback-setting/node_modules/deepstream.io-storage-rethinkdb/src/transform-data.js:33:15)
6|setting  |     at Connector.set (/home/david/briteback/repos/briteback-setting/node_modules/deepstream.io-storage-rethinkdb/src/connector.js:75:34)
6|setting  |     at RecordHandler.create (/home/david/repos/deepstream.io/src/record/record-handler.ts:315:29)
6|setting  |     at RecordHandler.onPermissionResponse (/home/david/repos/deepstream.io/src/record/record-handler.ts:509:5)
6|setting  |     at PermissionHandler.canPerformAction (/home/david/briteback/repos/briteback-setting/src/permissionHandler/can-perform-action.js:45:7)
6|setting  |     at RecordHandler.permissionAction (/home/david/repos/deepstream.io/src/record/record-handler.ts:472:37)
6|setting  |     at RecordHandler.onCreateOrReadComplete (/home/david/repos/deepstream.io/src/record/record-handler.ts:159:12)
6|setting  |     at onStorageResponse (/home/david/repos/deepstream.io/src/record/record-request.ts:42:18)
6|setting  |     at services.storage.get (/home/david/repos/deepstream.io/src/record/record-request.ts:90:9)
6|setting  |     at rethinkdb.table.get.run (/home/david/briteback/repos/briteback-setting/node_modules/deepstream.io-storage-rethinkdb/src/connector.js:104:9)
6|setting  |     at tryCatcher (/home/david/briteback/repos/briteback-setting/node_modules/deepstream.io-storage-rethinkdb/node_modules/bluebird/js/main/util.js:26:23)
6|setting  |     at Promise.successAdapter (/home/david/briteback/repos/briteback-setting/node_modules/deepstream.io-storage-rethinkdb/node_modules/bluebird/js/main/nodeify.js:23:30)
6|setting  |     at Promise._settlePromiseAt (/home/david/briteback/repos/briteback-setting/node_modules/deepstream.io-storage-rethinkdb/node_modules/bluebird/js/main/promise.js:582:21)
6|setting  |     at Promise._settlePromises (/home/david/briteback/repos/briteback-setting/node_modules/deepstream.io-storage-rethinkdb/node_modules/bluebird/js/main/promise.js:700:14)
6|setting  |     at Async._drainQueue (/home/david/briteback/repos/briteback-setting/node_modules/deepstream.io-storage-rethinkdb/node_modules/bluebird/js/main/async.js:123:16)
6|setting  |     at Async._drainQueues (/home/david/briteback/repos/briteback-setting/node_modules/deepstream.io-storage-rethinkdb/node_modules/bluebird/js/main/async.js:133:10)
6|setting  |     at Immediate.Async.drainQueues [as _onImmediate] (/home/david/briteback/repos/briteback-setting/node_modules/deepstream.io-storage-rethinkdb/node_modules/bluebird/js/main/async.js:15:14)
6|setting  |     at runCallback (timers.js:789:20)
6|setting  |     at tryOnImmediate (timers.js:751:5)
6|setting  |     at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by yasserf** [comment]
I'm still not able to replicate, just ran more manual tests and it seems fine. Looked through the stack trace as well and the create call is passing in an empty object which is being transformed in the backwards compatibility wrapper to { _v: 0, _d: {} }, which means __ds can never be undefined. 

Any chance u can provide your scripts? I used snapshot, setData and getRecord

**Comment by yasserf** [comment]
I think I know the issue 'face palm'. I think its failing because I haven't checked in the dist code

**Comment by remaininlight** [comment]
I am also having a similar issue with rc1, rc2 and rc3. When I run with the code:

`var RethinkDBStorageConnector = require( 'deepstream.io-storage-rethinkdb' );`
`dsServer.set( 'storage', new RethinkDBStorageConnector( {
    port: 28015,
    host: 'localhost'
}));`
It throws error:

> AUTH_SUCCESSFUL | open
/Users/user/test-project/node_modules/deepstream.io-storage-rethinkdb/src/transform-data.js:28
    data.__ds = value
              ^
TypeError: Cannot set property '__ds' of undefined
    at Object.module.exports.transformValueForStorage (/Users/user/test-project/node_modules/deepstream.io-storage-rethinkdb/src/transform-data.js:28:15)
    at Connector.set (/Users/user/test-project/node_modules/deepstream.io-storage-rethinkdb/src/connector.js:74:34)
    at RecordHandler.create (/Users/user/test-project/dependencies/deepstream.io/src/record/record-handler.ts:315:29)
    at RecordHandler.onPermissionResponse (/Users/user/test-project/dependencies/deepstream.io/src/record/record-handler.ts:509:5)
    at RuleApplication.run (/Users/user/test-project/dependencies/deepstream.io/src/permission/rule-application.ts:111:19)
    at new RuleApplication (/Users/user/test-project/dependencies/deepstream.io/src/permission/rule-application.ts:72:10)
    at ConfigPermissionHandler.canPerformAction (/Users/user/test-project/dependencies/deepstream.io/src/permission/config-permission-handler.ts:130:5)
    at RecordHandler.permissionAction (/Users/user/test-project/dependencies/deepstream.io/src/record/record-handler.ts:472:37)
    at RecordHandler.onCreateOrReadComplete (/Users/user/test-project/dependencies/deepstream.io/src/record/record-handler.ts:159:12)
    at onStorageResponse (/Users/user/test-project/dependencies/deepstream.io/src/record/record-request.ts:42:18)
    at services.storage.get (/Users/user/test-project/dependencies/deepstream.io/src/record/record-request.ts:90:9)
    at Connector.get (/Users/user/test-project/node_modules/deepstream.io-storage-rethinkdb/src/connector.js:106:7)
    at onCacheResponse (/Users/user/test-project/dependencies/deepstream.io/src/record/record-request.ts:87:22)
    at services.cache.get (/Users/user/test-project/dependencies/deepstream.io/src/record/record-request.ts:138:7)
    at process.nextTick (/Users/user/test-project/dependencies/deepstream.io/src/default-plugins/local-cache.ts:27:30)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

Also I am having an issue similar to https://github.com/deepstreamIO/deepstream.io/issues/880 when I use the Postgres connector ie. data is persisted to disk (I can see it using another Postgres client) but then it is never loaded back into Deepstream on startup. This occurs when I use config:

> plugins:
  storage:
    name: postgres
    options:
      user: user
      database: user
      password:
      host: localhost
      port: 5432 #postgres default port
      schema: ds #schema defaults to ds. Will be created if it doesn't exist
      max: 10 #concurrent connections
      idleTimeoutMillis: 30000 #timeout after which connection will be cut
      writeInterval: 200 #amout of milliseconds during which writes will be buffered
      notifications:
        CREATE_TABLE: true #Get notified when tables are created
        DESTROY_TABLE: true #Get notified when tables are dropped
        INSERT: true # Get notified when records are created
        UPDATE: false # Get notified when records are updated
        DELETE: true # Get notified when records are deleted

I am not having much luck with either database connector, how would you recommend to persist data in the 4.0 release candidates?

**Comment by yasserf** [comment]
Thank you for that! I believe I found the issue, was specifically to do with running it via the node API. Will release another candidate. Many thanks for the detailed logs everyone!

**Comment by daviderenger** [comment]
This works for me now, thanks!
