### ISSUE TITLE
Segfault caused by calling sendPrepared on a closed socket

### ISSUE THREAD

**Issue by SejH** [deepstreamIO/deepstream.io#879]
Using deepstream.io@3.1.1

In [subscription-registry.js:_onBroadcastTimeout](https://github.com/deepstreamIO/deepstream.io/blob/v3/src/utils/subscription-registry.js#L199) I have noticed that sometimes there is a socket in the sockets array with `isClosed` set to `true`, and calling sendPrepared on that socket sometimes causes a segfault in uws.
I have also seen that in [_addSocket](https://github.com/deepstreamIO/deepstream.io/blob/v3/src/utils/subscription-registry.js#L391), sometimes a closed socket is passed and it may cause the problem? It is very sporadic and hard to replicate, but with a lot of traffic it will cause our server to restart multiple times a day.

Currently we have solved it by checking each socket in the [loop](https://github.com/deepstreamIO/deepstream.io/blob/v3/src/utils/subscription-registry.js#L197) and not calling sendPrepared on any closed sockets. This seems to solve the segfault but not the underlying problem.

**Comment by yasserf** [comment]
Closing this issue as it is most likely exposed via V3 broadcastTimeout holding onto socket references. There has been a config option added called `subscriptionsSanityTimer` which checks to see if any subscriptions are closed in the subscription registry (which means not removed).
