### ISSUE TITLE
Question re low level protocol lib

### ISSUE THREAD

**Issue by joep** [deepstreamIO/deepstream.io#882]
I'm writing a client lib for the ESP8266, ESP32 and also for Ruby. Is there a small, low level, stand alone C lib for protocol parsing and message assembly? It is a little hard to dig some of these details out of the documentation and the protocol appears to be a moving target (I started working on the text one only to realize it is apparently changing to binary with v4).

**Comment by yasserf** [comment]
Hey, there currently isn't no, the only implementation is currently in JS. However a C parser would be epic. 

The current documentation is all here:

http://urp-protocol.io/

**Comment by yasserf** [comment]
Closing this issue, but if you happen to still be interested in this I would *love* to collaborate!
