### ISSUE TITLE
Snapshot always yields RECORD_NOT_FOUND with v4 RC4

### ISSUE THREAD

**Issue by daviderenger** [deepstreamIO/deepstream.io#887]
Hi again @yasserf, with the RC4 of v4 I'm getting RECORD_NOT_FOUND for all snapshots, changing to getRecord with exactly the same record name works. Nothing more in the logs even with debug logLevel, just record not found directly.

If I first do a getRecord, wait for it to be ready and then a snapshot it works but it never works alone!

/David

**Comment by yasserf** [comment]
Hey, thats odd! Will look into ASAP. Many thanks for providing such valuable feedback on v4!

**Comment by yasserf** [comment]
So I tested this with http://test.deepstream.io/v4/ and also looked through our E2E and unit tests (Which cover this scenario multiple times) and I can't seem to replicate again. Could you provide some more detail on your cache and storage and how you initialise it?

**Comment by daviderenger** [comment]
I don't have any cache enabled and use rethinkdb as described in issue #878, not with plugins: since I can't get it to work but with set(). I'm not close to a computer right now but I can look at it later tonight again and do some debugging to see where it goes wrong.

I'll also noticed that some records I had where reseted to version 0 and no data at all (written to db). Don't know if it is related but it might.

**Comment by daviderenger** [comment]
Comment on the reseted record. It was the record I tried to do a snapshot of that was reseted in the db to version 0

**Comment by daviderenger** [comment]
Closing in favor of #889
