### ISSUE TITLE
Make requestorName and requestorData configurable seperatly

### ISSUE THREAD

**Issue by daviderenger** [deepstreamIO/deepstream.io#888]
Hi, the feature to send requestorName to RPC providers is great! With that we can skip our hacky approach of injecting it to the bare message!

requestorName is very useful for us but requestorData is not useful at all and it is fairly big. We use it to send a lot of bootstrap data to the client. Before the API settles completely do you think its possible to have two options instead of provideRPCRequestorDetails, like:

provideRPCRequestorName
provideRPCRequestorData

maybe?
This will of course work for us too as it is now but there will be a lot of traffic that is of no use and a lot of data stuck on the socket using memory.

Also this:
socketWrapper.clientData = userData.clientData
Should probably not be set if the option provideRPCRequestorDetails is false.

Regards
David

**Comment by yasserf** [comment]
Hey David, yeah that makes alot of sense! The other option might be to do it on a per request state

```
rpc.provide('rpc-name', () => {}, { requestorName: true, requestorData: true })
```

Which can allow for better granularity and permissions going forward. What do you think?

**Comment by daviderenger** [comment]
Yeah that would be even better, then we csn skip it for all internal server to server rpcs!
