### ISSUE TITLE
Link for downloading the Windows binary does not work

### ISSUE THREAD

**Issue by dpisarenko** [deepstreamIO/deepstream.io#893]
Steps to reproduce:

1. Go to the page [Installing on Windows](https://deepstreamhub.com/open-source/install/windows/).
2. Click on the link above the lettering *Download the server from the link above and unzip it.*
3. Expected behavior: Download of the MSI file starts. Actual behavior: Nothing happens (at least I can't see anything).

It also looks suspicious that the link is just an empty space surrounded by a blue border.

![Screenshot](https://i.imgur.com/uMrc39j.png)

Chrome complains about some unsafe scripts (downloaded from a not trustworthy source).

I couldn't find any errors in the JavaScript console in Chrome.

**Comment by RefinedSoftwareLLC** [comment]
The page "https://github.com/deepstreamIO/deepstream.io/releases" does not have a deepstream.io-windows-3.1.5.zip file. I think the best solution is to update "https://deepstreamhub.com/open-source/install/windows/" to detect if newest version (3.1.5) doesn't have a windows download and show the lastest avaliable download for windows (3.1.4).

**Comment by yasserf** [comment]
Unfortunately windows with node 10 builds is giving us grief #935 

Tagging this as a website fix
