### ISSUE TITLE
INVALID_MESSAGE_DATA

### ISSUE THREAD

**Issue by rahil471** [deepstreamIO/deepstream.io#894]
`error: Deepstream client Error error=true, msg=unable to patch record data on hot path, event=INVALID_MESSAGE_DATA, topic=R`

I'm facing the above error, kindly help with resolution. 

`client.record.setData(recordName, key, data.toString());`

data is a number stored as string.

**Comment by rahil471** [comment]
Okay. 
But this is coming for records not added to hotPathPrefix.

**Comment by rahil471** [comment]
```
broadcastTimeout: 2
# A list of prefixes that, when a record is updated via setData and it matches one of the prefixes
# it will be permissioned and written directly to the cache and storage layers
storageHotPathPatterns:
  - book/
  # - metrics/
EOF
```

Record names that are giving the above error `ticker/BTC-INR`, `ticker/XRP-INR` and so on.
Version `3.2.3` `enterprise`

**Comment by rahil471** [comment]
Hi @yasserf  any solution to this? 

To give you a bit more of a context. 

I'm was updating the records using the standard way, basically getTherecord, wait for it to ready, set the attribute.  Check the code below. 

```
Deepstream.prototype.updateTickers = function(recordName, key, data){
    var self = this;
    const record = self.client.record.getRecord(recordName);
    if(!data && data !== 0){
        logger.warn('Not updating ticker as no data', {data:data, key:key});
        return;
    }
    record.whenReady(record=>{
        record.set(key, data.toString());
//        logger.info('Updated Ticker', { record: recordName, key: key, data: data});
    });
}
```
Also, above should I do record.discard after setting the data? 

But what is happening is, sometimes some of the records stop updating, I don't have any details on why they don't update. I only assumed that carrying out the above 3 steps is putting unnecessary load on deepstream (and hence the updates stop). The frequency of updates is like 5-6 updates/sec.

So there is no need for me to actually read the record and then update it, all I can do it directly write the data to whatever attribute is updated within the record. This is when I changed the above code to look like this. 

```
client.record.setData(recordName, key, data.toString());
```

But unfortunately, it's giving me and update error. 
```
error: Deepstream client Error error=true, msg=unable to patch record data on hot path, event=INVALID_MESSAGE_DATA, topic=R
```

And as I told you above I have not added it to `storageHotPathPatterns`

**Comment by yasserf** [comment]
hello @rahil471 

Sorry for the long delay. What you done generally makes sense and I can't seem to reproduce locally.

> Also, above should I do record.discard after setting the data?

If you need to do that you use of the api:

> client.record.setData(recordName, key, data.toString());

is much more performant

**Comment by yasserf** [comment]
Can't replicate this =(, if the setData doesn't work please let me know.
