### ISSUE TITLE
Perf benefit to keeping subscription count low?

### ISSUE THREAD

**Issue by TimMun** [deepstreamIO/deepstream.io#897]
Hi, I’m building a chat app where messages can sometimes be reported/upvoted, and I need to show the votes as they happen.

Currently I have two Lists, one called `messages` where the client only takes a snapshot of each message Record in the list, and the second list called `messageSubs` where the client subscribes to each Record in that list. All messages are always added to `messages`, and copied to `messageSubs` when they get voted on (`messagesSubs` is always a subset of `messages`). That way the client will only subscribe to messages that change votes. I expect the majority of messages won’t be voted on and therefore don’t need to be subscribed to.

What I’m wondering is, is there any real performance/reliability benefit in keeping the subscription count low? I did this because seemed wrong to have to client subscribe to every single Record. However if there only negligible benefit, I may just get rid of `messageSubs` and have the client subscribe to all messages.

**Comment by slachtar** [comment]
Hello,
Could you tell us how many messages and clients are expected to be handled?
Regards

**Comment by TimMun** [comment]
The app hasn't launched yet, so these are all estimates; just trying to figure if there's any benefit to managing the lists one way or the other. There will be many chat Rooms (possibly into the hundreds, but let's say I want to handle 300 rooms). I'd expect maybe 30 clients per room, and each room holds 50 messages; of which maybe 5-10 messages may need to be subscribed to. In other words, with the current implementation a single client takes a snapshot of 50 message Records and subscribes to ~5 of those message Records. I'm wondering whether this is actually any better than simply having the client subscribe to all 50 messages.

**Comment by yasserf** [comment]
The logic in the server does loop over subscriptions, however it has been optimised massively by us and other OS contributors and so shouldn't make a massive different. The only two issues is when a client disconnects we have to cleanup all the subscriptions and when they connect we have to run each individual one through permissions. I know this is a bit late of a response but it's a really good question!
