### ISSUE TITLE
Kafka messaging connector

### ISSUE THREAD

**Issue by thedrow** [deepstreamIO/deepstream.io#90]
For high scale deployments Kafka would be really really useful.
I don't know node js enough to contribute this so I'm opening an issue in hope that this will be implemented when I'll need it.

**Comment by yasserf** [comment]
Promising Kafka adaptor [created](
https://github.com/AlexBHarley/deepstream.io-msg-kafka) by @AlexBHarley. Needs a bit of a readme, tidying up and it should make it into the official adaptor set.
