### ISSUE TITLE
Ubuntu 18.04 LTS package not working + no proper removal script

### ISSUE THREAD

**Issue by mpathy** [deepstreamIO/deepstream.io#901]
This is what I get, when I install the deepstream package on Ubuntu 18.04 LTS (the current Ubuntu LTS version, available since April 2018)

```
$ sudo apt-get install -y deepstream.io

Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden NEUEN Pakete werden installiert:
  deepstream.io
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 15,5 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 45,1 MB Plattenplatz zusätzlich benutzt.
Holen:1 http://dl.bintray.com/deepstreamio/deb bionic/main amd64 deepstream.io amd64 3.1.3 [15,5 MB]
Es wurden 15,5 MB in 14 s geholt (1.097 kB/s).                                                                                        
Vormals nicht ausgewähltes Paket deepstream.io wird gewählt.
(Lese Datenbank ... 193815 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../deepstream.io_3.1.3_amd64.deb ...
Entpacken von deepstream.io (3.1.3) ...
deepstream.io (3.1.3) wird eingerichtet ...

$ deepstream
Error: No such module: uws_builtin
    at native ([eval]:697:28)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.237.../../constants/constants ([eval]:47938:13)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.236.../../constants/constants ([eval]:47209:23)
    at o ([eval]:1:265)
    at [eval]:1:316
{ Error: Cannot find module './uws_linux_57'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at o ([eval]:1:125)
    at [eval]:1:316
    at native ([eval]:699:20)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316 code: 'MODULE_NOT_FOUND' }
[eval]:710
            throw new Error('Compilation of WebSockets has failed and there is no pre-compiled binary ' +
            ^

Error: Compilation of WebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native ([eval]:710:19)
    at Object.11.events ([eval]:714:3)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.237.../../constants/constants ([eval]:47938:13)
    at o ([eval]:1:265)
    at [eval]:1:316
    at Object.236.../../constants/constants ([eval]:47209:23)
    at o ([eval]:1:265)
    at [eval]:1:316
```

It also prevents the deinstallation of the package, with the same error.

Please provide a working package for Ubuntu 18.04 LTS, or at least provide a prerm (pre removal) script that doesnt break if deepstream doesnt work. You should check in this file, if it runs and only stop it, if it does. 

Or otherwise after a deepstream stop, check if it is now closed, because that would also help in this case, because it never ran, because the package wasnt working.

**Comment by nishant-newton** [comment]
I am also having same issue. Looking for a solution from deepstream. Its been a while Ubuntu 18.04 is available and deepstream should have been working on it properly

**Comment by davidmoshal** [comment]
+1

**Comment by yasserf** [comment]
You can run deepstream directly on any flavour of linux (I think) using the .tar.gz release.

In order for me to get the distros working correctly I'll need to figure out how to compile nodejs with uws compatible flags on each linux arch which isn't my speciality (fun, but cpp compiler compatibility packages are not well documented and uws has a (fair enough) - not standard? not fixing - approach).

Heads up, I might also drop the packaging on each distro because the usage rates are abysmal, not worth the time vs other options and also because accordingly to some reviewers installs things in the totally incorrect place on the system.

Generally thinking of having a very basic two line script that creates a deepstream directory in the /opt mount, downloads the latest deepstream and sets up the linux scripts using `deepstream service install`. Would that satisfy your use case?

**Comment by yasserf** [comment]
I will be dropping the rpm and debian installs in favour or installing via a basic 

```
curl -o deepstream-url
tar -xzf deepstream-artifact
./deepstream service install
```

So much hassle otherwise, plus I have no idea where to install things to.
