### ISSUE TITLE
3.1.4 for mac?

### ISSUE THREAD

**Issue by brianmorton** [deepstreamIO/deepstream.io#902]
![image](https://user-images.githubusercontent.com/1434096/42191913-52519120-7e1a-11e8-8a86-be12716cad9a.png)

Will there be a binary released?

**Comment by brianmorton** [comment]
Thanks for the reply.

I am trying to maintain this for homebrew. We will obviously have to stay on 3.1.3 until a binary is for 3.1.4 or later is released :)

**Comment by yasserf** [comment]
Thank you! I'll try to get it done asap. If anyone has an older version of
osx maybe they could run the build? It's pretty simple and takes around
20minutes to get the artifact 😅😁

**Comment by brianmorton** [comment]
I'm on high sierra - I'll have a look at the build docs and see. If I end up with a binary, how would I get it to you?

**Comment by brianmorton** [comment]
This likely isn't happening for me unless you have an easy way to switch back to node 6.14 - not willing to risk mucking up my current environment!

**Comment by brianmorton** [comment]
```
$ ./scripts/package.sh v3.1.4
[...]
Creating 'build/deepstream', this will take a while...
Compiling deepstream... (1 SECONDS)....> WARNING: src/node.js doesn't exist. Trying 'lib/internal/bootstrap_node.js'
Compiling deepstream... (2 SECONDS)gyp: undefined not found (cwd: /private/tmp/dsio/nexe_node/node/6.14.3/node-v6.14.3) while trying to load undefined
Compiling deepstream... (12 SECONDS)In file included from ../src/async-wrap.cc:1:
In file included from ../src/async-wrap-inl.h:7:
In file included from ../src/base-object-inl.h:7:
In file included from ../src/env-inl.h:6:
In file included from ../src/env.h:7:
In file included from ../src/debug-agent.h:27:
In file included from ../src/node_mutex.h:4:
../src/util.h:21:10: fatal error: 'tr1/type_traits' file not found
#include <tr1/type_traits>  // NOLINT(build/c++tr1)
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [/private/tmp/dsio/nexe_node/node/6.14.3/node-v6.14.3/out/Release/obj.target/node_lib/src/async-wrap.o] Error 1
make: *** [node] Error 2
....> ERROR: The release executable has not been generated. This indicates a failure in the build process. There is likely additional information above.
```

**Comment by yasserf** [comment]
Got this working by rolling back. Will work in next update!

**Comment by brianmorton** [comment]
Cool, thanks for the hard work and keeping this updated. Let me know when its released (here), and then I'll link the update PR and close the issue.

**Comment by daveoon** [comment]
I have deployed by compiling a docker version, you can pull from my repo at daveoon/deepstream:3.1.4

hope this helps

**Comment by brianmorton** [comment]
@daveoon unless there is an official public download url, I'm afraid that won't fall into the guidelines for  [homebrew](https://github.com/Homebrew/homebrew-cask)

**Comment by dmundy2** [comment]
Hey, any update on getting this into Brew?

**Comment by brianmorton** [comment]
@dmundy2 until this ticket is updated with an official public download URL of the binary, it won't be added to brew.

**Comment by yasserf** [comment]
hello!

Sorry for not updating this, I have been swamped trying to get V4 done since theres an overhaul of alot of things back to OS land.

Good news is V4 is literally almost publishable, I just need to write an upgrade guide and a whole lot of documentation around new features. Any chance your still using deepstream and happy to update brew in a weeks time with the official release?

thanks!

**Comment by brianmorton** [comment]
@yasserf if you're providing a binary, then yes. if i have to build it, then no :)

**Comment by yasserf** [comment]
Will provide an official artefact! Build is mostly up and running again.
Thanks!

**Comment by yasserf** [comment]
Will update this issue once an official V4 binary is out. Thanks again!
