### ISSUE TITLE
want to have user presense from http

### ISSUE THREAD

**Issue by shravanthanvi** [deepstreamIO/deepstream.io#907]
Hi 

Want to check if the particular user is logged or not using presense using http api. 

regards

**Comment by shawub** [comment]
According to the documentation you can do this.  Never tried it myself https://deepstreamhub.com/docs/http/v1/#querying-online-users-presence-

**Comment by shravanthanvi** [comment]
this will get me all the users. Now if i want to check for a particular user how to do it

**Comment by jaime-ez** [comment]
Solved in v5.2.2
