### ISSUE TITLE
How to identify the no. of rpc providers?

### ISSUE THREAD

**Issue by KrishnaPG** [deepstreamIO/deepstream.io#908]
Is there anyway to identify how many rpc providers are currently active for a given rpc method?

In other words, is there a meta API for deepstream to track the rpc providers, as they get online and offline?

**Comment by yasserf** [comment]
Hey Krishna, 

There isn't no, but this is something that can go on the V4 roadmap as we have a bunch of new actions for this sort of thing.

Why would you need this feature?

**Comment by KrishnaPG** [comment]
Thanks @yasserf 

This is for Orchestration, so that a central monitoring agent can
- scale the number of providers up or down based on the pending volume of tasks (or turn around time)
- to relay any pending tasks waiting for the provider to come online

For example, we have scenarios where a client may make a request and provider may not be online at that time. The monitoring agent will catch that pending job, and when the provider comes back online will relay that job to it, posting the results back to the caller with a hook.

**Comment by yasserf** [comment]
Small update, this will be included in the 4.1 release

**Comment by KrishnaPG** [comment]
Great. Thank you @yasserf . Wondering what the semantics would be. The DS server would be maintaining the meta state, and clients has to `poll` that information, or would it be more like events raised by the server whenever a provider comes online and goes offline. A combination of both would be great, since in distributed systems it is very easy to miss the events (timing issues).

**Comment by yasserf** [comment]
It will be using a monitoring API, so probably something similar to (completely up in the air:

`deepstream.monitoring.subscribe(
  topic: TOPIC, 
  options: { name?: string, ... }, 
  callback: (error: null | string, ) => {})
)`

`const results = await deepstream.monitoring.snapshot(
    topic: TOPIC, 
    options: { name?: string, ... }, 
    callback: (error: null | string, ) => {})
)`

Depending on how granular we want things. I will open an epic to include these where we can have some discussions 👍

**Comment by yasserf** [comment]
Update: The releases have reshuffled a bit, monitoring was going to be a big epic but it has now been separated into two parts. One part is in 4.0 (monitoring plugins) and also a monitoring scaffold, however there hasn’t been any implementation of a WS spec around it since you can expose the information currently via a custom HTTP monitoring plugin if required.

Having a monitoring API is generally a great thing but need to flesh out some more useful cases before writing it down.

4.1 was focused on old ask protocols and 4.2 will be mqtt.

**Comment by yasserf** [comment]
Okay the way this work now is basically adding a custom plugin. Worked on making sure its a minimal amount of code.

```
export const GetRPCCountPlugin extends DeepstreamPlugin {
  constructor (options: any, private services: DeepstreamServices) {}

  init () {
    this.services.httpService.addGetPrefix('/rpc-count', (metaData: {}, response: DeepstreamHTTPResponse) => {
        response(null, {
          count: this.services.clusterStates.getStateRegistry(TOPIC.RPC).getAll().length
        })
    })
  }

  async whenReady () => {
    await this.services.httpService.whenReady()
  }
}
```
