### ISSUE TITLE
Proprietary protocol makes it harder to write clients

### ISSUE THREAD

**Issue by thedrow** [deepstreamIO/deepstream.io#91]
There's more complexity to grasp on how deepstream works internally so implementing clients becomes harder.
Can't we just use msgpack and get along? It has implementations all over the place and it's blazingly fast. Probably much faster than what you guys implemented.

**Comment by WolframHempel** [comment]
Please find more background on why we choose to go with an even simpler and faster protocol than messagepack here: https://github.com/deepstreamIO/deepstream.io/issues/35
