### ISSUE TITLE
Combine authentication strategies in config.yml

### ISSUE THREAD

**Issue by ahmadsholehin** [deepstreamIO/deepstream.io#922]
Documentation says that authentication strategies **can be combined** (https://deepstreamhub.com/docs/general/authentication/), but I haven't figured a way on how to enable this in the server's config.

How would one enable this?

**Comment by yasserf** [comment]
This can’t be done out of the box, and requires you to write a combination plunging to do so. I’ll keep this open as a feature request since it might make sense to have internally!

**Comment by yasserf** [comment]
I'm just going to cover this in a tutorial since its going to be quite hard to provide configuration for  otherwise.

**Comment by yasserf** [comment]
This has now been added into V4 🎉
