### ISSUE TITLE
Cannot read property 'on' of null

### ISSUE THREAD

**Issue by rexuslexus** [deepstreamIO/deepstream.io#923]
I am getting the following error when trying to configure rethinkdb as a storage provider.

INFO | library directory set to: /var/lib/deepstream
[eval:51580
    if (typeof this._dependency.on !== 'function' && typeof this._dependency.isReady === 'undefined') {

TypeError: Cannot read property 'on' of null

If I remove or comment out the storage plugin lines, deepstream starts without issue. I am attempting to point the storage provider to a separate VM where rethinkDB is running.

Thanks

**Comment by yasserf** [comment]
Hello! Is this still an issue? I can't reproduce it locally
