### ISSUE TITLE
Send random bytes crash server

### ISSUE THREAD

**Issue by phmasters** [deepstreamIO/deepstream.io#924]
When send  random bytes trough RPC call, it crashes the server.
the problem resides in message-processor.js

the line 54 must be placed after line 65 to prevent the problem. I'll do a pull request, but dont have the time now.

Thx

**Comment by rzhade3** [comment]
Hi @phmasters, have you been working on this? If not, I can submit a PR to fix this issue.

**Comment by yasserf** [comment]
Thanks for the fix 😁
