### ISSUE TITLE
Segfault on improper disconnect?

### ISSUE THREAD

**Issue by alexiri** [deepstreamIO/deepstream.io#926]
I'm seeing relatively regular segfaults in the latest version of deepstream, and now I've found a way to replicate it pretty easily.

1. Clone https://github.com/bertyhell/deepstream.io-client-UI
2. npm install inside the repo
3. Open a web browser (I tested with Chrome) to the UI page
4. Connect to a deepstream server
5. Reload the page and watch the server core dump

I guess the client is doing something the server doesn't like and it crashes, but that shouldn't happen.

I've attached one of my core dumps here, but I'm not quite sure what to do with it without any debug data.

https://www.dropbox.com/s/b9jd3fde206cznm/deepstream.29.core?dl=0

Here's an strace of the crash:

```
epoll_wait(3, [], 1024, 200)            = 0
epoll_wait(3, [], 1024, 200)            = 0
epoll_wait(3, [], 1024, 85)             = 0
epoll_wait(3, [], 1024, 115)            = 0
epoll_wait(3, [], 1024, 200)            = 0
epoll_wait(3, [], 1024, 200)            = 0
epoll_wait(3, [{EPOLLIN, {u32=25, u64=25}}], 1024, 200) = 1
recvfrom(25, "\210\202\236\274\341m\235U", 307183, 0, NULL, NULL) = 8
setsockopt(25, SOL_TCP, TCP_CORK, [1], 4) = 0
write(17, "CLIENT_DISCONNECTED | null\n", 27CLIENT_DISCONNECTED | null
) = 27
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x83726} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault
```

I'm running deepstream v3.1.5 in a docker container, connected to Redis and Postgres.

Anything else I can do to help diagnose this further? This is a pretty big issue...

**Comment by yasserf** [comment]
I wasn’t able to replicate this locally. Any chance you can try with latest releases as it uses a different uws library under hood

**Comment by alexiri** [comment]
Sorry, I'm no longer using Deepstream so I'm unable to test this. I just saw #927, though, maybe that fixed this issue.

**Comment by yasserf** [comment]
Sorry to hear =(

**Comment by yasserf** [comment]
Sorry to hear =(
