### ISSUE TITLE
Already Logged In

### ISSUE THREAD

**Issue by aila-cherim** [deepstreamIO/deepstream.io#929]
Hi, how can i know if my android ds client is already logged in without calling again the login method?

Thanks.

**Comment by aila-cherim** [comment]
Hello, thanks for response.
In android i have available only getAll() method deepstreamClient.presence.getAll() and is returning a string array with these values DSClient/DS Client and GraphQLServer/GraphQL Server. 

Can you give me an example how to retrive if is logged in or not?

Thank  you.

**Comment by slachtar** [comment]
Hello,
I don't have too much knowledge about android client, but I guess there's a isLogged like attribute in the dsclient object, try to enumerate all attributes of dsclient object.

Sorry, if I can't help here.

in javascript to receive an event each time a user logs in:
dsclient.presence.subscribe((username, isLoggedIn) => {}....

**Comment by yasserf** [comment]
Presence actually only tells you the status of the other connections and not your own.

It seems the Java SDK doesn't support getConnectionState. I'm looking for someone to partner on writing a Kotlin lightweight SDK with the binary parser but will not be doing that until so =(

You can solve your issue however by doing the following:

https://deepstreamhub.com/docs/client-java/DeepstreamClient/#addConnectionChangeListener(listener)

```java
client.addConnectionChangeListener(new ConnectionStateListener() {
    @Override
    public void connectionStateChanged(ConnectionState connectionState) {
        // handle change
    }
});
```

If the connection state is OPEN it means your connected 👍 

Sorry for late reply
