### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by aila-cherim** [deepstreamIO/deepstream.io#930]
Hello,

Please tell me what should i do to see this error message "Your message timed out because you're not authenticated. Have you called login()?" ?

Thanks.

**Comment by valentinvichnal** [comment]
Hello, check the auth part in your `config/config.yml`
By default there is no auth and deepstream server enable every client that authenticates with empty data.
You must call the login() function before trying to call RPC functions or access records.

This may help you: https://github.com/deepstreamIO/deepstream.io/issues/928
