### ISSUE TITLE
versions >= 3.2 do not work on windows

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io#935]
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Project\server\bin\deepstream.js ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at Object.<anonymous> (C:\Project\server\deepstream\deepstream.exe:322:30)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at _third_party_main.js:37:36
    at NativeModule.compile (internal/bootstrap/loaders.js:362:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:174:18)
    at internal/bootstrap/node.js:249:22
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at internal/bootstrap/node.js:249:22
```

**Comment by yasserf** [comment]
Can you provide a bit more context please?

**Comment by layanto** [comment]
All I did was run deepstream daemon which worked previously with 3.1.5.

**Comment by yasserf** [comment]
Ah that’s probably based around our bundling mechanism changing.

Will create a release again to fix that. For now you can use deepstream
start on your development environment

**Comment by layanto** [comment]
Running deepstream start I get:
```
Error: This version of µWS is not compatible with your Node.js build.
```
I am running node v10.15.0

**Comment by yasserf** [comment]
How you running it?

**Comment by yasserf** [comment]
Node / deepstream exe / operating system?

**Comment by layanto** [comment]
"deepstream.exe start" on Windows 10 1809 with node v10.15.0. Prior to deepstream v3.2.1, I was running deepstream with "deepstream.exe daemon".

**Comment by yasserf** [comment]
I wonder if the new version of uws is windows compatible 🤭. I’ll need to
change CI to rent ests on windows as well. If it isn’t then it’s a much
bigger issue 😅

**Comment by yasserf** [comment]
Seems it is windows compatible and now need to see if it’s a compilation issue from nexe

**Comment by yasserf** [comment]
So I haven't been able to get windows building on my machine, and it times out on CI. I'm not sure why but it seems the nexe build might be slightly different from the node compilation, likely toolset wise, and uWS states it doesn't support non official builds so I can chase it up there.

For now I will not be supporting windows =(, until I get some time and a well performing VM or access to a windows machine.

**Comment by yasserf** [comment]
Got a slightly more powerful macbook pro so will try my luck again with installing windows on virtual box
