### ISSUE TITLE
Auth request not working when using file-based authentication.

### ISSUE THREAD

**Issue by miiga** [deepstreamIO/deepstream.io#937]
Close please

**Comment by yasserf** [comment]
This should now be fixed 👍

**Comment by slachtar** [comment]
I'm facing the same issue with deepstream.io-windows-4.0.5-bd6d16fb
I've file based auth, logging from js client works fine.
using curl to authenticate, doesn't work,
it says: Unsuccessful authentication attempt.

here's the curl query:

`url.exe -X POST http://127.0.0.1:8080 -
H 'Content-Type: application/json' -d '{ \"body\": [{\"type\": \"email\", \"username\": \"jtapi\", \"password\": \"passw
ord\"}] }'`

**Comment by slachtar** [comment]
solved: we need to add the authData:{"username":username, "password":pass} with every http call and in same level than body.

**Comment by yasserf** [comment]
you can use the 'auth' endpoint, but it would require a custom auth endpoint that returns a token / stores it in a cache / checks it on each response.
