### ISSUE TITLE
NPM error while installing version 2.4.0

### ISSUE THREAD

**Issue by obsd** [deepstreamIO/deepstream.io#938]
Package.json
    "deepstream.io": "2.4.0",
    "deepstream.io-client-js": "2.3.0",

Error:
npm install
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t https://github.com/deepstreamIO/uws-dependency.git
npm ERR!
npm ERR! remote: Repository not found.
npm ERR! fatal: repository 'https://github.com/deepstreamIO/uws-dependency.git/' not found
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2019-03-17T15_34_19_844Z-debug.log

Let me know if you need anything else..

**Comment by yasserf** [comment]
Release 2.4.1 which now uses the more recent latest version of uws.

Are you using still on 2.4 due to clustering?

**Comment by amitkverma** [comment]
Yes
