### ISSUE TITLE
DS Server is not forwarding the client headers in connectionData to the HTTP Auth Webhook

### ISSUE THREAD

**Issue by marosygabor** [deepstreamIO/deepstream.io#939]
Until version 3.1.5 the deepstream server forwarded the `headers` (sent by the client during login) to the http auth webhook. Using the newer versions, the `headers` are empty and an empty  `referer` property appeared.

Object received by the auth webhook (ds server version 3.1.5) - expected value:
```json{
  "connectionData": {
    "remoteAddress": "127.0.0.1",
    "headers": {
      "host": "localhost:6020",
      "connection": "Upgrade",
      "pragma": "no-cache",
      "cache-control": "no-cache",
      "upgrade": "websocket",
      "origin": "http://localhost:8000",
      "sec-websocket-version": "13",
      "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "hu-HU,hu;q=0.9,en-US;q=0.8,en;q=0.7",
      "cookie": "sso.token=********; io=********",
      "sec-websocket-key": "********==",
      "sec-websocket-extensions": "permessage-deflate; client_max_window_bits"
    }
  },
  "authData": {
    "role": "user",
    "credentials": {
      "username": "anonymus",
      "password": "********"
    }
  }
}
```

Object received by the auth webhook (ds server version 3.2.2):
```json
{
  "connectionData": {
    "remoteAddress": "127.0.0.1",
    "headers": {},
    "referer": ""
  },
  "authData": {
    "role": "user",
    "credentials": {
      "username": "anonymus",
      "password": "********"
    }
  }
}
```

**Comment by yasserf** [comment]
Thanks for raising, yeah there is a new config option however it doesn’t
seem to work as expected. We would need to explicitly specify the headers
we want to pass on. There will be a release shortly to fix it, working on
parallel on getting V4 out as making changes in two code bases is very time
consuming!

**Comment by yasserf** [comment]
Hello,

This should be fixed now, be great if you can confirm.

Thanks,
Yasser

**Comment by marosygabor** [comment]
Thanks for the update. Shall I test it with the new config options?

**Comment by yasserf** [comment]
Yup! You need to specify the headers you want to copy within the connection endpoints

**Comment by marosygabor** [comment]
I confirm that the issue is resolved, this did the trick: 
`const server = new Deepstream({ connectionEndpoints: { websocket: { options: { headers: ['cookie'] } } } });`
Thanks :)
