### ISSUE TITLE
Error When Visiting Deepstream.io Website

### ISSUE THREAD

**Issue by deniskrop** [deepstreamIO/deepstream.io#943]
Is there anything questionable about this project, or is my ISP messing with my DNS-over-TLS because, or is your website broken? Because Firefox is telling me https://deepstream.io is insecure to visit. First time I'm checking out this project btw.

![sus](https://httpsimage.com/v2/310369fe-3e56-4908-a709-0e1a37763edd.png)

![investig8](https://httpsimage.com/v2/3cd37637-f154-4bf3-8f6c-9cd62c965c51.png)

Please let me know asap if this website is/isn't working for you so I know if I need to investigate my connection ASAP. Thanks (:

**Comment by yasserf** [comment]
Thanks for raising! We had an expired SSL cert on the opensource website which redirects to deepstreamHub open-source section. Updated it!

**Comment by yasserf** [comment]
Is this fixed? Our website is hosted on deepstreamHub.com and deepstream.io
cert expired and was just updated
