### ISSUE TITLE
Use existing http or express server instead of a new one

### ISSUE THREAD

**Issue by bkniffler** [deepstreamIO/deepstream.io#95]
Hey,
Currently deepstream opens its own http server on its own port, would it be possible to for example use an existing express http server and make deepstream use that instance?

**Comment by yasserf** [comment]
Hey, yep, this is currently being worked on and will be in the next release. See #87 for details

**Comment by bkniffler** [comment]
Ah, sorry, I missed that! Thanks for the hint.
