### ISSUE TITLE
deepstream behave unexpectedly

### ISSUE THREAD

**Issue by raushansingh629** [deepstreamIO/deepstream.io#953]
I am using deepstream server(docker images) and using rethinkdb(docker image) as storage. i restart the rethinkdb docker and try to set the record  from deepstream client(record.set()). it's showing error like "storage:ReqlDriverError: Connection is closed."  on both side(deepstream client and server).
 
but when i restart the deepstream docker also,then it working fine. 
why deepstream is behave like this?
  i configured deepstream wrong ? or it's bug in deepstream.

**Comment by yasserf** [comment]
Added `exitOnPluginError` to V4 settings. This will force deepstream to close whenever an error in a plugin occurs.

It's not exactly graceful but it solves alot of problems 👍
