### ISSUE TITLE
Is it possible to access server data (user.data) from client.presence.subscribe?

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io#954]
Possible use case to log in database event of user logged on and logged off and additional information (other than just username) from server data can be useful.

But for logged off, depending on whether this event triggers before or after the user is actually logged off deepstream, maybe server data for the user is already lost?

**Comment by yasserf** [comment]
So I would suggest something like the following.

- Add a custom plugin that listens to connection events
- Emit an event with the data you want

```
export default YourPlugin extends DeepstreamPlugin implements ConnectionListener {
  constructor (options: any, services: DeepstreamServices) {
  }
  
  onClientConnected (socketWrapper: SocketWrapper) {
    // log via a HTTP API, log something specific via DS
  }

  onClientDisconnected (socketWrapper: SocketWrapper) {
    // log via a HTTP API, log something specific via DS
  }
}
```

Generally we want to keep the surface area of the API really small. However, you can always cheat and post a HTTP command to the server to emit an event with the data you care about! That way your backend services will get the event.

**Comment by yasserf** [comment]
Closing this issue as it won't be implemented in core
