### ISSUE TITLE
"DeepstreamServer is not a constructor" error after upgrading to @deepstream/server v4

### ISSUE THREAD

**Issue by KrishnaPG** [deepstreamIO/deepstream.io#958]
After installing v4 rc8, and changing the module loading line from
````
const DeepstreamServer = require('deepstream.io');
```` 
to 
````
const DeepstreamServer = require('@deepstream/server');
````
the below code (which used to work fine in v3) started to give error. 
````
const server = new DeepstreamServer(serverConfig);
````
Error:
````
TypeError: DeepstreamServer is not a constructor
    at Object.<anonymous> (deepstream\src\index.js:116:16)
    at Module._compile (internal/modules/cjs/loader.js:685:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
````
The example code in [docs](https://deepstream.io/install/npm/index.html) (shown below) also faces the same problem.
````
const DeepstreamServer = require('@deepstream/server')
const server = new DeepstreamServer({ host: 'localhost', port: 6020 })
````

After verifying the code of the `@deepstream/server` npm package, it turns out `module.exports` is not defaulting to the `Deepstream` class in v4. In the earlier verion [here](https://github.com/deepstreamIO/deepstream.io/blob/3.5.2/src/deepstream.io.js#L29) it was marked as default export.

### Fix
Either the `Deepstream` class should be marked as the [default](https://github.com/deepstreamIO/deepstream.io/blob/v4/src/deepstream.io.ts#L40), or example code should be modified to use something as below:
````
const DeepstreamServer = require('@deepstream/server')
const server = new DeepstreamServer.Deepstream({ host: 'localhost', port: 6020 })
````

**Comment by yasserf** [comment]
hey!

Yeah that makes sense, we use destructing everywhere now but will make that change for backwards compatibility 👍

**Comment by yasserf** [comment]
This has been fixed in one of the previous RC releases. Thanks again for raising!

**Comment by yasserf** [comment]
Actually this is still an issue if you use require instead of Import

**Comment by yasserf** [comment]
I'm just going to have to mark this as a backwards compatibility issue!

**Comment by yasserf** [comment]
done

**Comment by KrishnaPG** [comment]
Thank you. So, is this fixed, or just marked as known issue (breaking change) ?

**Comment by yasserf** [comment]
Marked as a broken in release notes
