### ISSUE TITLE
Is deepstream(Enterprise) still running?

### ISSUE THREAD

**Issue by pgroot** [deepstreamIO/deepstream.io#977]
I emailed them twice but received no reply. and then I phoned them many times, although the number can be gone through, but still nobody answered. So, does anyone can help me to know the deepstream (Enterprise) is still running or not? Thx

**Comment by yasserf** [comment]
Hello @pgroot. Sorry to hear your emails were not responded to. You can reach me on our slack channel ( yasserf ) to discuss.

https://deepstreamio-slack.herokuapp.com/

Thanks!
