### ISSUE TITLE
build does not generate d.ts files

### ISSUE THREAD

**Issue by Vortex375** [deepstreamIO/deepstream.io#978]
When trying to use the Node.js interface and doing 
`import { Deepstream } from "@deepstream/server"`

I get the error message
```
Could not find a declaration file for module '@deepstream/server'. 'node_modules/@deepstream/server/dist/src/deepstream.io.js' implicitly has an 'any' type.
Try `npm install @types/deepstream__server` if it exists or add a new declaration (.d.ts) file containing `declare module '@deepstream/server';`
```
The reason is that the option
`"declaration": true`
is missing from its tsconfig.json.

I rebuilt the package with declarations enabled and it fixes the issue.

`"declaration": true`
Should be added to tsconfig.json and the package should be published with d.ts files in place.

**Comment by yasserf** [comment]
Thanks for raising! Feel free to raise a PR and publish it in the next
version!

**Comment by Vortex375** [comment]
Created PR #979
