### ISSUE TITLE
Validate and Modify Record on Server

### ISSUE THREAD

**Issue by ismael-iskauskas** [deepstreamIO/deepstream.io#980]
Is there any way to change the data on server side before its written to cache or db?

I need some kind of data validation, so i can make sure that the schema is valid. 

Are there any plans for adding such a feature? Some layer like permissions service, where u can hook in and modify the data.

OnMessageRecieve() => do something and callback
OnMessageSend() => do something and callback

Like the Middleware in express.js

**Comment by yasserf** [comment]
You can put that inside of your permission layer and say the message is denied if it doesn’t match your schema, plus a custom message.

Please look at 

https://deepstream.io/tutorials/custom-plugins/permission/index.html

**Comment by ismael-iskauskas** [comment]
Thank you. I tryed this but i do not get it to work as expected.
i cant access the data on record create or record read. 

```
canPerformAction(username, message, callback, authData, socketWrapper, passItOn) {
  if (message.topic === 5) {
            // Create 
            if (message.action === 15) {
                // **message.data always undefined**
            }

            if (message.action === 18) {
               // this one works kind of. Does not update record in cache. Client does not recieve the data
                let data = {};
                if(message.data) {
                    data = JSON.parse(message.data);
                }
               
                if(!data.owner) {
                    data.owner = username;
                }
                data.updated_at = Date.now();                
                message.data = JSON.stringify(data);
            }
        }
}
```

i think i miss something :/

**Comment by yasserf** [comment]
You want to validate on messages coming into the server, so that should be a RECORD_ACTION.UPDATE or RECORD_ACTION.PATCH. 

CREATE is what is used when you want to create a new empty record, and READ is when you request the data from the server.

**Comment by ismael-iskauskas** [comment]
My server code:

```
canPerformAction(username, message, callback, authData, socketWrapper, passItOn) {        
        // TOPIC RECORD
        if (message.topic === 5) {
            // ACTION CREATE RECORD
            if (message.action === 15) {
                let data = {};
                if(message.data) {
                    data = JSON.parse(message.data);
                }
                
                data.created_at = Date.now();                
                data.owner = username;
                message.data = JSON.stringify(data);
            }

            // ACTION UPDATE RECORD
            if (message.action === 18) {
                let data = {};
                if(message.data) {
                    data = JSON.parse(message.data);
                }                
                if(!data.owner) {
                    data.owner = username;
                }
                data.updated_at = Date.now();                
                message.data = JSON.stringify(data);
            }

        }

        if (message.topic === 6) {
            if (message.action === 2) {
                let data = JSON.parse(message.data);
                data.authData = authData;
                data.username = username;
                message.data = JSON.stringify(data);
            }
        }
        // pass request to Valve permission service
        this.permission.canPerformAction(username, message, callback, authData, socketWrapper, passItOn)
        return
    }
```

expected outcome in database
`{ "_id" : { "$oid" : "5d63861fedac8cd86098ed02" }, "ds_key" : "123456", "__ds" : { "_v" : 0 }, created_at: 123456789, owner: "Some User"}`

actually stored in database
`{ "_id" : { "$oid" : "5d63861fedac8cd86098ed02" }, "ds_key" : "123456", "__ds" : { "_v" : 0 } }`


Client code:
```
// ... Login etc 
let record = client.record.getRecord('test/123456') // create new record

record.whenReady(rec => {
        console.log(rec.get()) // expected: {created_at: 123456789, owner: "Some User"} what i get: {}
        
       rec.set({some:"data"});
       console.log(rec.get()) // expected: {created_at: 123456789, owner: "Some User", some:"data"} what i get: {some:"data"}
}
```
Do i have to subscribe to the record?
what i missing here

**Comment by yasserf** [comment]
create does not actually set any data and just sets it as empty, regardless of how you transform the data.

```
// ... Login etc 
await client.record.setData('test/123456', {})
let record = client.record.getRecord('test/123456') // create new record

record.whenReady(rec => {
        console.log(rec.get()) // expected: {created_at: 123456789, owner: "Some User"} what i get: {}
       rec.set({some:"data"});
       console.log(rec.get()) // expected: {created_at: 123456789, owner: "Some User", some:"data"} what i get: {some:"data"}
}
```

That should work since your doing a CREATEUPDATE (which sets the data) and then subscribes.

It's a valid usecase though, I'll have a think about it.

```
canPerformAction(username, message, callback, authData, socketWrapper, passItOn) {      
        // TOPIC RECORD
        if (message.topic === 5) {
            // ACTION UPDATE RECORD
            if (message.action === 18) {
                socketWrapper.parseData(message)
                if(!message.parsedData.owner) {
                    message.parsedData.owner = username;
                }
                message.parsedData.updated_at = Date.now();                
            }
        }

        if (message.topic === 6) {
            if (message.action === 2) {
                let data = JSON.parse(message.data);
                data.authData = authData;
                data.username = username;
                message.data = JSON.stringify(data);
            }
        }
        // pass request to Valve permission service
        this.permission.canPerformAction(username, message, callback, authData, socketWrapper, passItOn)
        return
    }
```

Also please use the RECORD_ACTION enum that is provided via `@deepstream/protobuf`, I don't know the enums by heart 😅

Thanks!

**Comment by ismael-iskauskas** [comment]
Sorry. Will import RECORD_ACTION. Just playing around with it.
```
rec.get()
```
hast the expected data if i restart the server between requests. 

Is there any way to trigger an update message from within the canPerformAction function?

**Comment by yasserf** [comment]
nope, its a one way pipeline to just verify data is permissioned. Not sure why you would want to do that but generally doing any other side effects than saying yes or no is usually a bad idea. If the user is supposed to know it is the owner and when it was last updated then the client should set those and you should permission against them accordingly. That being said all other clients will get the update if you augment it in the permission layer, so you can let each client have to connections so that it receives updates for its writes.

**Comment by ismael-iskauskas** [comment]
Hmm. I dont like that the client have to track created an updated timestamps. But ok. Than i have to do it this way. I mus t restructure some data, so that records with sensetiv data can not be requested by the client. Example User records have encrypted Password and some Tokens. This data must be moved out of user record because it is not possible to modify records before they are send. 

I still recommend some kind of middleware that can do such things. I will take a closer look at the source, maybe i will find a solution 

For now i close this issue. Thanks for the support
