### ISSUE TITLE
A listener of event subscriptions is not working with eepstream.io-windows-2.2.2 & 2.3.6

### ISSUE THREAD

**Issue by HemendPatel63** [deepstreamIO/deepstream.io#986]
I’m deepstream.io-windows-2.2.2. I have tried to upgrade it to latest version but it doesn’t work with window (https://github.com/deepstreamIO/deepstream.io/issues/935). 
I am trying to implement pattern use with event but .listen method is not responding. I have followed the step mention in below link to implement pattern. It doesn’t not though any exception, but it doesn’t trigger the listen event. 
https://deepstream.io/docs/client-js/event/

does it because of the deepstream version or environment(window)?

**Comment by yasserf** [comment]
The listen API changed from v2 to V4. Please look at the upgrade documentation.

As far as I know it works on windows now we default to using ws. Can you show me some logs?

**Comment by yasserf** [comment]
I’m not community supporting versions less than V4 since it is backwards compatible with all clients now and I can’t maintain two servers myself via OS

**Comment by HemendPatel63** [comment]
I'm not getting any exception but it's not trigger the event.listen event. 
I have created a small angular app to reproduce this using deepstream.io-windows-2.2.2.

https://gitlab.com/Hemendra.patel/angular-deepstream

let me know if you need more detail

**Comment by yasserf** [comment]
The repo only has one file. You also haven’t provided the versions of the client and the server.

**Comment by HemendPatel63** [comment]
I am using window 10 and the server version of deepstream is 2.2.2 and client I'm using 
https://gitlab.com/Hemendra.patel/angular-deepstream/tree/development/src/deepstream/deepstream.js as client.

Development branch of repo has full implementation of this.

**Comment by yasserf** [comment]
Hello,

Thank you for clarifying!

Unfortunately I no longer support v2 so I can’t really dig into this issue. However if not working on windows surprises me. Would you mind sending a screenshot of what happened when you run ‘deepstream.cmd start’ with V4? Thanks

**Comment by yasserf** [comment]
Can you please try this with the latest version and reopen if you can replicate? I can't on my end and know listening in used in quite a few projects. Thanks!
