### ISSUE TITLE
Server latency

### ISSUE THREAD

**Issue by thorsby** [deepstreamIO/deepstream.io#988]
I'm exploring Deepstream for an upcoming project and is quite happy with the feature set, but there seems to be some latency issues.

I've setup a simple test where two NodeJS clients connects to the Deepstream server and does simple ping-pong using events. The latency is measured as client to deepstream and to the other client. https://pastebin.com/8SARHC5s
```
Server 4.0.6 / Client 4.0.5
51-56ms

Server 4.1 / Client 4.0.5
11-14ms

Server 3.2.4 / Client 2.3.4
1-2ms
```
Obviously a complete roundtrip (eg. a request-response flow takes double)

I did these comparative tests as I initially found the 4.0.6 to be quite slow. It improves a lot in the recent 4.1 release, but is still quite high compared to V3 or something like regular websockets. Some latency is arguably acceptable, as Deepstream is much more than just a websocket, but what has changes so radically from V3?

**Comment by yasserf** [comment]
Hey! Yeah that was actually an artificial delay we added. It’s configurable (outgoing buffer output) and was reduced from 50ms to 10ms in 4.1 to speed up e2e tests (even though we could have done that in the framework didn’t feel it was important enough to have different). 

You can reduce that to 0 and it will basically send it out immediately. It won’t actually make a big difference anyways as we don’t correctly utilise protobuf group parsing and building, but it will be added soon enough!

**Comment by thorsby** [comment]
Ok. I configured it to 0 and I get  1-2ms, full round trip (Client 1 > 2 > 1) which I think is great. 
Should it not be 0 by default?

Is the reason that some latency is required to fully utilise protobuf in a future release?

**Comment by yasserf** [comment]
yup thats exactly it. in V3 things were a more optimal because of how it created unique messages per topic. That was removed in V4 however because it was really hard to work around while allowing multiple endpoints.

That being said however V4 meta updates (acks and so forth) and alot less frequent now so setting it to zero has alot less of an impact.

**Comment by yasserf** [comment]
Closing issue but if there’s any updates feel free to reopen!
