### ISSUE TITLE
'client.presence.subscribe' get other clients' uid

### ISSUE THREAD

**Issue by crapthings** [deepstreamIO/deepstream.io#989]
```js
client.getUid()
```

```js
client.presence.subscribe((username, isLoggedIn) => {
  // handle new user
})
```

any possible to get other clients' uid? after client is connected and disconnected?

**Comment by yasserf** [comment]
I’m sorry I don’t understand the question. Client.getUid is just a UID generator, it doesn’t have anything to do with the client session or presence.
