### ISSUE TITLE
Error: listen EADDRINUSE: address already in use 127.0.0.1:6020

### ISSUE THREAD

**Issue by DaisenTravel** [deepstreamIO/deepstream.io#996]
Hello:
First, my nodejs environment is good.
On https://deepstream.io/tutorials/install/nodejs/, step by step,use nodejs to create @deepstream/server,copy the code into index.js,but has a error on nodemon index.js.why?
PLS See attachment。
Looking forward to reply
Thanks a lot!

![image](https://user-images.githubusercontent.com/25305480/64924059-fac90600-d812-11e9-97b7-8529dc519830.png)

**Comment by DaisenTravel** [comment]
Plus: My port 6020 has not been occupied! But always prompted to be occupied!

**Comment by yasserf** [comment]
hey! Yeah this is a known issue that slipped out in 4.2 due to there being multiple endpoints added. Will get a fix out today!

**Comment by DaisenTravel** [comment]
Thank you! When you have repaired it, please let me know. Thank you again!

**Comment by DaisenTravel** [comment]
I just like NODEJS. Has that problem been fixed? Waiting for the test! Ha-ha! Thank you very much!

**Comment by yasserf** [comment]
hey! looking into it now!

**Comment by yasserf** [comment]
Okay should be out in 4.2.1!
