### ISSUE TITLE
Error: listen EADDRINUSE: address already in use 127.0.0.1:6020

### ISSUE THREAD

**Issue by DaisenTravel** [deepstreamIO/deepstream.io#999]
hi:
What's going on? It's the same mistake! Did you pass the test? You just added MQTT and other protocols! Is there anything wrong with my environment? Wait for your reply, thank you!
![image](https://user-images.githubusercontent.com/25305480/65092250-4d5f1980-d9ef-11e9-8a5c-45e5484928d5.png)

**Comment by DaisenTravel** [comment]
What's going on? It's the same mistake! Did you pass the test? You just added MQTT and other protocols! Is there anything wrong with my environment? This problem is not solved, can not continue to test! Looking forward to your reply, thank you!

**Comment by yasserf** [comment]
Passing in a host and port that way isn’t supported when not using a config file with explicit endpoints. It’s a backwards compatibility hack that was left from V3. Just remove those and it will be fine. I’ll put a depreciation notice up for those who use it still.

**Comment by yasserf** [comment]
And yes there’s a test script, it’s scripts/node-test.js

**Comment by DaisenTravel** [comment]
OK!Thank you very very much!Ha-ha!

**Comment by MohamedLamineAllal** [comment]
I'm in the same problem. A notice: why it's kept in the documentation at https://deepstream.io/tutorials/install/nodejs/. A better documentation help a lot. (i can too help with that).

Also i tried to load the configuration by providing the path as bellow
![Screenshot from 2019-09-21 02-17-12](https://user-images.githubusercontent.com/20062543/65365945-0141ee00-dc16-11e9-8591-1d41f0cbf3ef.png)

And i keep getting the error: 
```
.../src/config/js-yaml-loader.ts:175
  throw new Error(`Configuration file not found at: ${configPath}`)
        ^
Error: Configuration file not found at: .......
```
I also made the construction without providing any parameter. And it keep not working
```
Error: No config file found
    at getDefaultConfigPath (/home/..../node_modules/@deepstream/server/src/config/js-yaml-loader.ts:195:
```

**Comment by MohamedLamineAllal** [comment]
I was having the same problem. And i was using typescript and i didn't pay attention too to the output dir and build. I was able to run the server in the end.  But i ended up with a lot of questions.
I checked up the code source and i have seen how the config is loaded
```
const SUPPORTED_EXTENSIONS = ['.yml', '.yaml', '.json', '.js']
const DEFAULT_CONFIG_DIRS = [
  path.join('.', 'conf', 'config'), path.join('..', 'conf', 'config'),
  '/etc/deepstream/config', '/usr/local/etc/deepstream/config',
  '/usr/local/etc/deepstream/conf/config',
]

DEFAULT_CONFIG_DIRS.push(path.join(process.argv[1], '..', 'conf', 'config'))
DEFAULT_CONFIG_DIRS.push(path.join(process.argv[1], '..', '..', 'conf', 'config'))
```

Also i tested different things and all. Here what i came up with:

First of all if we don't precise any parameter in the constructor. A config from the default directories will get to load. If there isn't then the server fail to run.
And one of the places where we can put a config is ./conf  in the same folder as the server node script. 

Secondly we can precise a config as a string path (parameter in the constructor). config.yml or one of the supported extensions. That will allow the server to load the server config + the permission.yml and users.yml configs. Which too are supposed to be in the same folder. If not in the same folder there load will fail, and therefor the permission plugin will not load. And so does the users config. And no fall back to default will happen.

Thirdly the supported extensions for the config files are: yml, yaml, json, js.

In nodejs context. If nothing precised. There is no fallback to some default config. The config need to be provided in one of the default folders, or by precising a path to it. Or by passing a config object.

To precise the path, we need to precise the path to the config.yml file (the server config) [example: `path.join(__dirname, './conf/config.yml')`. Then from the same dir permission.yml and users.yml will be retrieved (the extension can be any of the supported one). We can not precise a path to a directory, it will fail.

We can precise the path to permission config or user config separatly within config.yaml as shown bellow:
```
# Permissioning example with default values for config-based permissioning
permission:
  type: config
  options:
    path: ./permissions.yml
    maxRuleIterations: 3
    cacheEvacuationInterval: 60000
```

Finally we can pass an object to configure the server, or by passing null as a parameter and use .set methods (i didn't test the second method). For configuring the server we need to follow the same structure as the yml file. With sometimes a bit different naming. The typescript declaration files or types show us the way. With an editor like vscode. Even if we are not using typescript we can keep get the autocompletion and type definitions.
And the simplest for equivalent to the previous version is :
```typescript
const webSocketServer = new Deepstream({
    connectionEndpoints: [
        {
            path: 'deepstream',
            type: 'ws-websocket',
            options: {
                port: 6020,
                host: '127.0.0.1'
            }
        }
    ]
});

webSocketServer.start();
```

My questions come as follow:
- have i missed something or am i wrong on some things above?
- When we provide the config as directly in the constructor through js. Why the name of properties is different then the one in the yml config. For example for the end points options. We have `urlPath` in yml and just `path` in js object (following the typescript declaration files) (and it work as i tested it)  [update: i tested too with urlPath and it work] so the typescript types declaration files need to be updated. ?

- Lastly if i write a more detailed and concise information would you include them in the documentation and how i should proceed ?

**Comment by yasserf** [comment]
Will get back to you on this, need a bit of time to add a response

**Comment by yasserf** [comment]
Will get back to you on this, need a bit of time to add a response

**Comment by yasserf** [comment]
hey!

Okay so the reason I didn't get back is because I took a step back and came up with a much clearer way of doing all this connection stuff (now in V5)

The idea is this, you have one http server (either uws or default) and all connection points and plugins point to that. You can configure the server like this:

```
const webSocketServer = new Deepstream({
    httpService: {
            type: 'default', // or uws
            options: {
                port: 6020,
                host: '127.0.0.1',
            }
        }
});

webSocketServer.start();
```

or if using the binary like this:

```
./deepstream start --port 6030 --host bla.com
```

Each endpoint registers against that one server, meaning you won't have more than one port open normally unless your running mqtt (currently). The only catch is you can't pick and choose now between node and uws, it's one or the other.

In terms of starting the server, you can either:

1- Pass in null, uses defaults built in `new Deepstream(null)`
2- Pass in config file name, loads from config file and merges missing properties from default, if nothing is passed in `new Deepstream()` it will look for the config file in either a folder called config in your current directory or one above.
```
path.join('.', 'conf', 'config'),
 path.join('..', 'conf', 'config')
```
3- You can pass in an object that is basically the translated yaml file into the deepstream config object

```
new Deepstream({
  ...
})
```

4- You can ovveride the deepstream config post creation and pre starting, which is the only way to override services

```
const ds = new Deepstream()
ds.set('auth', new MyOwnAuthHandler({}, ds.getServices()))
ds.start()
```

WIP documentation:

http://staging.deepstream.io/guides/post-it-board/setting-up-the-backend/
